shark::CSvmTrainer< InputType, CacheType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::CSvmTrainer< InputType, CacheType > Class Template Reference
Supervised Trainers
Training of C-SVMs for binary classification.
#include <shark/Algorithms/Trainers/CSvmTrainer.h>
Public Types
typedef CacheType QpFloatType
Convenience typedefs: this and many of the below typedefs build on the class template type CacheType. Simply changing that one template parameter CacheType thus allows to flexibly switch between using float or double as type for caching the kernel values. The default is float, offering sufficient accuracy in the vast majority of cases, at a memory cost of only four bytes. However, the template parameter makes it easy to use double instead, (e.g., in case high accuracy training is needed).
typedef AbstractKernelFunction< InputType > KernelType
Public Types inherited from shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >
typedef AbstractKernelFunction< InputType > KernelType
Public Types inherited from shark::AbstractWeightedTrainer< KernelClassifier< InputType > >
typedef base_type::ModelType ModelType
typedef base_type::InputType InputType
typedef base_type::LabelType LabelType
typedef base_type::DatasetType DatasetType
typedef WeightedLabeledData< InputType, LabelType > WeightedDatasetType
Public Types inherited from shark::AbstractTrainer< Model, LabelTypeT >
typedef Model ModelType
typedef ModelType::InputType InputType
typedef LabelTypeT LabelType
typedef LabeledData< InputType, LabelType > DatasetType
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
CSvmTrainer (KernelType *kernel, double C, bool offset, bool unconstrained=false)
CSvmTrainer (KernelType *kernel, double negativeC, double positiveC, bool offset, bool unconstrained=false)
std::string name () const
From INameable: return the class name.
void setComputeBinaryDerivative (bool compute)
void setMcSvmType (McSvm type)
sets the type of the multi-class svm used
void train (KernelClassifier< InputType > &svm, LabeledData< InputType, unsigned int > const &dataset)
Train the C-SVM.
void train (KernelClassifier< InputType > &svm, WeightedLabeledData< InputType, unsigned int > const &dataset)
Train the C-SVM using weights.
RealVector const & get_db_dParams () const
Public Member Functions inherited from shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >
AbstractSvmTrainer (KernelType *kernel, double C, bool offset, bool unconstrained=false)
AbstractSvmTrainer (KernelType *kernel, double negativeC, double positiveC, bool offset, bool unconstrained=false)
double C () const
Return the value of the regularization parameter C.
void setC (double C)
Set the value of the regularization parameter C.
RealVector const & regularizationParameters () const
void setRegularizationParameters (RealVector const &regularizers)
Set the value of the regularization parameter C.
KernelType * kernel ()
KernelType const * kernel () const
void setKernel (KernelType *kernel)
bool isUnconstrained () const
bool trainOffset () const
std::size_t cacheSize () const
void setCacheSize (std::size_t size)
RealVector parameterVector () const
get the hyper-parameter vector
void setParameterVector (RealVector const &newParameters)
set the vector of hyper-parameters
size_t numberOfParameters () const
return the number of hyper-parameters
Public Member Functions inherited from shark::AbstractWeightedTrainer< KernelClassifier< InputType > >
virtual void train (ModelType &model, WeightedDatasetType const &dataset)=0
Executes the algorithm and trains a model on the given weighted data.
virtual void train (ModelType &model, DatasetType const &dataset)
Executes the algorithm and trains a model on the given unweighted data.
Public Member Functions inherited from shark::AbstractTrainer< Model, LabelTypeT >
virtual void train (ModelType &model, DatasetType const &dataset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Public Member Functions inherited from shark::QpConfig
QpConfig (bool precomputedFlag=false, bool sparsifyFlag=true)
Constructor.
QpStoppingCondition & stoppingCondition ()
Read/write access to the stopping condition.
QpStoppingCondition const & stoppingCondition () const
Read access to the stopping condition.
QpSolutionProperties & solutionProperties ()
Access to the solution properties.
bool & precomputeKernel ()
Flag for using a precomputed kernel matrix.
bool const & precomputeKernel () const
Flag for using a precomputed kernel matrix.
bool & sparsify ()
Flag for sparsifying the model after training.
bool const & sparsify () const
Flag for sparsifying the model after training.
bool & shrinking ()
Flag for shrinking in the decomposition solver.
bool const & shrinking () const
Flag for shrinking in the decomposition solver.
bool & s2do ()
Flag for S2DO (instead of SMO)
bool const & s2do () const
Flag for S2DO (instead of SMO)
unsigned int & verbosity ()
Verbosity level of the solver.
unsigned int const & verbosity () const
Verbosity level of the solver.
unsigned long long const & accessCount () const
Number of kernel accesses.
void setMinAccuracy (double a)
void setMaxIterations (unsigned long long i)
void setTargetValue (double v)
void setMaxSeconds (double s)
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >
KernelType * m_kernel
RealVector m_regularizers
Vector of regularization parameters.
bool m_trainOffset
bool m_unconstrained
Is log(C) stored internally as a parameter instead of C? If yes, then we get rid of the constraint C > 0 on the level of the parameter interface.
std::size_t m_cacheSize
Number of values in the kernel cache. The size of the cache in bytes is the size of one entry (4 for float, 8 for double) times this number.
Protected Attributes inherited from shark::QpConfig
QpStoppingCondition m_stoppingcondition
conditions for when to stop the QP solver
QpSolutionProperties m_solutionproperties
properties of the approximate solution found by the solver
bool m_precomputedKernelMatrix
should the solver use a precomputed kernel matrix?
bool m_sparsify
should the trainer sparsify the model after training?
bool m_shrinking
should shrinking be used?
bool m_s2do
should S2DO be used instead of SMO?
unsigned int m_verbosity
verbosity level (currently unused)
unsigned long long m_accessCount
kernel access count
Detailed Description
template<class InputType, class CacheType = float>
class shark::CSvmTrainer< InputType, CacheType >
Training of C-SVMs for binary classification.
The C-SVM is the "standard" support vector machine for binary (two-class) classification. Given are data tuples \((x_i, y_i) \) with x-component denoting input and y-component denoting the label +1 or -1 (see the tutorial on label conventions; the implementation uses values 0/1), a kernel function k(x, x') and a regularization constant C > 0. Let H denote the kernel induced reproducing kernel Hilbert space of k, and let \(\phi \) denote the corresponding feature map. Then the SVM classifier is the function
\[ h(x) = \mathop{sign} (f(x)) \]
\[ f(x) = \langle w, \phi(x) \rangle + b \]
with coefficients w and b given by the (primal) optimization problem
\[ \min \frac{1}{2} \|w\|^2 + C \sum_i L(y_i, f(x_i)), \]
where \(L(y, f(x)) = \max\{0, 1 - y \cdot f(x)\} \) denotes the hinge loss.
For details refer to the paper:
Support-Vector Networks. Corinna Cortes and Vladimir Vapnik, Machine Learning, vol. 20 (1995), pp. 273-297.
or simply to the Wikipedia article:
http://en.wikipedia.org/wiki/Support_vector_machine
Definition at line 74 of file CSvmTrainer.h.
Member Typedef Documentation
KernelType
template<class InputType , class CacheType = float> typedef AbstractKernelFunction<InputType> shark::CSvmTrainer< InputType, CacheType >::KernelType
Definition at line 98 of file CSvmTrainer.h.
QpFloatType
template<class InputType , class CacheType = float> typedef CacheType shark::CSvmTrainer< InputType, CacheType >::QpFloatType
Convenience typedefs: this and many of the below typedefs build on the class template type CacheType. Simply changing that one template parameter CacheType thus allows to flexibly switch between using float or double as type for caching the kernel values. The default is float, offering sufficient accuracy in the vast majority of cases, at a memory cost of only four bytes. However, the template parameter makes it easy to use double instead, (e.g., in case high accuracy training is needed).
Definition at line 96 of file CSvmTrainer.h.
Constructor & Destructor Documentation
CSvmTrainer() [1/2]
template<class InputType , class CacheType = float> shark::CSvmTrainer< InputType, CacheType >::CSvmTrainer (KernelType * kernel, double C, bool offset, bool unconstrained = false) inline
Constructor
Parameters
kernel kernel function to use for training and prediction
C regularization parameter - always the 'true' value of C, even when unconstrained is set
offset whether to train the svm with offset term
unconstrained when a C-value is given via setParameter, should it be piped through the exp-function before using it in the solver?
Definition at line 105 of file CSvmTrainer.h.
CSvmTrainer() [2/2]
template<class InputType , class CacheType = float> shark::CSvmTrainer< InputType, CacheType >::CSvmTrainer (KernelType * kernel, double negativeC, double positiveC, bool offset, bool unconstrained = false) inline
Constructor
Parameters
kernel kernel function to use for training and prediction
negativeC regularization parameter of the negative class (label 0)
positiveC regularization parameter of the positive class (label 1)
offset whether to train the svm with offset term
unconstrained when a C-value is given via setParameter, should it be piped through the exp-function before using it in the solver?
Definition at line 115 of file CSvmTrainer.h.
Member Function Documentation
get_db_dParams()
template<class InputType , class CacheType = float> RealVector const & shark::CSvmTrainer< InputType, CacheType >::get_db_dParams () const inline
Definition at line 279 of file CSvmTrainer.h.
name()
template<class InputType , class CacheType = float> std::string shark::CSvmTrainer< InputType, CacheType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 120 of file CSvmTrainer.h.
Referenced by main().
setComputeBinaryDerivative()
template<class InputType , class CacheType = float> void shark::CSvmTrainer< InputType, CacheType >::setComputeBinaryDerivative (bool compute) inline
Definition at line 123 of file CSvmTrainer.h.
Referenced by shark::SvmLogisticInterpretation< InputType >::evalDerivative().
setMcSvmType()
template<class InputType , class CacheType = float> void shark::CSvmTrainer< InputType, CacheType >::setMcSvmType (McSvm type) inline
sets the type of the multi-class svm used
Definition at line 128 of file CSvmTrainer.h.
Referenced by main().
train() [1/2]
template<class InputType , class CacheType = float> void shark::CSvmTrainer< InputType, CacheType >::train (KernelClassifier< InputType > & svm, LabeledData< InputType, unsigned int > const & dataset) inline
Train the C-SVM.
Definition at line 134 of file CSvmTrainer.h.
References shark::ADM, shark::ATM, shark::ATS, shark::CS, shark::Classifier< Model >::decisionFunction(), shark::LabeledData< InputT, LabelT >::element(), shark::LabeledData< InputT, LabelT >::inputs(), shark::LabeledData< InputT, LabelT >::labels(), shark::LLW, shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::m_kernel, shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::m_trainOffset, shark::MMR, shark::numberOfClasses(), shark::LabeledData< InputT, LabelT >::numberOfElements(), shark::OVA, shark::ReinforcedSvm, shark::QpConfig::sparsify(), shark::QpSparseArray< QpFloatType >::width(), and shark::WW.
Referenced by shark::SvmLogisticInterpretation< InputType >::eval(), shark::SvmLogisticInterpretation< InputType >::evalDerivative(), main(), main(), and run_one_trial().
train() [2/2]
template<class InputType , class CacheType = float> void shark::CSvmTrainer< InputType, CacheType >::train (KernelClassifier< InputType > & svm, WeightedLabeledData< InputType, unsigned int > const & dataset) inline
Train the C-SVM using weights.
Definition at line 259 of file CSvmTrainer.h.
References shark::Classifier< Model >::decisionFunction(), shark::WeightedLabeledData< InputT, LabelT >::inputs(), shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::m_kernel, shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::m_trainOffset, shark::numberOfClasses(), SHARK_RUNTIME_CHECK, and shark::QpConfig::sparsify().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/CSvmTrainer.h