shark::NormalizeKernelUnitVariance< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::NormalizeKernelUnitVariance< InputType > Class Template Reference
Unsupervised Trainers
Determine the scaling factor of a ScaledKernel so that it has unit variance in feature space one on a given dataset.
#include <shark/Algorithms/Trainers/NormalizeKernelUnitVariance.h>
Public Member Functions
NormalizeKernelUnitVariance ()
std::string name () const
From INameable: return the class name.
double trace () const
double mean () const
void train (ScaledKernel< InputType > &kernel, UnlabeledData< InputType > const &input)
Public Member Functions inherited from shark::AbstractUnsupervisedTrainer< Model >
virtual void train (ModelType &model, DatasetType const &inputset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Attributes
double m_mean
double m_matrixTrace
Additional Inherited Members
Public Types inherited from shark::AbstractUnsupervisedTrainer< Model >
typedef Model ModelType
typedef Model::InputType InputType
typedef UnlabeledData< InputType > DatasetType
Detailed Description
template<class InputType = RealVector>
class shark::NormalizeKernelUnitVariance< InputType >
Determine the scaling factor of a ScaledKernel so that it has unit variance in feature space one on a given dataset.
For example in the multiple kernel learning setting, it can be important that the sub-kernels are normalized to unit variance in feature space. This class computes both the trace and the mean of a kernel matrix, and uses both to employ the "Multiplicative Kernel Scaling" laid out in "Kloft, Brefeld, Sonnenburg, Zien: l_p-Norm Multiple Kernel Learning. JMLR 12, 2011.". Given a ScaledKernel, which itself holds an arbitrary underlying kernel k, we compute
\[ \frac{1}{N}\sum_{i=1}^N k(x_i,x_i) - \frac{1}{N^2} \sum_{i,j=1}^N k(x_i,x_j) \]
Definition at line 60 of file NormalizeKernelUnitVariance.h.
Constructor & Destructor Documentation
NormalizeKernelUnitVariance()
template<class InputType = RealVector> shark::NormalizeKernelUnitVariance< InputType >::NormalizeKernelUnitVariance () inline
Definition at line 64 of file NormalizeKernelUnitVariance.h.
Member Function Documentation
mean()
template<class InputType = RealVector> double shark::NormalizeKernelUnitVariance< InputType >::mean () const inline
Definition at line 74 of file NormalizeKernelUnitVariance.h.
References shark::NormalizeKernelUnitVariance< InputType >::m_mean.
Referenced by main(), and main().
name()
template<class InputType = RealVector> std::string shark::NormalizeKernelUnitVariance< InputType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 68 of file NormalizeKernelUnitVariance.h.
trace()
template<class InputType = RealVector> double shark::NormalizeKernelUnitVariance< InputType >::trace () const inline
Definition at line 71 of file NormalizeKernelUnitVariance.h.
References shark::NormalizeKernelUnitVariance< InputType >::m_matrixTrace.
Referenced by main(), and main().
train()
template<class InputType = RealVector> void shark::NormalizeKernelUnitVariance< InputType >::train (ScaledKernel< InputType > & kernel, UnlabeledData< InputType > const & input) inline
Definition at line 78 of file NormalizeKernelUnitVariance.h.
References shark::ScaledKernel< InputType >::base(), shark::Data< Type >::batch(), shark::NormalizeKernelUnitVariance< InputType >::m_matrixTrace, shark::NormalizeKernelUnitVariance< InputType >::m_mean, shark::Data< Type >::numberOfBatches(), shark::Data< Type >::numberOfElements(), shark::ScaledKernel< InputType >::setFactor(), SHARK_ASSERT, and SHARK_RUNTIME_CHECK.
Referenced by shark::exportKernelMatrix(), main(), and main().
Member Data Documentation
m_matrixTrace
template<class InputType = RealVector> double shark::NormalizeKernelUnitVariance< InputType >::m_matrixTrace protected
Definition at line 112 of file NormalizeKernelUnitVariance.h.
Referenced by shark::NormalizeKernelUnitVariance< InputType >::trace(), and shark::NormalizeKernelUnitVariance< InputType >::train().
m_mean
template<class InputType = RealVector> double shark::NormalizeKernelUnitVariance< InputType >::m_mean protected
Definition at line 111 of file NormalizeKernelUnitVariance.h.
Referenced by shark::NormalizeKernelUnitVariance< InputType >::mean(), and shark::NormalizeKernelUnitVariance< InputType >::train().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/NormalizeKernelUnitVariance.h