shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType > Class Template Reference
Cost functions
Negative Wilcoxon-Mann-Whitney statistic.
#include <shark/ObjectiveFunctions/NegativeAUC.h>
Public Member Functions
NegativeWilcoxonMannWhitneyStatistic (bool invert=false)
std::string name () const
From INameable: return the class name.
double eval (Data< LabelType > const &target, Data< OutputType > const &prediction, unsigned int column) const
Computes Wilcoxon-Mann-Whitney statistic.
double eval (Data< LabelType > const &target, Data< OutputType > const &prediction) const
Public Member Functions inherited from shark::AbstractCost< LabelT, OutputT >
virtual ~AbstractCost ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstDerivative () const
returns true when the first parameter derivative is implemented
bool isLossFunction () const
returns true when the cost function is in fact a loss function
double operator() (Data< LabelType > const &targets, Data< OutputType > const &predictions) const
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Public Types inherited from shark::AbstractCost< LabelT, OutputT >
enum Feature { HAS_FIRST_DERIVATIVE = 1 , HAS_SECOND_DERIVATIVE = 2 , IS_LOSS_FUNCTION = 4 }
list of features a cost function can have
typedef OutputT OutputType
typedef LabelT LabelType
typedef Batch< OutputType >::type BatchOutputType
typedef Batch< LabelType >::type BatchLabelType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Protected Attributes inherited from shark::AbstractCost< LabelT, OutputT >
Features m_features
Detailed Description
template<class LabelType = unsigned int, class OutputType = LabelType>
class shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType >
Negative Wilcoxon-Mann-Whitney statistic.
This class computes the Wilcoxon-Mann-Whitney statistic, which is an unbiased estimate of the area under the ROC curve.
See, for example: Corinna Cortes, Mehryar Mohri. Confidence Intervals for the Area under the ROC Curve. NIPS, 2004
The area is negated so that optimizing the AUC corresponds to a minimization task.
Definition at line 164 of file NegativeAUC.h.
Constructor & Destructor Documentation
NegativeWilcoxonMannWhitneyStatistic()
template<class LabelType = unsigned int, class OutputType = LabelType> shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType >::NegativeWilcoxonMannWhitneyStatistic (bool invert = false) inline
Constructor.
Parameters
invert if set to true, the role of positive and negative class are switched
Definition at line 169 of file NegativeAUC.h.
Member Function Documentation
eval() [1/2]
template<class LabelType = unsigned int, class OutputType = LabelType> double shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType >::eval (Data< LabelType > const & targets, Data< OutputType > const & predictions) const inline virtual
Evaluates the cost of predictions, given targets.
Parameters
targets target values
predictions predictions, typically made by a model
Implements shark::AbstractCost< LabelT, OutputT >.
Definition at line 230 of file NegativeAUC.h.
References shark::dataDimension(), shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType >::eval(), shark::Data< Type >::numberOfElements(), and SHARK_RUNTIME_CHECK.
eval() [2/2]
template<class LabelType = unsigned int, class OutputType = LabelType> double shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType >::eval (Data< LabelType > const & target, Data< OutputType > const & prediction, unsigned int column) const inline
Computes Wilcoxon-Mann-Whitney statistic.
Parameters
target interpreted as binary class label
prediction interpreted as binary class label
column indicates the column of the prediction vector interpreted as probability of positive class
Definition at line 181 of file NegativeAUC.h.
References shark::Data< Type >::element(), and SHARK_RUNTIME_CHECK.
Referenced by shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType >::eval().
name()
template<class LabelType = unsigned int, class OutputType = LabelType> std::string shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 174 of file NegativeAUC.h.
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/NegativeAUC.h