shark::ConcatenatedModel< VectorType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::ConcatenatedModel< VectorType > Class Template Reference
Models
ConcatenatedModel concatenates two models such that the output of the first model is input to the second.
#include <shark/Models/ConcatenatedModel.h>
Public Types
typedef base_type::BatchInputType BatchInputType
typedef base_type::BatchOutputType BatchOutputType
typedef base_type::ParameterVectorType ParameterVectorType
Public Types inherited from shark::AbstractModel< VectorType, VectorType, VectorType >
enum Feature
typedef VectorType InputType
Defines the input type of the model.
typedef VectorType OutputType
Defines the output type of the model.
typedef AbstractModel< VectorType, VectorType, VectorType > ModelBaseType
Defines the BaseType used by the model (this type). Useful for creating derived models.
typedef Batch< InputType >::type BatchInputType
defines the batch type of the input type.
typedef Batch< OutputType >::type BatchOutputType
defines the batch type of the output type
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
std::string name () const
From INameable: return the class name.
Shape inputShape () const
Returns the expected shape of the input.
Shape outputShape () const
Returns the shape of the output.
void add (AbstractModel< VectorType, VectorType, VectorType > *layer, bool optimize)
void enableModelOptimization (std::size_t index, bool opt)
sets whether the parameters of the index-th model should be optimized
ParameterVectorType parameterVector () const
Return the parameter vector.
void setParameterVector (ParameterVectorType const &newParameters)
Set the parameter vector.
std::size_t numberOfParameters () const
Return the number of parameters.
boost::shared_ptr< State > createState () const
Creates an internal state of the model.
BatchOutputType const & hiddenResponses (State const &state, std::size_t index) const
State const & hiddenState (State const &state, std::size_t index) const
void eval (BatchInputType const &patterns, BatchOutputType &outputs) const
Standard interface for evaluating the response of the model to a batch of patterns.
void eval (BatchInputType const &patterns, BatchOutputType &outputs, State &state) const
Standard interface for evaluating the response of the model to a batch of patterns.
void weightedParameterDerivative (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &gradient) const
calculates the weighted sum of derivatives w.r.t the parameters.
void weightedInputDerivative (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchOutputType &derivatives) const
virtual void weightedDerivatives (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &gradient, BatchInputType &inputDerivative) const
calculates weighted input and parameter derivative at the same time
void read (InArchive &archive)
From ISerializable.
void write (OutArchive &archive) const
From ISerializable.
Public Member Functions inherited from shark::AbstractModel< VectorType, VectorType, VectorType >
AbstractModel ()
virtual ~AbstractModel ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
Returns true when the first parameter derivative is implemented.
bool hasFirstInputDerivative () const
Returns true when the first input derivative is implemented.
virtual void eval (InputType const &pattern, OutputType &output) const
Standard interface for evaluating the response of the model to a single pattern.
Data< OutputType > operator() (Data< InputType > const &patterns) const
Model evaluation as an operator for a whole dataset. This is a convenience function.
OutputType operator() (InputType const &pattern) const
Model evaluation as an operator for a single pattern. This is a convenience function.
BatchOutputType operator() (BatchInputType const &patterns) const
Model evaluation as an operator for a single pattern. This is a convenience function.
virtual void weightedInputDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchInputType &derivative) const
calculates the weighted sum of derivatives w.r.t the inputs
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractModel< VectorType, VectorType, VectorType >
Features m_features
Detailed Description
template<class VectorType>
class shark::ConcatenatedModel< VectorType >
ConcatenatedModel concatenates two models such that the output of the first model is input to the second.
Sometimes a series of models is needed to generate the desired output. For example when input data needs to be normalized before it can be put into the trained model. In this case, the ConcatenatedModel can be used to represent this series as one model. The easiest way to do is is using the operator >> of AbstractModel: ConcatenatedModel<InputType,OutputType> model = model1>>model2; InputType must be the type of input model1 receives and model2 the output of model2. The output of model1 and input of model2 must match. Another way of construction is calling the constructor of ConcatenatedModel using the constructor: ConcatenatedModel<InputType,OutputType> model (&modell,&model2); warning: model1 and model2 must outlive model. When they are destroyed first, behavior is undefined.
Definition at line 58 of file ConcatenatedModel.h.
Member Typedef Documentation
BatchInputType
template<class VectorType > typedef base_type::BatchInputType shark::ConcatenatedModel< VectorType >::BatchInputType
Definition at line 62 of file ConcatenatedModel.h.
BatchOutputType
template<class VectorType > typedef base_type::BatchOutputType shark::ConcatenatedModel< VectorType >::BatchOutputType
Definition at line 63 of file ConcatenatedModel.h.
ParameterVectorType
template<class VectorType > typedef base_type::ParameterVectorType shark::ConcatenatedModel< VectorType >::ParameterVectorType
Definition at line 64 of file ConcatenatedModel.h.
Member Function Documentation
add()
template<class VectorType > void shark::ConcatenatedModel< VectorType >::add (AbstractModel< VectorType, VectorType, VectorType > * layer, bool optimize) inline
Definition at line 81 of file ConcatenatedModel.h.
References shark::ConcatenatedModel< VectorType >::enableModelOptimization().
Referenced by shark::operator>>(), and shark::operator>>().
createState()
template<class VectorType > boost::shared_ptr< State > shark::ConcatenatedModel< VectorType >::createState () const inline virtual
Creates an internal state of the model.
The state is needed when the derivatives are to be calculated. Eval can store a state which is then reused to speed up the calculations of the derivatives. This also allows eval to be evaluated in parallel!
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 147 of file ConcatenatedModel.h.
enableModelOptimization()
template<class VectorType > void shark::ConcatenatedModel< VectorType >::enableModelOptimization (std::size_t index, bool opt) inline
sets whether the parameters of the index-th model should be optimized
If the model has non-differentiable submodels disabling those will make the whole model differentiable. Note that the models are ordered as model0 >> model1>> model2>>...
Definition at line 91 of file ConcatenatedModel.h.
References shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_INPUT_DERIVATIVE, shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_PARAMETER_DERIVATIVE, shark::AbstractModel< VectorType, VectorType, VectorType >::m_features, shark::TypedFlags< Flag >::reset(), and SIZE_CHECK.
Referenced by shark::ConcatenatedModel< VectorType >::add().
eval() [1/2]
template<class VectorType > void shark::ConcatenatedModel< VectorType >::eval (BatchInputType const & patterns, BatchOutputType & outputs) const inline virtual
Standard interface for evaluating the response of the model to a batch of patterns.
Parameters
patterns the inputs of the model
outputs the predictions or response of the model to every pattern
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 167 of file ConcatenatedModel.h.
References shark::swap().
eval() [2/2]
template<class VectorType > void shark::ConcatenatedModel< VectorType >::eval (BatchInputType const & patterns, BatchOutputType & outputs, State & state) const inline virtual
Standard interface for evaluating the response of the model to a batch of patterns.
Parameters
patterns the inputs of the model
outputs the predictions or response of the model to every pattern
state intermediate results stored by eval which can be reused for derivative computation.
Implements shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 175 of file ConcatenatedModel.h.
References shark::State::toState().
hiddenResponses()
template<class VectorType > BatchOutputType const & shark::ConcatenatedModel< VectorType >::hiddenResponses (State const & state, std::size_t index) const inline
Definition at line 156 of file ConcatenatedModel.h.
References shark::State::toState().
hiddenState()
template<class VectorType > State const & shark::ConcatenatedModel< VectorType >::hiddenState (State const & state, std::size_t index) const inline
Definition at line 161 of file ConcatenatedModel.h.
References shark::State::toState().
inputShape()
template<class VectorType > Shape shark::ConcatenatedModel< VectorType >::inputShape () const inline virtual
Returns the expected shape of the input.
Implements shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 72 of file ConcatenatedModel.h.
name()
template<class VectorType > std::string shark::ConcatenatedModel< VectorType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 67 of file ConcatenatedModel.h.
numberOfParameters()
template<class VectorType > std::size_t shark::ConcatenatedModel< VectorType >::numberOfParameters () const inline virtual
Return the number of parameters.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 138 of file ConcatenatedModel.h.
Referenced by shark::ConcatenatedModel< VectorType >::parameterVector(), shark::ConcatenatedModel< VectorType >::weightedDerivatives(), and shark::ConcatenatedModel< VectorType >::weightedParameterDerivative().
outputShape()
template<class VectorType > Shape shark::ConcatenatedModel< VectorType >::outputShape () const inline virtual
Returns the shape of the output.
Implements shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 76 of file ConcatenatedModel.h.
parameterVector()
template<class VectorType > ParameterVectorType shark::ConcatenatedModel< VectorType >::parameterVector () const inline virtual
Return the parameter vector.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 116 of file ConcatenatedModel.h.
References shark::ConcatenatedModel< VectorType >::numberOfParameters().
read()
template<class VectorType > void shark::ConcatenatedModel< VectorType >::read (InArchive & archive) inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 279 of file ConcatenatedModel.h.
setParameterVector()
template<class VectorType > void shark::ConcatenatedModel< VectorType >::setParameterVector (ParameterVectorType const & newParameters) inline virtual
Set the parameter vector.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 128 of file ConcatenatedModel.h.
weightedDerivatives()
template<class VectorType > virtual void shark::ConcatenatedModel< VectorType >::weightedDerivatives (BatchInputType const & patterns, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, ParameterVectorType & parameterDerivative, BatchInputType & inputDerivative) const inline virtual
calculates weighted input and parameter derivative at the same time
Sometimes, both derivatives are needed at the same time. But sometimes, when calculating the weighted parameter derivative, the input derivative can be calculated for free. This is for example true for the feed-forward neural networks. However, there exists the obvious default implementation that just calculates the derivatives one after another.
Parameters
patterns the patterns to evaluate
outputs the target outputs
coefficients the coefficients which are used to calculate the weighted sum
state intermediate results stored by eval to sped up calculations of the derivatives
parameterDerivative the calculated parameter derivative as sum over all derivates of all patterns
inputDerivative the calculated derivative for every pattern
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 246 of file ConcatenatedModel.h.
References shark::ConcatenatedModel< VectorType >::numberOfParameters(), shark::swap(), and shark::State::toState().
weightedInputDerivative()
template<class VectorType > void shark::ConcatenatedModel< VectorType >::weightedInputDerivative (BatchInputType const & patterns, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, BatchOutputType & derivatives) const inline
Definition at line 224 of file ConcatenatedModel.h.
References shark::swap(), and shark::State::toState().
weightedParameterDerivative()
template<class VectorType > void shark::ConcatenatedModel< VectorType >::weightedParameterDerivative (BatchInputType const & pattern, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, ParameterVectorType & derivative) const inline virtual
calculates the weighted sum of derivatives w.r.t the parameters.
Parameters
pattern the patterns to evaluate
outputs the target outputs
coefficients the coefficients which are used to calculate the weighted sum for every pattern
state intermediate results stored by eval to speed up calculations of the derivatives
derivative the calculated derivative as sum over all derivates of all patterns
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 187 of file ConcatenatedModel.h.
References shark::ConcatenatedModel< VectorType >::numberOfParameters(), shark::swap(), and shark::State::toState().
write()
template<class VectorType > void shark::ConcatenatedModel< VectorType >::write (OutArchive & archive) const inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 287 of file ConcatenatedModel.h.
The documentation for this class was generated from the following file:
include/shark/Models/ConcatenatedModel.h