shark::KernelMatrix< InputType, CacheType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::KernelMatrix< InputType, CacheType > Class Template Reference
Kernel Gram matrix.
#include <shark/LinAlg/KernelMatrix.h>
Public Types
typedef CacheType QpFloatType
Public Member Functions
KernelMatrix (AbstractKernelFunction< InputType > const &kernelfunction, Data< InputType > const &data)
QpFloatType operator() (std::size_t i, std::size_t j) const
return a single matrix entry
QpFloatType entry (std::size_t i, std::size_t j) const
return a single matrix entry
void row (std::size_t i, std::size_t start, std::size_t end, QpFloatType *storage) const
Computes the i-th row of the kernel matrix.
template<class M >
void matrix (blas::matrix_expression< M, blas::cpu_tag > &storage) const
Computes the kernel-matrix.
void flipColumnsAndRows (std::size_t i, std::size_t j)
swap two variables
std::size_t size () const
return the size of the quadratic matrix
unsigned long long getAccessCount () const
query the kernel access counter
void resetAccessCount ()
reset the kernel access counter
Protected Types
typedef Batch< InputType >::const_iterator PointerType
Protected Attributes
const AbstractKernelFunction< InputType > & kernel
Kernel function defining the kernel Gram matrix.
Data< InputType > m_data
std::vector< PointerType > x
Array of data pointers for kernel evaluations.
unsigned long long m_accessCounter
counter for the kernel accesses
Detailed Description
template<class InputType, class CacheType>
class shark::KernelMatrix< InputType, CacheType >
Kernel Gram matrix.
The KernelMatrix is the most prominent type of matrix for quadratic programming. It provides the Gram matrix of a fixed data set with respect to an inner product implicitly defined by a kernel function.
NOTE: The KernelMatrix class stores pointers to the data, instead of maintaining a copy of the data. Thus, it implicitly assumes that the dataset is not altered during the lifetime of the KernelMatrix object. This condition is ensured as long as the class is used via the various SVM-trainers.
Definition at line 71 of file KernelMatrix.h.
Member Typedef Documentation
PointerType
template<class InputType , class CacheType > typedef Batch<InputType>::const_iterator shark::KernelMatrix< InputType, CacheType >::PointerType protected
Definition at line 150 of file KernelMatrix.h.
QpFloatType
template<class InputType , class CacheType > typedef CacheType shark::KernelMatrix< InputType, CacheType >::QpFloatType
Definition at line 74 of file KernelMatrix.h.
Constructor & Destructor Documentation
KernelMatrix()
template<class InputType , class CacheType > shark::KernelMatrix< InputType, CacheType >::KernelMatrix (AbstractKernelFunction< InputType > const & kernelfunction, Data< InputType > const & data) inline
Constructor
Parameters
kernelfunction kernel function defining the Gram matrix
data data to evaluate the kernel function
Definition at line 79 of file KernelMatrix.h.
References shark::Data< Type >::elements(), shark::KernelMatrix< InputType, CacheType >::m_data, shark::Data< Type >::numberOfElements(), and shark::KernelMatrix< InputType, CacheType >::x.
Member Function Documentation
entry()
template<class InputType , class CacheType > QpFloatType shark::KernelMatrix< InputType, CacheType >::entry (std::size_t i, std::size_t j) const inline
return a single matrix entry
Definition at line 98 of file KernelMatrix.h.
References shark::AbstractKernelFunction< InputTypeT >::eval(), shark::KernelMatrix< InputType, CacheType >::kernel, shark::KernelMatrix< InputType, CacheType >::m_accessCounter, and shark::KernelMatrix< InputType, CacheType >::x.
Referenced by shark::KernelMatrix< InputType, CacheType >::operator()().
flipColumnsAndRows()
template<class InputType , class CacheType > void shark::KernelMatrix< InputType, CacheType >::flipColumnsAndRows (std::size_t i, std::size_t j) inline
swap two variables
Definition at line 127 of file KernelMatrix.h.
References shark::swap(), and shark::KernelMatrix< InputType, CacheType >::x.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::flipColumnsAndRows(), and shark::RegularizedKernelMatrix< InputType, CacheType >::flipColumnsAndRows().
getAccessCount()
template<class InputType , class CacheType > unsigned long long shark::KernelMatrix< InputType, CacheType >::getAccessCount () const inline
query the kernel access counter
Definition at line 137 of file KernelMatrix.h.
References shark::KernelMatrix< InputType, CacheType >::m_accessCounter.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::getAccessCount(), shark::RegularizedKernelMatrix< InputType, CacheType >::getAccessCount(), and shark::OneClassSvmTrainer< InputType, CacheType >::trainSVM().
matrix()
template<class InputType , class CacheType > template<class M > void shark::KernelMatrix< InputType, CacheType >::matrix (blas::matrix_expression< M, blas::cpu_tag > & storage) const inline
Computes the kernel-matrix.
Definition at line 120 of file KernelMatrix.h.
References shark::calculateRegularizedKernelMatrix(), shark::KernelMatrix< InputType, CacheType >::kernel, and shark::KernelMatrix< InputType, CacheType >::m_data.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::matrix(), and shark::RegularizedKernelMatrix< InputType, CacheType >::matrix().
operator()()
template<class InputType , class CacheType > QpFloatType shark::KernelMatrix< InputType, CacheType >::operator() (std::size_t i, std::size_t j) const inline
return a single matrix entry
Definition at line 94 of file KernelMatrix.h.
References shark::KernelMatrix< InputType, CacheType >::entry().
resetAccessCount()
template<class InputType , class CacheType > void shark::KernelMatrix< InputType, CacheType >::resetAccessCount () inline
reset the kernel access counter
Definition at line 141 of file KernelMatrix.h.
References shark::KernelMatrix< InputType, CacheType >::m_accessCounter.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::resetAccessCount(), and shark::RegularizedKernelMatrix< InputType, CacheType >::resetAccessCount().
row()
template<class InputType , class CacheType > void shark::KernelMatrix< InputType, CacheType >::row (std::size_t i, std::size_t start, std::size_t end, QpFloatType * storage) const inline
Computes the i-th row of the kernel matrix.
The entries start,...,end of the i-th row are computed and stored in storage. There must be enough room for this operation preallocated.
Definition at line 108 of file KernelMatrix.h.
References shark::AbstractKernelFunction< InputTypeT >::eval(), shark::KernelMatrix< InputType, CacheType >::kernel, shark::KernelMatrix< InputType, CacheType >::m_accessCounter, SHARK_PARALLEL_FOR, and shark::KernelMatrix< InputType, CacheType >::x.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::row(), and shark::RegularizedKernelMatrix< InputType, CacheType >::row().
size()
template<class InputType , class CacheType > std::size_t shark::KernelMatrix< InputType, CacheType >::size () const inline
return the size of the quadratic matrix
Definition at line 133 of file KernelMatrix.h.
References shark::KernelMatrix< InputType, CacheType >::x.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::size(), and shark::RegularizedKernelMatrix< InputType, CacheType >::size().
Member Data Documentation
kernel
template<class InputType , class CacheType > const AbstractKernelFunction<InputType>& shark::KernelMatrix< InputType, CacheType >::kernel protected
Kernel function defining the kernel Gram matrix.
Definition at line 146 of file KernelMatrix.h.
Referenced by shark::KernelMatrix< InputType, CacheType >::entry(), shark::KernelMatrix< InputType, CacheType >::matrix(), and shark::KernelMatrix< InputType, CacheType >::row().
m_accessCounter
template<class InputType , class CacheType > unsigned long long shark::KernelMatrix< InputType, CacheType >::m_accessCounter mutable protected
counter for the kernel accesses
Definition at line 155 of file KernelMatrix.h.
Referenced by shark::KernelMatrix< InputType, CacheType >::entry(), shark::KernelMatrix< InputType, CacheType >::getAccessCount(), shark::KernelMatrix< InputType, CacheType >::resetAccessCount(), and shark::KernelMatrix< InputType, CacheType >::row().
m_data
template<class InputType , class CacheType > Data<InputType> shark::KernelMatrix< InputType, CacheType >::m_data protected
Definition at line 148 of file KernelMatrix.h.
Referenced by shark::KernelMatrix< InputType, CacheType >::KernelMatrix(), and shark::KernelMatrix< InputType, CacheType >::matrix().
x
template<class InputType , class CacheType > std::vector<PointerType> shark::KernelMatrix< InputType, CacheType >::x protected
Array of data pointers for kernel evaluations.
Definition at line 152 of file KernelMatrix.h.
Referenced by shark::KernelMatrix< InputType, CacheType >::entry(), shark::KernelMatrix< InputType, CacheType >::flipColumnsAndRows(), shark::KernelMatrix< InputType, CacheType >::KernelMatrix(), shark::KernelMatrix< InputType, CacheType >::row(), and shark::KernelMatrix< InputType, CacheType >::size().
The documentation for this class was generated from the following file:
include/shark/LinAlg/KernelMatrix.h