shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT > Class Template Reference abstract
Algorithms to find a local minimum of\ref objfunctions.
An optimizer that optimizes general objective functions.
#include <shark/Algorithms/AbstractOptimizer.h>
Public Types
enum Feature {
REQUIRES_VALUE = 1 , REQUIRES_FIRST_DERIVATIVE = 2 , REQUIRES_SECOND_DERIVATIVE = 4 , CAN_SOLVE_CONSTRAINED = 8 ,
REQUIRES_CLOSEST_FEASIBLE = 16
}
Models features that the optimizer requires from the objective function.
typedef PointType SearchPointType
typedef ResultT ResultType
typedef SolutionTypeT SolutionType
typedef AbstractObjectiveFunction< PointType, ResultType > ObjectiveFunctionType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
const Features & features () const
virtual void updateFeatures ()
bool requiresValue () const
bool requiresFirstDerivative () const
bool requiresSecondDerivative () const
bool canSolveConstrained () const
bool requiresClosestFeasible () const
virtual ~AbstractOptimizer ()
virtual std::size_t numInitPoints () const =0
Returns the number of points this method requires for initialisation.
virtual void init (ObjectiveFunctionType const &function)
Initialize the optimizer for the supplied objective function.
virtual void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initPoints)=0
Initialize the optimizer for the supplied objective function using a set of initialisation points.
virtual void step (ObjectiveFunctionType const &function)=0
Carry out one step of the optimizer for the supplied objective function.
virtual SolutionType const & solution () const =0
Accesses the best solution obtained so far.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
virtual std::string name () const
returns the name of the object
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Member Functions
void checkFeatures (ObjectiveFunctionType const &objectiveFunction)
Convenience function that checks whether the features of the supplied objective function match with the required features of the optimizer.
Protected Attributes
Features m_features
Detailed Description
template<typename PointType, typename ResultT, typename SolutionTypeT>
class shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
An optimizer that optimizes general objective functions.
After construction and configurationg the optimizer, init() is called with the objective function to be used. After that step() can be called until the required solution is found. The solution can be queried using solution(). The type of the solution depends on the optimisation problem at hand. It is allowed to add constrains on the features the objective function needs to offer
These are:
REQUIRES_VALUE: The function is evaluated to use the optimizer and the HAS_VALUE-flag must be set
REQUIRES_FIRST_DERIVATIVE: The first derivative needs to be evaluated and
HAS_FIRST_DERIVATIVE must be set
REQUIRES_SECOND_DERIVATIVE: The second derivative needs to be evaluated and
HAS_SECOND_DERIVATIVE must be set
CAN_SOLVE_CONSTRAINED: The optimizer can solve functions which are constrained and where the IS_CONSTRAINED_FEATURE is set.
REQUIRES_CLOSEST_FEASIBLE: If the function is constrained, it must offer a way to construct the closest feasible point and
CAN_PROVIDE_CLOSEST_FEASIBLE must be set
Also when init() is called as offered by the AbstractOptimizer interface, the function is required to have the CAN_PROPOSE_STARTING_POINT flag.
Template Parameters
PointType The type of search space the optimizer works upon.
ResultT The objective space the optimizer works upon.
SolutionTypeT The type of the final solution.
Definition at line 73 of file AbstractOptimizer.h.
Member Typedef Documentation
FeatureNotAvailableException
template<typename PointType , typename ResultT , typename SolutionTypeT > typedef TypedFeatureNotAvailableException<Feature> shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::FeatureNotAvailableException
Definition at line 90 of file AbstractOptimizer.h.
Features
template<typename PointType , typename ResultT , typename SolutionTypeT > typedef TypedFlags<Feature> shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::Features
Definition at line 90 of file AbstractOptimizer.h.
ObjectiveFunctionType
template<typename PointType , typename ResultT , typename SolutionTypeT > typedef AbstractObjectiveFunction<PointType,ResultType> shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::ObjectiveFunctionType
Definition at line 78 of file AbstractOptimizer.h.
ResultType
template<typename PointType , typename ResultT , typename SolutionTypeT > typedef ResultT shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::ResultType
Definition at line 76 of file AbstractOptimizer.h.
SearchPointType
template<typename PointType , typename ResultT , typename SolutionTypeT > typedef PointType shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::SearchPointType
Definition at line 75 of file AbstractOptimizer.h.
SolutionType
template<typename PointType , typename ResultT , typename SolutionTypeT > typedef SolutionTypeT shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::SolutionType
Definition at line 77 of file AbstractOptimizer.h.
Member Enumeration Documentation
Feature
template<typename PointType , typename ResultT , typename SolutionTypeT > enum shark::AbstractOptimizer::Feature
Models features that the optimizer requires from the objective function.
See also
AbstractObjectiveFunction
Enumerator
REQUIRES_VALUE
REQUIRES_FIRST_DERIVATIVE
REQUIRES_SECOND_DERIVATIVE
CAN_SOLVE_CONSTRAINED
REQUIRES_CLOSEST_FEASIBLE
Definition at line 82 of file AbstractOptimizer.h.
Constructor & Destructor Documentation
~AbstractOptimizer()
template<typename PointType , typename ResultT , typename SolutionTypeT > virtual shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::~AbstractOptimizer () inline virtual
Definition at line 109 of file AbstractOptimizer.h.
Member Function Documentation
canSolveConstrained()
template<typename PointType , typename ResultT , typename SolutionTypeT > bool shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::canSolveConstrained () const inline
Definition at line 102 of file AbstractOptimizer.h.
References shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::CAN_SOLVE_CONSTRAINED, and shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::features().
Referenced by shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures().
checkFeatures()
template<typename PointType , typename ResultT , typename SolutionTypeT > void shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures (ObjectiveFunctionType const & objectiveFunction) inline protected
Convenience function that checks whether the features of the supplied objective function match with the required features of the optimizer.
Parameters
[in] objectiveFunction The function to match with.
Exceptions
shark::Exception
Definition at line 157 of file AbstractOptimizer.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::canProvideClosestFeasible(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::canSolveConstrained(), shark::AbstractObjectiveFunction< PointType, ResultT >::hasFirstDerivative(), shark::AbstractObjectiveFunction< PointType, ResultT >::hasSecondDerivative(), shark::AbstractObjectiveFunction< PointType, ResultT >::hasValue(), shark::AbstractObjectiveFunction< PointType, ResultT >::isConstrained(), shark::INameable::name(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresClosestFeasible(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresFirstDerivative(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresSecondDerivative(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresValue(), and SHARK_RUNTIME_CHECK.
Referenced by shark::LMCMA::init(), shark::VDCMA::init(), shark::IndicatorBasedMOCMA< Indicator >::init(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::init(), shark::SMSEMOA::init(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::init(), shark::GridSearch::init(), shark::NestedGridSearch::init(), shark::PointSearch::init(), and shark::SimplexDownhill::init().
features()
template<typename PointType , typename ResultT , typename SolutionTypeT > const Features & shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::features () const inline
Definition at line 90 of file AbstractOptimizer.h.
Referenced by shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::canSolveConstrained(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresClosestFeasible(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresFirstDerivative(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresSecondDerivative(), and shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresValue().
init() [1/2]
template<typename PointType , typename ResultT , typename SolutionTypeT > virtual void shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::init (ObjectiveFunctionType const & function) inline virtual
Initialize the optimizer for the supplied objective function.
Be aware that function.init() has to be called before calling this function! This function will initialize the algorithm with a number of points proposed by the function. Note that this must fail if the function can not propose starting point(s).
Parameters
[in] function The objective function to initialize for.
Definition at line 124 of file AbstractOptimizer.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::canProposeStartingPoint(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::init(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::numInitPoints(), shark::AbstractObjectiveFunction< PointType, ResultT >::proposeStartingPoint(), and SHARK_RUNTIME_CHECK.
Referenced by shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::init().
init() [2/2]
template<typename PointType , typename ResultT , typename SolutionTypeT > virtual void shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::init (ObjectiveFunctionType const & function, std::vector< SearchPointType > const & initPoints) pure virtual
Initialize the optimizer for the supplied objective function using a set of initialisation points.
Most single objective algorithms only require a single point. However multi-objective algorithms need a set of initialisation points. The number of points required should be numInitPoints(). Otherwise the algorithm might use heuristics to generate additional points if needed.
Be aware that function.init() has to be called before calling this function!
Parameters
[in] function The objective function to initialize for.
[in] initPoints points used for initialisation. Should be at least numInitPoints().
Implemented in shark::AbstractSingleObjectiveOptimizer< PointType >.
numInitPoints()
template<typename PointType , typename ResultT , typename SolutionTypeT > virtual std::size_t shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::numInitPoints () const pure virtual
Returns the number of points this method requires for initialisation.
The number of points supplied is allowed to be smaller, however in this case the optimizer will resort to techniques generating additional points if needed.
Implemented in shark::AbstractSingleObjectiveOptimizer< PointType >, shark::AbstractSingleObjectiveOptimizer< RealVector >, shark::AbstractSingleObjectiveOptimizer< SearchPointType >, shark::IndicatorBasedMOCMA< Indicator >, shark::MOEAD, shark::IndicatorBasedRealCodedNSGAII< Indicator >, shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >, shark::RVEA, shark::SMSEMOA, and shark::IndicatorBasedSteadyStateMOCMA< Indicator >.
Referenced by shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::init().
requiresClosestFeasible()
template<typename PointType , typename ResultT , typename SolutionTypeT > bool shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresClosestFeasible () const inline
Definition at line 105 of file AbstractOptimizer.h.
References shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::features(), and shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::REQUIRES_CLOSEST_FEASIBLE.
Referenced by shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures().
requiresFirstDerivative()
template<typename PointType , typename ResultT , typename SolutionTypeT > bool shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresFirstDerivative () const inline
Definition at line 96 of file AbstractOptimizer.h.
References shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::features(), and shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::REQUIRES_FIRST_DERIVATIVE.
Referenced by shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures().
requiresSecondDerivative()
template<typename PointType , typename ResultT , typename SolutionTypeT > bool shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresSecondDerivative () const inline
Definition at line 99 of file AbstractOptimizer.h.
References shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::features(), and shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::REQUIRES_SECOND_DERIVATIVE.
Referenced by shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures().
requiresValue()
template<typename PointType , typename ResultT , typename SolutionTypeT > bool shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::requiresValue () const inline
Definition at line 92 of file AbstractOptimizer.h.
References shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::features(), and shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::REQUIRES_VALUE.
Referenced by shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures().
solution()
template<typename PointType , typename ResultT , typename SolutionTypeT > virtual SolutionType const & shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::solution () const pure virtual
Accesses the best solution obtained so far.
Returns
An immutable reference to the best solution obtained so far.
Implemented in shark::AbstractMultiObjectiveOptimizer< PointTypeT >, shark::AbstractMultiObjectiveOptimizer< RealVector >, shark::AbstractSingleObjectiveOptimizer< PointType >, shark::AbstractSingleObjectiveOptimizer< RealVector >, and shark::AbstractSingleObjectiveOptimizer< SearchPointType >.
step()
template<typename PointType , typename ResultT , typename SolutionTypeT > virtual void shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::step (ObjectiveFunctionType const & function) pure virtual
Carry out one step of the optimizer for the supplied objective function.
Parameters
[in] function The objective function to initialize for.
Referenced by shark::OptimizationTrainer< Model, LabelTypeT >::train().
updateFeatures()
template<typename PointType , typename ResultT , typename SolutionTypeT > virtual void shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::updateFeatures () inline virtual
Definition at line 90 of file AbstractOptimizer.h.
Member Data Documentation
m_features
template<typename PointType , typename ResultT , typename SolutionTypeT > Features shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::m_features protected
Definition at line 90 of file AbstractOptimizer.h.
Referenced by shark::CMSA::CMSA(), shark::IndicatorBasedMOCMA< Indicator >::IndicatorBasedMOCMA(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::IndicatorBasedRealCodedNSGAII(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::IndicatorBasedSteadyStateMOCMA(), shark::LBFGS< SearchPointType >::LBFGS(), shark::LMCMA::LMCMA(), shark::SMSEMOA::SMSEMOA(), and shark::VDCMA::VDCMA().
The documentation for this class was generated from the following file:
include/shark/Algorithms/AbstractOptimizer.h