shark::RFTrainer< RealVector > Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::RFTrainer< RealVector > Class Reference
#include <shark/Algorithms/Trainers/RFTrainer.h>
Public Member Functions
RFTrainer (bool computeFeatureImportances=false, bool computeOOBerror=false)
Construct and compute feature importances when training or not.
std::string name () const
From INameable: return the class name.
void setMTry (std::size_t mtry)
void setNTrees (std::size_t numTrees)
Set the number of trees to grow. (default 100)
void setMinSplit (std::size_t numSamples)
Set Minimum number of samples that is split (default 10)
void setMaxDepth (std::size_t maxDepth)
Set Maximum depth of the tree (default 10000)
void setNodeSize (std::size_t nodeSize)
void minImpurity (double impurity)
The minimum impurity below which a a node is considere pure (default 1.e-10)
void epsilon (double distance)
The minimum dtsnace of features to be considered different (detault 1.e-10)
RealVector parameterVector () const
Return the parameter vector.
void setParameterVector (RealVector const &newParameters)
Set the parameter vector.
void train (RFClassifier< LabelType > &model, WeightedLabeledData< RealVector, LabelType > const &dataset)
Train a random forest for classification.
Public Member Functions inherited from shark::AbstractWeightedTrainer< RFClassifier< RealVector > >
virtual void train (ModelType &model, WeightedDatasetType const &dataset)=0
Executes the algorithm and trains a model on the given weighted data.
virtual void train (ModelType &model, DatasetType const &dataset)
Executes the algorithm and trains a model on the given unweighted data.
Public Member Functions inherited from shark::AbstractTrainer< Model, LabelTypeT >
virtual void train (ModelType &model, DatasetType const &dataset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Public Member Functions inherited from shark::IParameterizable< RealVector >
virtual ~IParameterizable ()
virtual std::size_t numberOfParameters () const
Return the number of parameters.
Additional Inherited Members
Public Types inherited from shark::AbstractWeightedTrainer< RFClassifier< RealVector > >
typedef base_type::ModelType ModelType
typedef base_type::InputType InputType
typedef base_type::LabelType LabelType
typedef base_type::DatasetType DatasetType
typedef WeightedLabeledData< InputType, LabelType > WeightedDatasetType
Public Types inherited from shark::AbstractTrainer< Model, LabelTypeT >
typedef Model ModelType
typedef ModelType::InputType InputType
typedef LabelTypeT LabelType
typedef LabeledData< InputType, LabelType > DatasetType
Public Types inherited from shark::IParameterizable< RealVector >
typedef RealVector ParameterVectorType
Detailed Description
Definition at line 194 of file RFTrainer.h.
Constructor & Destructor Documentation
RFTrainer()
shark::RFTrainer< RealVector >::RFTrainer (bool computeFeatureImportances = false, bool computeOOBerror = false) inline
Construct and compute feature importances when training or not.
Definition at line 199 of file RFTrainer.h.
Member Function Documentation
epsilon()
void shark::RFTrainer< RealVector >::epsilon (double distance) inline
The minimum dtsnace of features to be considered different (detault 1.e-10)
Definition at line 237 of file RFTrainer.h.
minImpurity()
void shark::RFTrainer< RealVector >::minImpurity (double impurity) inline
The minimum impurity below which a a node is considere pure (default 1.e-10)
Definition at line 234 of file RFTrainer.h.
name()
std::string shark::RFTrainer< RealVector >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 212 of file RFTrainer.h.
parameterVector()
RealVector shark::RFTrainer< RealVector >::parameterVector () const inline virtual
Return the parameter vector.
Reimplemented from shark::IParameterizable< RealVector >.
Definition at line 240 of file RFTrainer.h.
setMaxDepth()
void shark::RFTrainer< RealVector >::setMaxDepth (std::size_t maxDepth) inline
Set Maximum depth of the tree (default 10000)
Definition at line 227 of file RFTrainer.h.
setMinSplit()
void shark::RFTrainer< RealVector >::setMinSplit (std::size_t numSamples) inline
Set Minimum number of samples that is split (default 10)
Definition at line 224 of file RFTrainer.h.
setMTry()
void shark::RFTrainer< RealVector >::setMTry (std::size_t mtry) inline
Set the number of random attributes to investigate at each node.
Defualt is 0 which is translated to inputDim(data)/3 during training
Definition at line 218 of file RFTrainer.h.
setNodeSize()
void shark::RFTrainer< RealVector >::setNodeSize (std::size_t nodeSize) inline
Controls when a node is considered pure. If set to 1, a node is pure when it only consists of a single node.(default 5)
Definition at line 231 of file RFTrainer.h.
setNTrees()
void shark::RFTrainer< RealVector >::setNTrees (std::size_t numTrees) inline
Set the number of trees to grow. (default 100)
Definition at line 221 of file RFTrainer.h.
setParameterVector()
void shark::RFTrainer< RealVector >::setParameterVector (RealVector const & newParameters) inline virtual
Set the parameter vector.
Reimplemented from shark::IParameterizable< RealVector >.
Definition at line 243 of file RFTrainer.h.
References SHARK_ASSERT.
train()
void shark::RFTrainer< RealVector >::train (RFClassifier< LabelType > & model, WeightedLabeledData< RealVector, LabelType > const & dataset) inline
Train a random forest for classification.
Definition at line 249 of file RFTrainer.h.
References shark::Ensemble< ModelType, OutputType >::addModel(), shark::bootstrap(), shark::Ensemble< ModelType, OutputType >::clearModels(), shark::RFClassifier< LabelType >::computeFeatureImportances(), shark::RFClassifier< LabelType >::computeOOBerror(), shark::random::discrete(), shark::Data< Type >::elements(), shark::random::globalRng, shark::inputDimension(), shark::WeightedLabeledData< InputT, LabelT >::inputs(), shark::WeightedLabeledData< InputT, LabelT >::labels(), SHARK_CRITICAL_REGION, and SHARK_PARALLEL_FOR.
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/RFTrainer.h