shark::statistics::ResultTable< Parameter > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::statistics::ResultTable< Parameter > Class Template Reference
Stores results of a running experiment.
#include <shark/Statistics/Statistics.h>
Public Types
typedef std::map< Parameter, std::vector< RealVector > >::const_iterator const_iterator
Public Member Functions
ResultTable (std::size_t numDimensions, std::string const &parameterName="unnamed")
std::string const & parameterName () const
void setDimensionName (std::size_t i, std::string const &name)
std::string const & dimensionName (std::size_t i) const
std::size_t numDimensions () const
void update (Parameter const &parameter, RealVector const &point)
void update (Parameter const &parameter, double value)
void update (Parameter const &parameter, double value1, double value2)
void update (Parameter const &parameter, double value1, double value2, double value3)
std::vector< RealVector > const & operator[] (Parameter const &param) const
const_iterator begin () const
const_iterator end () const
std::size_t numParams () const
Parameter const & parameterValue (std::size_t i) const
template<class Archive >
void serialize (Archive &ar, const unsigned int file_version)
Detailed Description
template<class Parameter>
class shark::statistics::ResultTable< Parameter >
Stores results of a running experiment.
This is a simple three dimensional table with the dimensions. Experiments are thought of having a varied parameter (for example the algorithm names when several algorithms are compared) and for each parameter a set of vector valued points is stored - one vector for each trial of the experiment for a given parameter. It is posible to give every parameter and the whole table a name which adds meta information, for example to generate outputs.
Definition at line 202 of file Statistics.h.
Member Typedef Documentation
const_iterator
template<class Parameter > typedef std::map<Parameter,std::vector<RealVector>>::const_iterator shark::statistics::ResultTable< Parameter >::const_iterator
Definition at line 204 of file Statistics.h.
Constructor & Destructor Documentation
ResultTable()
template<class Parameter > shark::statistics::ResultTable< Parameter >::ResultTable (std::size_t numDimensions, std::string const & parameterName = "unnamed") inline
Definition at line 206 of file Statistics.h.
Member Function Documentation
begin()
template<class Parameter > const_iterator shark::statistics::ResultTable< Parameter >::begin () const inline
Definition at line 254 of file Statistics.h.
Referenced by shark::statistics::ResultTable< Parameter >::parameterValue().
dimensionName()
template<class Parameter > std::string const & shark::statistics::ResultTable< Parameter >::dimensionName (std::size_t i) const inline
Definition at line 217 of file Statistics.h.
end()
template<class Parameter > const_iterator shark::statistics::ResultTable< Parameter >::end () const inline
Definition at line 257 of file Statistics.h.
numDimensions()
template<class Parameter > std::size_t shark::statistics::ResultTable< Parameter >::numDimensions () const inline
Definition at line 221 of file Statistics.h.
Referenced by shark::statistics::ResultTable< Parameter >::update().
numParams()
template<class Parameter > std::size_t shark::statistics::ResultTable< Parameter >::numParams () const inline
Definition at line 261 of file Statistics.h.
operator[]()
template<class Parameter > std::vector< RealVector > const & shark::statistics::ResultTable< Parameter >::operator[] (Parameter const & param) const inline
Definition at line 250 of file Statistics.h.
parameterName()
template<class Parameter > std::string const & shark::statistics::ResultTable< Parameter >::parameterName () const inline
Definition at line 209 of file Statistics.h.
parameterValue()
template<class Parameter > Parameter const & shark::statistics::ResultTable< Parameter >::parameterValue (std::size_t i) const inline
Definition at line 265 of file Statistics.h.
References shark::statistics::ResultTable< Parameter >::begin().
serialize()
template<class Parameter > template<class Archive > void shark::statistics::ResultTable< Parameter >::serialize (Archive & ar, const unsigned int file_version) inline
Definition at line 273 of file Statistics.h.
setDimensionName()
template<class Parameter > void shark::statistics::ResultTable< Parameter >::setDimensionName (std::size_t i, std::string const & name) inline
Definition at line 213 of file Statistics.h.
Referenced by main().
update() [1/4]
template<class Parameter > void shark::statistics::ResultTable< Parameter >::update (Parameter const & parameter, double value) inline
Definition at line 230 of file Statistics.h.
References shark::statistics::ResultTable< Parameter >::update().
update() [2/4]
template<class Parameter > void shark::statistics::ResultTable< Parameter >::update (Parameter const & parameter, double value1, double value2) inline
Definition at line 235 of file Statistics.h.
References shark::statistics::ResultTable< Parameter >::update().
update() [3/4]
template<class Parameter > void shark::statistics::ResultTable< Parameter >::update (Parameter const & parameter, double value1, double value2, double value3) inline
Definition at line 242 of file Statistics.h.
References shark::statistics::ResultTable< Parameter >::update().
update() [4/4]
template<class Parameter > void shark::statistics::ResultTable< Parameter >::update (Parameter const & parameter, RealVector const & point) inline
Definition at line 225 of file Statistics.h.
References shark::statistics::ResultTable< Parameter >::numDimensions(), and SIZE_CHECK.
Referenced by main(), shark::statistics::ResultTable< Parameter >::update(), shark::statistics::ResultTable< Parameter >::update(), and shark::statistics::ResultTable< Parameter >::update().
The documentation for this class was generated from the following file:
include/shark/Statistics/Statistics.h