shark::PointSetKernel< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::PointSetKernel< InputType > Class Template Reference
Models » Kernels
Normalized version of a kernel function.
#include <shark/Models/Kernels/PointSetKernel.h>
Public Types
typedef base_type::BatchInputType BatchInputType
typedef base_type::ConstBatchInputReference ConstBatchInputReference
typedef base_type::ConstInputReference ConstInputReference
Public Types inherited from shark::AbstractKernelFunction< InputTypeT >
enum Feature { HAS_FIRST_PARAMETER_DERIVATIVE = 1 , HAS_FIRST_INPUT_DERIVATIVE = 2 , IS_NORMALIZED = 4 , SUPPORTS_VARIABLE_INPUT_SIZE = 8 }
enumerations of kerneland metric features (flags)
typedef base_type::InputType InputType
Input type of the Kernel.
typedef base_type::BatchInputType BatchInputType
batch input type of the kernel
typedef base_type::ConstInputReference ConstInputReference
Const references to InputType.
typedef base_type::ConstBatchInputReference ConstBatchInputReference
Const references to BatchInputType.
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::AbstractMetric< InputTypeT >
typedef InputTypeT InputType
Input type of the Kernel.
typedef Batch< InputTypeT >::type BatchInputType
batch input type of the kernel
typedef ConstProxyReference< InputTypeconst >::type ConstInputReference
Const references to InputType.
typedef ConstProxyReference< BatchInputTypeconst >::type ConstBatchInputReference
Const references to BatchInputType.
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
PointSetKernel (AbstractKernelFunction< InputType > *base)
std::string name () const
returns the name of the object
RealVector parameterVector () const
Return the parameter vector.
void setParameterVector (RealVector const &newParameters)
Set the parameter vector.
std::size_t numberOfParameters () const
Return the number of parameters.
boost::shared_ptr< State > createState () const
creates the internal state of the kernel
double eval (ConstInputReference x1, ConstInputReference x2) const
void eval (ConstBatchInputReference const &batchX1, ConstBatchInputReference const &batchX2, RealMatrix &result, State &state) const
void eval (ConstBatchInputReference const &batchX1, ConstBatchInputReference const &batchX2, RealMatrix &result) const
void weightedParameterDerivative (ConstBatchInputReference const &batchX1, ConstBatchInputReference const &batchX2, RealMatrix const &coefficients, State const &state, RealVector &gradient) const
Public Member Functions inherited from shark::AbstractKernelFunction< InputTypeT >
AbstractKernelFunction ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
bool hasFirstInputDerivative () const
bool isNormalized () const
bool supportsVariableInputSize () const
virtual double eval (ConstInputReference x1, ConstInputReference x2) const
Evaluates the kernel function.
double operator() (ConstInputReference x1, ConstInputReference x2) const
Convenience operator which evaluates the kernel function.
virtual void eval (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2, RealMatrix &result, State &state) const =0
Evaluates the subset of the KernelGram matrix which is defined by X1(rows) and X2 (columns).
virtual void eval (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2, RealMatrix &result) const
Evaluates the subset of the KernelGram matrix which is defined by X1(rows) and X2 (columns).
RealMatrix operator() (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2) const
Evaluates the subset of the KernelGram matrix which is defined by X1(rows) and X2 (columns).
virtual void weightedParameterDerivative (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2, RealMatrix const &coefficients, State const &state, RealVector &gradient) const
Computes the gradient of the parameters as a weighted sum over the gradient of all elements of the batch.
virtual void weightedInputDerivative (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2, RealMatrix const &coefficientsX2, State const &state, BatchInputType &gradient) const
Calculates the derivative of the inputs X1 (only x1!).
virtual double featureDistanceSqr (ConstInputReference x1, ConstInputReference x2) const
Computes the squared distance in the kernel induced feature space.
virtual RealMatrix featureDistanceSqr (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2) const
Computes the squared distance in the kernel induced feature space.
Public Member Functions inherited from shark::AbstractMetric< InputTypeT >
AbstractMetric ()
virtual ~AbstractMetric ()
virtual void read (InArchive &archive)
From ISerializable, reads a metric from an archive.
virtual void write (OutArchive &archive) const
From ISerializable, writes a metric to an archive.
double featureDistance (ConstInputReference x1, ConstInputReference x2) const
Computes the distance in the kernel induced feature space.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Attributes
AbstractKernelFunction< InputType > * m_base
kernel to normalize
Protected Attributes inherited from shark::AbstractKernelFunction< InputTypeT >
Features m_features
Detailed Description
template<class InputType = RealVector>
class shark::PointSetKernel< InputType >
Normalized version of a kernel function.
For a positive definite kernel k, the normalized kernel
\[ \tilde k(x, y) := \frac{k(x, y)}{\sqrt{k(x, x) \cdot k(y, y)}} \]
is again a positive definite kernel function.
Definition at line 51 of file PointSetKernel.h.
Member Typedef Documentation
BatchInputType
template<class InputType = RealVector> typedef base_type::BatchInputType shark::PointSetKernel< InputType >::BatchInputType
Definition at line 68 of file PointSetKernel.h.
ConstBatchInputReference
template<class InputType = RealVector> typedef base_type::ConstBatchInputReference shark::PointSetKernel< InputType >::ConstBatchInputReference
Definition at line 69 of file PointSetKernel.h.
ConstInputReference
template<class InputType = RealVector> typedef base_type::ConstInputReference shark::PointSetKernel< InputType >::ConstInputReference
Definition at line 70 of file PointSetKernel.h.
Constructor & Destructor Documentation
PointSetKernel()
template<class InputType = RealVector> shark::PointSetKernel< InputType >::PointSetKernel (AbstractKernelFunction< InputType > * base) inline
Definition at line 72 of file PointSetKernel.h.
References shark::AbstractKernelFunction< InputTypeT >::HAS_FIRST_PARAMETER_DERIVATIVE, shark::AbstractKernelFunction< InputTypeT >::hasFirstParameterDerivative(), shark::PointSetKernel< InputType >::m_base, shark::AbstractKernelFunction< InputTypeT >::m_features, and SHARK_ASSERT.
Member Function Documentation
createState()
template<class InputType = RealVector> boost::shared_ptr< State > shark::PointSetKernel< InputType >::createState () const inline virtual
creates the internal state of the kernel
Reimplemented from shark::AbstractKernelFunction< InputTypeT >.
Definition at line 94 of file PointSetKernel.h.
eval() [1/3]
template<class InputType = RealVector> void shark::PointSetKernel< InputType >::eval (ConstBatchInputReference const & batchX1, ConstBatchInputReference const & batchX2, RealMatrix & result) const inline
Definition at line 126 of file PointSetKernel.h.
References shark::batchSize(), shark::AbstractKernelFunction< InputTypeT >::eval(), shark::getBatchElement(), and shark::PointSetKernel< InputType >::m_base.
eval() [2/3]
template<class InputType = RealVector> void shark::PointSetKernel< InputType >::eval (ConstBatchInputReference const & batchX1, ConstBatchInputReference const & batchX2, RealMatrix & result, State & state) const inline
Definition at line 110 of file PointSetKernel.h.
References shark::batchSize(), shark::AbstractKernelFunction< InputTypeT >::eval(), shark::getBatchElement(), shark::PointSetKernel< InputType >::m_base, and shark::State::toState().
eval() [3/3]
template<class InputType = RealVector> double shark::PointSetKernel< InputType >::eval (ConstInputReference x1, ConstInputReference x2) const inline
evaluates \(k(x,y) \)
calculates
\[ \tilde k(x, y) := \frac{k(x, y)}{\sqrt{k(x, x) \cdot k(y, y)}} \]
Definition at line 103 of file PointSetKernel.h.
name()
template<class InputType = RealVector> std::string shark::PointSetKernel< InputType >::name () const inline virtual
returns the name of the object
Reimplemented from shark::INameable.
Definition at line 78 of file PointSetKernel.h.
References shark::PointSetKernel< InputType >::m_base, and shark::INameable::name().
numberOfParameters()
template<class InputType = RealVector> std::size_t shark::PointSetKernel< InputType >::numberOfParameters () const inline virtual
Return the number of parameters.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 89 of file PointSetKernel.h.
References shark::PointSetKernel< InputType >::m_base, and shark::IParameterizable< VectorType >::numberOfParameters().
Referenced by shark::PointSetKernel< InputType >::weightedParameterDerivative().
parameterVector()
template<class InputType = RealVector> RealVector shark::PointSetKernel< InputType >::parameterVector () const inline virtual
Return the parameter vector.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 81 of file PointSetKernel.h.
References shark::PointSetKernel< InputType >::m_base, and shark::IParameterizable< VectorType >::parameterVector().
setParameterVector()
template<class InputType = RealVector> void shark::PointSetKernel< InputType >::setParameterVector (RealVector const & newParameters) inline virtual
Set the parameter vector.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 85 of file PointSetKernel.h.
References shark::PointSetKernel< InputType >::m_base, and shark::IParameterizable< VectorType >::setParameterVector().
weightedParameterDerivative()
template<class InputType = RealVector> void shark::PointSetKernel< InputType >::weightedParameterDerivative (ConstBatchInputReference const & batchX1, ConstBatchInputReference const & batchX2, RealMatrix const & coefficients, State const & state, RealVector & gradient) const inline
Definition at line 140 of file PointSetKernel.h.
References shark::batchSize(), shark::getBatchElement(), shark::PointSetKernel< InputType >::m_base, shark::PointSetKernel< InputType >::numberOfParameters(), shark::State::toState(), and shark::AbstractKernelFunction< InputTypeT >::weightedParameterDerivative().
Member Data Documentation
m_base
template<class InputType = RealVector> AbstractKernelFunction<InputType>* shark::PointSetKernel< InputType >::m_base protected
kernel to normalize
Definition at line 168 of file PointSetKernel.h.
Referenced by shark::PointSetKernel< InputType >::eval(), shark::PointSetKernel< InputType >::eval(), shark::PointSetKernel< InputType >::name(), shark::PointSetKernel< InputType >::numberOfParameters(), shark::PointSetKernel< InputType >::parameterVector(), shark::PointSetKernel< InputType >::PointSetKernel(), shark::PointSetKernel< InputType >::setParameterVector(), and shark::PointSetKernel< InputType >::weightedParameterDerivative().
The documentation for this class was generated from the following file:
include/shark/Models/Kernels/PointSetKernel.h