shark::BiasSolver< Matrix > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::BiasSolver< Matrix > Class Template Reference
#include <shark/Algorithms/QP/QpMcBoxDecomp.h>
Public Types
typedef Matrix::QpFloatType QpFloatType
Public Member Functions
BiasSolver (QpMcBoxDecomp< Matrix > *problem)
void solve (RealVector &bias, QpStoppingCondition &stop, QpSparseArray< QpFloatType > const &nu, bool sumToZero, QpSolutionProperties *prop=NULL)
Detailed Description
template<class Matrix>
class shark::BiasSolver< Matrix >
Definition at line 640 of file QpMcBoxDecomp.h.
Member Typedef Documentation
QpFloatType
template<class Matrix > typedef Matrix::QpFloatType shark::BiasSolver< Matrix >::QpFloatType
Definition at line 642 of file QpMcBoxDecomp.h.
Constructor & Destructor Documentation
BiasSolver()
template<class Matrix > shark::BiasSolver< Matrix >::BiasSolver (QpMcBoxDecomp< Matrix > * problem) inline
Definition at line 643 of file QpMcBoxDecomp.h.
Member Function Documentation
solve()
template<class Matrix > void shark::BiasSolver< Matrix >::solve (RealVector & bias, QpStoppingCondition & stop, QpSparseArray< QpFloatType > const & nu, bool sumToZero, QpSolutionProperties * prop = NULL) inline
Definition at line 645 of file QpMcBoxDecomp.h.
References shark::QpSolutionProperties::iterations, shark::QpStoppingCondition::minAccuracy, shark::Timer::now(), shark::QpSparseArray< QpFloatType >::row(), and shark::QpSolver< Problem, SelectionStrategy >::solve().
The documentation for this class was generated from the following file:
include/shark/Algorithms/QP/QpMcBoxDecomp.h