shark::IndicatorBasedRealCodedNSGAII< Indicator > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::IndicatorBasedRealCodedNSGAII< Indicator > Class Template Reference
Algorithms to find a local minimum of\ref objfunctions. » Multi-objective Direct-Search optimizers
Implements the NSGA-II.
#include <shark/Algorithms/DirectSearch/RealCodedNSGAII.h>
Public Member Functions
IndicatorBasedRealCodedNSGAII (random::rng_type &rng=random::globalRng)
Default c'tor.
std::string name () const
returns the name of the object
double crossoverProbability () const
Returns the probability that crossover is applied.
double & crossoverProbability ()
Returns the probability that crossover is applied.
double nm () const
Returns the mutation variation strength parameter.
double & nm ()
Returns a reference to the mutation variation strength parameter.
double nc () const
Returns the crossover variation strength parameter.
double & nc ()
Returns a reference to the crossover variation strength parameter.
std::size_t mu () const
Returns the number of elements in the front.
std::size_t & mu ()
Returns the number of elements in the front.
std::size_t numInitPoints () const
The number of points used for initialization of the algorithm.
Indicator & indicator ()
Returns the indicator used.
Indicator const & indicator () const
Returns the indicator used.
void read (InArchive &archive)
Read the component from the supplied archive.
void write (OutArchive &archive) const
Write the component to the supplied archive.
void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initialSearchPoints)
Initializes the algorithm for the supplied objective function.
void step (ObjectiveFunctionType const &function)
Executes one iteration of the algorithm.
Public Member Functions inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
SolutionType const & solution () const
Accesses the current approximation of the Pareto-set and -front, respectively.
Public Member Functions inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
const Features & features () const
virtual void updateFeatures ()
bool requiresValue () const
bool requiresFirstDerivative () const
bool requiresSecondDerivative () const
bool canSolveConstrained () const
bool requiresClosestFeasible () const
virtual ~AbstractOptimizer ()
virtual void init (ObjectiveFunctionType const &function)
Initialize the optimizer for the supplied objective function.
virtual void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initPoints)=0
Initialize the optimizer for the supplied objective function using a set of initialisation points.
virtual void step (ObjectiveFunctionType const &function)=0
Carry out one step of the optimizer for the supplied objective function.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Types
typedef shark::Individual< RealVector, RealVector > IndividualType
The individual type of the NSGA-II.
Protected Member Functions
void doInit (std::vector< SearchPointType > const &initialSearchPoints, std::vector< ResultType > const &functionValues, RealVector const &lowerBounds, RealVector const &upperBounds, std::size_t mu, double nm, double nc, double crossover_prob)
std::vector< IndividualType > generateOffspring () const
void updatePopulation (std::vector< IndividualType > const &offspringVec)
Protected Member Functions inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
void checkFeatures (ObjectiveFunctionType const &objectiveFunction)
Convenience function that checks whether the features of the supplied objective function match with the required features of the optimizer.
Protected Attributes
std::vector< IndividualType > m_parents
Population of size \(\mu + 1\).
random::rng_type * mpe_rng
Protected Attributes inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
SolutionType m_best
The current Pareto-set/-front.
Protected Attributes inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
Features m_features
Additional Inherited Members
Public Types inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
typedef super::SearchPointType SearchPointType
typedef super::SolutionType SolutionType
typedef super::ObjectiveFunctionType ObjectiveFunctionType
Public Types inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
enum Feature {
REQUIRES_VALUE = 1 , REQUIRES_FIRST_DERIVATIVE = 2 , REQUIRES_SECOND_DERIVATIVE = 4 , CAN_SOLVE_CONSTRAINED = 8 ,
REQUIRES_CLOSEST_FEASIBLE = 16
}
Models features that the optimizer requires from the objective function.
typedef PointType SearchPointType
typedef ResultT ResultType
typedef SolutionTypeT SolutionType
typedef AbstractObjectiveFunction< PointType, ResultType > ObjectiveFunctionType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Detailed Description
template<typename Indicator>
class shark::IndicatorBasedRealCodedNSGAII< Indicator >
Implements the NSGA-II.
Please see the following papers for further reference: Deb, Agrawal, Pratap and Meyarivan. A Fast and Elitist Multiobjective Genetic Algorithm: NSGA-II IEEE TRANSACTIONS ON EVOLUTIONARY COMPUTATION, VOL. 6, NO. 2, APRIL 2002
Definition at line 61 of file RealCodedNSGAII.h.
Member Typedef Documentation
IndividualType
template<typename Indicator > typedef shark::Individual<RealVector,RealVector> shark::IndicatorBasedRealCodedNSGAII< Indicator >::IndividualType protected
The individual type of the NSGA-II.
Definition at line 193 of file RealCodedNSGAII.h.
Constructor & Destructor Documentation
IndicatorBasedRealCodedNSGAII()
template<typename Indicator > shark::IndicatorBasedRealCodedNSGAII< Indicator >::IndicatorBasedRealCodedNSGAII (random::rng_type & rng = random::globalRng) inline
Default c'tor.
Definition at line 65 of file RealCodedNSGAII.h.
References shark::IndicatorBasedRealCodedNSGAII< Indicator >::crossoverProbability(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::m_features, shark::IndicatorBasedRealCodedNSGAII< Indicator >::mu(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::nc(), and shark::IndicatorBasedRealCodedNSGAII< Indicator >::nm().
Member Function Documentation
crossoverProbability() [1/2]
template<typename Indicator > double & shark::IndicatorBasedRealCodedNSGAII< Indicator >::crossoverProbability () inline
Returns the probability that crossover is applied.
Definition at line 82 of file RealCodedNSGAII.h.
crossoverProbability() [2/2]
template<typename Indicator > double shark::IndicatorBasedRealCodedNSGAII< Indicator >::crossoverProbability () const inline
Returns the probability that crossover is applied.
Definition at line 78 of file RealCodedNSGAII.h.
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::IndicatorBasedRealCodedNSGAII(), and shark::IndicatorBasedRealCodedNSGAII< Indicator >::init().
doInit()
template<typename Indicator > void shark::IndicatorBasedRealCodedNSGAII< Indicator >::doInit (std::vector< SearchPointType > const & initialSearchPoints, std::vector< ResultType > const & functionValues, RealVector const & lowerBounds, RealVector const & upperBounds, std::size_t mu, double nm, double nc, double crossover_prob) inline protected
Definition at line 195 of file RealCodedNSGAII.h.
References shark::random::discrete(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::indicator(), shark::PolynomialMutator::init(), shark::SimulatedBinaryCrossover< PointType >::init(), shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, shark::SimulatedBinaryCrossover< PointType >::m_nc, shark::PolynomialMutator::m_nm, shark::IndicatorBasedRealCodedNSGAII< Indicator >::m_parents, shark::IndicatorBasedRealCodedNSGAII< Indicator >::mpe_rng, shark::IndicatorBasedRealCodedNSGAII< Indicator >::mu(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::nc(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::nm(), and SIZE_CHECK.
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::init().
generateOffspring()
template<typename Indicator > std::vector< IndividualType > shark::IndicatorBasedRealCodedNSGAII< Indicator >::generateOffspring () const inline protected
Definition at line 242 of file RealCodedNSGAII.h.
References shark::random::coinToss(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::m_parents, shark::IndicatorBasedRealCodedNSGAII< Indicator >::mpe_rng, and shark::IndicatorBasedRealCodedNSGAII< Indicator >::mu().
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::step().
indicator() [1/2]
template<typename Indicator > Indicator & shark::IndicatorBasedRealCodedNSGAII< Indicator >::indicator () inline
Returns the indicator used.
Definition at line 118 of file RealCodedNSGAII.h.
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::doInit().
indicator() [2/2]
template<typename Indicator > Indicator const & shark::IndicatorBasedRealCodedNSGAII< Indicator >::indicator () const inline
Returns the indicator used.
Definition at line 122 of file RealCodedNSGAII.h.
init()
template<typename Indicator > void shark::IndicatorBasedRealCodedNSGAII< Indicator >::init (ObjectiveFunctionType const & function, std::vector< SearchPointType > const & initialSearchPoints) inline
Initializes the algorithm for the supplied objective function.
Parameters
[in] function The objective function.
[in] initialSearchPoints A set of intiial search points.
Definition at line 153 of file RealCodedNSGAII.h.
References shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::crossoverProbability(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::doInit(), shark::AbstractObjectiveFunction< PointType, ResultT >::eval(), shark::AbstractObjectiveFunction< PointType, ResultT >::getConstraintHandler(), shark::AbstractObjectiveFunction< PointType, ResultT >::hasConstraintHandler(), shark::AbstractObjectiveFunction< PointType, ResultT >::isConstrained(), shark::AbstractObjectiveFunction< PointType, ResultT >::isFeasible(), shark::BoxConstraintHandler< Vector >::lower(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::mu(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::nc(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::nm(), shark::AbstractObjectiveFunction< PointType, ResultT >::numberOfVariables(), and SHARK_RUNTIME_CHECK.
mu() [1/2]
template<typename Indicator > std::size_t & shark::IndicatorBasedRealCodedNSGAII< Indicator >::mu () inline
Returns the number of elements in the front.
Definition at line 108 of file RealCodedNSGAII.h.
mu() [2/2]
template<typename Indicator > std::size_t shark::IndicatorBasedRealCodedNSGAII< Indicator >::mu () const inline
Returns the number of elements in the front.
Definition at line 104 of file RealCodedNSGAII.h.
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::doInit(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::generateOffspring(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::IndicatorBasedRealCodedNSGAII(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::init(), and shark::IndicatorBasedRealCodedNSGAII< Indicator >::updatePopulation().
name()
template<typename Indicator > std::string shark::IndicatorBasedRealCodedNSGAII< Indicator >::name () const inline virtual
returns the name of the object
Reimplemented from shark::INameable.
Reimplemented in shark::RealCodedNSGAIII.
Definition at line 73 of file RealCodedNSGAII.h.
nc() [1/2]
template<typename Indicator > double & shark::IndicatorBasedRealCodedNSGAII< Indicator >::nc () inline
Returns a reference to the crossover variation strength parameter.
Definition at line 99 of file RealCodedNSGAII.h.
References shark::SimulatedBinaryCrossover< PointType >::m_nc.
nc() [2/2]
template<typename Indicator > double shark::IndicatorBasedRealCodedNSGAII< Indicator >::nc () const inline
Returns the crossover variation strength parameter.
Definition at line 95 of file RealCodedNSGAII.h.
References shark::SimulatedBinaryCrossover< PointType >::m_nc.
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::doInit(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::IndicatorBasedRealCodedNSGAII(), and shark::IndicatorBasedRealCodedNSGAII< Indicator >::init().
nm() [1/2]
template<typename Indicator > double & shark::IndicatorBasedRealCodedNSGAII< Indicator >::nm () inline
Returns a reference to the mutation variation strength parameter.
Definition at line 91 of file RealCodedNSGAII.h.
References shark::PolynomialMutator::m_nm.
nm() [2/2]
template<typename Indicator > double shark::IndicatorBasedRealCodedNSGAII< Indicator >::nm () const inline
Returns the mutation variation strength parameter.
Definition at line 87 of file RealCodedNSGAII.h.
References shark::PolynomialMutator::m_nm.
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::doInit(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::IndicatorBasedRealCodedNSGAII(), and shark::IndicatorBasedRealCodedNSGAII< Indicator >::init().
numInitPoints()
template<typename Indicator > std::size_t shark::IndicatorBasedRealCodedNSGAII< Indicator >::numInitPoints () const inline virtual
The number of points used for initialization of the algorithm.
Implements shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >.
Definition at line 113 of file RealCodedNSGAII.h.
read()
template<typename Indicator > void shark::IndicatorBasedRealCodedNSGAII< Indicator >::read (InArchive & archive) inline virtual
Read the component from the supplied archive.
Parameters
[in,out] archive The archive to read from.
Reimplemented from shark::ISerializable.
Definition at line 126 of file RealCodedNSGAII.h.
References shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, and shark::IndicatorBasedRealCodedNSGAII< Indicator >::m_parents.
step()
template<typename Indicator > void shark::IndicatorBasedRealCodedNSGAII< Indicator >::step (ObjectiveFunctionType const & function) inline
Executes one iteration of the algorithm.
Parameters
[in] function The function to iterate upon.
Definition at line 185 of file RealCodedNSGAII.h.
References shark::IndicatorBasedRealCodedNSGAII< Indicator >::generateOffspring(), and shark::IndicatorBasedRealCodedNSGAII< Indicator >::updatePopulation().
updatePopulation()
template<typename Indicator > void shark::IndicatorBasedRealCodedNSGAII< Indicator >::updatePopulation (std::vector< IndividualType > const & offspringVec) inline protected
Definition at line 264 of file RealCodedNSGAII.h.
References shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, shark::IndicatorBasedRealCodedNSGAII< Indicator >::m_parents, and shark::IndicatorBasedRealCodedNSGAII< Indicator >::mu().
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::step().
write()
template<typename Indicator > void shark::IndicatorBasedRealCodedNSGAII< Indicator >::write (OutArchive & archive) const inline virtual
Write the component to the supplied archive.
Parameters
[in,out] archive The archive to write to.
Reimplemented from shark::ISerializable.
Definition at line 136 of file RealCodedNSGAII.h.
References shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, and shark::IndicatorBasedRealCodedNSGAII< Indicator >::m_parents.
Member Data Documentation
m_parents
template<typename Indicator > std::vector<IndividualType> shark::IndicatorBasedRealCodedNSGAII< Indicator >::m_parents protected
Population of size \(\mu + 1\).
Definition at line 279 of file RealCodedNSGAII.h.
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::doInit(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::generateOffspring(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::read(), shark::IndicatorBasedRealCodedNSGAII< Indicator >::updatePopulation(), and shark::IndicatorBasedRealCodedNSGAII< Indicator >::write().
mpe_rng
template<typename Indicator > random::rng_type* shark::IndicatorBasedRealCodedNSGAII< Indicator >::mpe_rng protected
Definition at line 280 of file RealCodedNSGAII.h.
Referenced by shark::IndicatorBasedRealCodedNSGAII< Indicator >::doInit(), and shark::IndicatorBasedRealCodedNSGAII< Indicator >::generateOffspring().
The documentation for this class was generated from the following file:
include/shark/Algorithms/DirectSearch/RealCodedNSGAII.h