shark::EpsilonSvmTrainer< InputType, CacheType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::EpsilonSvmTrainer< InputType, CacheType > Class Template Reference
Supervised Trainers
Training of Epsilon-SVMs for regression.
#include <shark/Algorithms/Trainers/EpsilonSvmTrainer.h>
Public Types
typedef CacheType QpFloatType
typedef KernelMatrix< InputType, QpFloatType > KernelMatrixType
typedef BlockMatrix2x2< KernelMatrixType > BlockMatrixType
typedef CachedMatrix< BlockMatrixType > CachedBlockMatrixType
typedef PrecomputedMatrix< BlockMatrixType > PrecomputedBlockMatrixType
typedef AbstractModel< InputType, RealVector > ModelType
typedef AbstractKernelFunction< InputType > KernelType
Public Types inherited from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >
typedef AbstractKernelFunction< InputType > KernelType
Public Types inherited from shark::AbstractTrainer< Model, LabelTypeT >
typedef Model ModelType
typedef ModelType::InputType InputType
typedef LabelTypeT LabelType
typedef LabeledData< InputType, LabelType > DatasetType
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
EpsilonSvmTrainer (KernelType *kernel, double C, double epsilon, bool unconstrained=false)
std::string name () const
From INameable: return the class name.
double epsilon () const
void setEpsilon (double epsilon)
RealVector parameterVector () const
get the hyper-parameter vector
void setParameterVector (RealVector const &newParameters)
set the vector of hyper-parameters
size_t numberOfParameters () const
return the number of hyper-parameters
void train (KernelExpansion< InputType > &svm, LabeledData< InputType, RealVector > const &dataset)
Public Member Functions inherited from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >
AbstractSvmTrainer (KernelType *kernel, double C, bool offset, bool unconstrained=false)
AbstractSvmTrainer (KernelType *kernel, double negativeC, double positiveC, bool offset, bool unconstrained=false)
double C () const
Return the value of the regularization parameter C.
void setC (double C)
Set the value of the regularization parameter C.
RealVector const & regularizationParameters () const
void setRegularizationParameters (RealVector const &regularizers)
Set the value of the regularization parameter C.
KernelType * kernel ()
KernelType const * kernel () const
void setKernel (KernelType *kernel)
bool isUnconstrained () const
bool trainOffset () const
std::size_t cacheSize () const
void setCacheSize (std::size_t size)
Public Member Functions inherited from shark::AbstractTrainer< Model, LabelTypeT >
virtual void train (ModelType &model, DatasetType const &dataset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Public Member Functions inherited from shark::QpConfig
QpConfig (bool precomputedFlag=false, bool sparsifyFlag=true)
Constructor.
QpStoppingCondition & stoppingCondition ()
Read/write access to the stopping condition.
QpStoppingCondition const & stoppingCondition () const
Read access to the stopping condition.
QpSolutionProperties & solutionProperties ()
Access to the solution properties.
bool & precomputeKernel ()
Flag for using a precomputed kernel matrix.
bool const & precomputeKernel () const
Flag for using a precomputed kernel matrix.
bool & sparsify ()
Flag for sparsifying the model after training.
bool const & sparsify () const
Flag for sparsifying the model after training.
bool & shrinking ()
Flag for shrinking in the decomposition solver.
bool const & shrinking () const
Flag for shrinking in the decomposition solver.
bool & s2do ()
Flag for S2DO (instead of SMO)
bool const & s2do () const
Flag for S2DO (instead of SMO)
unsigned int & verbosity ()
Verbosity level of the solver.
unsigned int const & verbosity () const
Verbosity level of the solver.
unsigned long long const & accessCount () const
Number of kernel accesses.
void setMinAccuracy (double a)
void setMaxIterations (unsigned long long i)
void setTargetValue (double v)
void setMaxSeconds (double s)
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >
KernelType * m_kernel
RealVector m_regularizers
Vector of regularization parameters.
bool m_trainOffset
bool m_unconstrained
Is log(C) stored internally as a parameter instead of C? If yes, then we get rid of the constraint C > 0 on the level of the parameter interface.
std::size_t m_cacheSize
Number of values in the kernel cache. The size of the cache in bytes is the size of one entry (4 for float, 8 for double) times this number.
Protected Attributes inherited from shark::QpConfig
QpStoppingCondition m_stoppingcondition
conditions for when to stop the QP solver
QpSolutionProperties m_solutionproperties
properties of the approximate solution found by the solver
bool m_precomputedKernelMatrix
should the solver use a precomputed kernel matrix?
bool m_sparsify
should the trainer sparsify the model after training?
bool m_shrinking
should shrinking be used?
bool m_s2do
should S2DO be used instead of SMO?
unsigned int m_verbosity
verbosity level (currently unused)
unsigned long long m_accessCount
kernel access count
Detailed Description
template<class InputType, class CacheType = float>
class shark::EpsilonSvmTrainer< InputType, CacheType >
Training of Epsilon-SVMs for regression.
The Epsilon-SVM is a support vector machine variant for regression problems. Given are data tuples \((x_i, y_i) \) with x-component denoting input and y-component denoting a real-valued label (see the tutorial on label conventions; the implementation uses RealVector), a kernel function k(x, x'), a regularization constant C > 0, and a loss insensitivity parameter \(\varepsilon \). Let H denote the kernel induced reproducing kernel Hilbert space of k, and let \(\phi \) denote the corresponding feature map. Then the SVM regression function is of the form
\[ (x) = \langle w, \phi(x) \rangle + b \]
with coefficients w and b given by the (primal) optimization problem
\[ \min \frac{1}{2} \|w\|^2 + C \sum_i L(y_i, f(x_i)), \]
where
\[ L(y, f(x)) = \max\{0, |y - f(x)| - \varepsilon \} \]
is the \(\varepsilon \) insensitive absolute loss.
Definition at line 80 of file EpsilonSvmTrainer.h.
Member Typedef Documentation
BlockMatrixType
template<class InputType , class CacheType = float> typedef BlockMatrix2x2< KernelMatrixType > shark::EpsilonSvmTrainer< InputType, CacheType >::BlockMatrixType
Definition at line 87 of file EpsilonSvmTrainer.h.
CachedBlockMatrixType
template<class InputType , class CacheType = float> typedef CachedMatrix< BlockMatrixType > shark::EpsilonSvmTrainer< InputType, CacheType >::CachedBlockMatrixType
Definition at line 88 of file EpsilonSvmTrainer.h.
KernelMatrixType
template<class InputType , class CacheType = float> typedef KernelMatrix< InputType, QpFloatType > shark::EpsilonSvmTrainer< InputType, CacheType >::KernelMatrixType
Definition at line 86 of file EpsilonSvmTrainer.h.
KernelType
template<class InputType , class CacheType = float> typedef AbstractKernelFunction<InputType> shark::EpsilonSvmTrainer< InputType, CacheType >::KernelType
Definition at line 92 of file EpsilonSvmTrainer.h.
ModelType
template<class InputType , class CacheType = float> typedef AbstractModel<InputType, RealVector> shark::EpsilonSvmTrainer< InputType, CacheType >::ModelType
Definition at line 91 of file EpsilonSvmTrainer.h.
PrecomputedBlockMatrixType
template<class InputType , class CacheType = float> typedef PrecomputedMatrix< BlockMatrixType > shark::EpsilonSvmTrainer< InputType, CacheType >::PrecomputedBlockMatrixType
Definition at line 89 of file EpsilonSvmTrainer.h.
QpFloatType
template<class InputType , class CacheType = float> typedef CacheType shark::EpsilonSvmTrainer< InputType, CacheType >::QpFloatType
Definition at line 84 of file EpsilonSvmTrainer.h.
Constructor & Destructor Documentation
EpsilonSvmTrainer()
template<class InputType , class CacheType = float> shark::EpsilonSvmTrainer< InputType, CacheType >::EpsilonSvmTrainer (KernelType * kernel, double C, double epsilon, bool unconstrained = false) inline
Constructor
Parameters
kernel kernel function to use for training and prediction
C regularization parameter - always the 'true' value of C, even when unconstrained is set
epsilon Loss insensitivity parameter.
unconstrained when a C-value is given via setParameter, should it be piped through the exp-function before using it in the solver?
Definition at line 100 of file EpsilonSvmTrainer.h.
Member Function Documentation
epsilon()
template<class InputType , class CacheType = float> double shark::EpsilonSvmTrainer< InputType, CacheType >::epsilon () const inline
Definition at line 109 of file EpsilonSvmTrainer.h.
Referenced by shark::EpsilonSvmTrainer< InputType, CacheType >::setEpsilon().
name()
template<class InputType , class CacheType = float> std::string shark::EpsilonSvmTrainer< InputType, CacheType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 106 of file EpsilonSvmTrainer.h.
numberOfParameters()
template<class InputType , class CacheType = float> size_t shark::EpsilonSvmTrainer< InputType, CacheType >::numberOfParameters () const inline virtual
return the number of hyper-parameters
Reimplemented from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >.
Definition at line 129 of file EpsilonSvmTrainer.h.
References shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::numberOfParameters().
parameterVector()
template<class InputType , class CacheType = float> RealVector shark::EpsilonSvmTrainer< InputType, CacheType >::parameterVector () const inline virtual
get the hyper-parameter vector
Reimplemented from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >.
Definition at line 115 of file EpsilonSvmTrainer.h.
References shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::m_unconstrained, and shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::parameterVector().
setEpsilon()
template<class InputType , class CacheType = float> void shark::EpsilonSvmTrainer< InputType, CacheType >::setEpsilon (double epsilon) inline
Definition at line 111 of file EpsilonSvmTrainer.h.
References shark::EpsilonSvmTrainer< InputType, CacheType >::epsilon().
Referenced by shark::EpsilonSvmTrainer< InputType, CacheType >::setParameterVector().
setParameterVector()
template<class InputType , class CacheType = float> void shark::EpsilonSvmTrainer< InputType, CacheType >::setParameterVector (RealVector const & newParameters) inline virtual
set the vector of hyper-parameters
Reimplemented from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >.
Definition at line 121 of file EpsilonSvmTrainer.h.
References shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::m_unconstrained, shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::numberOfParameters(), shark::EpsilonSvmTrainer< InputType, CacheType >::setEpsilon(), shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::setParameterVector(), and SHARK_ASSERT.
train()
template<class InputType , class CacheType = float> void shark::EpsilonSvmTrainer< InputType, CacheType >::train (KernelExpansion< InputType > & svm, LabeledData< InputType, RealVector > const & dataset) inline
Definition at line 132 of file EpsilonSvmTrainer.h.
References shark::LabeledData< InputT, LabelT >::inputs(), shark::labelDimension(), shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::m_kernel, shark::QpConfig::precomputeKernel(), shark::KernelExpansion< InputType >::setStructure(), SHARK_RUNTIME_CHECK, shark::QpConfig::sparsify(), and shark::KernelExpansion< InputType >::sparsify().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/EpsilonSvmTrainer.h