shark::SquaredHingeLinearCSvmTrainer< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::SquaredHingeLinearCSvmTrainer< InputType > Class Template Reference
#include <shark/Algorithms/Trainers/CSvmTrainer.h>
Public Member Functions
SquaredHingeLinearCSvmTrainer (double C, bool unconstrained=false)
std::string name () const
From INameable: return the class name.
void train (LinearClassifier< InputType > &model, LabeledData< InputType, unsigned int > const &dataset)
Public Member Functions inherited from shark::AbstractLinearSvmTrainer< InputType >
AbstractLinearSvmTrainer (double C, bool offset, bool unconstrained)
double C () const
Return the value of the regularization parameter C.
void setC (double C)
Set the value of the regularization parameter C.
bool isUnconstrained () const
Is the regularization parameter provided in logarithmic (unconstrained) form as a parameter?
bool trainOffset () const
RealVector parameterVector () const
Get the hyper-parameter vector.
void setParameterVector (RealVector const &newParameters)
Set the vector of hyper-parameters.
size_t numberOfParameters () const
Return the number of hyper-parameters.
Public Member Functions inherited from shark::AbstractTrainer< LinearClassifier< InputType >, unsigned int >
virtual void train (ModelType &model, DatasetType const &dataset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Public Member Functions inherited from shark::QpConfig
QpConfig (bool precomputedFlag=false, bool sparsifyFlag=true)
Constructor.
QpStoppingCondition & stoppingCondition ()
Read/write access to the stopping condition.
QpStoppingCondition const & stoppingCondition () const
Read access to the stopping condition.
QpSolutionProperties & solutionProperties ()
Access to the solution properties.
bool & precomputeKernel ()
Flag for using a precomputed kernel matrix.
bool const & precomputeKernel () const
Flag for using a precomputed kernel matrix.
bool & sparsify ()
Flag for sparsifying the model after training.
bool const & sparsify () const
Flag for sparsifying the model after training.
bool & shrinking ()
Flag for shrinking in the decomposition solver.
bool const & shrinking () const
Flag for shrinking in the decomposition solver.
bool & s2do ()
Flag for S2DO (instead of SMO)
bool const & s2do () const
Flag for S2DO (instead of SMO)
unsigned int & verbosity ()
Verbosity level of the solver.
unsigned int const & verbosity () const
Verbosity level of the solver.
unsigned long long const & accessCount () const
Number of kernel accesses.
void setMinAccuracy (double a)
void setMaxIterations (unsigned long long i)
void setTargetValue (double v)
void setMaxSeconds (double s)
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Additional Inherited Members
Public Types inherited from shark::AbstractLinearSvmTrainer< InputType >
typedef LinearClassifier< InputType > ModelType
Public Types inherited from shark::AbstractTrainer< LinearClassifier< InputType >, unsigned int >
typedef LinearClassifier< InputType > ModelType
typedef ModelType::InputType InputType
typedef unsigned int LabelType
typedef LabeledData< InputType, LabelType > DatasetType
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Attributes inherited from shark::AbstractLinearSvmTrainer< InputType >
QpStoppingCondition m_stoppingcondition
conditions for when to stop the QP solver
QpSolutionProperties m_solutionproperties
properties of the approximate solution found by the solver
unsigned int m_verbosity
verbosity level (currently unused)
Protected Attributes inherited from shark::AbstractLinearSvmTrainer< InputType >
double m_C
Regularization parameter. The exact meaning depends on the sub-class, but the value is always positive, and higher implies a less regular solution.
bool m_trainOffset
Is the SVM trained with or without bias?
bool m_unconstrained
Is log(C) stored internally as a parameter instead of C? If yes, then we get rid of the constraint C > 0 on the level of the parameter interface.
Protected Attributes inherited from shark::QpConfig
QpStoppingCondition m_stoppingcondition
conditions for when to stop the QP solver
QpSolutionProperties m_solutionproperties
properties of the approximate solution found by the solver
bool m_precomputedKernelMatrix
should the solver use a precomputed kernel matrix?
bool m_sparsify
should the trainer sparsify the model after training?
bool m_shrinking
should shrinking be used?
bool m_s2do
should S2DO be used instead of SMO?
unsigned int m_verbosity
verbosity level (currently unused)
unsigned long long m_accessCount
kernel access count
Detailed Description
template<class InputType>
class shark::SquaredHingeLinearCSvmTrainer< InputType >
Definition at line 1040 of file CSvmTrainer.h.
Constructor & Destructor Documentation
SquaredHingeLinearCSvmTrainer()
template<class InputType > shark::SquaredHingeLinearCSvmTrainer< InputType >::SquaredHingeLinearCSvmTrainer (double C, bool unconstrained = false) inline
Definition at line 1045 of file CSvmTrainer.h.
Member Function Documentation
name()
template<class InputType > std::string shark::SquaredHingeLinearCSvmTrainer< InputType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 1049 of file CSvmTrainer.h.
train()
template<class InputType > void shark::SquaredHingeLinearCSvmTrainer< InputType >::train (LinearClassifier< InputType > & model, LabeledData< InputType, unsigned int > const & dataset) inline
Definition at line 1052 of file CSvmTrainer.h.
References shark::AbstractLinearSvmTrainer< InputType >::C(), shark::Classifier< Model >::decisionFunction(), shark::inputDimension(), shark::QpConfig::solutionProperties(), shark::QpBoxLinear< InputT >::solutionWeightVector(), shark::QpBoxLinear< InputT >::solve(), shark::QpConfig::stoppingCondition(), and shark::QpConfig::verbosity().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/CSvmTrainer.h