shark::CMAIndividual< FitnessType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::CMAIndividual< FitnessType > Class Template Reference
#include <shark/Algorithms/DirectSearch/CMA/CMAIndividual.h>
Public Member Functions
CMAIndividual ()
Default constructor that initializes the individual's attributes to default values.
CMAIndividual (std::size_t searchSpaceDimension, double successThreshold=0.44, double initialStepSize=1.0)
void updateAsParent (CMAChromosome::IndividualSuccess offspringSuccess)
void updateAsOffspring ()
template<class randomType >
void mutate (randomType &rng)
double & noSuccessfulOffspring ()
double noSuccessfulOffspring () const
std::size_t parent () const
std::size_t & parent ()
Public Member Functions inherited from shark::Individual< RealVector, FitnessType, CMAChromosome >
Individual ()
Default constructor that initializes the individual's attributes to default values.
SearchPointType & searchPoint ()
Returns a reference to the search point that is associated with the individual.
SearchPointType const & searchPoint () const
Returns a const reference to the search point that is associated with the individual.
CMAChromosome & chromosome ()
Returns a reference to the chromosome that is associated with the individual.
CMAChromosome const & chromosome () const
Returns a const reference to the chromosome that is associated with the individual.
FitnessType & unpenalizedFitness ()
Returns a reference to the unpenalized fitness of the individual.
FitnessType const & unpenalizedFitness () const
Returns the unpenalized fitness of the individual.
FitnessType & penalizedFitness ()
Returns a reference to the penalized fitness of the individual.
FitnessType const & penalizedFitness () const
Returns the unpenalized fitness of the individual.
unsigned int rank () const
Returns the level of non-dominance of the individual.
unsigned int & rank ()
Returns a reference to the level of non-dominance of the individual. Allows for lvalue()-semantic.
bool selected () const
Returns true if the individual is selected for the next parent generation.
bool & selected ()
Returns true if the individual is selected for the next parent generation.
void serialize (Archive &archive, const unsigned int version)
Stores the individual and all of its chromosomes in an archive.
Additional Inherited Members
Public Types inherited from shark::Individual< RealVector, FitnessType, CMAChromosome >
typedef FitnessType FitnessType
typedef RealVector SearchPointType
Protected Attributes inherited from shark::Individual< RealVector, FitnessType, CMAChromosome >
SearchPointType m_searchPoint
The search point associated with the individual.
CMAChromosome m_chromosome
The search point associated with the individual.
unsigned int m_rank
The level of non-dominance of the individual. The lower the better.
bool m_selected
Is the individual selected for the next parent set?
FitnessType m_penalizedFitness
Penalized fitness of the individual.
FitnessType m_unpenalizedFitness
Unpenalized fitness of the individual.
Detailed Description
template<class FitnessType>
class shark::CMAIndividual< FitnessType >
Definition at line 44 of file CMAIndividual.h.
Constructor & Destructor Documentation
CMAIndividual() [1/2]
template<class FitnessType > shark::CMAIndividual< FitnessType >::CMAIndividual () inline
Default constructor that initializes the individual's attributes to default values.
Definition at line 51 of file CMAIndividual.h.
CMAIndividual() [2/2]
template<class FitnessType > shark::CMAIndividual< FitnessType >::CMAIndividual (std::size_t searchSpaceDimension, double successThreshold = 0.44, double initialStepSize = 1.0) inline
Definition at line 52 of file CMAIndividual.h.
References shark::Individual< RealVector, FitnessType, CMAChromosome >::chromosome(), and shark::Individual< RealVector, FitnessType, CMAChromosome >::searchPoint().
Member Function Documentation
mutate()
template<class FitnessType > template<class randomType > void shark::CMAIndividual< FitnessType >::mutate (randomType & rng) inline
Definition at line 68 of file CMAIndividual.h.
References shark::Individual< RealVector, FitnessType, CMAChromosome >::chromosome(), shark::MultiVariateNormalDistributionCholesky::generate(), shark::CMAChromosome::m_lastStep, shark::CMAChromosome::m_mutationDistribution, shark::CMAChromosome::m_stepSize, and shark::Individual< RealVector, FitnessType, CMAChromosome >::searchPoint().
noSuccessfulOffspring() [1/2]
template<class FitnessType > double & shark::CMAIndividual< FitnessType >::noSuccessfulOffspring () inline
Definition at line 75 of file CMAIndividual.h.
References shark::Individual< RealVector, FitnessType, CMAChromosome >::chromosome().
noSuccessfulOffspring() [2/2]
template<class FitnessType > double shark::CMAIndividual< FitnessType >::noSuccessfulOffspring () const inline
Definition at line 79 of file CMAIndividual.h.
References shark::Individual< RealVector, FitnessType, CMAChromosome >::chromosome().
parent() [1/2]
template<class FitnessType > std::size_t & shark::CMAIndividual< FitnessType >::parent () inline
Definition at line 86 of file CMAIndividual.h.
parent() [2/2]
template<class FitnessType > std::size_t shark::CMAIndividual< FitnessType >::parent () const inline
Definition at line 83 of file CMAIndividual.h.
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::updatePopulation().
updateAsOffspring()
template<class FitnessType > void shark::CMAIndividual< FitnessType >::updateAsOffspring () inline
Definition at line 64 of file CMAIndividual.h.
References shark::Individual< RealVector, FitnessType, CMAChromosome >::chromosome(), and shark::CMAChromosome::updateAsOffspring().
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::updatePopulation().
updateAsParent()
template<class FitnessType > void shark::CMAIndividual< FitnessType >::updateAsParent (CMAChromosome::IndividualSuccess offspringSuccess) inline
Definition at line 61 of file CMAIndividual.h.
References shark::Individual< RealVector, FitnessType, CMAChromosome >::chromosome(), and shark::CMAChromosome::updateAsParent().
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::updatePopulation().
The documentation for this class was generated from the following file:
include/shark/Algorithms/DirectSearch/CMA/CMAIndividual.h