shark::LooError< ModelTypeT, LabelType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::LooError< ModelTypeT, LabelType > Class Template Reference
Objective functions
Leave-one-out error objective function.
#include <shark/ObjectiveFunctions/LooError.h>
Public Types
typedef ModelTypeT ModelType
typedef ModelType::InputType InputType
typedef ModelType::OutputType OutputType
typedef LabeledData< InputType, LabelType > DatasetType
typedef AbstractTrainer< ModelType, LabelType > TrainerType
typedef AbstractLoss< LabelType, typename ModelType::OutputType > LossType
Public Types inherited from shark::AbstractObjectiveFunction< RealVector, double >
enum Feature
List of features that are supported by an implementation.
typedef RealVector SearchPointType
typedef double ResultType
typedef boost::mpl::if_< std::is_arithmetic< double >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
LooError (DatasetType const &dataset, ModelType *model, TrainerType *trainer, LossType *loss, IParameterizable<> *meta=NULL)
Constructor.
std::string name () const
From INameable: return the class name.
std::size_t numberOfVariables () const
Accesses the number of variables.
double eval () const
double eval (const RealVector &parameters) const
Public Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
virtual void init ()
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual bool hasScalableDimensionality () const
virtual void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
virtual std::size_t numberOfObjectives () const
virtual bool hasScalableObjectives () const
virtual void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
virtual SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Protected Attributes
DataView< DatasetType const > m_dataset
IParameterizable * mep_meta
ModelType * mep_model
TrainerType * mep_trainer
LossType * mep_loss
Protected Attributes inherited from shark::AbstractObjectiveFunction< RealVector, double >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Additional Inherited Members
Protected Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Detailed Description
template<class ModelTypeT, class LabelType = typename ModelTypeT::OutputType>
class shark::LooError< ModelTypeT, LabelType >
Leave-one-out error objective function.
The leave-one-out measure is the average prediction performance of a learning machine on a dataset, where each sample is predicted by a machine trained on all but the sample to be predicted. This is an extreme form of cross-validation, with a fold size of one.
In general the leave-one-out error is costly to compute, since it requires training of a large number of learning machines. However, certain machines allow for a more efficient implementation. Refer to LooErrorCSvm for an example.
Definition at line 63 of file LooError.h.
Member Typedef Documentation
DatasetType
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> typedef LabeledData<InputType, LabelType> shark::LooError< ModelTypeT, LabelType >::DatasetType
Definition at line 69 of file LooError.h.
InputType
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> typedef ModelType::InputType shark::LooError< ModelTypeT, LabelType >::InputType
Definition at line 67 of file LooError.h.
LossType
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> typedef AbstractLoss<LabelType, typename ModelType::OutputType> shark::LooError< ModelTypeT, LabelType >::LossType
Definition at line 71 of file LooError.h.
ModelType
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> typedef ModelTypeT shark::LooError< ModelTypeT, LabelType >::ModelType
Definition at line 66 of file LooError.h.
OutputType
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> typedef ModelType::OutputType shark::LooError< ModelTypeT, LabelType >::OutputType
Definition at line 68 of file LooError.h.
TrainerType
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> typedef AbstractTrainer<ModelType, LabelType> shark::LooError< ModelTypeT, LabelType >::TrainerType
Definition at line 70 of file LooError.h.
Constructor & Destructor Documentation
LooError()
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> shark::LooError< ModelTypeT, LabelType >::LooError (DatasetType const & dataset, ModelType * model, TrainerType * trainer, LossType * loss, IParameterizable<> * meta = NULL) inline
Constructor.
Parameters
dataset Full data set for leave-one-out.
model Model built on subsets of the data.
trainer Trainer for learning on each subset.
loss Loss function for judging the validation output.
meta Meta object with parameters that influences the process, typically a trainer.
Definition at line 82 of file LooError.h.
References shark::AbstractObjectiveFunction< RealVector, double >::HAS_VALUE, and shark::AbstractObjectiveFunction< RealVector, double >::m_features.
Member Function Documentation
eval() [1/2]
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> double shark::LooError< ModelTypeT, LabelType >::eval () const inline
Evaluate the leave-one-out error: train sub-models, evaluate objective, return the average.
Definition at line 114 of file LooError.h.
References shark::AbstractLoss< LabelT, OutputT >::eval(), shark::LooError< ModelTypeT, LabelType >::m_dataset, shark::AbstractObjectiveFunction< RealVector, double >::m_evaluationCounter, shark::LooError< ModelTypeT, LabelType >::mep_loss, shark::LooError< ModelTypeT, LabelType >::mep_model, shark::LooError< ModelTypeT, LabelType >::mep_trainer, shark::subset(), shark::toDataset(), and shark::AbstractTrainer< Model, LabelTypeT >::train().
Referenced by shark::LooError< ModelTypeT, LabelType >::eval().
eval() [2/2]
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> double shark::LooError< ModelTypeT, LabelType >::eval (const RealVector & parameters) const inline virtual
Evaluate the leave-one-out error for the given parameters passed to the meta object (typically these parameters need to be optimized in a model selection procedure).
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 138 of file LooError.h.
References shark::LooError< ModelTypeT, LabelType >::eval(), shark::LooError< ModelTypeT, LabelType >::mep_meta, shark::IParameterizable< VectorType >::setParameterVector(), and SHARK_ASSERT.
name()
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> std::string shark::LooError< ModelTypeT, LabelType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 99 of file LooError.h.
References shark::LooError< ModelTypeT, LabelType >::mep_loss, shark::LooError< ModelTypeT, LabelType >::mep_model, shark::LooError< ModelTypeT, LabelType >::mep_trainer, and shark::INameable::name().
numberOfVariables()
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> std::size_t shark::LooError< ModelTypeT, LabelType >::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 107 of file LooError.h.
References shark::LooError< ModelTypeT, LabelType >::mep_meta, and shark::IParameterizable< VectorType >::numberOfParameters().
Member Data Documentation
m_dataset
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> DataView<DatasetType const> shark::LooError< ModelTypeT, LabelType >::m_dataset protected
Definition at line 144 of file LooError.h.
Referenced by shark::LooError< ModelTypeT, LabelType >::eval().
mep_loss
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> LossType* shark::LooError< ModelTypeT, LabelType >::mep_loss protected
Definition at line 148 of file LooError.h.
Referenced by shark::LooError< ModelTypeT, LabelType >::eval(), and shark::LooError< ModelTypeT, LabelType >::name().
mep_meta
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> IParameterizable* shark::LooError< ModelTypeT, LabelType >::mep_meta protected
Definition at line 145 of file LooError.h.
Referenced by shark::LooError< ModelTypeT, LabelType >::eval(), and shark::LooError< ModelTypeT, LabelType >::numberOfVariables().
mep_model
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> ModelType* shark::LooError< ModelTypeT, LabelType >::mep_model protected
Definition at line 146 of file LooError.h.
Referenced by shark::LooError< ModelTypeT, LabelType >::eval(), and shark::LooError< ModelTypeT, LabelType >::name().
mep_trainer
template<class ModelTypeT , class LabelType = typename ModelTypeT::OutputType> TrainerType* shark::LooError< ModelTypeT, LabelType >::mep_trainer protected
Definition at line 147 of file LooError.h.
Referenced by shark::LooError< ModelTypeT, LabelType >::eval(), and shark::LooError< ModelTypeT, LabelType >::name().
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/LooError.h