shark::RegularizationNetworkTrainer< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::RegularizationNetworkTrainer< InputType > Class Template Reference
Supervised Trainers
Training of a regularization network.
#include <shark/Algorithms/Trainers/RegularizationNetworkTrainer.h>
Public Types
typedef AbstractModel< InputType, RealVector > ModelType
typedef AbstractKernelFunction< InputType > KernelType
Public Types inherited from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >
typedef AbstractKernelFunction< InputType > KernelType
Public Types inherited from shark::AbstractTrainer< Model, LabelTypeT >
typedef Model ModelType
typedef ModelType::InputType InputType
typedef LabelTypeT LabelType
typedef LabeledData< InputType, LabelType > DatasetType
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
RegularizationNetworkTrainer (KernelType *kernel, double betaInv, bool unconstrained=false)
std::string name () const
From INameable: return the class name.
double noiseVariance () const
Returns the assumed noise variance (i.e., 1/C)
void setNoiseVariance (double betaInv)
Sets the assumed noise variance (i.e., 1/C)
double precision () const
Returns the precision (i.e., C), the inverse of the assumed noise variance.
void setPrecision (double beta)
Sets the precision (i.e., C), the inverse of the assumed noise variance.
void train (KernelExpansion< InputType > &svm, const LabeledData< InputType, RealVector > &dataset)
Public Member Functions inherited from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >
AbstractSvmTrainer (KernelType *kernel, double C, bool offset, bool unconstrained=false)
AbstractSvmTrainer (KernelType *kernel, double negativeC, double positiveC, bool offset, bool unconstrained=false)
double C () const
Return the value of the regularization parameter C.
void setC (double C)
Set the value of the regularization parameter C.
RealVector const & regularizationParameters () const
void setRegularizationParameters (RealVector const &regularizers)
Set the value of the regularization parameter C.
KernelType * kernel ()
KernelType const * kernel () const
void setKernel (KernelType *kernel)
bool isUnconstrained () const
bool trainOffset () const
std::size_t cacheSize () const
void setCacheSize (std::size_t size)
RealVector parameterVector () const
get the hyper-parameter vector
void setParameterVector (RealVector const &newParameters)
set the vector of hyper-parameters
size_t numberOfParameters () const
return the number of hyper-parameters
Public Member Functions inherited from shark::AbstractTrainer< Model, LabelTypeT >
virtual void train (ModelType &model, DatasetType const &dataset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Public Member Functions inherited from shark::QpConfig
QpConfig (bool precomputedFlag=false, bool sparsifyFlag=true)
Constructor.
QpStoppingCondition & stoppingCondition ()
Read/write access to the stopping condition.
QpStoppingCondition const & stoppingCondition () const
Read access to the stopping condition.
QpSolutionProperties & solutionProperties ()
Access to the solution properties.
bool & precomputeKernel ()
Flag for using a precomputed kernel matrix.
bool const & precomputeKernel () const
Flag for using a precomputed kernel matrix.
bool & sparsify ()
Flag for sparsifying the model after training.
bool const & sparsify () const
Flag for sparsifying the model after training.
bool & shrinking ()
Flag for shrinking in the decomposition solver.
bool const & shrinking () const
Flag for shrinking in the decomposition solver.
bool & s2do ()
Flag for S2DO (instead of SMO)
bool const & s2do () const
Flag for S2DO (instead of SMO)
unsigned int & verbosity ()
Verbosity level of the solver.
unsigned int const & verbosity () const
Verbosity level of the solver.
unsigned long long const & accessCount () const
Number of kernel accesses.
void setMinAccuracy (double a)
void setMaxIterations (unsigned long long i)
void setTargetValue (double v)
void setMaxSeconds (double s)
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >
KernelType * m_kernel
RealVector m_regularizers
Vector of regularization parameters.
bool m_trainOffset
bool m_unconstrained
Is log(C) stored internally as a parameter instead of C? If yes, then we get rid of the constraint C > 0 on the level of the parameter interface.
std::size_t m_cacheSize
Number of values in the kernel cache. The size of the cache in bytes is the size of one entry (4 for float, 8 for double) times this number.
Protected Attributes inherited from shark::QpConfig
QpStoppingCondition m_stoppingcondition
conditions for when to stop the QP solver
QpSolutionProperties m_solutionproperties
properties of the approximate solution found by the solver
bool m_precomputedKernelMatrix
should the solver use a precomputed kernel matrix?
bool m_sparsify
should the trainer sparsify the model after training?
bool m_shrinking
should shrinking be used?
bool m_s2do
should S2DO be used instead of SMO?
unsigned int m_verbosity
verbosity level (currently unused)
unsigned long long m_accessCount
kernel access count
Detailed Description
template<class InputType>
class shark::RegularizationNetworkTrainer< InputType >
Training of a regularization network.
A regularization network is a kernel-based model for regression problems. Given are data tuples \((x_i, y_i) \) with x-component denoting input and y-component denoting a real-valued label (see the tutorial on label conventions; the implementation uses RealVector), a kernel function k(x, x') and a regularization constant \(C > 0\). Let H denote the kernel induced reproducing kernel Hilbert space of k, and let \(\phi \) denote the corresponding feature map. Then the SVM regression function is of the form
\[ f(x) = \langle w, \phi(x) \rangle + b \]
with coefficients w and b given by the (primal) optimization problem
\[ \min \frac{1}{2} \|w\|^2 + C \sum_i L(y_i, f(x_i)), \]
where the simple quadratic loss is employed:
\[ L(y, f(x)) = (y - f(x))^2 \]
Regularization networks can be interpreted as a special type of support vector machine (for regression, with squared loss, and thus with non-sparse weights).
Training a regularization network is identical to training a Gaussian process for regression. The parameter \(C \) then corresponds precision of the noise (denoted by \(\beta \) in Bishop's textbook). The precision is the inverse of the variance of the noise. The variance of the noise is denoted by \(\sigma_n^2 \) in the textbook by Rasmussen and Williams. Accordingly, \(C = 1/\sigma_n^2 \).
Definition at line 86 of file RegularizationNetworkTrainer.h.
Member Typedef Documentation
KernelType
template<class InputType > typedef AbstractKernelFunction<InputType> shark::RegularizationNetworkTrainer< InputType >::KernelType
Definition at line 90 of file RegularizationNetworkTrainer.h.
ModelType
template<class InputType > typedef AbstractModel<InputType, RealVector> shark::RegularizationNetworkTrainer< InputType >::ModelType
Definition at line 89 of file RegularizationNetworkTrainer.h.
Constructor & Destructor Documentation
RegularizationNetworkTrainer()
template<class InputType > shark::RegularizationNetworkTrainer< InputType >::RegularizationNetworkTrainer (KernelType * kernel, double betaInv, bool unconstrained = false) inline
Parameters
kernel Kernel
betaInv Inverse precision, equal to assumed noise variance, equal to inverse regularization parameter C
unconstrained Indicates exponential encoding of the regularization parameter
Definition at line 96 of file RegularizationNetworkTrainer.h.
Member Function Documentation
name()
template<class InputType > std::string shark::RegularizationNetworkTrainer< InputType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 101 of file RegularizationNetworkTrainer.h.
noiseVariance()
template<class InputType > double shark::RegularizationNetworkTrainer< InputType >::noiseVariance () const inline
Returns the assumed noise variance (i.e., 1/C)
Definition at line 105 of file RegularizationNetworkTrainer.h.
References shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::C().
Referenced by shark::RegularizationNetworkTrainer< InputType >::train().
precision()
template<class InputType > double shark::RegularizationNetworkTrainer< InputType >::precision () const inline
Returns the precision (i.e., C), the inverse of the assumed noise variance.
Definition at line 112 of file RegularizationNetworkTrainer.h.
References shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::C().
setNoiseVariance()
template<class InputType > void shark::RegularizationNetworkTrainer< InputType >::setNoiseVariance (double betaInv) inline
Sets the assumed noise variance (i.e., 1/C)
Definition at line 108 of file RegularizationNetworkTrainer.h.
References shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::C().
setPrecision()
template<class InputType > void shark::RegularizationNetworkTrainer< InputType >::setPrecision (double beta) inline
Sets the precision (i.e., C), the inverse of the assumed noise variance.
Definition at line 115 of file RegularizationNetworkTrainer.h.
References shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::C().
train()
template<class InputType > void shark::RegularizationNetworkTrainer< InputType >::train (KernelExpansion< InputType > & svm, const LabeledData< InputType, RealVector > & dataset) inline
Definition at line 118 of file RegularizationNetworkTrainer.h.
References shark::KernelExpansion< InputType >::alpha(), shark::calculateRegularizedKernelMatrix(), shark::Data< Type >::elements(), shark::LabeledData< InputT, LabelT >::inputs(), shark::labelDimension(), shark::LabeledData< InputT, LabelT >::labels(), shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >::m_kernel, shark::mean(), shark::RegularizationNetworkTrainer< InputType >::noiseVariance(), shark::KernelExpansion< InputType >::offset(), and shark::KernelExpansion< InputType >::setStructure().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/RegularizationNetworkTrainer.h