shark::IndicatorBasedMOCMA< Indicator > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::IndicatorBasedMOCMA< Indicator > Class Template Reference
Algorithms to find a local minimum of\ref objfunctions. » Multi-objective Direct-Search optimizers
Implements the generational MO-CMA-ES.
#include <shark/Algorithms/DirectSearch/MOCMA.h>
Public Types
enum NotionOfSuccess { IndividualBased , PopulationBased }
Public Types inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
typedef super::SearchPointType SearchPointType
typedef super::SolutionType SolutionType
typedef super::ObjectiveFunctionType ObjectiveFunctionType
Public Types inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
enum Feature {
REQUIRES_VALUE = 1 , REQUIRES_FIRST_DERIVATIVE = 2 , REQUIRES_SECOND_DERIVATIVE = 4 , CAN_SOLVE_CONSTRAINED = 8 ,
REQUIRES_CLOSEST_FEASIBLE = 16
}
Models features that the optimizer requires from the objective function.
typedef PointType SearchPointType
typedef ResultT ResultType
typedef SolutionTypeT SolutionType
typedef AbstractObjectiveFunction< PointType, ResultType > ObjectiveFunctionType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
IndicatorBasedMOCMA (random::rng_type &rng=random::globalRng)
std::string name () const
Returns the name of the algorithm.
std::size_t mu () const
std::size_t & mu ()
std::size_t numInitPoints () const
The number of points used for initialization of the algorithm.
double initialSigma () const
double & initialSigma ()
NotionOfSuccess notionOfSuccess () const
NotionOfSuccess & notionOfSuccess ()
void read (InArchive &archive)
Read the component from the supplied archive.
void write (OutArchive &archive) const
Write the component to the supplied archive.
void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initialSearchPoints)
Initializes the algorithm for the supplied objective function.
void step (ObjectiveFunctionType const &function)
Executes one iteration of the algorithm.
Indicator & indicator ()
Indicator const & indicator () const
Public Member Functions inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
SolutionType const & solution () const
Accesses the current approximation of the Pareto-set and -front, respectively.
Public Member Functions inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
const Features & features () const
virtual void updateFeatures ()
bool requiresValue () const
bool requiresFirstDerivative () const
bool requiresSecondDerivative () const
bool canSolveConstrained () const
bool requiresClosestFeasible () const
virtual ~AbstractOptimizer ()
virtual void init (ObjectiveFunctionType const &function)
Initialize the optimizer for the supplied objective function.
virtual void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initPoints)=0
Initialize the optimizer for the supplied objective function using a set of initialisation points.
virtual void step (ObjectiveFunctionType const &function)=0
Carry out one step of the optimizer for the supplied objective function.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Types
typedef CMAIndividual< RealVector > IndividualType
The individual type of the SteadyState-MOCMA.
Protected Member Functions
void doInit (std::vector< SearchPointType > const &initialSearchPoints, std::vector< ResultType > const &functionValues, std::size_t mu, double initialSigma)
std::vector< IndividualType > generateOffspring () const
void updatePopulation (std::vector< IndividualType > const &offspringVec)
Protected Member Functions inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
void checkFeatures (ObjectiveFunctionType const &objectiveFunction)
Convenience function that checks whether the features of the supplied objective function match with the required features of the optimizer.
Protected Attributes
std::vector< IndividualType > m_parents
Population of size \(\mu + 1\).
Protected Attributes inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
SolutionType m_best
The current Pareto-set/-front.
Protected Attributes inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
Features m_features
Detailed Description
template<typename Indicator = HypervolumeIndicator>
class shark::IndicatorBasedMOCMA< Indicator >
Implements the generational MO-CMA-ES.
Please see the following papers for further reference:
Igel, Suttorp and Hansen. Steady-state Selection and Efficient Covariance Matrix Update in the Multi-Objective CMA-ES.
Voﬂ, Hansen and Igel. Improved Step Size Adaptation for the MO-CMA-ES.
Definition at line 54 of file MOCMA.h.
Member Typedef Documentation
IndividualType
template<typename Indicator = HypervolumeIndicator> typedef CMAIndividual<RealVector> shark::IndicatorBasedMOCMA< Indicator >::IndividualType protected
The individual type of the SteadyState-MOCMA.
Definition at line 163 of file MOCMA.h.
Member Enumeration Documentation
NotionOfSuccess
template<typename Indicator = HypervolumeIndicator> enum shark::IndicatorBasedMOCMA::NotionOfSuccess
Enumerator
IndividualBased
PopulationBased
Definition at line 56 of file MOCMA.h.
Constructor & Destructor Documentation
IndicatorBasedMOCMA()
template<typename Indicator = HypervolumeIndicator> shark::IndicatorBasedMOCMA< Indicator >::IndicatorBasedMOCMA (random::rng_type & rng = random::globalRng) inline
Definition at line 62 of file MOCMA.h.
References shark::IndicatorBasedMOCMA< Indicator >::initialSigma(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::m_features, shark::IndicatorBasedMOCMA< Indicator >::mu(), shark::IndicatorBasedMOCMA< Indicator >::notionOfSuccess(), and shark::IndicatorBasedMOCMA< Indicator >::PopulationBased.
Member Function Documentation
doInit()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedMOCMA< Indicator >::doInit (std::vector< SearchPointType > const & initialSearchPoints, std::vector< ResultType > const & functionValues, std::size_t mu, double initialSigma) inline protected
Definition at line 165 of file MOCMA.h.
References shark::random::discrete(), shark::IndicatorBasedMOCMA< Indicator >::indicator(), shark::IndicatorBasedMOCMA< Indicator >::initialSigma(), shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, shark::IndicatorBasedMOCMA< Indicator >::m_parents, shark::IndicatorBasedMOCMA< Indicator >::mu(), and SIZE_CHECK.
Referenced by shark::IndicatorBasedMOCMA< Indicator >::init().
generateOffspring()
template<typename Indicator = HypervolumeIndicator> std::vector< IndividualType > shark::IndicatorBasedMOCMA< Indicator >::generateOffspring () const inline protected
Definition at line 207 of file MOCMA.h.
References shark::IndicatorBasedMOCMA< Indicator >::m_parents, and shark::IndicatorBasedMOCMA< Indicator >::mu().
Referenced by shark::IndicatorBasedMOCMA< Indicator >::step().
indicator() [1/2]
template<typename Indicator = HypervolumeIndicator> Indicator & shark::IndicatorBasedMOCMA< Indicator >::indicator () inline
Definition at line 155 of file MOCMA.h.
Referenced by shark::IndicatorBasedMOCMA< Indicator >::doInit(), and main().
indicator() [2/2]
template<typename Indicator = HypervolumeIndicator> Indicator const & shark::IndicatorBasedMOCMA< Indicator >::indicator () const inline
Definition at line 158 of file MOCMA.h.
init()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedMOCMA< Indicator >::init (ObjectiveFunctionType const & function, std::vector< SearchPointType > const & initialSearchPoints) inline
Initializes the algorithm for the supplied objective function.
Parameters
[in] function The objective function.
[in] initialSearchPoints A set of intiial search points.
Definition at line 130 of file MOCMA.h.
References shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures(), shark::IndicatorBasedMOCMA< Indicator >::doInit(), shark::AbstractObjectiveFunction< PointType, ResultT >::eval(), shark::IndicatorBasedMOCMA< Indicator >::initialSigma(), shark::AbstractObjectiveFunction< PointType, ResultT >::isFeasible(), shark::IndicatorBasedMOCMA< Indicator >::mu(), and SHARK_RUNTIME_CHECK.
Referenced by main().
initialSigma() [1/2]
template<typename Indicator = HypervolumeIndicator> double & shark::IndicatorBasedMOCMA< Indicator >::initialSigma () inline
Definition at line 92 of file MOCMA.h.
initialSigma() [2/2]
template<typename Indicator = HypervolumeIndicator> double shark::IndicatorBasedMOCMA< Indicator >::initialSigma () const inline
Definition at line 89 of file MOCMA.h.
Referenced by shark::IndicatorBasedMOCMA< Indicator >::doInit(), shark::IndicatorBasedMOCMA< Indicator >::IndicatorBasedMOCMA(), and shark::IndicatorBasedMOCMA< Indicator >::init().
mu() [1/2]
template<typename Indicator = HypervolumeIndicator> std::size_t & shark::IndicatorBasedMOCMA< Indicator >::mu () inline
Definition at line 80 of file MOCMA.h.
mu() [2/2]
template<typename Indicator = HypervolumeIndicator> std::size_t shark::IndicatorBasedMOCMA< Indicator >::mu () const inline
Definition at line 77 of file MOCMA.h.
Referenced by shark::IndicatorBasedMOCMA< Indicator >::doInit(), shark::IndicatorBasedMOCMA< Indicator >::generateOffspring(), shark::IndicatorBasedMOCMA< Indicator >::IndicatorBasedMOCMA(), shark::IndicatorBasedMOCMA< Indicator >::init(), main(), and shark::IndicatorBasedMOCMA< Indicator >::updatePopulation().
name()
template<typename Indicator = HypervolumeIndicator> std::string shark::IndicatorBasedMOCMA< Indicator >::name () const inline virtual
Returns the name of the algorithm.
Reimplemented from shark::INameable.
Definition at line 73 of file MOCMA.h.
notionOfSuccess() [1/2]
template<typename Indicator = HypervolumeIndicator> NotionOfSuccess & shark::IndicatorBasedMOCMA< Indicator >::notionOfSuccess () inline
Definition at line 99 of file MOCMA.h.
notionOfSuccess() [2/2]
template<typename Indicator = HypervolumeIndicator> NotionOfSuccess shark::IndicatorBasedMOCMA< Indicator >::notionOfSuccess () const inline
Definition at line 96 of file MOCMA.h.
Referenced by shark::IndicatorBasedMOCMA< Indicator >::IndicatorBasedMOCMA().
numInitPoints()
template<typename Indicator = HypervolumeIndicator> std::size_t shark::IndicatorBasedMOCMA< Indicator >::numInitPoints () const inline virtual
The number of points used for initialization of the algorithm.
Implements shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >.
Definition at line 85 of file MOCMA.h.
read()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedMOCMA< Indicator >::read (InArchive & archive) inline virtual
Read the component from the supplied archive.
Parameters
[in,out] archive The archive to read from.
Reimplemented from shark::ISerializable.
Definition at line 102 of file MOCMA.h.
References shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, and shark::IndicatorBasedMOCMA< Indicator >::m_parents.
step()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedMOCMA< Indicator >::step (ObjectiveFunctionType const & function) inline
Executes one iteration of the algorithm.
Parameters
[in] function The function to iterate upon.
Definition at line 148 of file MOCMA.h.
References shark::IndicatorBasedMOCMA< Indicator >::generateOffspring(), and shark::IndicatorBasedMOCMA< Indicator >::updatePopulation().
Referenced by main().
updatePopulation()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedMOCMA< Indicator >::updatePopulation (std::vector< IndividualType > const & offspringVec) inline protected
Definition at line 218 of file MOCMA.h.
References shark::IndicatorBasedMOCMA< Indicator >::IndividualBased, shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, shark::IndicatorBasedMOCMA< Indicator >::m_parents, shark::IndicatorBasedMOCMA< Indicator >::mu(), shark::IndicatorBasedMOCMA< Indicator >::PopulationBased, shark::CMAChromosome::Successful, and shark::CMAChromosome::Unsuccessful.
Referenced by shark::IndicatorBasedMOCMA< Indicator >::step().
write()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedMOCMA< Indicator >::write (OutArchive & archive) const inline virtual
Write the component to the supplied archive.
Parameters
[in,out] archive The archive to write to.
Reimplemented from shark::ISerializable.
Definition at line 112 of file MOCMA.h.
References shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, and shark::IndicatorBasedMOCMA< Indicator >::m_parents.
Member Data Documentation
m_parents
template<typename Indicator = HypervolumeIndicator> std::vector<IndividualType> shark::IndicatorBasedMOCMA< Indicator >::m_parents protected
Population of size \(\mu + 1\).
Definition at line 250 of file MOCMA.h.
Referenced by shark::IndicatorBasedMOCMA< Indicator >::doInit(), shark::IndicatorBasedMOCMA< Indicator >::generateOffspring(), shark::IndicatorBasedMOCMA< Indicator >::read(), shark::IndicatorBasedMOCMA< Indicator >::updatePopulation(), and shark::IndicatorBasedMOCMA< Indicator >::write().
The documentation for this class was generated from the following file:
include/shark/Algorithms/DirectSearch/MOCMA.h