shark::Shark Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::Shark Class Reference
Allows for querying compile settings at runtime. Provides the current command line arguments to the rest of the library.
#include <shark/Core/Shark.h>
Classes
struct Version
Models a version according to the major.minor.patch versioning scheme.
Static Public Member Functions
static BuildType buildType ()
Accesses the build type of the library.
static bool hasOpenMp ()
Queries whether Shark has been compiled with OpenMP enabled.
static bool isDynamicLibrary ()
Queries whether Shark has been compiled as dynamic library.
static bool isOfficialRelease ()
Checks whether this is an official Shark release.
template<typename Stream >
static void info (Stream &s)
Prints information about the Shark Machine Learning Library to the supplied stream.
Protected Member Functions
Shark ()
Shark (const Shark &shark)
Shark & operator= (const Shark &rhs)
Detailed Description
Allows for querying compile settings at runtime. Provides the current command line arguments to the rest of the library.
Definition at line 169 of file Shark.h.
Constructor & Destructor Documentation
Shark() [1/2]
shark::Shark::Shark () protected
Shark() [2/2]
shark::Shark::Shark (const Shark & shark) protected
Member Function Documentation
buildType()
static BuildType shark::Shark::buildType () inline static
Accesses the build type of the library.
Definition at line 226 of file Shark.h.
Referenced by info().
hasOpenMp()
static bool shark::Shark::hasOpenMp () inline static
Queries whether Shark has been compiled with OpenMP enabled.
Definition at line 233 of file Shark.h.
Referenced by info().
info()
template<typename Stream > static void shark::Shark::info (Stream & s) inline static
Prints information about the Shark Machine Learning Library to the supplied stream.
Definition at line 255 of file Shark.h.
References buildType(), shark::DEBUG_BUILD_TYPE, hasOpenMp(), isDynamicLibrary(), isOfficialRelease(), shark::Shark::Version< major, minor, patch >::MAJOR(), shark::Shark::Version< major, minor, patch >::MINOR(), shark::Shark::Version< major, minor, patch >::PATCH(), and shark::RELEASE_BUILD_TYPE.
Referenced by main().
isDynamicLibrary()
static bool shark::Shark::isDynamicLibrary () inline static
Queries whether Shark has been compiled as dynamic library.
Definition at line 240 of file Shark.h.
Referenced by info().
isOfficialRelease()
static bool shark::Shark::isOfficialRelease () inline static
Checks whether this is an official Shark release.
Definition at line 247 of file Shark.h.
Referenced by info().
operator=()
Shark & shark::Shark::operator= (const Shark & rhs) protected
The documentation for this class was generated from the following file:
include/shark/Core/Shark.h