shark::ProjectBudgetMaintenanceStrategy< RealVector > Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::ProjectBudgetMaintenanceStrategy< RealVector > Class Reference
Budget maintenance strategy that projects a vector.
#include <shark/Algorithms/Trainers/Budgeted/ProjectBudgetMaintenanceStrategy.h>
Public Member Functions
ProjectBudgetMaintenanceStrategy ()
constructor.
virtual void addToModel (ModelType &model, InputType const &alpha, ElementType const &supportVector)
std::string name () const
class name
Public Member Functions inherited from shark::AbstractBudgetMaintenanceStrategy< RealVector >
AbstractBudgetMaintenanceStrategy ()
virtual void addToModel (ModelType &model, RealVector const &alpha, ElementType const &supportVector)=0
std::string name () const
return the class name
Additional Inherited Members
Public Types inherited from shark::AbstractBudgetMaintenanceStrategy< RealVector >
typedef KernelExpansion< RealVector > ModelType
typedef LabeledData< RealVector, unsigned int > DataType
typedef DataType::element_type ElementType
Static Public Member Functions inherited from shark::AbstractBudgetMaintenanceStrategy< RealVector >
static void findSmallestVector (ModelType const &model, size_t &minIndex, double &minAlpha)
Detailed Description
Budget maintenance strategy that projects a vector.
This is an specialization of the project budget maintenance strategy
that handles simple real-valued vectors. This is a nearly 1:1 adoption of the strategy presented in Wang, Cramer and Vucetic.
Definition at line 104 of file ProjectBudgetMaintenanceStrategy.h.
Constructor & Destructor Documentation
ProjectBudgetMaintenanceStrategy()
shark::ProjectBudgetMaintenanceStrategy< RealVector >::ProjectBudgetMaintenanceStrategy () inline
constructor.
Definition at line 113 of file ProjectBudgetMaintenanceStrategy.h.
Member Function Documentation
addToModel()
virtual void shark::ProjectBudgetMaintenanceStrategy< RealVector >::addToModel (ModelType & model, InputType const & alpha, ElementType const & supportVector) inline virtual
add a vector to the model. this will add the given vector to the model and merge the budget so that afterwards the budget size is kept the same. If the budget has a free entry anyway, no merging will be performed, but instead the given vector is simply added to the budget.
Parameters
[in,out] model the model the strategy will work with
[in] alpha alphas for the new budget vector
[in] supportVector the vector to add to the model by applying the maintenance strategy
Definition at line 127 of file ProjectBudgetMaintenanceStrategy.h.
References shark::KernelExpansion< InputType >::alpha(), shark::KernelExpansion< InputType >::basis(), shark::createLabeledDataFromRange(), shark::Data< Type >::element(), shark::AbstractBudgetMaintenanceStrategy< InputType >::findSmallestVector(), shark::inputDimension(), shark::LabeledData< InputT, LabelT >::inputs(), shark::KernelExpansion< InputType >::kernel(), shark::Data< Type >::numberOfElements(), and SHARK_ASSERT.
name()
std::string shark::ProjectBudgetMaintenanceStrategy< RealVector >::name () const inline
class name
Definition at line 221 of file ProjectBudgetMaintenanceStrategy.h.
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/Budgeted/ProjectBudgetMaintenanceStrategy.h