shark::NormalDistributedPoints Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::NormalDistributedPoints Class Reference
Generates a set of normally distributed points.
#include <shark/Data/DataDistribution.h>
Public Member Functions
NormalDistributedPoints (std::size_t dim)
Generates a simple distribution with.
NormalDistributedPoints (RealMatrix const &covariance, RealVector const &offset)
void draw (RealVector &input) const
Generates a single pair of input and label.
Public Member Functions inherited from shark::DataDistribution< RealVector >
virtual ~DataDistribution ()
Virtual destructor.
RealVector operator() ()
UnlabeledData< RealVector > generateDataset (std::size_t size, std::size_t maximumBatchSize) const
Generates a data set with samples from from the distribution.
UnlabeledData< RealVector > generateDataset (std::size_t size) const
Generates a data set with samples from from the distribution.
Detailed Description
Generates a set of normally distributed points.
Definition at line 379 of file DataDistribution.h.
Constructor & Destructor Documentation
NormalDistributedPoints() [1/2]
shark::NormalDistributedPoints::NormalDistributedPoints (std::size_t dim) inline
Generates a simple distribution with.
Definition at line 383 of file DataDistribution.h.
References shark::covariance(), and shark::MultiVariateNormalDistributionCholesky::setCovarianceMatrix().
NormalDistributedPoints() [2/2]
shark::NormalDistributedPoints::NormalDistributedPoints (RealMatrix const & covariance, RealVector const & offset) inline
Definition at line 388 of file DataDistribution.h.
References shark::covariance(), and SIZE_CHECK.
Member Function Documentation
draw()
void shark::NormalDistributedPoints::draw (RealVector & input) const inline virtual
Generates a single pair of input and label.
Parameters
input the generated input
Implements shark::DataDistribution< RealVector >.
Definition at line 392 of file DataDistribution.h.
References shark::random::globalRng.
The documentation for this class was generated from the following file:
include/shark/Data/DataDistribution.h