shark::ExactGradient< RBMType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::ExactGradient< RBMType > Class Template Reference
#include <shark/Unsupervised/RBM/GradientApproximations/ExactGradient.h>
Public Types
typedef RBMType RBM
Public Types inherited from shark::AbstractObjectiveFunction< RealVector, double >
enum Feature
List of features that are supported by an implementation.
typedef RealVector SearchPointType
typedef double ResultType
typedef boost::mpl::if_< std::is_arithmetic< double >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
ExactGradient (RBM *rbm)
std::string name () const
From INameable: return the class name.
void setData (UnlabeledData< RealVector > const &data)
SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
std::size_t numberOfVariables () const
Accesses the number of variables.
void setRegularizer (double factor, SingleObjectiveFunction *regularizer)
double eval (SearchPointType const &parameter) const
Evaluates the objective function for the supplied argument.
double evalDerivative (SearchPointType const &parameter, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
long double getLogPartition ()
Public Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
virtual void init ()
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual bool hasScalableDimensionality () const
virtual void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
virtual std::size_t numberOfObjectives () const
virtual bool hasScalableObjectives () const
virtual void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Protected Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< RealVector, double >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
template<class RBMType>
class shark::ExactGradient< RBMType >
Definition at line 40 of file ExactGradient.h.
Member Typedef Documentation
RBM
template<class RBMType > typedef RBMType shark::ExactGradient< RBMType >::RBM
Definition at line 44 of file ExactGradient.h.
Constructor & Destructor Documentation
ExactGradient()
template<class RBMType > shark::ExactGradient< RBMType >::ExactGradient (RBM * rbm) inline
Definition at line 46 of file ExactGradient.h.
References shark::AbstractObjectiveFunction< RealVector, double >::CAN_PROPOSE_STARTING_POINT, shark::AbstractObjectiveFunction< RealVector, double >::HAS_FIRST_DERIVATIVE, shark::AbstractObjectiveFunction< RealVector, double >::m_features, and SHARK_ASSERT.
Member Function Documentation
eval()
template<class RBMType > double shark::ExactGradient< RBMType >::eval (SearchPointType const & input) const inline virtual
Evaluates the objective function for the supplied argument.
Parameters
[in] input The argument for which the function shall be evaluated.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 74 of file ExactGradient.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::eval(), shark::negativeLogLikelihood(), and shark::Data< Type >::numberOfElements().
evalDerivative()
template<class RBMType > double shark::ExactGradient< RBMType >::evalDerivative (SearchPointType const & input, FirstOrderDerivative & derivative) const inline virtual
Evaluates the objective function and calculates its gradient.
Parameters
[in] input The argument to eval the function for.
[out] derivative The derivate is placed here.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 84 of file ExactGradient.h.
References shark::Data< Type >::batches(), shark::GibbsOperator< RBMType >::createSample(), shark::AbstractObjectiveFunction< PointType, ResultT >::evalDerivative(), and shark::Data< Type >::numberOfElements().
getLogPartition()
template<class RBMType > long double shark::ExactGradient< RBMType >::getLogPartition () inline
Definition at line 131 of file ExactGradient.h.
name()
template<class RBMType > std::string shark::ExactGradient< RBMType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 54 of file ExactGradient.h.
numberOfVariables()
template<class RBMType > std::size_t shark::ExactGradient< RBMType >::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 65 of file ExactGradient.h.
proposeStartingPoint()
template<class RBMType > SearchPointType shark::ExactGradient< RBMType >::proposeStartingPoint () const inline virtual
Proposes a starting point in the feasible search space of the function.
Returns
The generated starting point.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 61 of file ExactGradient.h.
setData()
template<class RBMType > void shark::ExactGradient< RBMType >::setData (UnlabeledData< RealVector > const & data) inline
Definition at line 57 of file ExactGradient.h.
setRegularizer()
template<class RBMType > void shark::ExactGradient< RBMType >::setRegularizer (double factor, SingleObjectiveFunction * regularizer) inline
Definition at line 69 of file ExactGradient.h.
The documentation for this class was generated from the following file:
include/shark/Unsupervised/RBM/GradientApproximations/ExactGradient.h