shark::GaussianTaskKernel< InputTypeT > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::GaussianTaskKernel< InputTypeT > Class Template Reference
Models » Kernels
Special "Gaussian-like" kernel function on tasks.
#include <shark/Models/Kernels/MultiTaskKernel.h>
Public Types
typedef InputTypeT InputType
typedef MultiTaskSample< InputType > MultiTaskSampleType
typedef AbstractKernelFunction< InputType > KernelType
Public Types inherited from shark::AbstractKernelFunction< std::size_t >
enum Feature
enumerations of kerneland metric features (flags)
typedef base_type::InputType InputType
Input type of the Kernel.
typedef base_type::BatchInputType BatchInputType
batch input type of the kernel
typedef base_type::ConstInputReference ConstInputReference
Const references to InputType.
typedef base_type::ConstBatchInputReference ConstBatchInputReference
Const references to BatchInputType.
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::AbstractMetric< InputTypeT >
typedef InputTypeT InputType
Input type of the Kernel.
typedef Batch< InputTypeT >::type BatchInputType
batch input type of the kernel
typedef ConstProxyReference< InputTypeconst >::type ConstInputReference
Const references to InputType.
typedef ConstProxyReference< BatchInputTypeconst >::type ConstBatchInputReference
Const references to BatchInputType.
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
GaussianTaskKernel (Data< MultiTaskSampleType > const &data, std::size_t tasks, KernelType &inputkernel, double gamma)
Construction of a Gaussian kernel on tasks.
std::string name () const
From INameable: return the class name.
RealVector parameterVector () const
Return the parameter vector.
void setParameterVector (RealVector const &newParameters)
Set the parameter vector.
std::size_t numberOfParameters () const
Return the number of parameters.
std::size_t numberOfTasks () const
double gamma () const
Kernel bandwidth parameter.
double sigma () const
Kernel width parameter, equivalent to the bandwidth parameter.
void setGamma (double gamma)
void setWidth (double sigma)
Set the kernel width (equivalent to setting the bandwidth).
void read (InArchive &ar)
From ISerializable.
void write (OutArchive &ar) const
From ISerializable.
Public Member Functions inherited from shark::DiscreteKernel
DiscreteKernel (RealMatrix const &matrix)
Construction of the kernel from a positive definite, symmetric matrix.
std::size_t size () const
Cardinality of the discrete space.
boost::shared_ptr< State > createState () const
DiscreteKernels don't have a state so they return an EmptyState object.
double eval (ConstInputReference x1, ConstInputReference x2) const
Evaluates the kernel function.
void eval (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2, RealMatrix &result, State &state) const
Evaluates the kernel function for every point combination of the two batches.
void eval (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2, RealMatrix &result) const
Evaluates the kernel function for every point combination of the two batches.
Public Member Functions inherited from shark::AbstractKernelFunction< std::size_t >
AbstractKernelFunction ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
bool hasFirstInputDerivative () const
bool isNormalized () const
bool supportsVariableInputSize () const
double operator() (ConstInputReference x1, ConstInputReference x2) const
Convenience operator which evaluates the kernel function.
RealMatrix operator() (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2) const
Evaluates the subset of the KernelGram matrix which is defined by X1(rows) and X2 (columns).
virtual void weightedParameterDerivative (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2, RealMatrix const &coefficients, State const &state, RealVector &gradient) const
Computes the gradient of the parameters as a weighted sum over the gradient of all elements of the batch.
virtual void weightedInputDerivative (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2, RealMatrix const &coefficientsX2, State const &state, BatchInputType &gradient) const
Calculates the derivative of the inputs X1 (only x1!).
virtual double featureDistanceSqr (ConstInputReference x1, ConstInputReference x2) const
Computes the squared distance in the kernel induced feature space.
virtual RealMatrix featureDistanceSqr (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2) const
Computes the squared distance in the kernel induced feature space.
Public Member Functions inherited from shark::AbstractMetric< InputTypeT >
AbstractMetric ()
virtual ~AbstractMetric ()
virtual double featureDistanceSqr (ConstInputReference x1, ConstInputReference x2) const =0
Computes the squared distance in the kernel induced feature space.
virtual RealMatrix featureDistanceSqr (ConstBatchInputReference batchX1, ConstBatchInputReference batchX2) const =0
double featureDistance (ConstInputReference x1, ConstInputReference x2) const
Computes the distance in the kernel induced feature space.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Member Functions
void computeMatrix ()
Compute the Gram matrix of the task kernel.
Protected Attributes
Data< MultiTaskSampleType > const & m_data
multi-task data
KernelType * mpe_inputKernel
kernel on inputs
double m_gamma
bandwidth of the Gaussian task kernel
Protected Attributes inherited from shark::DiscreteKernel
RealMatrix m_matrix
kernel matrix
Protected Attributes inherited from shark::AbstractKernelFunction< std::size_t >
Features m_features
Detailed Description
template<class InputTypeT>
class shark::GaussianTaskKernel< InputTypeT >
Special "Gaussian-like" kernel function on tasks.
See
Learning Marginal Predictors: Transfer to an Unlabeled Task. G. Blanchard, G. Lee, C. Scott.
This class computes a Gaussian kernel based on the distance of empirical distributions in feature space induced by yet another kernel. This is useful for multi-task and transfer learning. It reduces the definition of a kernel on tasks to that of a kernel on inputs, plus a single bandwidth parameter for the Gaussian kernel of distributions.
Given unlabaled data \(x_i, t_i \) where the x-component is an input and the t-component is a task index, the kernel on tasks t and t' is defined as
\[ k(t, t') = \exp \left(-\gamma \cdot \left\| \frac{1}{\ell_{t}\ell{t'}} \sum_{i | t_i = t}\sum_{j | t_j = t'} k'(x_i, x_j) \right\|^2 \right) \]
where k' is an arbitrary kernel on inputs.
Definition at line 129 of file MultiTaskKernel.h.
Member Typedef Documentation
InputType
template<class InputTypeT > typedef InputTypeT shark::GaussianTaskKernel< InputTypeT >::InputType
Definition at line 134 of file MultiTaskKernel.h.
KernelType
template<class InputTypeT > typedef AbstractKernelFunction<InputType> shark::GaussianTaskKernel< InputTypeT >::KernelType
Definition at line 136 of file MultiTaskKernel.h.
MultiTaskSampleType
template<class InputTypeT > typedef MultiTaskSample<InputType> shark::GaussianTaskKernel< InputTypeT >::MultiTaskSampleType
Definition at line 135 of file MultiTaskKernel.h.
Constructor & Destructor Documentation
GaussianTaskKernel()
template<class InputTypeT > shark::GaussianTaskKernel< InputTypeT >::GaussianTaskKernel (Data< MultiTaskSampleType > const & data, std::size_t tasks, KernelType & inputkernel, double gamma) inline
Construction of a Gaussian kernel on tasks.
Parameters
data unlabeled data from multiple tasks
tasks number of tasks in the problem
inputkernel kernel on inputs based on which task similarity is defined
gamma Gaussian bandwidth parameter (also refer to the member functions setGamma and setSigma).
Definition at line 144 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::computeMatrix().
Member Function Documentation
computeMatrix()
template<class InputTypeT > void shark::GaussianTaskKernel< InputTypeT >::computeMatrix () inline protected
Compute the Gram matrix of the task kernel.
Here is the real meat. This function implements the kernel function defined in
Learning Marginal Predictors: Transfer to an Unlabeled Task. G. Blanchard, G. Lee, C. Scott.
In a first step the function computes the inner products of the task-wise empirical distributions, represented by their mean elements in the kernel-induced feature space. In a second step this information is used for the computation of squared distances between empirical distribution, which allows for the straightforward computation of a Gaussian kernel.
Definition at line 236 of file MultiTaskKernel.h.
References shark::AbstractKernelFunction< InputTypeT >::eval(), shark::GaussianTaskKernel< InputTypeT >::m_data, shark::GaussianTaskKernel< InputTypeT >::m_gamma, shark::DiscreteKernel::m_matrix, shark::GaussianTaskKernel< InputTypeT >::mpe_inputKernel, and shark::GaussianTaskKernel< InputTypeT >::numberOfTasks().
Referenced by shark::GaussianTaskKernel< InputTypeT >::GaussianTaskKernel(), and shark::GaussianTaskKernel< InputTypeT >::setParameterVector().
gamma()
template<class InputTypeT > double shark::GaussianTaskKernel< InputTypeT >::gamma () const inline
Kernel bandwidth parameter.
Definition at line 179 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::m_gamma.
Referenced by shark::GaussianTaskKernel< InputTypeT >::setGamma().
name()
template<class InputTypeT > std::string shark::GaussianTaskKernel< InputTypeT >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::DiscreteKernel.
Definition at line 157 of file MultiTaskKernel.h.
numberOfParameters()
template<class InputTypeT > std::size_t shark::GaussianTaskKernel< InputTypeT >::numberOfParameters () const inline virtual
Return the number of parameters.
Reimplemented from shark::DiscreteKernel.
Definition at line 171 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::mpe_inputKernel, and shark::IParameterizable< VectorType >::numberOfParameters().
numberOfTasks()
template<class InputTypeT > std::size_t shark::GaussianTaskKernel< InputTypeT >::numberOfTasks () const inline
Definition at line 175 of file MultiTaskKernel.h.
References shark::DiscreteKernel::size().
Referenced by shark::GaussianTaskKernel< InputTypeT >::computeMatrix().
parameterVector()
template<class InputTypeT > RealVector shark::GaussianTaskKernel< InputTypeT >::parameterVector () const inline virtual
Return the parameter vector.
Reimplemented from shark::DiscreteKernel.
Definition at line 160 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::m_gamma, shark::GaussianTaskKernel< InputTypeT >::mpe_inputKernel, and shark::IParameterizable< VectorType >::parameterVector().
read()
template<class InputTypeT > void shark::GaussianTaskKernel< InputTypeT >::read (InArchive & ar) inline virtual
From ISerializable.
Reimplemented from shark::DiscreteKernel.
Definition at line 205 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::m_gamma, and shark::DiscreteKernel::read().
setGamma()
template<class InputTypeT > void shark::GaussianTaskKernel< InputTypeT >::setGamma (double gamma) inline
Definition at line 189 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::gamma(), shark::GaussianTaskKernel< InputTypeT >::m_gamma, and SHARK_ASSERT.
setParameterVector()
template<class InputTypeT > void shark::GaussianTaskKernel< InputTypeT >::setParameterVector (RealVector const & newParameters) inline virtual
Set the parameter vector.
Reimplemented from shark::DiscreteKernel.
Definition at line 164 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::computeMatrix(), shark::GaussianTaskKernel< InputTypeT >::m_gamma, shark::GaussianTaskKernel< InputTypeT >::mpe_inputKernel, shark::IParameterizable< VectorType >::numberOfParameters(), and shark::IParameterizable< VectorType >::setParameterVector().
setWidth()
template<class InputTypeT > void shark::GaussianTaskKernel< InputTypeT >::setWidth (double sigma) inline
Set the kernel width (equivalent to setting the bandwidth).
The bandwidth gamma and the width sigma are connected: \(gamma = 1 / (2 \cdot sigma^2) \).
Definition at line 198 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::m_gamma, SHARK_ASSERT, and shark::GaussianTaskKernel< InputTypeT >::sigma().
sigma()
template<class InputTypeT > double shark::GaussianTaskKernel< InputTypeT >::sigma () const inline
Kernel width parameter, equivalent to the bandwidth parameter.
The bandwidth gamma and the width sigma are connected: \(gamma = 1 / (2 \cdot sigma^2) \).
Definition at line 185 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::m_gamma.
Referenced by shark::GaussianTaskKernel< InputTypeT >::setWidth().
write()
template<class InputTypeT > void shark::GaussianTaskKernel< InputTypeT >::write (OutArchive & ar) const inline virtual
From ISerializable.
Reimplemented from shark::DiscreteKernel.
Definition at line 212 of file MultiTaskKernel.h.
References shark::GaussianTaskKernel< InputTypeT >::m_gamma, and shark::DiscreteKernel::write().
Member Data Documentation
m_data
template<class InputTypeT > Data<MultiTaskSampleType > const& shark::GaussianTaskKernel< InputTypeT >::m_data protected
multi-task data
Definition at line 281 of file MultiTaskKernel.h.
Referenced by shark::GaussianTaskKernel< InputTypeT >::computeMatrix().
m_gamma
template<class InputTypeT > double shark::GaussianTaskKernel< InputTypeT >::m_gamma protected
bandwidth of the Gaussian task kernel
Definition at line 283 of file MultiTaskKernel.h.
Referenced by shark::GaussianTaskKernel< InputTypeT >::computeMatrix(), shark::GaussianTaskKernel< InputTypeT >::gamma(), shark::GaussianTaskKernel< InputTypeT >::parameterVector(), shark::GaussianTaskKernel< InputTypeT >::read(), shark::GaussianTaskKernel< InputTypeT >::setGamma(), shark::GaussianTaskKernel< InputTypeT >::setParameterVector(), shark::GaussianTaskKernel< InputTypeT >::setWidth(), shark::GaussianTaskKernel< InputTypeT >::sigma(), and shark::GaussianTaskKernel< InputTypeT >::write().
mpe_inputKernel
template<class InputTypeT > KernelType* shark::GaussianTaskKernel< InputTypeT >::mpe_inputKernel protected
kernel on inputs
Definition at line 282 of file MultiTaskKernel.h.
Referenced by shark::GaussianTaskKernel< InputTypeT >::computeMatrix(), shark::GaussianTaskKernel< InputTypeT >::numberOfParameters(), shark::GaussianTaskKernel< InputTypeT >::parameterVector(), and shark::GaussianTaskKernel< InputTypeT >::setParameterVector().
The documentation for this class was generated from the following file:
include/shark/Models/Kernels/MultiTaskKernel.h