shark::Perceptron< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::Perceptron< InputType > Class Template Reference
Supervised Trainers
Perceptron online learning algorithm.
#include <shark/Algorithms/Trainers/Perceptron.h>
Public Member Functions
Perceptron (AbstractKernelFunction< InputType > *kernel, std::size_t maxTimesPattern=10000)
Constructor.
std::string name () const
From INameable: return the class name.
void train (KernelClassifier< InputType > &classifier, LabeledData< InputType, unsigned int > const &dataset)
Public Member Functions inherited from shark::AbstractTrainer< KernelClassifier< InputType >, unsigned int >
virtual void train (ModelType &model, DatasetType const &dataset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Additional Inherited Members
Public Types inherited from shark::AbstractTrainer< KernelClassifier< InputType >, unsigned int >
typedef KernelClassifier< InputType > ModelType
typedef ModelType::InputType InputType
typedef unsigned int LabelType
typedef LabeledData< InputType, LabelType > DatasetType
Detailed Description
template<class InputType>
class shark::Perceptron< InputType >
Perceptron online learning algorithm.
Definition at line 46 of file Perceptron.h.
Constructor & Destructor Documentation
Perceptron()
template<class InputType > shark::Perceptron< InputType >::Perceptron (AbstractKernelFunction< InputType > * kernel, std::size_t maxTimesPattern = 10000) inline
Constructor.
Parameters
kernel is the (Mercer) kernel function.
maxTimesPattern defines the maximum number of times the data is processed before the algorithms stopps.
Definition at line 53 of file Perceptron.h.
Member Function Documentation
name()
template<class InputType > std::string shark::Perceptron< InputType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 57 of file Perceptron.h.
train()
template<class InputType > void shark::Perceptron< InputType >::train (KernelClassifier< InputType > & classifier, LabeledData< InputType, unsigned int > const & dataset) inline
Definition at line 60 of file Perceptron.h.
References shark::KernelExpansion< InputType >::alpha(), shark::Classifier< Model >::decisionFunction(), shark::LabeledData< InputT, LabelT >::element(), shark::LabeledData< InputT, LabelT >::inputs(), shark::LabeledData< InputT, LabelT >::numberOfElements(), and shark::KernelExpansion< InputType >::setStructure().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/Perceptron.h