shark::RealCodedNSGAIII Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::RealCodedNSGAIII Class Reference
Algorithms to find a local minimum of\ref objfunctions. » Multi-objective Direct-Search optimizers
Implements the NSGA-III.
#include <shark/Algorithms/DirectSearch/RealCodedNSGAIII.h>
Public Member Functions
RealCodedNSGAIII (random::rng_type &rng=random::globalRng)
Default c'tor.
std::string name () const
returns the name of the object
Public Member Functions inherited from shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >
IndicatorBasedRealCodedNSGAII (random::rng_type &rng=random::globalRng)
Default c'tor.
double crossoverProbability () const
Returns the probability that crossover is applied.
double & crossoverProbability ()
Returns the probability that crossover is applied.
double nm () const
Returns the mutation variation strength parameter.
double & nm ()
Returns a reference to the mutation variation strength parameter.
double nc () const
Returns the crossover variation strength parameter.
double & nc ()
Returns a reference to the crossover variation strength parameter.
std::size_t mu () const
Returns the number of elements in the front.
std::size_t & mu ()
Returns the number of elements in the front.
std::size_t numInitPoints () const
The number of points used for initialization of the algorithm.
NSGA3Indicator & indicator ()
Returns the indicator used.
NSGA3Indicator const & indicator () const
Returns the indicator used.
void read (InArchive &archive)
Read the component from the supplied archive.
void write (OutArchive &archive) const
Write the component to the supplied archive.
void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initialSearchPoints)
Initializes the algorithm for the supplied objective function.
void step (ObjectiveFunctionType const &function)
Executes one iteration of the algorithm.
Public Member Functions inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
SolutionType const & solution () const
Accesses the current approximation of the Pareto-set and -front, respectively.
Public Member Functions inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
const Features & features () const
virtual void updateFeatures ()
bool requiresValue () const
bool requiresFirstDerivative () const
bool requiresSecondDerivative () const
bool canSolveConstrained () const
bool requiresClosestFeasible () const
virtual ~AbstractOptimizer ()
virtual void init (ObjectiveFunctionType const &function)
Initialize the optimizer for the supplied objective function.
virtual void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initPoints)=0
Initialize the optimizer for the supplied objective function using a set of initialisation points.
virtual void step (ObjectiveFunctionType const &function)=0
Carry out one step of the optimizer for the supplied objective function.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Member Functions
void doInit (std::vector< SearchPointType > const &initialSearchPoints, std::vector< ResultType > const &functionValues, RealVector const &lowerBounds, RealVector const &upperBounds, std::size_t mu, double nm, double nc, double crossover_prob, std::vector< Preference > const &indicatorPreferences=std::vector< Preference >())
Protected Member Functions inherited from shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >
void doInit (std::vector< SearchPointType > const &initialSearchPoints, std::vector< ResultType > const &functionValues, RealVector const &lowerBounds, RealVector const &upperBounds, std::size_t mu, double nm, double nc, double crossover_prob)
std::vector< IndividualType > generateOffspring () const
void updatePopulation (std::vector< IndividualType > const &offspringVec)
Protected Member Functions inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
void checkFeatures (ObjectiveFunctionType const &objectiveFunction)
Convenience function that checks whether the features of the supplied objective function match with the required features of the optimizer.
Additional Inherited Members
Public Types inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
typedef super::SearchPointType SearchPointType
typedef super::SolutionType SolutionType
typedef super::ObjectiveFunctionType ObjectiveFunctionType
Public Types inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
enum Feature {
REQUIRES_VALUE = 1 , REQUIRES_FIRST_DERIVATIVE = 2 , REQUIRES_SECOND_DERIVATIVE = 4 , CAN_SOLVE_CONSTRAINED = 8 ,
REQUIRES_CLOSEST_FEASIBLE = 16
}
Models features that the optimizer requires from the objective function.
typedef PointType SearchPointType
typedef ResultT ResultType
typedef SolutionTypeT SolutionType
typedef AbstractObjectiveFunction< PointType, ResultType > ObjectiveFunctionType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Protected Types inherited from shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >
typedef shark::Individual< RealVector, RealVector > IndividualType
The individual type of the NSGA-II.
Protected Attributes inherited from shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >
std::vector< IndividualType > m_parents
Population of size \(\mu + 1\).
random::rng_type * mpe_rng
Protected Attributes inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
SolutionType m_best
The current Pareto-set/-front.
Protected Attributes inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
Features m_features
Detailed Description
Implements the NSGA-III.
The NSGAIII works similar to the NSGAII except that the crowding distance is replaced by its own, reference point based indicator.
Please see the following papers for further reference: Deb, Kalyanmoy, and Himanshu Jain. "An evolutionary many-objective optimization algorithm using reference-point-based nondominated sorting approach, part I: Solving problems with box constraints." IEEE Trans. Evolutionary Computation 18.4 (2014): 577-601.
Definition at line 54 of file RealCodedNSGAIII.h.
Constructor & Destructor Documentation
RealCodedNSGAIII()
shark::RealCodedNSGAIII::RealCodedNSGAIII (random::rng_type & rng = random::globalRng) inline
Default c'tor.
Definition at line 59 of file RealCodedNSGAIII.h.
Member Function Documentation
doInit()
void shark::RealCodedNSGAIII::doInit (std::vector< SearchPointType > const & initialSearchPoints, std::vector< ResultType > const & functionValues, RealVector const & lowerBounds, RealVector const & upperBounds, std::size_t mu, double nm, double nc, double crossover_prob, std::vector< Preference > const & indicatorPreferences = std::vector<Preference>()) inline protected
Definition at line 66 of file RealCodedNSGAIII.h.
References shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >::doInit(), shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >::indicator(), shark::NSGA3Indicator::init(), shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >::mpe_rng, shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >::mu(), shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >::nc(), and shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >::nm().
name()
std::string shark::RealCodedNSGAIII::name () const inline virtual
returns the name of the object
Reimplemented from shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >.
Definition at line 62 of file RealCodedNSGAIII.h.
The documentation for this class was generated from the following file:
include/shark/Algorithms/DirectSearch/RealCodedNSGAIII.h