shark::CrossEntropy< unsigned int, OutputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::CrossEntropy< unsigned int, OutputType > Class Template Reference
#include <shark/ObjectiveFunctions/Loss/CrossEntropy.h>
Public Member Functions
CrossEntropy ()
std::string name () const
From INameable: return the class name.
double eval (UIntVector const &target, BatchOutputType const &prediction) const
double eval (ConstLabelReference target, ConstOutputReference prediction) const
evaluate the loss for a target and a prediction
double evalDerivative (UIntVector const &target, BatchOutputType const &prediction, BatchOutputType &gradient) const
double evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType &gradient) const
evaluate the loss and its derivative for a target and a prediction
double evalDerivative (ConstLabelReference target, ConstOutputReference prediction, BatchOutputType &gradient, MatrixType &hessian) const
Public Member Functions inherited from shark::AbstractLoss< unsigned int, OutputType >
AbstractLoss ()
virtual double eval (BatchLabelType const &target, BatchOutputType const &prediction) const=0
evaluate the loss for a batch of targets and a prediction
double eval (Data< LabelType > const &targets, Data< OutputType > const &predictions) const
virtual double evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType &gradient, MatrixType &hessian) const
evaluate the loss and its first and second derivative for a target and a prediction
virtual double evalDerivative (BatchLabelType const &target, BatchOutputType const &prediction, BatchOutputType &gradient) const
evaluate the loss and the derivative w.r.t. the prediction
double operator() (LabelType const &target, OutputType const &prediction) const
evaluate the loss for a target and a prediction
double operator() (BatchLabelType const &target, BatchOutputType const &prediction) const
Public Member Functions inherited from shark::AbstractCost< LabelT, OutputT >
virtual ~AbstractCost ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstDerivative () const
returns true when the first parameter derivative is implemented
bool isLossFunction () const
returns true when the cost function is in fact a loss function
virtual double eval (Data< LabelType > const &targets, Data< OutputType > const &predictions) const =0
double operator() (Data< LabelType > const &targets, Data< OutputType > const &predictions) const
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Public Types inherited from shark::AbstractLoss< unsigned int, OutputType >
typedef OutputType OutputType
typedef unsigned int LabelType
typedef RealMatrix MatrixType
typedef Batch< OutputType >::type BatchOutputType
typedef Batch< LabelType >::type BatchLabelType
typedef ConstProxyReference< LabelTypeconst >::type ConstLabelReference
Const references to LabelType.
typedef ConstProxyReference< OutputTypeconst >::type ConstOutputReference
Const references to OutputType.
Public Types inherited from shark::AbstractCost< LabelT, OutputT >
enum Feature { HAS_FIRST_DERIVATIVE = 1 , HAS_SECOND_DERIVATIVE = 2 , IS_LOSS_FUNCTION = 4 }
list of features a cost function can have
typedef OutputT OutputType
typedef LabelT LabelType
typedef Batch< OutputType >::type BatchOutputType
typedef Batch< LabelType >::type BatchLabelType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Protected Attributes inherited from shark::AbstractCost< LabelT, OutputT >
Features m_features
Detailed Description
template<class OutputType>
class shark::CrossEntropy< unsigned int, OutputType >
Definition at line 72 of file CrossEntropy.h.
Constructor & Destructor Documentation
CrossEntropy()
template<class OutputType > shark::CrossEntropy< unsigned int, OutputType >::CrossEntropy () inline
Definition at line 94 of file CrossEntropy.h.
Member Function Documentation
eval() [1/2]
template<class OutputType > double shark::CrossEntropy< unsigned int, OutputType >::eval (ConstLabelReference target, ConstOutputReference prediction) const inline virtual
evaluate the loss for a target and a prediction
Parameters
target target value
prediction prediction, typically made by a model
Reimplemented from shark::AbstractLoss< unsigned int, OutputType >.
Definition at line 113 of file CrossEntropy.h.
References RANGE_CHECK.
eval() [2/2]
template<class OutputType > double shark::CrossEntropy< unsigned int, OutputType >::eval (UIntVector const & target, BatchOutputType const & prediction) const inline
Definition at line 105 of file CrossEntropy.h.
evalDerivative() [1/3]
template<class OutputType > double shark::CrossEntropy< unsigned int, OutputType >::evalDerivative (ConstLabelReference target, ConstOutputReference prediction, BatchOutputType & gradient, MatrixType & hessian) const inline
Definition at line 194 of file CrossEntropy.h.
References RANGE_CHECK, and shark::sigmoid().
evalDerivative() [2/3]
template<class OutputType > double shark::CrossEntropy< unsigned int, OutputType >::evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType & gradient) const inline virtual
evaluate the loss and its derivative for a target and a prediction
Parameters
target target value
prediction prediction, typically made by a model
gradient the gradient of the loss function with respect to the prediction
Reimplemented from shark::AbstractLoss< unsigned int, OutputType >.
Definition at line 168 of file CrossEntropy.h.
References RANGE_CHECK, and shark::sigmoid().
evalDerivative() [3/3]
template<class OutputType > double shark::CrossEntropy< unsigned int, OutputType >::evalDerivative (UIntVector const & target, BatchOutputType const & prediction, BatchOutputType & gradient) const inline
Definition at line 133 of file CrossEntropy.h.
References RANGE_CHECK, and shark::sigmoid().
name()
template<class OutputType > std::string shark::CrossEntropy< unsigned int, OutputType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 99 of file CrossEntropy.h.
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/Loss/CrossEntropy.h