shark::Classifier< Model > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::Classifier< Model > Class Template Reference
Models
Conversion of real-valued or vector valued outputs to class labels.
#include <shark/Models/Classifier.h>
Public Types
typedef Model DecisionFunctionType
typedef Model::InputType InputType
typedef unsigned int OutputType
typedef Batch< InputType >::type BatchInputType
typedef Batch< unsignedint >::type BatchOutputType
typedef Model::ParameterVectorType ParameterVectorType
Public Types inherited from shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >
enum Feature
typedef Model::InputType InputType
Defines the input type of the model.
typedef unsigned int OutputType
Defines the output type of the model.
typedef AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType > ModelBaseType
Defines the BaseType used by the model (this type). Useful for creating derived models.
typedef Batch< InputType >::type BatchInputType
defines the batch type of the input type.
typedef Batch< OutputType >::type BatchOutputType
defines the batch type of the output type
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
Classifier ()
Classifier (Model const &decisionFunction)
std::string name () const
returns the name of the object
ParameterVectorType parameterVector () const
Return the parameter vector.
void setParameterVector (ParameterVectorType const &newParameters)
std::size_t numberOfParameters () const
Return the number of parameters.
Shape inputShape () const
Returns the expected shape of the input.
Shape outputShape () const
Returns the shape of the output.
RealVector const & bias () const
RealVector & bias ()
Model const & decisionFunction () const
Return the decision function.
Model & decisionFunction ()
Return the decision function.
void eval (BatchInputType const &input, BatchOutputType &output) const
void eval (BatchInputType const &input, BatchOutputType &output, State &state) const
void eval (InputType const &pattern, OutputType &output) const
Standard interface for evaluating the response of the model to a single pattern.
void read (InArchive &archive)
From ISerializable.
void write (OutArchive &archive) const
From ISerializable.
Public Member Functions inherited from shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >
AbstractModel ()
virtual ~AbstractModel ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
Returns true when the first parameter derivative is implemented.
bool hasFirstInputDerivative () const
Returns true when the first input derivative is implemented.
virtual boost::shared_ptr< State > createState () const
Creates an internal state of the model.
virtual void eval (BatchInputType const &patterns, BatchOutputType &outputs) const
Standard interface for evaluating the response of the model to a batch of patterns.
virtual void eval (BatchInputType const &patterns, BatchOutputType &outputs, State &state) const=0
Standard interface for evaluating the response of the model to a batch of patterns.
Data< OutputType > operator() (Data< InputType > const &patterns) const
Model evaluation as an operator for a whole dataset. This is a convenience function.
OutputType operator() (InputType const &pattern) const
Model evaluation as an operator for a single pattern. This is a convenience function.
BatchOutputType operator() (BatchInputType const &patterns) const
Model evaluation as an operator for a single pattern. This is a convenience function.
virtual void weightedParameterDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, Model::ParameterVectorType &derivative) const
calculates the weighted sum of derivatives w.r.t the parameters.
virtual void weightedInputDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchInputType &derivative) const
calculates the weighted sum of derivatives w.r.t the inputs
virtual void weightedDerivatives (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, Model::ParameterVectorType &parameterDerivative, BatchInputType &inputDerivative) const
calculates weighted input and parameter derivative at the same time
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
virtual void setParameterVector (ParameterVectorType const &newParameters)
Set the parameter vector.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >
Features m_features
Detailed Description
template<class Model>
class shark::Classifier< Model >
Conversion of real-valued or vector valued outputs to class labels.
The Classifier is a model converting the real-valued vector output of an underlying decision function to a class label 0, ..., d-1 by means of an arg-max operation. The class returns the argument of the maximal input component as its output. This convertson is adjusted to interpret the output of a linear model, a neural network or a support vector machine for multi-category classification.
In the special case that d is 1, it is assumed that the model can be represented as a 2 d vector with both components having the same value but opposite sign. In consequence, a positive output of the model is interpreted as class 1, a negative as class 0.
The underlying decision function is an arbitrary model. It should be default constructable and it can be accessed using decisionFunction(). The parameters of the Classifier are the ones of the decision function.
Optionally the model allows to set bias values which are added on the predicted values of the decision function. Thus adding positive weights on a class makes it more likely to be predicted. In the binary case with a single output, a positive weight makes class one more likely and a negative weight class 0.
Definition at line 66 of file Classifier.h.
Member Typedef Documentation
BatchInputType
template<class Model > typedef Batch<InputType>::type shark::Classifier< Model >::BatchInputType
Definition at line 77 of file Classifier.h.
BatchOutputType
template<class Model > typedef Batch<unsignedint>::type shark::Classifier< Model >::BatchOutputType
Definition at line 78 of file Classifier.h.
DecisionFunctionType
template<class Model > typedef Model shark::Classifier< Model >::DecisionFunctionType
Definition at line 74 of file Classifier.h.
InputType
template<class Model > typedef Model::InputType shark::Classifier< Model >::InputType
Definition at line 75 of file Classifier.h.
OutputType
template<class Model > typedef unsigned int shark::Classifier< Model >::OutputType
Definition at line 76 of file Classifier.h.
ParameterVectorType
template<class Model > typedef Model::ParameterVectorType shark::Classifier< Model >::ParameterVectorType
Definition at line 79 of file Classifier.h.
Constructor & Destructor Documentation
Classifier() [1/2]
template<class Model > shark::Classifier< Model >::Classifier () inline
Definition at line 81 of file Classifier.h.
Classifier() [2/2]
template<class Model > shark::Classifier< Model >::Classifier (Model const & decisionFunction) inline
Definition at line 82 of file Classifier.h.
Member Function Documentation
bias() [1/2]
template<class Model > RealVector & shark::Classifier< Model >::bias () inline
Definition at line 114 of file Classifier.h.
bias() [2/2]
template<class Model > RealVector const & shark::Classifier< Model >::bias () const inline
Definition at line 111 of file Classifier.h.
Referenced by shark::Classifier< Model >::eval(), and shark::Classifier< Model >::eval().
decisionFunction() [1/2]
template<class Model > Model & shark::Classifier< Model >::decisionFunction () inline
Return the decision function.
Definition at line 124 of file Classifier.h.
decisionFunction() [2/2]
template<class Model > Model const & shark::Classifier< Model >::decisionFunction () const inline
Return the decision function.
Definition at line 119 of file Classifier.h.
Referenced by shark::SvmLogisticInterpretation< InputType >::eval(), shark::SvmLogisticInterpretation< InputType >::evalDerivative(), main(), run(), shark::LinearClassifier< VectorType >::setStructure(), shark::LinearClassifier< VectorType >::setStructure(), shark::KernelBudgetedSGDTrainer< InputType, CacheType >::train(), shark::KernelSGDTrainer< InputType, CacheType >::train(), shark::Perceptron< InputType >::train(), shark::KernelMeanClassifier< InputType >::train(), shark::CSvmTrainer< InputType, CacheType >::train(), shark::SquaredHingeCSvmTrainer< InputType, CacheType >::train(), shark::CSvmTrainer< InputType, CacheType >::train(), and shark::SquaredHingeLinearCSvmTrainer< InputType >::train().
eval() [1/3]
template<class Model > void shark::Classifier< Model >::eval (BatchInputType const & input, BatchOutputType & output) const inline
Definition at line 128 of file Classifier.h.
References shark::batchSize(), shark::Classifier< Model >::bias(), and SIZE_CHECK.
Referenced by shark::Classifier< Model >::eval().
eval() [2/3]
template<class Model > void shark::Classifier< Model >::eval (BatchInputType const & input, BatchOutputType & output, State & state) const inline
Definition at line 149 of file Classifier.h.
References shark::Classifier< Model >::eval().
eval() [3/3]
template<class Model > void shark::Classifier< Model >::eval (InputType const & pattern, OutputType & output) const inline virtual
Standard interface for evaluating the response of the model to a single pattern.
Parameters
pattern the input of the model
output the prediction or response of the model to the pattern
Reimplemented from shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >.
Definition at line 153 of file Classifier.h.
References shark::Classifier< Model >::bias(), and SIZE_CHECK.
inputShape()
template<class Model > Shape shark::Classifier< Model >::inputShape () const inline virtual
Returns the expected shape of the input.
Implements shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >.
Definition at line 101 of file Classifier.h.
name()
template<class Model > std::string shark::Classifier< Model >::name () const inline virtual
returns the name of the object
Reimplemented from shark::INameable.
Reimplemented in shark::KernelClassifier< InputType >, shark::LinearClassifier< VectorType >, and shark::NearestNeighborModel< InputType, unsigned int >.
Definition at line 85 of file Classifier.h.
numberOfParameters()
template<class Model > std::size_t shark::Classifier< Model >::numberOfParameters () const inline virtual
Return the number of parameters.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 96 of file Classifier.h.
outputShape()
template<class Model > Shape shark::Classifier< Model >::outputShape () const inline virtual
Returns the shape of the output.
For the classifier, Shape is a number representing the number of classes.
Implements shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >.
Definition at line 107 of file Classifier.h.
parameterVector()
template<class Model > ParameterVectorType shark::Classifier< Model >::parameterVector () const inline virtual
Return the parameter vector.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 88 of file Classifier.h.
read()
template<class Model > void shark::Classifier< Model >::read (InArchive & archive) inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >.
Definition at line 172 of file Classifier.h.
setParameterVector()
template<class Model > void shark::Classifier< Model >::setParameterVector (ParameterVectorType const & newParameters) inline
Definition at line 92 of file Classifier.h.
Referenced by main().
write()
template<class Model > void shark::Classifier< Model >::write (OutArchive & archive) const inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >.
Definition at line 177 of file Classifier.h.
The documentation for this class was generated from the following file:
include/shark/Models/Classifier.h