shark::ZeroOneLoss< unsigned int, blas::vector< Float > > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::ZeroOneLoss< unsigned int, blas::vector< Float > > Class Template Reference
0-1-loss for classification.
#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>
Public Types
typedef base_type::BatchLabelType BatchLabelType
typedef base_type::BatchOutputType BatchOutputType
Public Types inherited from shark::AbstractLoss< unsigned int, blas::vector< Float > >
typedef blas::vector< Float > OutputType
typedef unsigned int LabelType
typedef RealMatrix MatrixType
typedef Batch< OutputType >::type BatchOutputType
typedef Batch< LabelType >::type BatchLabelType
typedef ConstProxyReference< LabelTypeconst >::type ConstLabelReference
Const references to LabelType.
typedef ConstProxyReference< OutputTypeconst >::type ConstOutputReference
Const references to OutputType.
Public Types inherited from shark::AbstractCost< LabelT, OutputT >
enum Feature { HAS_FIRST_DERIVATIVE = 1 , HAS_SECOND_DERIVATIVE = 2 , IS_LOSS_FUNCTION = 4 }
list of features a cost function can have
typedef OutputT OutputType
typedef LabelT LabelType
typedef Batch< OutputType >::type BatchOutputType
typedef Batch< LabelType >::type BatchLabelType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
ZeroOneLoss (double threshold=0.0)
std::string name () const
From INameable: return the class name.
double eval (BatchLabelType const &labels, BatchOutputType const &predictions) const
double eval (Data< unsigned int > const &targets, Data< blas::vector< Float > > const &predictions, RealVector const &weights) const
Public Member Functions inherited from shark::AbstractLoss< unsigned int, blas::vector< Float > >
AbstractLoss ()
virtual double eval (ConstLabelReference target, ConstOutputReference prediction) const
evaluate the loss for a target and a prediction
double eval (Data< LabelType > const &targets, Data< OutputType > const &predictions) const
virtual double evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType &gradient) const
evaluate the loss and its derivative for a target and a prediction
virtual double evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType &gradient, MatrixType &hessian) const
evaluate the loss and its first and second derivative for a target and a prediction
virtual double evalDerivative (BatchLabelType const &target, BatchOutputType const &prediction, BatchOutputType &gradient) const
evaluate the loss and the derivative w.r.t. the prediction
double operator() (LabelType const &target, OutputType const &prediction) const
evaluate the loss for a target and a prediction
double operator() (BatchLabelType const &target, BatchOutputType const &prediction) const
Public Member Functions inherited from shark::AbstractCost< LabelT, OutputT >
virtual ~AbstractCost ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstDerivative () const
returns true when the first parameter derivative is implemented
bool isLossFunction () const
returns true when the cost function is in fact a loss function
virtual double eval (Data< LabelType > const &targets, Data< OutputType > const &predictions) const =0
double operator() (Data< LabelType > const &targets, Data< OutputType > const &predictions) const
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractCost< LabelT, OutputT >
Features m_features
Detailed Description
template<class Float>
class shark::ZeroOneLoss< unsigned int, blas::vector< Float > >
0-1-loss for classification.
Definition at line 85 of file ZeroOneLoss.h.
Member Typedef Documentation
BatchLabelType
template<class Float > typedef base_type::BatchLabelType shark::ZeroOneLoss< unsigned int, blas::vector< Float > >::BatchLabelType
Definition at line 89 of file ZeroOneLoss.h.
BatchOutputType
template<class Float > typedef base_type::BatchOutputType shark::ZeroOneLoss< unsigned int, blas::vector< Float > >::BatchOutputType
Definition at line 90 of file ZeroOneLoss.h.
Constructor & Destructor Documentation
ZeroOneLoss()
template<class Float > shark::ZeroOneLoss< unsigned int, blas::vector< Float > >::ZeroOneLoss (double threshold = 0.0) inline
constructor
Parameters
threshold in the case dim(predictions) == 1, predictions strictly larger than this parameter are regarded as belonging to the positive class
Definition at line 95 of file ZeroOneLoss.h.
Member Function Documentation
eval() [1/2]
template<class Float > double shark::ZeroOneLoss< unsigned int, blas::vector< Float > >::eval (BatchLabelType const & labels, BatchOutputType const & predictions) const inline virtual
Return zero if labels == arg max { predictions_i } and one otherwise, where the index i runs over the components of the predictions vector. A special version of dim(predictions) == 1 computes the predicted labels by thresholding at zero. Shark's label convention is used, saying that a positive value encodes class 0, a negative value encodes class 1.
Implements shark::AbstractLoss< unsigned int, blas::vector< Float > >.
Definition at line 114 of file ZeroOneLoss.h.
References SIZE_CHECK.
eval() [2/2]
template<class Float > double shark::ZeroOneLoss< unsigned int, blas::vector< Float > >::eval (Data< unsigned int > const & targets, Data< blas::vector< Float > > const & predictions, RealVector const & weights) const inline
Definition at line 125 of file ZeroOneLoss.h.
References shark::Data< Type >::batch(), shark::Data< Type >::numberOfBatches(), shark::Data< Type >::numberOfElements(), and SIZE_CHECK.
name()
template<class Float > std::string shark::ZeroOneLoss< unsigned int, blas::vector< Float > >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 101 of file ZeroOneLoss.h.
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/Loss/ZeroOneLoss.h