shark::BarsAndStripes Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::BarsAndStripes Class Reference
Generates the Bars-And-Stripes problem. In this problem, a 4x4 image has either rows or columns of the same value.
#include <shark/Unsupervised/RBM/Problems/BarsAndStripes.h>
Public Member Functions
BarsAndStripes (std::size_t batchSize=32, bool bipolar=false)
UnlabeledData< RealVector > data () const
Returns all input pattern of the BarsAndStripes problem.
std::size_t inputDimension () const
returns the dimensionality of the data
Detailed Description
Generates the Bars-And-Stripes problem. In this problem, a 4x4 image has either rows or columns of the same value.
Definition at line 36 of file BarsAndStripes.h.
Constructor & Destructor Documentation
BarsAndStripes()
shark::BarsAndStripes::BarsAndStripes (std::size_t batchSize = 32, bool bipolar = false) inline
Definition at line 40 of file BarsAndStripes.h.
References shark::batchSize(), shark::createDataFromRange(), and data().
Member Function Documentation
data()
UnlabeledData< RealVector > shark::BarsAndStripes::data () const inline
Returns all input pattern of the BarsAndStripes problem.
Definition at line 61 of file BarsAndStripes.h.
Referenced by BarsAndStripes(), and main().
inputDimension()
std::size_t shark::BarsAndStripes::inputDimension () const inline
returns the dimensionality of the data
Definition at line 66 of file BarsAndStripes.h.
Referenced by main().
The documentation for this class was generated from the following file:
include/shark/Unsupervised/RBM/Problems/BarsAndStripes.h