shark::LogisticRegression< InputVectorType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::LogisticRegression< InputVectorType > Class Template Reference
Supervised Trainers
Trainer for Logistic regression.
#include <shark/Algorithms/Trainers/LogisticRegression.h>
Public Types
typedef base_type::ModelType ModelType
typedef base_type::DatasetType DatasetType
typedef base_type::WeightedDatasetType WeightedDatasetType
Public Types inherited from shark::AbstractWeightedTrainer< Model, LabelTypeT >
typedef base_type::ModelType ModelType
typedef base_type::InputType InputType
typedef base_type::LabelType LabelType
typedef base_type::DatasetType DatasetType
typedef WeightedLabeledData< InputType, LabelType > WeightedDatasetType
Public Types inherited from shark::AbstractTrainer< Model, LabelTypeT >
typedef Model ModelType
typedef ModelType::InputType InputType
typedef LabelTypeT LabelType
typedef LabeledData< InputType, LabelType > DatasetType
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
LogisticRegression (double lambda1=0, double lambda2=0, bool bias=true, double accuracy=1.e-8)
Constructor.
std::string name () const
From INameable: return the class name.
double lambda1 () const
Return the current setting of the l1-regularization parameter.
double lambda2 () const
Return the current setting of the l2-regularization parameter.
void setLambda1 (double lambda)
Set the l1-regularization parameter.
void setLambda2 (double lambda)
Set the l2-regularization parameter.
double accuracy () const
Return the current setting of the accuracy (maximal gradient component of the optimization problem).
void setAccuracy (double accuracy)
Set the accuracy (maximal gradient component of the optimization problem).
RealVector parameterVector () const
Get the regularization parameters lambda1 and lambda2 through the IParameterizable interface.
void setParameterVector (RealVector const &param)
Set the regularization parameters lambda1 and lambda2 through the IParameterizable interface.
size_t numberOfParameters () const
Return the number of parameters (one in this case).
void train (ModelType &model, DatasetType const &dataset)
Train a linear model with logistic regression.
void train (ModelType &model, WeightedDatasetType const &dataset)
Train a linear model with logistic regression using weights.
Public Member Functions inherited from shark::AbstractWeightedTrainer< Model, LabelTypeT >
virtual void train (ModelType &model, WeightedDatasetType const &dataset)=0
Executes the algorithm and trains a model on the given weighted data.
virtual void train (ModelType &model, DatasetType const &dataset)
Executes the algorithm and trains a model on the given unweighted data.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Detailed Description
template<class InputVectorType = RealVector>
class shark::LogisticRegression< InputVectorType >
Trainer for Logistic regression.
Logistic regression solves the following optimization problem:
\[ \min_{w,b} \sum_i u_i l(y_i,f(x_i^Tw+b)) +\lambda_1 |w|_1 +\lambda_2 |w|^2_2 \]
Where \(l\) is the cross-entropy loss and \(u_i\) are individual weuights for each point(assumed to be 1). Logistic regression is one of the most well known machine learning algorithms for classification using linear models.
The solver is based on LBFGS for the case where no l1-regularization is used. Otherwise the problem is transformed into a constrained problem and the constrined-LBFGS algorithm is used. This is one of the most efficient solvers for logistic regression as long as the number of data points is not too large.
Definition at line 59 of file LogisticRegression.h.
Member Typedef Documentation
DatasetType
template<class InputVectorType = RealVector> typedef base_type::DatasetType shark::LogisticRegression< InputVectorType >::DatasetType
Definition at line 65 of file LogisticRegression.h.
ModelType
template<class InputVectorType = RealVector> typedef base_type::ModelType shark::LogisticRegression< InputVectorType >::ModelType
Definition at line 64 of file LogisticRegression.h.
WeightedDatasetType
template<class InputVectorType = RealVector> typedef base_type::WeightedDatasetType shark::LogisticRegression< InputVectorType >::WeightedDatasetType
Definition at line 66 of file LogisticRegression.h.
Constructor & Destructor Documentation
LogisticRegression()
template<class InputVectorType = RealVector> shark::LogisticRegression< InputVectorType >::LogisticRegression (double lambda1 = 0, double lambda2 = 0, bool bias = true, double accuracy = 1.e-8) inline
Constructor.
Parameters
lambda1 value of the 1-norm regularization parameter (see class description)
lambda2 value of the 2-norm regularization parameter (see class description)
bias whether to train with bias or not
accuracy stopping criterion for the iterative solver, maximal gradient component of the objective function (see class description)
Definition at line 74 of file LogisticRegression.h.
References shark::LogisticRegression< InputVectorType >::accuracy(), shark::LogisticRegression< InputVectorType >::lambda1(), shark::LogisticRegression< InputVectorType >::lambda2(), shark::LogisticRegression< InputVectorType >::setAccuracy(), shark::LogisticRegression< InputVectorType >::setLambda1(), and shark::LogisticRegression< InputVectorType >::setLambda2().
Member Function Documentation
accuracy()
template<class InputVectorType = RealVector> double shark::LogisticRegression< InputVectorType >::accuracy () const inline
Return the current setting of the accuracy (maximal gradient component of the optimization problem).
Definition at line 108 of file LogisticRegression.h.
Referenced by shark::LogisticRegression< InputVectorType >::LogisticRegression(), and shark::LogisticRegression< InputVectorType >::setAccuracy().
lambda1()
template<class InputVectorType = RealVector> double shark::LogisticRegression< InputVectorType >::lambda1 () const inline
Return the current setting of the l1-regularization parameter.
Definition at line 87 of file LogisticRegression.h.
Referenced by shark::LogisticRegression< InputVectorType >::LogisticRegression().
lambda2()
template<class InputVectorType = RealVector> double shark::LogisticRegression< InputVectorType >::lambda2 () const inline
Return the current setting of the l2-regularization parameter.
Definition at line 92 of file LogisticRegression.h.
Referenced by shark::LogisticRegression< InputVectorType >::LogisticRegression().
name()
template<class InputVectorType = RealVector> std::string shark::LogisticRegression< InputVectorType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 82 of file LogisticRegression.h.
numberOfParameters()
template<class InputVectorType = RealVector> size_t shark::LogisticRegression< InputVectorType >::numberOfParameters () const inline virtual
Return the number of parameters (one in this case).
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 131 of file LogisticRegression.h.
parameterVector()
template<class InputVectorType = RealVector> RealVector shark::LogisticRegression< InputVectorType >::parameterVector () const inline virtual
Get the regularization parameters lambda1 and lambda2 through the IParameterizable interface.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 119 of file LogisticRegression.h.
setAccuracy()
template<class InputVectorType = RealVector> void shark::LogisticRegression< InputVectorType >::setAccuracy (double accuracy) inline
Set the accuracy (maximal gradient component of the optimization problem).
Definition at line 113 of file LogisticRegression.h.
References shark::LogisticRegression< InputVectorType >::accuracy(), and SHARK_RUNTIME_CHECK.
Referenced by shark::LogisticRegression< InputVectorType >::LogisticRegression().
setLambda1()
template<class InputVectorType = RealVector> void shark::LogisticRegression< InputVectorType >::setLambda1 (double lambda) inline
Set the l1-regularization parameter.
Definition at line 97 of file LogisticRegression.h.
References SHARK_RUNTIME_CHECK.
Referenced by shark::LogisticRegression< InputVectorType >::LogisticRegression(), and shark::LogisticRegression< InputVectorType >::setParameterVector().
setLambda2()
template<class InputVectorType = RealVector> void shark::LogisticRegression< InputVectorType >::setLambda2 (double lambda) inline
Set the l2-regularization parameter.
Definition at line 103 of file LogisticRegression.h.
References SHARK_RUNTIME_CHECK.
Referenced by shark::LogisticRegression< InputVectorType >::LogisticRegression(), and shark::LogisticRegression< InputVectorType >::setParameterVector().
setParameterVector()
template<class InputVectorType = RealVector> void shark::LogisticRegression< InputVectorType >::setParameterVector (RealVector const & param) inline virtual
Set the regularization parameters lambda1 and lambda2 through the IParameterizable interface.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 124 of file LogisticRegression.h.
References shark::LogisticRegression< InputVectorType >::setLambda1(), shark::LogisticRegression< InputVectorType >::setLambda2(), and SIZE_CHECK.
train() [1/2]
template<class InputVectorType = RealVector> void shark::LogisticRegression< InputVectorType >::train (ModelType & model, DatasetType const & dataset)
Train a linear model with logistic regression.
train() [2/2]
template<class InputVectorType = RealVector> void shark::LogisticRegression< InputVectorType >::train (ModelType & model, WeightedDatasetType const & dataset)
Train a linear model with logistic regression using weights.
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/LogisticRegression.h