shark::ValidatedStoppingCriterion Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::ValidatedStoppingCriterion Class Reference
Given the current Result set of the optimizer, calculates the validation error using a validation function and hands the results over to the underlying stopping criterion.
#include <shark/Algorithms/StoppingCriteria/ValidatedStoppingCriterion.h>
Public Types
typedef ValidatedSingleObjectiveResultSet< PointType > ValidationResultSet
typedef AbstractStoppingCriterion< ValidationResultSet > StoppingCriterionType
typedef SingleObjectiveFunction ObjectiveFunctionType
Public Types inherited from shark::AbstractStoppingCriterion< SingleObjectiveResultSet< RealVector > >
typedef SingleObjectiveResultSet< RealVector > ResultSet
Public Member Functions
ValidatedStoppingCriterion (ObjectiveFunctionType *validation, StoppingCriterionType *child)
bool stop (ResultSet const &set)
returns true if training should stop
void reset ()
resets the internal state. call before a new trial
Protected Attributes
ObjectiveFunctionType * mpe_validation
StoppingCriterionType * mpe_child
Detailed Description
Given the current Result set of the optimizer, calculates the validation error using a validation function and hands the results over to the underlying stopping criterion.
Currently only implemented for functions over RealVector
Definition at line 47 of file ValidatedStoppingCriterion.h.
Member Typedef Documentation
ObjectiveFunctionType
typedef SingleObjectiveFunction shark::ValidatedStoppingCriterion::ObjectiveFunctionType
Definition at line 55 of file ValidatedStoppingCriterion.h.
StoppingCriterionType
typedef AbstractStoppingCriterion< ValidationResultSet > shark::ValidatedStoppingCriterion::StoppingCriterionType
Definition at line 54 of file ValidatedStoppingCriterion.h.
ValidationResultSet
typedef ValidatedSingleObjectiveResultSet<PointType> shark::ValidatedStoppingCriterion::ValidationResultSet
Definition at line 53 of file ValidatedStoppingCriterion.h.
Constructor & Destructor Documentation
ValidatedStoppingCriterion()
shark::ValidatedStoppingCriterion::ValidatedStoppingCriterion (ObjectiveFunctionType * validation, StoppingCriterionType * child) inline
Definition at line 58 of file ValidatedStoppingCriterion.h.
References reset().
Member Function Documentation
reset()
void shark::ValidatedStoppingCriterion::reset () inline virtual
resets the internal state. call before a new trial
Implements shark::AbstractStoppingCriterion< SingleObjectiveResultSet< RealVector > >.
Definition at line 67 of file ValidatedStoppingCriterion.h.
References mpe_child, and shark::AbstractStoppingCriterion< ResultSetT >::reset().
Referenced by ValidatedStoppingCriterion().
stop()
bool shark::ValidatedStoppingCriterion::stop (ResultSet const & set) inline virtual
returns true if training should stop
Implements shark::AbstractStoppingCriterion< SingleObjectiveResultSet< RealVector > >.
Definition at line 63 of file ValidatedStoppingCriterion.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::eval(), mpe_child, mpe_validation, shark::ResultSet< SearchPointT, ResultT >::point, and shark::AbstractStoppingCriterion< ResultSetT >::stop().
Member Data Documentation
mpe_child
StoppingCriterionType* shark::ValidatedStoppingCriterion::mpe_child protected
Definition at line 72 of file ValidatedStoppingCriterion.h.
Referenced by reset(), and stop().
mpe_validation
ObjectiveFunctionType* shark::ValidatedStoppingCriterion::mpe_validation protected
Definition at line 71 of file ValidatedStoppingCriterion.h.
Referenced by stop().
The documentation for this class was generated from the following file:
include/shark/Algorithms/StoppingCriteria/ValidatedStoppingCriterion.h