shark::ResizeLayer< VectorType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::ResizeLayer< VectorType > Class Template Reference
Models
Resizes an input image to a given size.
#include <shark/Models/ResizeLayer.h>
Public Types
typedef base_type::BatchOutputType BatchOutputType
typedef base_type::BatchInputType BatchInputType
typedef base_type::ParameterVectorType ParameterVectorType
Public Types inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
enum Feature { HAS_FIRST_PARAMETER_DERIVATIVE = 1 , HAS_FIRST_INPUT_DERIVATIVE = 4 }
typedef InputTypeT InputType
Defines the input type of the model.
typedef OutputTypeT OutputType
Defines the output type of the model.
typedef AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType > ModelBaseType
Defines the BaseType used by the model (this type). Useful for creating derived models.
typedef Batch< InputType >::type BatchInputType
defines the batch type of the input type.
typedef Batch< OutputType >::type BatchOutputType
defines the batch type of the output type
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
ResizeLayer ()
Default Constructor; use setStructure later.
ResizeLayer (Shape const &inputShape, Shape const &outputShape, Interpolation type=Interpolation::Spline)
Configures the model.
std::string name () const
returns the name of the object
Shape inputShape () const
Returns the expected shape of the input.
Shape outputShape () const
Returns the shape of the output.
ParameterVectorType parameterVector () const
Obtain the parameter vector.
void setParameterVector (ParameterVectorType const &newParameters)
Set the new parameters of the model.
size_t numberOfParameters () const
Return the number of parameters.
void setStructure (Shape const &inputShape, Shape const &outputShape, Interpolation type=Interpolation::Spline)
Configures the model.
boost::shared_ptr< State > createState () const
Creates an internal state of the model.
void eval (BatchInputType const &inputs, BatchOutputType &outputs, State &) const
Evaluate the model.
void weightedParameterDerivative (BatchInputType const &inputs, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &gradient) const
Calculates the first derivative w.r.t the parameters and summing them up over all inputs of the last computed batch.
void weightedInputDerivative (BatchInputType const &inputs, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchInputType &derivatives) const
Calculates the first derivative w.r.t the inputs and summs them up over all inputs of the last computed batch.
void read (InArchive &archive)
From ISerializable.
void write (OutArchive &archive) const
From ISerializable.
Public Member Functions inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
AbstractModel ()
virtual ~AbstractModel ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
Returns true when the first parameter derivative is implemented.
bool hasFirstInputDerivative () const
Returns true when the first input derivative is implemented.
virtual void eval (BatchInputType const &patterns, BatchOutputType &outputs) const
Standard interface for evaluating the response of the model to a batch of patterns.
virtual void eval (InputType const &pattern, OutputType &output) const
Standard interface for evaluating the response of the model to a single pattern.
Data< OutputType > operator() (Data< InputType > const &patterns) const
Model evaluation as an operator for a whole dataset. This is a convenience function.
OutputType operator() (InputType const &pattern) const
Model evaluation as an operator for a single pattern. This is a convenience function.
BatchOutputType operator() (BatchInputType const &patterns) const
Model evaluation as an operator for a single pattern. This is a convenience function.
virtual void weightedDerivatives (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &parameterDerivative, BatchInputType &inputDerivative) const
calculates weighted input and parameter derivative at the same time
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
Features m_features
Detailed Description
template<class VectorType = RealVector>
class shark::ResizeLayer< VectorType >
Resizes an input image to a given size.
The image is resized using an interpolation algorithm which can be chosen by the user. Right now, only spline interpolation is supported. This will slightly smooth input images over a 4x4 grid. This also means that resizing to the same size is not an identity operation
The derivative of the model wrt its input images is available.
Definition at line 57 of file ResizeLayer.h.
Member Typedef Documentation
BatchInputType
template<class VectorType = RealVector> typedef base_type::BatchInputType shark::ResizeLayer< VectorType >::BatchInputType
Definition at line 66 of file ResizeLayer.h.
BatchOutputType
template<class VectorType = RealVector> typedef base_type::BatchOutputType shark::ResizeLayer< VectorType >::BatchOutputType
Definition at line 65 of file ResizeLayer.h.
ParameterVectorType
template<class VectorType = RealVector> typedef base_type::ParameterVectorType shark::ResizeLayer< VectorType >::ParameterVectorType
Definition at line 67 of file ResizeLayer.h.
Constructor & Destructor Documentation
ResizeLayer() [1/2]
template<class VectorType = RealVector> shark::ResizeLayer< VectorType >::ResizeLayer () inline
Default Constructor; use setStructure later.
Definition at line 70 of file ResizeLayer.h.
References shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_INPUT_DERIVATIVE, shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_PARAMETER_DERIVATIVE, and shark::AbstractModel< VectorType, VectorType, VectorType >::m_features.
ResizeLayer() [2/2]
template<class VectorType = RealVector> shark::ResizeLayer< VectorType >::ResizeLayer (Shape const & inputShape, Shape const & outputShape, Interpolation type = Interpolation::Spline) inline
Configures the model.
inputShape Shape of the image imHeight x imWidth x channel
outputShape Shape of the resized output imHeight x imWidth
type Type of interpolation to perform, default is Spline-Interpolation
Definition at line 80 of file ResizeLayer.h.
References shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_INPUT_DERIVATIVE, shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_PARAMETER_DERIVATIVE, shark::ResizeLayer< VectorType >::inputShape(), shark::AbstractModel< VectorType, VectorType, VectorType >::m_features, shark::ResizeLayer< VectorType >::outputShape(), and shark::ResizeLayer< VectorType >::setStructure().
Member Function Documentation
createState()
template<class VectorType = RealVector> boost::shared_ptr< State > shark::ResizeLayer< VectorType >::createState () const inline virtual
Creates an internal state of the model.
The state is needed when the derivatives are to be calculated. Eval can store a state which is then reused to speed up the calculations of the derivatives. This also allows eval to be evaluated in parallel!
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 136 of file ResizeLayer.h.
eval()
template<class VectorType = RealVector> void shark::ResizeLayer< VectorType >::eval (BatchInputType const & inputs, BatchOutputType & outputs, State &) const inline virtual
Evaluate the model.
Implements shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 143 of file ResizeLayer.h.
References shark::Shape::numElements(), and SIZE_CHECK.
inputShape()
template<class VectorType = RealVector> Shape shark::ResizeLayer< VectorType >::inputShape () const inline virtual
Returns the expected shape of the input.
Implements shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 92 of file ResizeLayer.h.
Referenced by shark::ResizeLayer< VectorType >::ResizeLayer(), and shark::ResizeLayer< VectorType >::setStructure().
name()
template<class VectorType = RealVector> std::string shark::ResizeLayer< VectorType >::name () const inline virtual
returns the name of the object
Reimplemented from shark::INameable.
Definition at line 88 of file ResizeLayer.h.
numberOfParameters()
template<class VectorType = RealVector> size_t shark::ResizeLayer< VectorType >::numberOfParameters () const inline virtual
Return the number of parameters.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 109 of file ResizeLayer.h.
outputShape()
template<class VectorType = RealVector> Shape shark::ResizeLayer< VectorType >::outputShape () const inline virtual
Returns the shape of the output.
Implements shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 96 of file ResizeLayer.h.
Referenced by shark::ResizeLayer< VectorType >::ResizeLayer(), and shark::ResizeLayer< VectorType >::setStructure().
parameterVector()
template<class VectorType = RealVector> ParameterVectorType shark::ResizeLayer< VectorType >::parameterVector () const inline virtual
Obtain the parameter vector.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 101 of file ResizeLayer.h.
read()
template<class VectorType = RealVector> void shark::ResizeLayer< VectorType >::read (InArchive & archive) inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 185 of file ResizeLayer.h.
setParameterVector()
template<class VectorType = RealVector> void shark::ResizeLayer< VectorType >::setParameterVector (ParameterVectorType const & newParameters) inline virtual
Set the new parameters of the model.
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 106 of file ResizeLayer.h.
setStructure()
template<class VectorType = RealVector> void shark::ResizeLayer< VectorType >::setStructure (Shape const & inputShape, Shape const & outputShape, Interpolation type = Interpolation::Spline) inline
Configures the model.
inputShape Shape of the image imHeight x imWidth x channel
outputShape Shape of the resized output imHeight x imWidth
type Type of interpolation to perform, default is Spline-Interpolation
Definition at line 118 of file ResizeLayer.h.
References shark::ResizeLayer< VectorType >::inputShape(), and shark::ResizeLayer< VectorType >::outputShape().
Referenced by shark::ResizeLayer< VectorType >::ResizeLayer().
weightedInputDerivative()
template<class VectorType = RealVector> void shark::ResizeLayer< VectorType >::weightedInputDerivative (BatchInputType const & inputs, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, BatchInputType & derivatives) const inline virtual
Calculates the first derivative w.r.t the inputs and summs them up over all inputs of the last computed batch.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 162 of file ResizeLayer.h.
References shark::Shape::numElements(), and SIZE_CHECK.
weightedParameterDerivative()
template<class VectorType = RealVector> void shark::ResizeLayer< VectorType >::weightedParameterDerivative (BatchInputType const & inputs, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, ParameterVectorType & gradient) const inline virtual
Calculates the first derivative w.r.t the parameters and summing them up over all inputs of the last computed batch.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 154 of file ResizeLayer.h.
write()
template<class VectorType = RealVector> void shark::ResizeLayer< VectorType >::write (OutArchive & archive) const inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 192 of file ResizeLayer.h.
The documentation for this class was generated from the following file:
include/shark/Models/ResizeLayer.h