shark::IParameterizable< VectorType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::IParameterizable< VectorType > Class Template Reference
Top level interface for everything that holds parameters.
#include <shark/Core/IParameterizable.h>
Public Types
typedef VectorType ParameterVectorType
Public Member Functions
virtual ~IParameterizable ()
virtual ParameterVectorType parameterVector () const
Return the parameter vector.
virtual void setParameterVector (ParameterVectorType const &newParameters)
Set the parameter vector.
virtual std::size_t numberOfParameters () const
Return the number of parameters.
Detailed Description
template<class VectorType = RealVector>
class shark::IParameterizable< VectorType >
Top level interface for everything that holds parameters.
This interface is inherited by AbstractModel for unified access to the parameters of models, but also by objective functions and algorithms with hyper-parameters.
the type of parameter vector can be chosen, e.g. to change precision or port parameters to GPU
Definition at line 53 of file IParameterizable.h.
Member Typedef Documentation
ParameterVectorType
template<class VectorType = RealVector> typedef VectorType shark::IParameterizable< VectorType >::ParameterVectorType
Definition at line 55 of file IParameterizable.h.
Constructor & Destructor Documentation
~IParameterizable()
template<class VectorType = RealVector> virtual shark::IParameterizable< VectorType >::~IParameterizable () inline virtual
Definition at line 56 of file IParameterizable.h.
Member Function Documentation
numberOfParameters()
template<class VectorType = RealVector> virtual std::size_t shark::IParameterizable< VectorType >::numberOfParameters () const inline virtual
Return the number of parameters.
Reimplemented in shark::AbstractSvmTrainer< InputType, LabelType, Model, Trainer >, shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >, shark::AbstractSvmTrainer< InputType, unsigned int >, shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >, shark::AbstractSvmTrainer< InputType, unsigned int, KernelExpansion< InputType > >, shark::AbstractSvmTrainer< InputType, unsigned int, MissingFeaturesKernelExpansion< InputType > >, shark::AbstractLinearSvmTrainer< InputType >, shark::KernelBudgetedSGDTrainer< InputType, CacheType >, shark::EpsilonSvmTrainer< InputType, CacheType >, shark::KernelSGDTrainer< InputType, CacheType >, shark::LassoRegression< InputVectorType >, shark::LDA, shark::LinearRegression, shark::LinearSAGTrainer< InputType, LabelType >, shark::LogisticRegression< InputVectorType >, shark::OneClassSvmTrainer< InputType, CacheType >, shark::Classifier< Model >, shark::Classifier< detail::BaseNearestNeighbor< InputType, unsigned int > >, shark::Classifier< KernelExpansion< InputType > >, shark::Classifier< LinearModel< RealVector > >, shark::Centroids, shark::ClusteringModel< InputT, OutputT >, shark::ClusteringModel< InputT, RealVector >, shark::ClusteringModel< InputT, unsigned int >, shark::HierarchicalClustering< InputT >, shark::CMACMap, shark::ConcatenatedModel< VectorType >, shark::Conv2DModel< VectorType, ActivationFunction >, shark::DropoutLayer< VectorType >, shark::ARDKernelUnconstrained< InputType >, shark::DiscreteKernel, shark::GaussianRbfKernel< InputType >, shark::KernelExpansion< InputType >, shark::ModelKernel< InputType >, shark::MonomialKernel< InputType >, shark::GaussianTaskKernel< InputTypeT >, shark::NormalizedKernel< InputType >, shark::PointSetKernel< InputType >, shark::PolynomialKernel< InputType >, shark::ProductKernel< InputType >, shark::ProductKernel< MultiTaskSample< InputTypeT > >, shark::ScaledKernel< InputType >, shark::WeightedSumKernel< InputType >, shark::WeightedSumKernel< InputType >, shark::LinearModel< InputType, ActivationFunction >, shark::LinearModel< RealVector >, shark::NeuronLayer< NeuronType, VectorType >, shark::Normalizer< VectorType >, shark::OneVersusOneClassifier< InputType, VectorType >, shark::PoolingLayer< VectorType >, shark::RBFLayer, shark::ResizeLayer< VectorType >, shark::CARTree< LabelType >, shark::BinaryLayer, shark::BipolarLayer, shark::GaussianLayer, and shark::RBM< VisibleLayerT, HiddenLayerT, randomT >.
Definition at line 71 of file IParameterizable.h.
References shark::IParameterizable< VectorType >::parameterVector().
Referenced by shark::ProductKernel< InputType >::addKernel(), shark::calculateKernelMatrixParameterDerivative(), shark::NegativeGaussianProcessEvidence< InputType, OutputType, LabelType >::eval(), shark::RadiusMarginQuotient< InputType, CacheType >::eval(), shark::VariationalAutoencoderError< SearchPointType >::eval(), shark::NegativeGaussianProcessEvidence< InputType, OutputType, LabelType >::evalDerivative(), shark::KernelTargetAlignment< InputType, LabelType >::evalDerivative(), shark::RadiusMarginQuotient< InputType, CacheType >::evalDerivative(), shark::VariationalAutoencoderError< SearchPointType >::evalDerivative(), shark::initRandomNormal(), shark::initRandomUniform(), shark::AbstractSvmTrainer< InputType, LabelType, Model, Trainer >::numberOfParameters(), shark::KernelBudgetedSGDTrainer< InputType, CacheType >::numberOfParameters(), shark::KernelSGDTrainer< InputType, CacheType >::numberOfParameters(), shark::OneClassSvmTrainer< InputType, CacheType >::numberOfParameters(), shark::ClusteringModel< InputT, OutputT >::numberOfParameters(), shark::GaussianTaskKernel< InputTypeT >::numberOfParameters(), shark::NormalizedKernel< InputType >::numberOfParameters(), shark::PointSetKernel< InputType >::numberOfParameters(), shark::ScaledKernel< InputType >::numberOfParameters(), shark::CrossValidationError< ModelTypeT, LabelTypeT >::numberOfVariables(), shark::KernelTargetAlignment< InputType, LabelType >::numberOfVariables(), shark::LooError< ModelTypeT, LabelType >::numberOfVariables(), shark::LooErrorCSvm< InputType, CacheType >::numberOfVariables(), shark::NegativeGaussianProcessEvidence< InputType, OutputType, LabelType >::numberOfVariables(), shark::NegativeLogLikelihood::numberOfVariables(), shark::RadiusMarginQuotient< InputType, CacheType >::numberOfVariables(), shark::VariationalAutoencoderError< SearchPointType >::numberOfVariables(), shark::OneClassSvmTrainer< InputType, CacheType >::parameterVector(), shark::VariationalAutoencoderError< SearchPointType >::sampleZ(), shark::AbstractSvmTrainer< InputType, LabelType, Model, Trainer >::setParameterVector(), shark::KernelBudgetedSGDTrainer< InputType, CacheType >::setParameterVector(), shark::KernelSGDTrainer< InputType, CacheType >::setParameterVector(), shark::OneClassSvmTrainer< InputType, CacheType >::setParameterVector(), shark::GaussianTaskKernel< InputTypeT >::setParameterVector(), and shark::NegativeGaussianProcessEvidence< InputType, OutputType, LabelType >::setThreshold().
parameterVector()
template<class VectorType = RealVector> virtual ParameterVectorType shark::IParameterizable< VectorType >::parameterVector () const inline virtual
Return the parameter vector.
Reimplemented in shark::AbstractSvmTrainer< InputType, LabelType, Model, Trainer >, shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >, shark::AbstractSvmTrainer< InputType, unsigned int >, shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >, shark::AbstractSvmTrainer< InputType, unsigned int, KernelExpansion< InputType > >, shark::AbstractSvmTrainer< InputType, unsigned int, MissingFeaturesKernelExpansion< InputType > >, shark::AbstractLinearSvmTrainer< InputType >, shark::KernelBudgetedSGDTrainer< InputType, CacheType >, shark::EpsilonSvmTrainer< InputType, CacheType >, shark::KernelSGDTrainer< InputType, CacheType >, shark::LassoRegression< InputVectorType >, shark::LDA, shark::LinearRegression, shark::LinearSAGTrainer< InputType, LabelType >, shark::LogisticRegression< InputVectorType >, shark::OneClassSvmTrainer< InputType, CacheType >, shark::RFTrainer< unsigned int >, shark::RFTrainer< RealVector >, shark::Classifier< Model >, shark::Classifier< detail::BaseNearestNeighbor< InputType, unsigned int > >, shark::Classifier< KernelExpansion< InputType > >, shark::Classifier< LinearModel< RealVector > >, shark::Centroids, shark::ClusteringModel< InputT, OutputT >, shark::ClusteringModel< InputT, RealVector >, shark::ClusteringModel< InputT, unsigned int >, shark::HierarchicalClustering< InputT >, shark::CMACMap, shark::ConcatenatedModel< VectorType >, shark::Conv2DModel< VectorType, ActivationFunction >, shark::DropoutLayer< VectorType >, shark::ARDKernelUnconstrained< InputType >, shark::DiscreteKernel, shark::GaussianRbfKernel< InputType >, shark::KernelExpansion< InputType >, shark::LinearKernel< InputType >, shark::ModelKernel< InputType >, shark::MonomialKernel< InputType >, shark::GaussianTaskKernel< InputTypeT >, shark::NormalizedKernel< InputType >, shark::PointSetKernel< InputType >, shark::PolynomialKernel< InputType >, shark::ProductKernel< InputType >, shark::ProductKernel< MultiTaskSample< InputTypeT > >, shark::ScaledKernel< InputType >, shark::WeightedSumKernel< InputType >, shark::WeightedSumKernel< InputType >, shark::LinearModel< InputType, ActivationFunction >, shark::LinearModel< RealVector >, shark::NeuronLayer< NeuronType, VectorType >, shark::Normalizer< VectorType >, shark::OneVersusOneClassifier< InputType, VectorType >, shark::PoolingLayer< VectorType >, shark::RBFLayer, shark::ResizeLayer< VectorType >, shark::CARTree< LabelType >, shark::BinaryLayer, shark::BipolarLayer, shark::GaussianLayer, and shark::RBM< VisibleLayerT, HiddenLayerT, randomT >.
Definition at line 59 of file IParameterizable.h.
Referenced by shark::IParameterizable< VectorType >::numberOfParameters(), shark::AbstractSvmTrainer< InputType, LabelType, Model, Trainer >::parameterVector(), shark::KernelBudgetedSGDTrainer< InputType, CacheType >::parameterVector(), shark::KernelSGDTrainer< InputType, CacheType >::parameterVector(), shark::OneClassSvmTrainer< InputType, CacheType >::parameterVector(), shark::ClusteringModel< InputT, OutputT >::parameterVector(), shark::GaussianTaskKernel< InputTypeT >::parameterVector(), shark::NormalizedKernel< InputType >::parameterVector(), shark::PointSetKernel< InputType >::parameterVector(), shark::ScaledKernel< InputType >::parameterVector(), shark::NegativeLogLikelihood::proposeStartingPoint(), shark::VariationalAutoencoderError< SearchPointType >::proposeStartingPoint(), shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >::write(), and shark::AbstractMetric< InputTypeT >::write().
setParameterVector()
template<class VectorType = RealVector> virtual void shark::IParameterizable< VectorType >::setParameterVector (ParameterVectorType const & newParameters) inline virtual
Set the parameter vector.
Reimplemented in shark::RBM< VisibleLayerT, HiddenLayerT, randomT >, shark::LassoRegression< InputVectorType >, shark::LinearRegression, shark::ConcatenatedModel< VectorType >, shark::Conv2DModel< VectorType, ActivationFunction >, shark::DropoutLayer< VectorType >, shark::NeuronLayer< NeuronType, VectorType >, shark::PoolingLayer< VectorType >, shark::ResizeLayer< VectorType >, shark::AbstractSvmTrainer< InputType, LabelType, Model, Trainer >, shark::AbstractSvmTrainer< InputType, RealVector, KernelExpansion< InputType > >, shark::AbstractSvmTrainer< InputType, unsigned int >, shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >, shark::AbstractSvmTrainer< InputType, unsigned int, KernelExpansion< InputType > >, shark::AbstractSvmTrainer< InputType, unsigned int, MissingFeaturesKernelExpansion< InputType > >, shark::AbstractLinearSvmTrainer< InputType >, shark::KernelBudgetedSGDTrainer< InputType, CacheType >, shark::EpsilonSvmTrainer< InputType, CacheType >, shark::KernelSGDTrainer< InputType, CacheType >, shark::LinearSAGTrainer< InputType, LabelType >, shark::OneClassSvmTrainer< InputType, CacheType >, shark::RFTrainer< unsigned int >, shark::RFTrainer< RealVector >, shark::Centroids, shark::ClusteringModel< InputT, OutputT >, shark::ClusteringModel< InputT, RealVector >, shark::ClusteringModel< InputT, unsigned int >, shark::HierarchicalClustering< InputT >, shark::CMACMap, shark::ARDKernelUnconstrained< InputType >, shark::DiscreteKernel, shark::GaussianRbfKernel< InputType >, shark::KernelExpansion< InputType >, shark::LinearKernel< InputType >, shark::ModelKernel< InputType >, shark::MonomialKernel< InputType >, shark::GaussianTaskKernel< InputTypeT >, shark::NormalizedKernel< InputType >, shark::PointSetKernel< InputType >, shark::PolynomialKernel< InputType >, shark::ProductKernel< InputType >, shark::ProductKernel< MultiTaskSample< InputTypeT > >, shark::ScaledKernel< InputType >, shark::WeightedSumKernel< InputType >, shark::WeightedSumKernel< InputType >, shark::RBFLayer, shark::BinaryLayer, shark::BipolarLayer, shark::GaussianLayer, shark::LDA, shark::LogisticRegression< InputVectorType >, shark::CARTree< LabelType >, shark::Normalizer< VectorType >, and shark::OneVersusOneClassifier< InputType, VectorType >.
Definition at line 65 of file IParameterizable.h.
References SHARK_ASSERT.
Referenced by shark::LooError< ModelTypeT, LabelType >::eval(), shark::NegativeGaussianProcessEvidence< InputType, OutputType, LabelType >::eval(), shark::LooErrorCSvm< InputType, CacheType >::eval(), shark::KernelTargetAlignment< InputType, LabelType >::eval(), shark::NegativeLogLikelihood::eval(), shark::CrossValidationError< ModelTypeT, LabelTypeT >::eval(), shark::RadiusMarginQuotient< InputType, CacheType >::eval(), shark::SvmLogisticInterpretation< InputType >::eval(), shark::VariationalAutoencoderError< SearchPointType >::eval(), shark::NegativeGaussianProcessEvidence< InputType, OutputType, LabelType >::evalDerivative(), shark::KernelTargetAlignment< InputType, LabelType >::evalDerivative(), shark::NegativeLogLikelihood::evalDerivative(), shark::RadiusMarginQuotient< InputType, CacheType >::evalDerivative(), shark::SvmLogisticInterpretation< InputType >::evalDerivative(), shark::VariationalAutoencoderError< SearchPointType >::evalDerivative(), shark::initRandomNormal(), shark::initRandomUniform(), shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >::read(), shark::AbstractMetric< InputTypeT >::read(), shark::VariationalAutoencoderError< SearchPointType >::sampleZ(), shark::AbstractSvmTrainer< InputType, LabelType, Model, Trainer >::setParameterVector(), shark::KernelBudgetedSGDTrainer< InputType, CacheType >::setParameterVector(), shark::KernelSGDTrainer< InputType, CacheType >::setParameterVector(), shark::OneClassSvmTrainer< InputType, CacheType >::setParameterVector(), shark::ClusteringModel< InputT, OutputT >::setParameterVector(), shark::GaussianTaskKernel< InputTypeT >::setParameterVector(), shark::NormalizedKernel< InputType >::setParameterVector(), shark::PointSetKernel< InputType >::setParameterVector(), and shark::ScaledKernel< InputType >::setParameterVector().
The documentation for this class was generated from the following file:
include/shark/Core/IParameterizable.h