shark::HardClusteringModel< InputT > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::HardClusteringModel< InputT > Class Template Reference
Models » Clustering Algorithms
Model for "hard" clustering.
#include <shark/Models/Clustering/HardClusteringModel.h>
Public Types
typedef base_type::BatchInputType BatchInputType
typedef base_type::BatchOutputType BatchOutputType
typedef base_type::InputType InputType
typedef base_type::OutputType OutputType
Public Types inherited from shark::ClusteringModel< InputT, unsigned int >
typedef AbstractClustering< InputT > ClusteringType
typedef base_type::BatchInputType BatchInputType
typedef base_type::BatchOutputType BatchOutputType
Public Types inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
enum Feature { HAS_FIRST_PARAMETER_DERIVATIVE = 1 , HAS_FIRST_INPUT_DERIVATIVE = 4 }
typedef InputTypeT InputType
Defines the input type of the model.
typedef OutputTypeT OutputType
Defines the output type of the model.
typedef AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType > ModelBaseType
Defines the BaseType used by the model (this type). Useful for creating derived models.
typedef Batch< InputType >::type BatchInputType
defines the batch type of the input type.
typedef Batch< OutputType >::type BatchOutputType
defines the batch type of the output type
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
HardClusteringModel (ClusteringType *clustering)
Constructor.
std::string name () const
From INameable: return the class name.
Shape inputShape () const
Returns the expected shape of the input.
Shape outputShape () const
Returns the shape of the output.
void eval (InputType const &pattern, OutputType &output) const
Compute best matching cluster.
void eval (BatchInputType const &patterns, BatchOutputType &outputs) const
Compute best matching cluster for a batch of inputs.
Public Member Functions inherited from shark::ClusteringModel< InputT, unsigned int >
ClusteringModel (ClusteringType *clustering)
Constructor.
RealVector parameterVector () const
Redirect parameter access to the clustering object.
void setParameterVector (RealVector const &newParameters)
Redirect parameter access to the clustering object.
std::size_t numberOfParameters () const
Redirect parameter access to the clustering object.
void read (InArchive &archive)
From ISerializable, reads a model from an archive.
void write (OutArchive &archive) const
From ISerializable, writes a model to an archive.
void eval (BatchInputType const &patterns, BatchOutputType &outputs, State &state) const
Standard interface for evaluating the response of the model to a batch of patterns.
Public Member Functions inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
AbstractModel ()
virtual ~AbstractModel ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
Returns true when the first parameter derivative is implemented.
bool hasFirstInputDerivative () const
Returns true when the first input derivative is implemented.
virtual boost::shared_ptr< State > createState () const
Creates an internal state of the model.
virtual void eval (BatchInputType const &patterns, BatchOutputType &outputs) const
Standard interface for evaluating the response of the model to a batch of patterns.
virtual void eval (BatchInputType const &patterns, BatchOutputType &outputs, State &state) const =0
Standard interface for evaluating the response of the model to a batch of patterns.
Data< OutputType > operator() (Data< InputType > const &patterns) const
Model evaluation as an operator for a whole dataset. This is a convenience function.
OutputType operator() (InputType const &pattern) const
Model evaluation as an operator for a single pattern. This is a convenience function.
BatchOutputType operator() (BatchInputType const &patterns) const
Model evaluation as an operator for a single pattern. This is a convenience function.
virtual void weightedParameterDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &derivative) const
calculates the weighted sum of derivatives w.r.t the parameters.
virtual void weightedInputDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchInputType &derivative) const
calculates the weighted sum of derivatives w.r.t the inputs
virtual void weightedDerivatives (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &parameterDerivative, BatchInputType &inputDerivative) const
calculates weighted input and parameter derivative at the same time
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Additional Inherited Members
Protected Attributes inherited from shark::ClusteringModel< InputT, unsigned int >
ClusteringType * mep_clustering
Clustering object, see class AbstractClustering.
Protected Attributes inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
Features m_features
Detailed Description
template<class InputT>
class shark::HardClusteringModel< InputT >
Model for "hard" clustering.
The HardClusteringModel is based on an Clustering Algorithms object. Given an input, the model outputs the index of the best matching cluster.
See also SoftClusteringModel for general cluster membership.
Definition at line 55 of file HardClusteringModel.h.
Member Typedef Documentation
BatchInputType
template<class InputT > typedef base_type::BatchInputType shark::HardClusteringModel< InputT >::BatchInputType
Definition at line 60 of file HardClusteringModel.h.
BatchOutputType
template<class InputT > typedef base_type::BatchOutputType shark::HardClusteringModel< InputT >::BatchOutputType
Definition at line 61 of file HardClusteringModel.h.
InputType
template<class InputT > typedef base_type::InputType shark::HardClusteringModel< InputT >::InputType
Definition at line 62 of file HardClusteringModel.h.
OutputType
template<class InputT > typedef base_type::OutputType shark::HardClusteringModel< InputT >::OutputType
Definition at line 63 of file HardClusteringModel.h.
Constructor & Destructor Documentation
HardClusteringModel()
template<class InputT > shark::HardClusteringModel< InputT >::HardClusteringModel (ClusteringType * clustering) inline
Constructor.
Definition at line 67 of file HardClusteringModel.h.
Member Function Documentation
eval() [1/2]
template<class InputT > void shark::HardClusteringModel< InputT >::eval (BatchInputType const & patterns, BatchOutputType & outputs) const inline
Compute best matching cluster for a batch of inputs.
The actual computation is redirected to the clustering object.
Definition at line 96 of file HardClusteringModel.h.
References shark::AbstractClustering< InputT >::hardMembership(), and shark::ClusteringModel< InputT, unsigned int >::mep_clustering.
eval() [2/2]
template<class InputT > void shark::HardClusteringModel< InputT >::eval (InputType const & pattern, OutputType & output) const inline virtual
Compute best matching cluster.
The actual computation is redirected to the clustering object.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 88 of file HardClusteringModel.h.
References shark::AbstractClustering< InputT >::hardMembership(), and shark::ClusteringModel< InputT, unsigned int >::mep_clustering.
inputShape()
template<class InputT > Shape shark::HardClusteringModel< InputT >::inputShape () const inline virtual
Returns the expected shape of the input.
Implements shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 77 of file HardClusteringModel.h.
References shark::AbstractClustering< InputT >::inputShape(), and shark::ClusteringModel< InputT, unsigned int >::mep_clustering.
name()
template<class InputT > std::string shark::HardClusteringModel< InputT >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 72 of file HardClusteringModel.h.
outputShape()
template<class InputT > Shape shark::HardClusteringModel< InputT >::outputShape () const inline virtual
Returns the shape of the output.
Implements shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 80 of file HardClusteringModel.h.
References shark::ClusteringModel< InputT, unsigned int >::mep_clustering, and shark::AbstractClustering< InputT >::numberOfClusters().
The documentation for this class was generated from the following file:
include/shark/Models/Clustering/HardClusteringModel.h