shark::AbstractBudgetMaintenanceStrategy< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::AbstractBudgetMaintenanceStrategy< InputType > Class Template Reference abstract
This is the abstract interface for any budget maintenance strategy.
#include <shark/Algorithms/Trainers/Budgeted/AbstractBudgetMaintenanceStrategy.h>
Public Types
typedef KernelExpansion< InputType > ModelType
typedef LabeledData< InputType, unsigned int > DataType
typedef DataType::element_type ElementType
Public Member Functions
AbstractBudgetMaintenanceStrategy ()
virtual void addToModel (ModelType &model, InputType const &alpha, ElementType const &supportVector)=0
std::string name () const
return the class name
Static Public Member Functions
static void findSmallestVector (ModelType const &model, size_t &minIndex, double &minAlpha)
Detailed Description
template<class InputType>
class shark::AbstractBudgetMaintenanceStrategy< InputType >
This is the abstract interface for any budget maintenance strategy.
To allow for easy exchange of budget maintenance strategies, each of them should derive from this class. The only function it defines is addToModel, which, when implemented, will add a given supportvector and given alphas to the provided model by applying the respective budget maintenance strategy. (Note that not all merging strategies need the alphas, but some do)
Definition at line 62 of file AbstractBudgetMaintenanceStrategy.h.
Member Typedef Documentation
DataType
template<class InputType > typedef LabeledData<InputType, unsigned int> shark::AbstractBudgetMaintenanceStrategy< InputType >::DataType
Definition at line 67 of file AbstractBudgetMaintenanceStrategy.h.
ElementType
template<class InputType > typedef DataType::element_type shark::AbstractBudgetMaintenanceStrategy< InputType >::ElementType
Definition at line 68 of file AbstractBudgetMaintenanceStrategy.h.
ModelType
template<class InputType > typedef KernelExpansion<InputType> shark::AbstractBudgetMaintenanceStrategy< InputType >::ModelType
Definition at line 66 of file AbstractBudgetMaintenanceStrategy.h.
Constructor & Destructor Documentation
AbstractBudgetMaintenanceStrategy()
template<class InputType > shark::AbstractBudgetMaintenanceStrategy< InputType >::AbstractBudgetMaintenanceStrategy () inline
Definition at line 70 of file AbstractBudgetMaintenanceStrategy.h.
Member Function Documentation
addToModel()
template<class InputType > virtual void shark::AbstractBudgetMaintenanceStrategy< InputType >::addToModel (ModelType & model, InputType const & alpha, ElementType const & supportVector) pure virtual
this is the main interface, which adds a given supportvector with given alpha coefficients to the model.
Parameters
[in,out] model the model the strategy will work with
[in] alpha alphas for the new budget vector
[in] supportVector the vector to add to the model by applying the maintenance strategy
Implemented in shark::MergeBudgetMaintenanceStrategy< RealVector >, shark::ProjectBudgetMaintenanceStrategy< InputType >, and shark::RemoveBudgetMaintenanceStrategy< InputType >.
findSmallestVector()
template<class InputType > static void shark::AbstractBudgetMaintenanceStrategy< InputType >::findSmallestVector (ModelType const & model, size_t & minIndex, double & minAlpha) inline static
this will find the vector with the smallest alpha, measured in 2-norm in the given model. now there is a special case: if there is somewhere a zero coefficient, then obviously this is the smallest element. in this case we just proceed as usual. the caller must decide what to do with such a vector.
note: The model is not allowed to be empty and an exception is thrown in this case.
Parameters
[in] model the model we want to search
[out] minIndex the index of the vector with smallest coefficient
[out] minAlpha the 2-norm of the alpha coefficient of the found vector
Definition at line 95 of file AbstractBudgetMaintenanceStrategy.h.
References shark::KernelExpansion< InputType >::alpha(), and SHARK_RUNTIME_CHECK.
Referenced by shark::MergeBudgetMaintenanceStrategy< RealVector >::addToModel(), shark::ProjectBudgetMaintenanceStrategy< RealVector >::addToModel(), and shark::RemoveBudgetMaintenanceStrategy< InputType >::addToModel().
name()
template<class InputType > std::string shark::AbstractBudgetMaintenanceStrategy< InputType >::name () const inline
return the class name
Definition at line 117 of file AbstractBudgetMaintenanceStrategy.h.
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/Budgeted/AbstractBudgetMaintenanceStrategy.h