shark::NeuronLayer< NeuronType, VectorType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::NeuronLayer< NeuronType, VectorType > Class Template Reference
Models
Neuron activation layer.
#include <shark/Models/NeuronLayers.h>
Public Types
typedef base_type::BatchInputType BatchInputType
typedef base_type::BatchOutputType BatchOutputType
typedef base_type::ParameterVectorType ParameterVectorType
Public Types inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
enum Feature { HAS_FIRST_PARAMETER_DERIVATIVE = 1 , HAS_FIRST_INPUT_DERIVATIVE = 4 }
typedef InputTypeT InputType
Defines the input type of the model.
typedef OutputTypeT OutputType
Defines the output type of the model.
typedef AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType > ModelBaseType
Defines the BaseType used by the model (this type). Useful for creating derived models.
typedef Batch< InputType >::type BatchInputType
defines the batch type of the input type.
typedef Batch< OutputType >::type BatchOutputType
defines the batch type of the output type
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
NeuronLayer (Shape const &shape=Shape())
std::string name () const
From INameable: return the class name.
NeuronType const & neuron () const
NeuronType & neuron ()
Shape inputShape () const
Returns the expected shape of the input.
Shape outputShape () const
Returns the shape of the output.
ParameterVectorType parameterVector () const
obtain the parameter vector
void setParameterVector (ParameterVectorType const &newParameters)
overwrite the parameter vector
size_t numberOfParameters () const
return the number of parameter
boost::shared_ptr< State > createState () const
Creates an internal state of the model.
void eval (BatchInputType const &inputs, BatchOutputType &outputs) const
Standard interface for evaluating the response of the model to a batch of patterns.
void eval (VectorType const &input, VectorType &output) const
void eval (BatchInputType const &inputs, BatchOutputType &outputs, State &state) const
Standard interface for evaluating the response of the model to a batch of patterns.
void weightedParameterDerivative (BatchInputType const &inputs, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &gradient) const
Calculates the first derivative w.r.t the parameters and summing them up over all inputs of the last computed batch.
void weightedInputDerivative (BatchInputType const &inputs, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchInputType &derivative) const
Calculates the first derivative w.r.t the inputs and summs them up over all inputs of the last computed batch.
void read (InArchive &archive)
From ISerializable.
void write (OutArchive &archive) const
From ISerializable.
Public Member Functions inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
AbstractModel ()
virtual ~AbstractModel ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
Returns true when the first parameter derivative is implemented.
bool hasFirstInputDerivative () const
Returns true when the first input derivative is implemented.
virtual void eval (InputType const &pattern, OutputType &output) const
Standard interface for evaluating the response of the model to a single pattern.
Data< OutputType > operator() (Data< InputType > const &patterns) const
Model evaluation as an operator for a whole dataset. This is a convenience function.
OutputType operator() (InputType const &pattern) const
Model evaluation as an operator for a single pattern. This is a convenience function.
BatchOutputType operator() (BatchInputType const &patterns) const
Model evaluation as an operator for a single pattern. This is a convenience function.
virtual void weightedDerivatives (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &parameterDerivative, BatchInputType &inputDerivative) const
calculates weighted input and parameter derivative at the same time
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >
Features m_features
Detailed Description
template<class NeuronType, class VectorType = RealVector>
class shark::NeuronLayer< NeuronType, VectorType >
Neuron activation layer.
Applies a nonlinear activation function to the given input. Various choices for activations are given in Neuron activation functions.
Definition at line 255 of file NeuronLayers.h.
Member Typedef Documentation
BatchInputType
template<class NeuronType , class VectorType = RealVector> typedef base_type::BatchInputType shark::NeuronLayer< NeuronType, VectorType >::BatchInputType
Definition at line 262 of file NeuronLayers.h.
BatchOutputType
template<class NeuronType , class VectorType = RealVector> typedef base_type::BatchOutputType shark::NeuronLayer< NeuronType, VectorType >::BatchOutputType
Definition at line 263 of file NeuronLayers.h.
ParameterVectorType
template<class NeuronType , class VectorType = RealVector> typedef base_type::ParameterVectorType shark::NeuronLayer< NeuronType, VectorType >::ParameterVectorType
Definition at line 264 of file NeuronLayers.h.
Constructor & Destructor Documentation
NeuronLayer()
template<class NeuronType , class VectorType = RealVector> shark::NeuronLayer< NeuronType, VectorType >::NeuronLayer (Shape const & shape = Shape()) inline
Definition at line 266 of file NeuronLayers.h.
References shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_INPUT_DERIVATIVE, shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_PARAMETER_DERIVATIVE, and shark::AbstractModel< VectorType, VectorType, VectorType >::m_features.
Member Function Documentation
createState()
template<class NeuronType , class VectorType = RealVector> boost::shared_ptr< State > shark::NeuronLayer< NeuronType, VectorType >::createState () const inline virtual
Creates an internal state of the model.
The state is needed when the derivatives are to be calculated. Eval can store a state which is then reused to speed up the calculations of the derivatives. This also allows eval to be evaluated in parallel!
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 301 of file NeuronLayers.h.
eval() [1/3]
template<class NeuronType , class VectorType = RealVector> void shark::NeuronLayer< NeuronType, VectorType >::eval (BatchInputType const & patterns, BatchOutputType & outputs) const inline virtual
Standard interface for evaluating the response of the model to a batch of patterns.
Parameters
patterns the inputs of the model
outputs the predictions or response of the model to every pattern
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 307 of file NeuronLayers.h.
References shark::Shape::numElements(), and SIZE_CHECK.
eval() [2/3]
template<class NeuronType , class VectorType = RealVector> void shark::NeuronLayer< NeuronType, VectorType >::eval (BatchInputType const & patterns, BatchOutputType & outputs, State & state) const inline virtual
Standard interface for evaluating the response of the model to a batch of patterns.
Parameters
patterns the inputs of the model
outputs the predictions or response of the model to every pattern
state intermediate results stored by eval which can be reused for derivative computation.
Implements shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 320 of file NeuronLayers.h.
References shark::Shape::numElements(), SIZE_CHECK, and shark::State::toState().
eval() [3/3]
template<class NeuronType , class VectorType = RealVector> void shark::NeuronLayer< NeuronType, VectorType >::eval (VectorType const & input, VectorType & output) const inline
Definition at line 314 of file NeuronLayers.h.
References shark::Shape::numElements(), and SIZE_CHECK.
inputShape()
template<class NeuronType , class VectorType = RealVector> Shape shark::NeuronLayer< NeuronType, VectorType >::inputShape () const inline virtual
Returns the expected shape of the input.
Implements shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 278 of file NeuronLayers.h.
name()
template<class NeuronType , class VectorType = RealVector> std::string shark::NeuronLayer< NeuronType, VectorType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 272 of file NeuronLayers.h.
neuron() [1/2]
template<class NeuronType , class VectorType = RealVector> NeuronType & shark::NeuronLayer< NeuronType, VectorType >::neuron () inline
Definition at line 276 of file NeuronLayers.h.
neuron() [2/2]
template<class NeuronType , class VectorType = RealVector> NeuronType const & shark::NeuronLayer< NeuronType, VectorType >::neuron () const inline
Definition at line 275 of file NeuronLayers.h.
numberOfParameters()
template<class NeuronType , class VectorType = RealVector> size_t shark::NeuronLayer< NeuronType, VectorType >::numberOfParameters () const inline virtual
return the number of parameter
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 297 of file NeuronLayers.h.
outputShape()
template<class NeuronType , class VectorType = RealVector> Shape shark::NeuronLayer< NeuronType, VectorType >::outputShape () const inline virtual
Returns the shape of the output.
Implements shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 282 of file NeuronLayers.h.
parameterVector()
template<class NeuronType , class VectorType = RealVector> ParameterVectorType shark::NeuronLayer< NeuronType, VectorType >::parameterVector () const inline virtual
obtain the parameter vector
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 287 of file NeuronLayers.h.
read()
template<class NeuronType , class VectorType = RealVector> void shark::NeuronLayer< NeuronType, VectorType >::read (InArchive & archive) inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 356 of file NeuronLayers.h.
setParameterVector()
template<class NeuronType , class VectorType = RealVector> void shark::NeuronLayer< NeuronType, VectorType >::setParameterVector (ParameterVectorType const & newParameters) inline virtual
overwrite the parameter vector
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 292 of file NeuronLayers.h.
References SIZE_CHECK.
weightedInputDerivative()
template<class NeuronType , class VectorType = RealVector> void shark::NeuronLayer< NeuronType, VectorType >::weightedInputDerivative (BatchInputType const & inputs, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, BatchInputType & derivative) const inline virtual
Calculates the first derivative w.r.t the inputs and summs them up over all inputs of the last computed batch.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 339 of file NeuronLayers.h.
References SIZE_CHECK, and shark::State::toState().
weightedParameterDerivative()
template<class NeuronType , class VectorType = RealVector> void shark::NeuronLayer< NeuronType, VectorType >::weightedParameterDerivative (BatchInputType const & inputs, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, ParameterVectorType & gradient) const inline virtual
Calculates the first derivative w.r.t the parameters and summing them up over all inputs of the last computed batch.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 328 of file NeuronLayers.h.
References SIZE_CHECK.
write()
template<class NeuronType , class VectorType = RealVector> void shark::NeuronLayer< NeuronType, VectorType >::write (OutArchive & archive) const inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >.
Definition at line 358 of file NeuronLayers.h.
The documentation for this class was generated from the following file:
include/shark/Models/NeuronLayers.h