shark::RemoveBudgetMaintenanceStrategy< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::RemoveBudgetMaintenanceStrategy< InputType > Class Template Reference
Budget maintenance strategy that removes a vector.
#include <shark/Algorithms/Trainers/Budgeted/RemoveBudgetMaintenanceStrategy.h>
Public Types
enum RemoveStrategyFlavor { RANDOM = 0 , SMALLEST = 1 }
the flavors of the remove strategy
Public Types inherited from shark::AbstractBudgetMaintenanceStrategy< InputType >
typedef KernelExpansion< InputType > ModelType
typedef LabeledData< InputType, unsigned int > DataType
typedef DataType::element_type ElementType
Public Member Functions
RemoveBudgetMaintenanceStrategy (RemoveStrategyFlavor flavor=SMALLEST)
virtual void addToModel (ModelType &model, InputType const &alpha, ElementType const &supportVector)
std::string name () const
class name
Public Member Functions inherited from shark::AbstractBudgetMaintenanceStrategy< InputType >
AbstractBudgetMaintenanceStrategy ()
std::string name () const
return the class name
Protected Attributes
size_t m_flavor
flavor for removing a vector
Additional Inherited Members
Static Public Member Functions inherited from shark::AbstractBudgetMaintenanceStrategy< InputType >
static void findSmallestVector (ModelType const &model, size_t &minIndex, double &minAlpha)
Detailed Description
template<class InputType>
class shark::RemoveBudgetMaintenanceStrategy< InputType >
Budget maintenance strategy that removes a vector.
This is an budget strategy that simply removes one of the budget vectors. Depending on the flavor, this can be e.g. a random one, the smallest one (w.r.t. to 2-norm of the alphas)
Definition at line 63 of file RemoveBudgetMaintenanceStrategy.h.
Member Enumeration Documentation
RemoveStrategyFlavor
template<class InputType > enum shark::RemoveBudgetMaintenanceStrategy::RemoveStrategyFlavor
the flavors of the remove strategy
Enumerator
RANDOM
SMALLEST
Definition at line 72 of file RemoveBudgetMaintenanceStrategy.h.
Constructor & Destructor Documentation
RemoveBudgetMaintenanceStrategy()
template<class InputType > shark::RemoveBudgetMaintenanceStrategy< InputType >::RemoveBudgetMaintenanceStrategy (RemoveStrategyFlavor flavor = SMALLEST) inline
constructor.
Parameters
[in] flavor enum that decides on the method a vector is removed.
Definition at line 77 of file RemoveBudgetMaintenanceStrategy.h.
References SHARK_RUNTIME_CHECK.
Member Function Documentation
addToModel()
template<class InputType > virtual void shark::RemoveBudgetMaintenanceStrategy< InputType >::addToModel (ModelType & model, InputType const & alpha, ElementType const & supportVector) inline virtual
add a vector to the model. this will add the given vector to the model and remove another one depending on the flavor.
Parameters
[in,out] model the model the strategy will work with
[in] alpha alphas for the new budget vector
[in] supportVector the vector to add to the model by applying the maintenance strategy
Implements shark::AbstractBudgetMaintenanceStrategy< InputType >.
Definition at line 91 of file RemoveBudgetMaintenanceStrategy.h.
References shark::KernelExpansion< InputType >::alpha(), shark::KernelExpansion< InputType >::basis(), shark::random::discrete(), shark::Data< Type >::element(), shark::AbstractBudgetMaintenanceStrategy< InputType >::findSmallestVector(), shark::RemoveBudgetMaintenanceStrategy< InputType >::m_flavor, shark::Data< Type >::numberOfElements(), shark::RemoveBudgetMaintenanceStrategy< InputType >::RANDOM, and shark::RemoveBudgetMaintenanceStrategy< InputType >::SMALLEST.
name()
template<class InputType > std::string shark::RemoveBudgetMaintenanceStrategy< InputType >::name () const inline
class name
Definition at line 134 of file RemoveBudgetMaintenanceStrategy.h.
Member Data Documentation
m_flavor
template<class InputType > size_t shark::RemoveBudgetMaintenanceStrategy< InputType >::m_flavor protected
flavor for removing a vector
Definition at line 139 of file RemoveBudgetMaintenanceStrategy.h.
Referenced by shark::RemoveBudgetMaintenanceStrategy< InputType >::addToModel().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/Budgeted/RemoveBudgetMaintenanceStrategy.h