shark::BiasSolverSimplex< Matrix > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::BiasSolverSimplex< Matrix > Class Template Reference
#include <shark/Algorithms/QP/QpMcSimplexDecomp.h>
Public Types
typedef Matrix::QpFloatType QpFloatType
Public Member Functions
BiasSolverSimplex (QpMcSimplexDecomp< Matrix > *problem)
void solve (RealVector &bias, QpStoppingCondition &stop, QpSparseArray< QpFloatType > const &nu, bool sumToZero, QpSolutionProperties *prop=NULL)
Detailed Description
template<class Matrix>
class shark::BiasSolverSimplex< Matrix >
Definition at line 886 of file QpMcSimplexDecomp.h.
Member Typedef Documentation
QpFloatType
template<class Matrix > typedef Matrix::QpFloatType shark::BiasSolverSimplex< Matrix >::QpFloatType
Definition at line 888 of file QpMcSimplexDecomp.h.
Constructor & Destructor Documentation
BiasSolverSimplex()
template<class Matrix > shark::BiasSolverSimplex< Matrix >::BiasSolverSimplex (QpMcSimplexDecomp< Matrix > * problem) inline
Definition at line 889 of file QpMcSimplexDecomp.h.
Member Function Documentation
solve()
template<class Matrix > void shark::BiasSolverSimplex< Matrix >::solve (RealVector & bias, QpStoppingCondition & stop, QpSparseArray< QpFloatType > const & nu, bool sumToZero, QpSolutionProperties * prop = NULL) inline
Definition at line 891 of file QpMcSimplexDecomp.h.
References shark::QpSolutionProperties::iterations, shark::QpStoppingCondition::minAccuracy, shark::Timer::now(), shark::QpSparseArray< QpFloatType >::row(), and shark::QpSolver< Problem, SelectionStrategy >::solve().
The documentation for this class was generated from the following file:
include/shark/Algorithms/QP/QpMcSimplexDecomp.h