shark::IndicatorBasedSteadyStateMOCMA< Indicator > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::IndicatorBasedSteadyStateMOCMA< Indicator > Class Template Reference
Algorithms to find a local minimum of\ref objfunctions. » Multi-objective Direct-Search optimizers
Implements the \((\mu+1)\)-MO-CMA-ES.
#include <shark/Algorithms/DirectSearch/SteadyStateMOCMA.h>
Public Types
enum NotionOfSuccess { IndividualBased , PopulationBased }
Public Types inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
typedef super::SearchPointType SearchPointType
typedef super::SolutionType SolutionType
typedef super::ObjectiveFunctionType ObjectiveFunctionType
Public Types inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
enum Feature {
REQUIRES_VALUE = 1 , REQUIRES_FIRST_DERIVATIVE = 2 , REQUIRES_SECOND_DERIVATIVE = 4 , CAN_SOLVE_CONSTRAINED = 8 ,
REQUIRES_CLOSEST_FEASIBLE = 16
}
Models features that the optimizer requires from the objective function.
typedef PointType SearchPointType
typedef ResultT ResultType
typedef SolutionTypeT SolutionType
typedef AbstractObjectiveFunction< PointType, ResultType > ObjectiveFunctionType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
IndicatorBasedSteadyStateMOCMA (random::rng_type &rng=random::globalRng)
std::string name () const
Returns the name of the algorithm.
std::size_t mu () const
std::size_t & mu ()
std::size_t numInitPoints () const
Returns the number of points this method requires for initialisation.
double initialSigma () const
double & initialSigma ()
NotionOfSuccess notionOfSuccess () const
NotionOfSuccess & notionOfSuccess ()
Indicator & indicator ()
Indicator const & indicator () const
void read (InArchive &archive)
Read the component from the supplied archive.
void write (OutArchive &archive) const
Write the component to the supplied archive.
void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initialSearchPoints)
Initializes the algorithm for the supplied objective function.
void step (ObjectiveFunctionType const &function)
Executes one iteration of the algorithm.
Public Member Functions inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
SolutionType const & solution () const
Accesses the current approximation of the Pareto-set and -front, respectively.
Public Member Functions inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
const Features & features () const
virtual void updateFeatures ()
bool requiresValue () const
bool requiresFirstDerivative () const
bool requiresSecondDerivative () const
bool canSolveConstrained () const
bool requiresClosestFeasible () const
virtual ~AbstractOptimizer ()
virtual void init (ObjectiveFunctionType const &function)
Initialize the optimizer for the supplied objective function.
virtual void init (ObjectiveFunctionType const &function, std::vector< SearchPointType > const &initPoints)=0
Initialize the optimizer for the supplied objective function using a set of initialisation points.
virtual void step (ObjectiveFunctionType const &function)=0
Carry out one step of the optimizer for the supplied objective function.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Types
typedef CMAIndividual< RealVector > IndividualType
The individual type of the SteadyState-MOCMA.
Protected Member Functions
void doInit (std::vector< SearchPointType > const &initialSearchPoints, std::vector< ResultType > const &functionValues, std::size_t mu, double initialSigma)
std::vector< IndividualType > generateOffspring () const
void updatePopulation (std::vector< IndividualType > const &offspringVec)
Protected Member Functions inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
void checkFeatures (ObjectiveFunctionType const &objectiveFunction)
Convenience function that checks whether the features of the supplied objective function match with the required features of the optimizer.
Protected Attributes
std::vector< IndividualType > m_parents
Population of size \(\mu + 1\).
Protected Attributes inherited from shark::AbstractMultiObjectiveOptimizer< RealVector >
SolutionType m_best
The current Pareto-set/-front.
Protected Attributes inherited from shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >
Features m_features
Detailed Description
template<typename Indicator = HypervolumeIndicator>
class shark::IndicatorBasedSteadyStateMOCMA< Indicator >
Implements the \((\mu+1)\)-MO-CMA-ES.
Please see the following papers for further reference:
Igel, Suttorp and Hansen. Steady-state Selection and Efficient Covariance Matrix Update in the Multi-Objective CMA-ES.
Voﬂ, Hansen and Igel. Improved Step Size Adaptation for the MO-CMA-ES.
Definition at line 51 of file SteadyStateMOCMA.h.
Member Typedef Documentation
IndividualType
template<typename Indicator = HypervolumeIndicator> typedef CMAIndividual<RealVector> shark::IndicatorBasedSteadyStateMOCMA< Indicator >::IndividualType protected
The individual type of the SteadyState-MOCMA.
Definition at line 160 of file SteadyStateMOCMA.h.
Member Enumeration Documentation
NotionOfSuccess
template<typename Indicator = HypervolumeIndicator> enum shark::IndicatorBasedSteadyStateMOCMA::NotionOfSuccess
Enumerator
IndividualBased
PopulationBased
Definition at line 53 of file SteadyStateMOCMA.h.
Constructor & Destructor Documentation
IndicatorBasedSteadyStateMOCMA()
template<typename Indicator = HypervolumeIndicator> shark::IndicatorBasedSteadyStateMOCMA< Indicator >::IndicatorBasedSteadyStateMOCMA (random::rng_type & rng = random::globalRng) inline
Definition at line 59 of file SteadyStateMOCMA.h.
References shark::IndicatorBasedSteadyStateMOCMA< Indicator >::initialSigma(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::m_features, shark::IndicatorBasedSteadyStateMOCMA< Indicator >::mu(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::notionOfSuccess(), and shark::IndicatorBasedSteadyStateMOCMA< Indicator >::PopulationBased.
Member Function Documentation
doInit()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedSteadyStateMOCMA< Indicator >::doInit (std::vector< SearchPointType > const & initialSearchPoints, std::vector< ResultType > const & functionValues, std::size_t mu, double initialSigma) inline protected
Definition at line 162 of file SteadyStateMOCMA.h.
References shark::random::discrete(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::indicator(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::initialSigma(), shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, shark::IndicatorBasedSteadyStateMOCMA< Indicator >::m_parents, shark::IndicatorBasedSteadyStateMOCMA< Indicator >::mu(), and SIZE_CHECK.
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::init().
generateOffspring()
template<typename Indicator = HypervolumeIndicator> std::vector< IndividualType > shark::IndicatorBasedSteadyStateMOCMA< Indicator >::generateOffspring () const inline protected
Definition at line 206 of file SteadyStateMOCMA.h.
References shark::random::discrete(), and shark::IndicatorBasedSteadyStateMOCMA< Indicator >::m_parents.
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::step().
indicator() [1/2]
template<typename Indicator = HypervolumeIndicator> Indicator & shark::IndicatorBasedSteadyStateMOCMA< Indicator >::indicator () inline
Definition at line 99 of file SteadyStateMOCMA.h.
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::doInit().
indicator() [2/2]
template<typename Indicator = HypervolumeIndicator> Indicator const & shark::IndicatorBasedSteadyStateMOCMA< Indicator >::indicator () const inline
Definition at line 102 of file SteadyStateMOCMA.h.
init()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedSteadyStateMOCMA< Indicator >::init (ObjectiveFunctionType const & function, std::vector< SearchPointType > const & initialSearchPoints) inline
Initializes the algorithm for the supplied objective function.
Parameters
[in] function The objective function.
[in] initialSearchPoints A set of intiial search points.
Definition at line 134 of file SteadyStateMOCMA.h.
References shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::checkFeatures(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::doInit(), shark::AbstractObjectiveFunction< PointType, ResultT >::eval(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::initialSigma(), shark::AbstractObjectiveFunction< PointType, ResultT >::isFeasible(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::mu(), and SHARK_RUNTIME_CHECK.
initialSigma() [1/2]
template<typename Indicator = HypervolumeIndicator> double & shark::IndicatorBasedSteadyStateMOCMA< Indicator >::initialSigma () inline
Definition at line 88 of file SteadyStateMOCMA.h.
initialSigma() [2/2]
template<typename Indicator = HypervolumeIndicator> double shark::IndicatorBasedSteadyStateMOCMA< Indicator >::initialSigma () const inline
Definition at line 85 of file SteadyStateMOCMA.h.
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::doInit(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::IndicatorBasedSteadyStateMOCMA(), and shark::IndicatorBasedSteadyStateMOCMA< Indicator >::init().
mu() [1/2]
template<typename Indicator = HypervolumeIndicator> std::size_t & shark::IndicatorBasedSteadyStateMOCMA< Indicator >::mu () inline
Definition at line 77 of file SteadyStateMOCMA.h.
mu() [2/2]
template<typename Indicator = HypervolumeIndicator> std::size_t shark::IndicatorBasedSteadyStateMOCMA< Indicator >::mu () const inline
Definition at line 74 of file SteadyStateMOCMA.h.
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::doInit(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::IndicatorBasedSteadyStateMOCMA(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::init(), and shark::IndicatorBasedSteadyStateMOCMA< Indicator >::updatePopulation().
name()
template<typename Indicator = HypervolumeIndicator> std::string shark::IndicatorBasedSteadyStateMOCMA< Indicator >::name () const inline virtual
Returns the name of the algorithm.
Reimplemented from shark::INameable.
Definition at line 70 of file SteadyStateMOCMA.h.
notionOfSuccess() [1/2]
template<typename Indicator = HypervolumeIndicator> NotionOfSuccess & shark::IndicatorBasedSteadyStateMOCMA< Indicator >::notionOfSuccess () inline
Definition at line 95 of file SteadyStateMOCMA.h.
notionOfSuccess() [2/2]
template<typename Indicator = HypervolumeIndicator> NotionOfSuccess shark::IndicatorBasedSteadyStateMOCMA< Indicator >::notionOfSuccess () const inline
Definition at line 92 of file SteadyStateMOCMA.h.
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::IndicatorBasedSteadyStateMOCMA().
numInitPoints()
template<typename Indicator = HypervolumeIndicator> std::size_t shark::IndicatorBasedSteadyStateMOCMA< Indicator >::numInitPoints () const inline virtual
Returns the number of points this method requires for initialisation.
The number of points supplied is allowed to be smaller, however in this case the optimizer will resort to techniques generating additional points if needed.
Implements shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >.
Definition at line 81 of file SteadyStateMOCMA.h.
read()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedSteadyStateMOCMA< Indicator >::read (InArchive & archive) inline virtual
Read the component from the supplied archive.
Parameters
[in,out] archive The archive to read from.
Reimplemented from shark::ISerializable.
Definition at line 106 of file SteadyStateMOCMA.h.
References shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, and shark::IndicatorBasedSteadyStateMOCMA< Indicator >::m_parents.
step()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedSteadyStateMOCMA< Indicator >::step (ObjectiveFunctionType const & function) inline
Executes one iteration of the algorithm.
Parameters
[in] function The function to iterate upon.
Definition at line 152 of file SteadyStateMOCMA.h.
References shark::IndicatorBasedSteadyStateMOCMA< Indicator >::generateOffspring(), and shark::IndicatorBasedSteadyStateMOCMA< Indicator >::updatePopulation().
updatePopulation()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedSteadyStateMOCMA< Indicator >::updatePopulation (std::vector< IndividualType > const & offspringVec) inline protected
Definition at line 222 of file SteadyStateMOCMA.h.
References shark::IndicatorBasedSteadyStateMOCMA< Indicator >::IndividualBased, shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, shark::IndicatorBasedSteadyStateMOCMA< Indicator >::m_parents, shark::IndicatorBasedSteadyStateMOCMA< Indicator >::mu(), shark::CMAIndividual< FitnessType >::parent(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::PopulationBased, shark::Individual< PointType, FitnessTypeT, Chromosome >::rank(), shark::Individual< PointType, FitnessTypeT, Chromosome >::selected(), shark::CMAChromosome::Successful, shark::CMAChromosome::Unsuccessful, shark::CMAIndividual< FitnessType >::updateAsOffspring(), and shark::CMAIndividual< FitnessType >::updateAsParent().
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::step().
write()
template<typename Indicator = HypervolumeIndicator> void shark::IndicatorBasedSteadyStateMOCMA< Indicator >::write (OutArchive & archive) const inline virtual
Write the component to the supplied archive.
Parameters
[in,out] archive The archive to write to.
Reimplemented from shark::ISerializable.
Definition at line 116 of file SteadyStateMOCMA.h.
References shark::AbstractMultiObjectiveOptimizer< RealVector >::m_best, and shark::IndicatorBasedSteadyStateMOCMA< Indicator >::m_parents.
Member Data Documentation
m_parents
template<typename Indicator = HypervolumeIndicator> std::vector<IndividualType> shark::IndicatorBasedSteadyStateMOCMA< Indicator >::m_parents protected
Population of size \(\mu + 1\).
Definition at line 255 of file SteadyStateMOCMA.h.
Referenced by shark::IndicatorBasedSteadyStateMOCMA< Indicator >::doInit(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::generateOffspring(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::read(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::updatePopulation(), and shark::IndicatorBasedSteadyStateMOCMA< Indicator >::write().
The documentation for this class was generated from the following file:
include/shark/Algorithms/DirectSearch/SteadyStateMOCMA.h