shark::OneClassSvmTrainer< InputType, CacheType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::OneClassSvmTrainer< InputType, CacheType > Class Template Reference
Unsupervised Trainers
Training of one-class SVMs.
#include <shark/Algorithms/Trainers/OneClassSvmTrainer.h>
Public Types
typedef CacheType QpFloatType
typedef AbstractModel< InputType, RealVector > ModelType
typedef AbstractKernelFunction< InputType > KernelType
typedef KernelMatrix< InputType, QpFloatType > KernelMatrixType
typedef CachedMatrix< KernelMatrixType > CachedMatrixType
typedef PrecomputedMatrix< KernelMatrixType > PrecomputedMatrixType
Public Types inherited from shark::AbstractUnsupervisedTrainer< KernelExpansion< InputType > >
typedef KernelExpansion< InputType > ModelType
typedef Model::InputType InputType
typedef UnlabeledData< InputType > DatasetType
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
OneClassSvmTrainer (KernelType *kernel, double nu)
std::string name () const
From INameable: return the class name.
double nu () const
void setNu (double nu)
KernelType * kernel ()
const KernelType * kernel () const
void setKernel (KernelType *kernel)
double CacheSize () const
void setCacheSize (std::size_t size)
RealVector parameterVector () const
get the hyper-parameter vector
void setParameterVector (RealVector const &newParameters)
set the vector of hyper-parameters
size_t numberOfParameters () const
return the number of hyper-parameters
void train (KernelExpansion< InputType > &svm, UnlabeledData< InputType > const &inputset)
Public Member Functions inherited from shark::AbstractUnsupervisedTrainer< KernelExpansion< InputType > >
virtual void train (ModelType &model, DatasetType const &inputset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Public Member Functions inherited from shark::QpConfig
QpConfig (bool precomputedFlag=false, bool sparsifyFlag=true)
Constructor.
QpStoppingCondition & stoppingCondition ()
Read/write access to the stopping condition.
QpStoppingCondition const & stoppingCondition () const
Read access to the stopping condition.
QpSolutionProperties & solutionProperties ()
Access to the solution properties.
bool & precomputeKernel ()
Flag for using a precomputed kernel matrix.
bool const & precomputeKernel () const
Flag for using a precomputed kernel matrix.
bool & sparsify ()
Flag for sparsifying the model after training.
bool const & sparsify () const
Flag for sparsifying the model after training.
bool & shrinking ()
Flag for shrinking in the decomposition solver.
bool const & shrinking () const
Flag for shrinking in the decomposition solver.
bool & s2do ()
Flag for S2DO (instead of SMO)
bool const & s2do () const
Flag for S2DO (instead of SMO)
unsigned int & verbosity ()
Verbosity level of the solver.
unsigned int const & verbosity () const
Verbosity level of the solver.
unsigned long long const & accessCount () const
Number of kernel accesses.
void setMinAccuracy (double a)
void setMaxIterations (unsigned long long i)
void setTargetValue (double v)
void setMaxSeconds (double s)
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Protected Member Functions
template<class MatrixType >
void trainSVM (KernelExpansion< InputType > &svm, UnlabeledData< InputType > const &inputset)
Protected Attributes
KernelType * m_kernel
double m_nu
std::size_t m_cacheSize
Protected Attributes inherited from shark::QpConfig
QpStoppingCondition m_stoppingcondition
conditions for when to stop the QP solver
QpSolutionProperties m_solutionproperties
properties of the approximate solution found by the solver
bool m_precomputedKernelMatrix
should the solver use a precomputed kernel matrix?
bool m_sparsify
should the trainer sparsify the model after training?
bool m_shrinking
should shrinking be used?
bool m_s2do
should S2DO be used instead of SMO?
unsigned int m_verbosity
verbosity level (currently unused)
unsigned long long m_accessCount
kernel access count
Detailed Description
template<class InputType, class CacheType = float>
class shark::OneClassSvmTrainer< InputType, CacheType >
Training of one-class SVMs.
The one-class support vector machine is an unsupervised method for learning the high probability region of a distribution. Given are data points \(x_i, i \in \{1, \dots, m\} \), a kernel function k(x, x') and a regularization constant C > 0. Let H denote the kernel induced reproducing kernel Hilbert space of k, and let \(\phi \) denote the corresponding feature map. Then an estimate of a high probability region of the distribution generating the sample points is described by the set where the following function takes positive values:
\[ f(x) = \langle w, \phi(x) \rangle + b \]
with coefficients w and b given by the (primal) optimization problem
\[ \min \frac{1}{2} \|w\|^2 + \frac{1}{\nu m} \sum_{i=1}^m \xi_i - \rho \]
\[ \text{s.t. } \langle w, \phi(x_i) \rangle + b \geq \rho - \xi_i; \xi_i \geq 0 \]
\(0 \leq \nu, \rho \leq 1 \) are parameters of the method for controlling the smoothness of the solution and the amount of probability mass covered.
For more details refer to the paper:
Estimating the support of a high-dimensional distribution. B. Schölkopf, J. C. Platt, J. Shawe-Taylor, A. Smola, and R. C. Williamson, 1999.
Definition at line 85 of file OneClassSvmTrainer.h.
Member Typedef Documentation
CachedMatrixType
template<class InputType , class CacheType = float> typedef CachedMatrix< KernelMatrixType > shark::OneClassSvmTrainer< InputType, CacheType >::CachedMatrixType
Definition at line 95 of file OneClassSvmTrainer.h.
KernelMatrixType
template<class InputType , class CacheType = float> typedef KernelMatrix<InputType, QpFloatType> shark::OneClassSvmTrainer< InputType, CacheType >::KernelMatrixType
Definition at line 94 of file OneClassSvmTrainer.h.
KernelType
template<class InputType , class CacheType = float> typedef AbstractKernelFunction<InputType> shark::OneClassSvmTrainer< InputType, CacheType >::KernelType
Definition at line 91 of file OneClassSvmTrainer.h.
ModelType
template<class InputType , class CacheType = float> typedef AbstractModel<InputType, RealVector> shark::OneClassSvmTrainer< InputType, CacheType >::ModelType
Definition at line 90 of file OneClassSvmTrainer.h.
PrecomputedMatrixType
template<class InputType , class CacheType = float> typedef PrecomputedMatrix< KernelMatrixType > shark::OneClassSvmTrainer< InputType, CacheType >::PrecomputedMatrixType
Definition at line 96 of file OneClassSvmTrainer.h.
QpFloatType
template<class InputType , class CacheType = float> typedef CacheType shark::OneClassSvmTrainer< InputType, CacheType >::QpFloatType
Definition at line 89 of file OneClassSvmTrainer.h.
Constructor & Destructor Documentation
OneClassSvmTrainer()
template<class InputType , class CacheType = float> shark::OneClassSvmTrainer< InputType, CacheType >::OneClassSvmTrainer (KernelType * kernel, double nu) inline
Definition at line 98 of file OneClassSvmTrainer.h.
Member Function Documentation
CacheSize()
template<class InputType , class CacheType = float> double shark::OneClassSvmTrainer< InputType, CacheType >::CacheSize () const inline
Definition at line 119 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_cacheSize.
kernel() [1/2]
template<class InputType , class CacheType = float> KernelType * shark::OneClassSvmTrainer< InputType, CacheType >::kernel () inline
Definition at line 112 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel.
Referenced by shark::OneClassSvmTrainer< InputType, CacheType >::setKernel().
kernel() [2/2]
template<class InputType , class CacheType = float> const KernelType * shark::OneClassSvmTrainer< InputType, CacheType >::kernel () const inline
Definition at line 114 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel.
name()
template<class InputType , class CacheType = float> std::string shark::OneClassSvmTrainer< InputType, CacheType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 105 of file OneClassSvmTrainer.h.
nu()
template<class InputType , class CacheType = float> double shark::OneClassSvmTrainer< InputType, CacheType >::nu () const inline
Definition at line 108 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_nu.
Referenced by shark::OneClassSvmTrainer< InputType, CacheType >::setNu().
numberOfParameters()
template<class InputType , class CacheType = float> size_t shark::OneClassSvmTrainer< InputType, CacheType >::numberOfParameters () const inline virtual
return the number of hyper-parameters
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 142 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel, and shark::IParameterizable< VectorType >::numberOfParameters().
parameterVector()
template<class InputType , class CacheType = float> RealVector shark::OneClassSvmTrainer< InputType, CacheType >::parameterVector () const inline virtual
get the hyper-parameter vector
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 125 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel, shark::OneClassSvmTrainer< InputType, CacheType >::m_nu, shark::IParameterizable< VectorType >::numberOfParameters(), and shark::IParameterizable< VectorType >::parameterVector().
setCacheSize()
template<class InputType , class CacheType = float> void shark::OneClassSvmTrainer< InputType, CacheType >::setCacheSize (std::size_t size) inline
Definition at line 121 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_cacheSize.
setKernel()
template<class InputType , class CacheType = float> void shark::OneClassSvmTrainer< InputType, CacheType >::setKernel (KernelType * kernel) inline
Definition at line 116 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::kernel(), and shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel.
setNu()
template<class InputType , class CacheType = float> void shark::OneClassSvmTrainer< InputType, CacheType >::setNu (double nu) inline
Definition at line 110 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_nu, and shark::OneClassSvmTrainer< InputType, CacheType >::nu().
Referenced by shark::OneClassSvmTrainer< InputType, CacheType >::setParameterVector().
setParameterVector()
template<class InputType , class CacheType = float> void shark::OneClassSvmTrainer< InputType, CacheType >::setParameterVector (RealVector const & newParameters) inline virtual
set the vector of hyper-parameters
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 134 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel, shark::IParameterizable< VectorType >::numberOfParameters(), shark::OneClassSvmTrainer< InputType, CacheType >::setNu(), shark::IParameterizable< VectorType >::setParameterVector(), and SHARK_ASSERT.
train()
template<class InputType , class CacheType = float> void shark::OneClassSvmTrainer< InputType, CacheType >::train (KernelExpansion< InputType > & svm, UnlabeledData< InputType > const & inputset) inline
Definition at line 145 of file OneClassSvmTrainer.h.
References shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel, shark::OneClassSvmTrainer< InputType, CacheType >::m_nu, shark::QpConfig::precomputeKernel(), shark::KernelExpansion< InputType >::setStructure(), SHARK_RUNTIME_CHECK, shark::QpConfig::sparsify(), and shark::KernelExpansion< InputType >::sparsify().
Referenced by main().
trainSVM()
template<class InputType , class CacheType = float> template<class MatrixType > void shark::OneClassSvmTrainer< InputType, CacheType >::trainSVM (KernelExpansion< InputType > & svm, UnlabeledData< InputType > const & inputset) inline protected
Definition at line 166 of file OneClassSvmTrainer.h.
References shark::KernelExpansion< InputType >::alpha(), shark::KernelMatrix< InputType, CacheType >::getAccessCount(), shark::QpConfig::m_accessCount, shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel, shark::OneClassSvmTrainer< InputType, CacheType >::m_nu, shark::QpConfig::m_shrinking, shark::KernelExpansion< InputType >::offset(), shark::QpConfig::solutionProperties(), shark::QpSolver< Problem, SelectionStrategy >::solve(), and shark::QpConfig::stoppingCondition().
Member Data Documentation
m_cacheSize
template<class InputType , class CacheType = float> std::size_t shark::OneClassSvmTrainer< InputType, CacheType >::m_cacheSize protected
Definition at line 163 of file OneClassSvmTrainer.h.
Referenced by shark::OneClassSvmTrainer< InputType, CacheType >::CacheSize(), and shark::OneClassSvmTrainer< InputType, CacheType >::setCacheSize().
m_kernel
template<class InputType , class CacheType = float> KernelType* shark::OneClassSvmTrainer< InputType, CacheType >::m_kernel protected
Definition at line 161 of file OneClassSvmTrainer.h.
Referenced by shark::OneClassSvmTrainer< InputType, CacheType >::kernel(), shark::OneClassSvmTrainer< InputType, CacheType >::kernel(), shark::OneClassSvmTrainer< InputType, CacheType >::numberOfParameters(), shark::OneClassSvmTrainer< InputType, CacheType >::parameterVector(), shark::OneClassSvmTrainer< InputType, CacheType >::setKernel(), shark::OneClassSvmTrainer< InputType, CacheType >::setParameterVector(), shark::OneClassSvmTrainer< InputType, CacheType >::train(), and shark::OneClassSvmTrainer< InputType, CacheType >::trainSVM().
m_nu
template<class InputType , class CacheType = float> double shark::OneClassSvmTrainer< InputType, CacheType >::m_nu protected
Definition at line 162 of file OneClassSvmTrainer.h.
Referenced by shark::OneClassSvmTrainer< InputType, CacheType >::nu(), shark::OneClassSvmTrainer< InputType, CacheType >::parameterVector(), shark::OneClassSvmTrainer< InputType, CacheType >::setNu(), shark::OneClassSvmTrainer< InputType, CacheType >::train(), and shark::OneClassSvmTrainer< InputType, CacheType >::trainSVM().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/OneClassSvmTrainer.h