shark::benchmarks::ELLI1 Struct Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::benchmarks::ELLI1 Struct Reference
Objective functions » Benchmark functions
Multi-objective optimization benchmark function ELLI1.
#include <shark/ObjectiveFunctions/Benchmarks/ELLI1.h>
Public Member Functions
ELLI1 (std::size_t numVariables=0)
std::string name () const
From INameable: return the class name.
std::size_t numberOfObjectives () const
std::size_t numberOfVariables () const
Accesses the number of variables.
bool hasScalableDimensionality () const
void setNumberOfVariables (std::size_t numVariables)
Adjusts the number of variables if the function is scalable.
void init ()
ResultType eval (const SearchPointType &x) const
Evaluates the objective function for the supplied argument.
SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
Public Member Functions inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual bool hasScalableObjectives () const
virtual void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Public Types inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
enum Feature {
HAS_VALUE = 1 , HAS_FIRST_DERIVATIVE = 2 , HAS_SECOND_DERIVATIVE = 4 , CAN_PROPOSE_STARTING_POINT = 8 ,
IS_CONSTRAINED_FEATURE = 16 , HAS_CONSTRAINT_HANDLER = 32 , CAN_PROVIDE_CLOSEST_FEASIBLE = 64 , IS_THREAD_SAFE = 128 ,
IS_NOISY = 256
}
List of features that are supported by an implementation.
typedef PointType SearchPointType
typedef ResultT ResultType
typedef boost::mpl::if_< std::is_arithmetic< ResultT >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Protected Member Functions inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
Multi-objective optimization benchmark function ELLI1.
The function is described in
Christian Igel, Nikolaus Hansen, and Stefan Roth. Covariance Matrix Adaptation for Multi-objective Optimization. Evolutionary Computation 15(1), pp. 1-28, 2007
Definition at line 59 of file ELLI1.h.
Constructor & Destructor Documentation
ELLI1()
shark::benchmarks::ELLI1::ELLI1 (std::size_t numVariables = 0) inline
Definition at line 61 of file ELLI1.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::CAN_PROPOSE_STARTING_POINT, shark::AbstractObjectiveFunction< PointType, ResultT >::m_features, and setNumberOfVariables().
Member Function Documentation
eval()
ResultType shark::benchmarks::ELLI1::eval (const SearchPointType & input) const inline virtual
Evaluates the objective function for the supplied argument.
Parameters
[in] input The argument for which the function shall be evaluated.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 93 of file ELLI1.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::m_evaluationCounter, numberOfVariables(), and shark::sqr().
hasScalableDimensionality()
bool shark::benchmarks::ELLI1::hasScalableDimensionality () const inline virtual
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 78 of file ELLI1.h.
init()
void shark::benchmarks::ELLI1::init () inline virtual
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 89 of file ELLI1.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::mep_rng, numberOfVariables(), and shark::blas::randomRotationMatrix().
name()
std::string shark::benchmarks::ELLI1::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 67 of file ELLI1.h.
numberOfObjectives()
std::size_t shark::benchmarks::ELLI1::numberOfObjectives () const inline virtual
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 70 of file ELLI1.h.
numberOfVariables()
std::size_t shark::benchmarks::ELLI1::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 74 of file ELLI1.h.
Referenced by eval(), init(), and proposeStartingPoint().
proposeStartingPoint()
SearchPointType shark::benchmarks::ELLI1::proposeStartingPoint () const inline virtual
Proposes a starting point in the feasible search space of the function.
Returns
The generated starting point.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 113 of file ELLI1.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::mep_rng, numberOfVariables(), and shark::random::uni().
setNumberOfVariables()
void shark::benchmarks::ELLI1::setNumberOfVariables (std::size_t numberOfVariables) inline virtual
Adjusts the number of variables if the function is scalable.
Parameters
[in] numberOfVariables The new dimension.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 82 of file ELLI1.h.
Referenced by ELLI1().
The documentation for this struct was generated from the following file:
include/shark/ObjectiveFunctions/Benchmarks/ELLI1.h