shark::IndicatorBasedSelection< Indicator > Struct Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::IndicatorBasedSelection< Indicator > Struct Template Reference
Implements the well-known indicator-based selection strategy.
#include <shark/Algorithms/DirectSearch/Operators/Selection/IndicatorBasedSelection.h>
Public Member Functions
template<typename PopulationType >
void operator() (PopulationType &population, std::size_t mu)
Executes the algorithm and assigns each member of the population its level non-dominance (rank) and its individual contribution to the front it belongs to (share).
template<typename Archive >
void serialize (Archive &archive, const unsigned int version)
Stores/restores the serializer's state.
Indicator & indicator ()
Indicator const & indicator () const
Detailed Description
template<typename Indicator>
struct shark::IndicatorBasedSelection< Indicator >
Implements the well-known indicator-based selection strategy.
See Kalyanmoy Deb and Amrit Pratap and Sameer Agarwal and T. Meyarivan, A Fast Elitist Multi-Objective Genetic Algorithm: NSGA-II, IEEE Transactions on Evolutionary Computation Year 2000, Volume 6, p. 182-197
Template Parameters
Indicator The second-level sorting criterion.
Definition at line 54 of file IndicatorBasedSelection.h.
Member Function Documentation
indicator() [1/2]
template<typename Indicator > Indicator & shark::IndicatorBasedSelection< Indicator >::indicator () inline
Definition at line 121 of file IndicatorBasedSelection.h.
Referenced by shark::SMSEMOA::indicator(), and shark::SMSEMOA::indicator().
indicator() [2/2]
template<typename Indicator > Indicator const & shark::IndicatorBasedSelection< Indicator >::indicator () const inline
Definition at line 124 of file IndicatorBasedSelection.h.
operator()()
template<typename Indicator > template<typename PopulationType > void shark::IndicatorBasedSelection< Indicator >::operator() (PopulationType & population, std::size_t mu) inline
Executes the algorithm and assigns each member of the population its level non-dominance (rank) and its individual contribution to the front it belongs to (share).
Parameters
[in,out] population The population to be ranked.
[in,out] mu the number of individuals to select
Definition at line 64 of file IndicatorBasedSelection.h.
References shark::nonDominatedSort(), shark::penalizedFitness(), and shark::ranks().
serialize()
template<typename Indicator > template<typename Archive > void shark::IndicatorBasedSelection< Indicator >::serialize (Archive & archive, const unsigned int version) inline
Stores/restores the serializer's state.
Template Parameters
Archive Type of the archive.
Parameters
[in,out] archive The archive to serialize to.
[in] version number, currently unused.
Definition at line 117 of file IndicatorBasedSelection.h.
The documentation for this struct was generated from the following file:
include/shark/Algorithms/DirectSearch/Operators/Selection/IndicatorBasedSelection.h