shark::statistics::Statistics< Parameter > Struct Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::statistics::Statistics< Parameter > Struct Template Reference
Generates Statistics over the results of an experiment.
#include <shark/Statistics/Statistics.h>
Public Types
typedef std::map< Parameter, std::map< std::string, RealVector > >::const_iterator const_iterator
Public Member Functions
Statistics (ResultTable< Parameter > const *table)
void addStatistic (std::string const &statisticName, BaseStatisticsObject const &object)
void addStatistic (BaseStatisticsObject const &object)
std::map< std::string, RealVector > const & operator[] (Parameter const &parameter) const
const_iterator begin () const
const_iterator end () const
std::string const & parameterName () const
std::size_t numParams () const
Parameter const & parameterValue (std::size_t i) const
std::size_t numDimensions () const
std::string const & dimensionName (std::size_t i) const
std::size_t numStatistics () const
std::string const & statisticName (std::size_t i) const
Detailed Description
template<class Parameter>
struct shark::statistics::Statistics< Parameter >
Generates Statistics over the results of an experiment.
Given the results of an experiment stored in a ResultsTable, computes several tatistics for each variable.
Definition at line 291 of file Statistics.h.
Member Typedef Documentation
const_iterator
template<class Parameter > typedef std::map<Parameter,std::map<std::string,RealVector>>::const_iterator shark::statistics::Statistics< Parameter >::const_iterator
Definition at line 293 of file Statistics.h.
Constructor & Destructor Documentation
Statistics()
template<class Parameter > shark::statistics::Statistics< Parameter >::Statistics (ResultTable< Parameter > const * table) inline
Definition at line 294 of file Statistics.h.
Member Function Documentation
addStatistic() [1/2]
template<class Parameter > void shark::statistics::Statistics< Parameter >::addStatistic (BaseStatisticsObject const & object) inline
Definition at line 305 of file Statistics.h.
References shark::statistics::Statistics< Parameter >::addStatistic().
addStatistic() [2/2]
template<class Parameter > void shark::statistics::Statistics< Parameter >::addStatistic (std::string const & statisticName, BaseStatisticsObject const & object) inline
Definition at line 296 of file Statistics.h.
References shark::statistics::Statistics< Parameter >::end(), and shark::statistics::Statistics< Parameter >::statisticName().
Referenced by shark::statistics::Statistics< Parameter >::addStatistic(), and main().
begin()
template<class Parameter > const_iterator shark::statistics::Statistics< Parameter >::begin () const inline
Definition at line 313 of file Statistics.h.
dimensionName()
template<class Parameter > std::string const & shark::statistics::Statistics< Parameter >::dimensionName (std::size_t i) const inline
Definition at line 338 of file Statistics.h.
Referenced by shark::statistics::printCSV().
end()
template<class Parameter > const_iterator shark::statistics::Statistics< Parameter >::end () const inline
Definition at line 316 of file Statistics.h.
Referenced by shark::statistics::Statistics< Parameter >::addStatistic().
numDimensions()
template<class Parameter > std::size_t shark::statistics::Statistics< Parameter >::numDimensions () const inline
Definition at line 334 of file Statistics.h.
Referenced by shark::statistics::printCSV().
numParams()
template<class Parameter > std::size_t shark::statistics::Statistics< Parameter >::numParams () const inline
Definition at line 325 of file Statistics.h.
Referenced by shark::statistics::printCSV().
numStatistics()
template<class Parameter > std::size_t shark::statistics::Statistics< Parameter >::numStatistics () const inline
Definition at line 343 of file Statistics.h.
Referenced by shark::statistics::printCSV().
operator[]()
template<class Parameter > std::map< std::string, RealVector > const & shark::statistics::Statistics< Parameter >::operator[] (Parameter const & parameter) const inline
Definition at line 309 of file Statistics.h.
parameterName()
template<class Parameter > std::string const & shark::statistics::Statistics< Parameter >::parameterName () const inline
Definition at line 321 of file Statistics.h.
Referenced by shark::statistics::printCSV().
parameterValue()
template<class Parameter > Parameter const & shark::statistics::Statistics< Parameter >::parameterValue (std::size_t i) const inline
Definition at line 329 of file Statistics.h.
Referenced by shark::statistics::printCSV().
statisticName()
template<class Parameter > std::string const & shark::statistics::Statistics< Parameter >::statisticName (std::size_t i) const inline
Definition at line 346 of file Statistics.h.
Referenced by shark::statistics::Statistics< Parameter >::addStatistic(), and shark::statistics::printCSV().
The documentation for this struct was generated from the following file:
include/shark/Statistics/Statistics.h