shark::LogisticNeuron Struct Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::LogisticNeuron Struct Reference
Models » Neuron activation functions
Neuron which computes the Logistic (logistic) function with range [0,1].
#include <shark/Models/NeuronLayers.h>
Public Types
typedef EmptyState State
Public Member Functions
template<class Arg >
void evalInPlace (Arg &arg) const
template<class Arg >
void evalInPlace (Arg &arg, State &) const
template<class Output , class Derivative >
void multiplyDerivative (Output const &output, Derivative &der, State const &state) const
Detailed Description
Neuron which computes the Logistic (logistic) function with range [0,1].
The Logistic function is
\[ f(x)=\frac 1 {1+exp^(-x)}\]
it's derivative can be computed as
\[ f'(x)= f(x)(1-f(x)) \]
Definition at line 78 of file NeuronLayers.h.
Member Typedef Documentation
State
typedef EmptyState shark::LogisticNeuron::State
Definition at line 79 of file NeuronLayers.h.
Member Function Documentation
evalInPlace() [1/2]
template<class Arg > void shark::LogisticNeuron::evalInPlace (Arg & arg) const inline
Definition at line 81 of file NeuronLayers.h.
References shark::sigmoid().
Referenced by evalInPlace().
evalInPlace() [2/2]
template<class Arg > void shark::LogisticNeuron::evalInPlace (Arg & arg, State &) const inline
Definition at line 86 of file NeuronLayers.h.
References evalInPlace().
multiplyDerivative()
template<class Output , class Derivative > void shark::LogisticNeuron::multiplyDerivative (Output const & output, Derivative & der, State const & state) const inline
Definition at line 91 of file NeuronLayers.h.
The documentation for this struct was generated from the following file:
include/shark/Models/NeuronLayers.h