shark::benchmarks::Discus Struct Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::benchmarks::Discus Struct Reference
Objective functions » Benchmark functions
Convex quadratic benchmark function.
#include <shark/ObjectiveFunctions/Benchmarks/Discus.h>
Public Member Functions
Discus (std::size_t numberOfVariables=5, double alpha=1.E-3)
std::string name () const
From INameable: return the class name.
std::size_t numberOfVariables () const
Accesses the number of variables.
bool hasScalableDimensionality () const
void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
double eval (SearchPointType const &p) const
Evaluates the objective function for the supplied argument.
double evalDerivative (SearchPointType const &p, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
double alpha () const
void setAlpha (double alpha)
Public Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
virtual void init ()
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual std::size_t numberOfObjectives () const
virtual bool hasScalableObjectives () const
virtual void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Public Types inherited from shark::AbstractObjectiveFunction< RealVector, double >
enum Feature
List of features that are supported by an implementation.
typedef RealVector SearchPointType
typedef double ResultType
typedef boost::mpl::if_< std::is_arithmetic< double >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Protected Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< RealVector, double >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
Convex quadratic benchmark function.
Definition at line 42 of file Discus.h.
Constructor & Destructor Documentation
Discus()
shark::benchmarks::Discus::Discus (std::size_t numberOfVariables = 5, double alpha = 1.E-3) inline
Definition at line 44 of file Discus.h.
References shark::AbstractObjectiveFunction< RealVector, double >::CAN_PROPOSE_STARTING_POINT, shark::AbstractObjectiveFunction< RealVector, double >::HAS_FIRST_DERIVATIVE, shark::AbstractObjectiveFunction< RealVector, double >::m_features, and numberOfVariables().
Member Function Documentation
alpha()
double shark::benchmarks::Discus::alpha () const inline
Definition at line 92 of file Discus.h.
Referenced by setAlpha().
eval()
double shark::benchmarks::Discus::eval (SearchPointType const & input) const inline virtual
Evaluates the objective function for the supplied argument.
Parameters
[in] input The argument for which the function shall be evaluated.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 77 of file Discus.h.
References shark::AbstractObjectiveFunction< RealVector, double >::m_evaluationCounter, and shark::sqr().
Referenced by evalDerivative().
evalDerivative()
double shark::benchmarks::Discus::evalDerivative (SearchPointType const & input, FirstOrderDerivative & derivative) const inline virtual
Evaluates the objective function and calculates its gradient.
Parameters
[in] input The argument to eval the function for.
[out] derivative The derivate is placed here.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 85 of file Discus.h.
References eval().
hasScalableDimensionality()
bool shark::benchmarks::Discus::hasScalableDimensionality () const inline virtual
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 58 of file Discus.h.
name()
std::string shark::benchmarks::Discus::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 51 of file Discus.h.
numberOfVariables()
std::size_t shark::benchmarks::Discus::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 54 of file Discus.h.
Referenced by Discus(), proposeStartingPoint(), and setNumberOfVariables().
proposeStartingPoint()
SearchPointType shark::benchmarks::Discus::proposeStartingPoint () const inline virtual
Proposes a starting point in the feasible search space of the function.
Returns
The generated starting point.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 68 of file Discus.h.
References shark::AbstractObjectiveFunction< RealVector, double >::mep_rng, numberOfVariables(), and shark::random::uni().
setAlpha()
void shark::benchmarks::Discus::setAlpha (double alpha) inline
Definition at line 96 of file Discus.h.
References alpha().
setNumberOfVariables()
void shark::benchmarks::Discus::setNumberOfVariables (std::size_t numberOfVariables) inline virtual
Adjusts the number of variables if the function is scalable.
Parameters
[in] numberOfVariables The new dimension.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 64 of file Discus.h.
References numberOfVariables().
The documentation for this struct was generated from the following file:
include/shark/ObjectiveFunctions/Benchmarks/Discus.h