shark::benchmarks::DTLZ7 Struct Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::benchmarks::DTLZ7 Struct Reference
Objective functions » Benchmark functions
Implements the benchmark function DTLZ7.
#include <shark/ObjectiveFunctions/Benchmarks/DTLZ7.h>
Public Member Functions
DTLZ7 (std::size_t numVariables=0)
std::string name () const
From INameable: return the class name.
std::size_t numberOfObjectives () const
bool hasScalableObjectives () const
void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t numberOfVariables () const
Accesses the number of variables.
bool hasScalableDimensionality () const
void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
ResultType eval (const SearchPointType &x) const
Evaluates the objective function for the supplied argument.
Public Member Functions inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
virtual void init ()
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
virtual SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Public Types inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
enum Feature {
HAS_VALUE = 1 , HAS_FIRST_DERIVATIVE = 2 , HAS_SECOND_DERIVATIVE = 4 , CAN_PROPOSE_STARTING_POINT = 8 ,
IS_CONSTRAINED_FEATURE = 16 , HAS_CONSTRAINT_HANDLER = 32 , CAN_PROVIDE_CLOSEST_FEASIBLE = 64 , IS_THREAD_SAFE = 128 ,
IS_NOISY = 256
}
List of features that are supported by an implementation.
typedef PointType SearchPointType
typedef ResultT ResultType
typedef boost::mpl::if_< std::is_arithmetic< ResultT >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Protected Member Functions inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
Implements the benchmark function DTLZ7.
See: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.18.7531&rep=rep1&type=pdf The benchmark function exposes the following features:
Scalable w.r.t. the searchspace and w.r.t. the objective space.
Disconnected Pareto front.
Definition at line 50 of file DTLZ7.h.
Constructor & Destructor Documentation
DTLZ7()
shark::benchmarks::DTLZ7::DTLZ7 (std::size_t numVariables = 0) inline
Definition at line 52 of file DTLZ7.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::announceConstraintHandler().
Member Function Documentation
eval()
ResultType shark::benchmarks::DTLZ7::eval (const SearchPointType & input) const inline virtual
Evaluates the objective function for the supplied argument.
Parameters
[in] input The argument for which the function shall be evaluated.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 87 of file DTLZ7.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::m_evaluationCounter, numberOfObjectives(), and numberOfVariables().
hasScalableDimensionality()
bool shark::benchmarks::DTLZ7::hasScalableDimensionality () const inline virtual
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 74 of file DTLZ7.h.
hasScalableObjectives()
bool shark::benchmarks::DTLZ7::hasScalableObjectives () const inline virtual
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 63 of file DTLZ7.h.
name()
std::string shark::benchmarks::DTLZ7::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 57 of file DTLZ7.h.
numberOfObjectives()
std::size_t shark::benchmarks::DTLZ7::numberOfObjectives () const inline virtual
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 60 of file DTLZ7.h.
Referenced by eval(), and setNumberOfObjectives().
numberOfVariables()
std::size_t shark::benchmarks::DTLZ7::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 70 of file DTLZ7.h.
References shark::BoxConstraintHandler< Vector >::dimensions().
Referenced by eval(), and setNumberOfVariables().
setNumberOfObjectives()
void shark::benchmarks::DTLZ7::setNumberOfObjectives (std::size_t numberOfObjectives) inline virtual
Adjusts the number of objectives if the function is scalable.
Parameters
numberOfObjectives The new number of objectives to optimize for.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 66 of file DTLZ7.h.
References numberOfObjectives().
setNumberOfVariables()
void shark::benchmarks::DTLZ7::setNumberOfVariables (std::size_t numberOfVariables) inline virtual
Adjusts the number of variables if the function is scalable.
Parameters
[in] numberOfVariables The new dimension.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 80 of file DTLZ7.h.
References numberOfVariables(), and shark::BoxConstraintHandler< Vector >::setBounds().
The documentation for this struct was generated from the following file:
include/shark/ObjectiveFunctions/Benchmarks/DTLZ7.h