shark::Shark::Version< major, minor, patch > Struct Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::Shark::Version< major, minor, patch > Struct Template Reference
Models a version according to the major.minor.patch versioning scheme.
#include <shark/Core/Shark.h>
Static Public Member Functions
static const char * DEFAULT_FORMAT ()
Default printf-format for formatting version numbers.
static unsigned int MAJOR ()
Returns the major revision number.
static unsigned int MINOR ()
Returns the minor revision number.
static unsigned int PATCH ()
Returns the patch revision number.
Detailed Description
template<unsigned int major, unsigned int minor, unsigned int patch>
struct shark::Shark::Version< major, minor, patch >
Models a version according to the major.minor.patch versioning scheme.
Definition at line 181 of file Shark.h.
Member Function Documentation
DEFAULT_FORMAT()
template<unsigned int major, unsigned int minor, unsigned int patch> static const char * shark::Shark::Version< major, minor, patch >::DEFAULT_FORMAT () inline static
Default printf-format for formatting version numbers.
Definition at line 184 of file Shark.h.
MAJOR()
template<unsigned int major, unsigned int minor, unsigned int patch> static unsigned int shark::Shark::Version< major, minor, patch >::MAJOR () inline static
Returns the major revision number.
Definition at line 189 of file Shark.h.
Referenced by shark::Shark::info().
MINOR()
template<unsigned int major, unsigned int minor, unsigned int patch> static unsigned int shark::Shark::Version< major, minor, patch >::MINOR () inline static
Returns the minor revision number.
Definition at line 194 of file Shark.h.
Referenced by shark::Shark::info().
PATCH()
template<unsigned int major, unsigned int minor, unsigned int patch> static unsigned int shark::Shark::Version< major, minor, patch >::PATCH () inline static
Returns the patch revision number.
Definition at line 199 of file Shark.h.
Referenced by shark::Shark::info().
The documentation for this struct was generated from the following file:
include/shark/Core/Shark.h