#!/bin/sh
echo "applying astyle to all source and header files"
liste=`find \! -type d -a \! -iwholename "*CVS*" -a \! -iname "moc_*" -a \( -iname "*.c" -o -iname "*.cc" -o -iname "*.cpp" -o -iname "*.h" -o -iname "*.hpp" \)`
for i in $liste; do
	echo "formatting file $i"
	astyle --options=none --style=attach\
	-t4 -p -U -O -n $i 1>/dev/null 2>/dev/null
done