build/examples/Unsupervised/BinaryRBM.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
BinaryRBM.cpp File Reference
#include <shark/Unsupervised/RBM/BinaryRBM.h>
#include <shark/Algorithms/GradientDescent/SteepestDescent.h>
#include <shark/Unsupervised/RBM/Problems/BarsAndStripes.h>
#include <shark/Unsupervised/RBM/analytics.h>
#include <iostream>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 15 of file BinaryRBM.cpp.
References shark::BarsAndStripes::data(), shark::random::globalRng, shark::SteepestDescent< SearchPointType >::init(), shark::AbstractObjectiveFunction< PointType, ResultT >::init(), shark::initRandomUniform(), shark::BarsAndStripes::inputDimension(), shark::negativeLogLikelihood(), shark::ContrastiveDivergence< Operator >::setData(), shark::ContrastiveDivergence< Operator >::setK(), shark::SteepestDescent< SearchPointType >::setLearningRate(), shark::SteepestDescent< SearchPointType >::setMomentum(), shark::RBM< VisibleLayerT, HiddenLayerT, randomT >::setStructure(), and shark::SteepestDescent< SearchPointType >::step().