build/examples/EA/SOO/CMAPlot.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
CMAPlot.cpp File Reference
#include <shark/Algorithms/DirectSearch/CMA.h>
#include <shark/ObjectiveFunctions/Benchmarks/Benchmarks.h>
#include <boost/property_tree/json_parser.hpp>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 42 of file CMAPlot.cpp.
References shark::CMA::condition(), shark::CMA::eigenValues(), shark::CMA::eigenVectors(), shark::AbstractObjectiveFunction< PointType, ResultT >::evaluationCounter(), shark::CMA::init(), shark::AbstractObjectiveFunction< PointType, ResultT >::init(), shark::CMA::mean(), shark::ResultSet< SearchPointT, ResultT >::point, shark::CMA::sigma(), shark::AbstractSingleObjectiveOptimizer< PointType >::solution(), shark::CMA::step(), and shark::ResultSet< SearchPointT, ResultT >::value.