build/examples/Supervised/CSvmTutorial.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
CSvmTutorial.cpp File Reference
#include <shark/Algorithms/Trainers/CSvmTrainer.h>
#include <shark/Models/Kernels/GaussianRbfKernel.h>
#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>
#include <shark/Data/DataDistribution.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 9 of file CSvmTutorial.cpp.
References shark::ZeroOneLoss< LabelType, OutputType >::eval(), shark::LabeledDataDistribution< InputType, LabelType >::generateDataset(), shark::LabeledData< InputT, LabelT >::inputs(), shark::QpSolutionProperties::iterations, shark::LabeledData< InputT, LabelT >::labels(), shark::QpStoppingCondition::minAccuracy, shark::CSvmTrainer< InputType, CacheType >::name(), shark::QpSolutionProperties::seconds, shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::setCacheSize(), shark::QpConfig::solutionProperties(), shark::QpConfig::sparsify(), shark::QpConfig::stoppingCondition(), shark::CSvmTrainer< InputType, CacheType >::train(), and shark::QpSolutionProperties::value.