build/examples/Supervised/CSvmMaxLikelihoodMS.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
CSvmMaxLikelihoodMS.cpp File Reference
#include <shark/Data/Dataset.h>
#include <shark/Data/CVDatasetTools.h>
#include <shark/Data/DataDistribution.h>
#include <shark/Data/Statistics.h>
#include <shark/Models/Kernels/ArdKernel.h>
#include <shark/Algorithms/QP/QuadraticProgram.h>
#include <shark/Algorithms/Trainers/CSvmTrainer.h>
#include <shark/Algorithms/GradientDescent/Rprop.h>
#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>
#include <shark/ObjectiveFunctions/SvmLogisticInterpretation.h>
#include <shark/Algorithms/Trainers/NormalizeComponentsUnitVariance.h>
Functions
RealVector run_one_trial (bool verbose)
int main ()
Variables
unsigned int useful_dim = 5
unsigned int noise_dim = 5
unsigned int total_dim = useful_dim + noise_dim
Function Documentation
main()
int main ()
Definition at line 180 of file CSvmMaxLikelihoodMS.cpp.
References shark::Data< Type >::element(), shark::meanvar(), run_one_trial(), and total_dim.
run_one_trial()
RealVector run_one_trial (bool verbose)
Definition at line 23 of file CSvmMaxLikelihoodMS.cpp.
References shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::C(), shark::createCVIID(), shark::ZeroOneLoss< LabelType, OutputType >::eval(), shark::SvmLogisticInterpretation< InputType >::eval(), shark::ARDKernelUnconstrained< InputType >::gammaVector(), shark::LabeledDataDistribution< InputType, LabelType >::generateDataset(), shark::Rprop< SearchPointType >::init(), shark::AbstractObjectiveFunction< RealVector, double >::init(), shark::LabeledData< InputT, LabelT >::inputs(), shark::LabeledData< InputT, LabelT >::labels(), shark::Rprop< SearchPointType >::maxDelta(), noise_dim, shark::ARDKernelUnconstrained< InputType >::parameterVector(), shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::parameterVector(), shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::setParameterVector(), shark::AbstractSingleObjectiveOptimizer< SearchPointType >::solution(), shark::Rprop< SearchPointType >::step(), total_dim, shark::NormalizeComponentsUnitVariance< DataType >::train(), shark::CSvmTrainer< InputType, CacheType >::train(), shark::transformInputs(), and useful_dim.
Referenced by main().
Variable Documentation
noise_dim
unsigned int noise_dim = 5
Definition at line 20 of file CSvmMaxLikelihoodMS.cpp.
Referenced by run_one_trial().
total_dim
unsigned int total_dim = useful_dim + noise_dim
Definition at line 21 of file CSvmMaxLikelihoodMS.cpp.
Referenced by main(), and run_one_trial().
useful_dim
unsigned int useful_dim = 5
Definition at line 19 of file CSvmMaxLikelihoodMS.cpp.
Referenced by run_one_trial().