build/examples/Data/Datasets.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
Datasets.cpp File Reference
#include <shark/Data/Dataset.h>
#include <shark/Data/DataView.h>
#include <shark/Models/LinearModel.h>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 77 of file Datasets.cpp.
References shark::Data< Type >::batch(), shark::Data< Type >::batches(), shark::batchSize(), shark::classSizes(), shark::createDataFromRange(), shark::createLabeledDataFromRange(), shark::dataDimension(), shark::Data< Type >::elements(), shark::getBatchElement(), shark::inputDimension(), shark::Data< Type >::makeIndependent(), shark::Data< Type >::numberOfBatches(), shark::numberOfClasses(), shark::DataView< DatasetType >::size(), shark::subset(), shark::toDataset(), shark::transform(), shark::transformInputs(), and shark::transformLabels().