build/examples/Supervised/DeepNetworkTrainingRBM.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
DeepNetworkTrainingRBM.cpp File Reference
#include <shark/Models/LinearModel.h>
#include <shark/Models/ConcatenatedModel.h>
#include <shark/Unsupervised/RBM/BinaryRBM.h>
#include <shark/ObjectiveFunctions/ErrorFunction.h>
#include <shark/ObjectiveFunctions/Loss/SquaredLoss.h>
#include <shark/ObjectiveFunctions/Loss/CrossEntropy.h>
#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>
#include <shark/ObjectiveFunctions/Regularizer.h>
#include <shark/Algorithms/GradientDescent/SteepestDescent.h>
#include <shark/Algorithms/GradientDescent/Rprop.h>
Functions
LabeledData< RealVector, unsigned int > createProblem ()
BinaryRBM trainRBM (UnlabeledData< RealVector > const &data, std::size_t numHidden, std::size_t iterations, double regularisation, double learningRate)
int main ()
Function Documentation
createProblem()
LabeledData<RealVector,unsigned int> createProblem ()
Definition at line 19 of file DeepNetworkTrainingRBM.cpp.
References shark::random::coinToss(), and shark::random::globalRng.
Referenced by main().
main()
int main ()
Definition at line 86 of file DeepNetworkTrainingRBM.cpp.
References createProblem(), shark::ZeroOneLoss< LabelType, OutputType >::eval(), shark::RBM< VisibleLayerT, HiddenLayerT, randomT >::evaluationType(), shark::RBM< VisibleLayerT, HiddenLayerT, randomT >::hiddenNeurons(), shark::ErrorFunction< SearchPointType >::init(), shark::Rprop< SearchPointType >::init(), shark::initRandomNormal(), shark::LabeledData< InputT, LabelT >::inputs(), shark::LabeledData< InputT, LabelT >::labels(), shark::numberOfClasses(), shark::LabeledData< InputT, LabelT >::numberOfElements(), shark::ErrorFunction< SearchPointType >::numberOfVariables(), shark::ErrorFunction< SearchPointType >::setRegularizer(), shark::LabeledData< InputT, LabelT >::shuffle(), shark::AbstractSingleObjectiveOptimizer< SearchPointType >::solution(), shark::splitAtElement(), shark::Rprop< SearchPointType >::step(), trainRBM(), and shark::RBM< VisibleLayerT, HiddenLayerT, randomT >::weightMatrix().
trainRBM()
BinaryRBM trainRBM (UnlabeledData< RealVector > const & data, std::size_t numHidden, std::size_t iterations, double regularisation, double learningRate)
Definition at line 48 of file DeepNetworkTrainingRBM.cpp.
References shark::dataDimension(), shark::random::globalRng, shark::SteepestDescent< SearchPointType >::init(), shark::AbstractObjectiveFunction< PointType, ResultT >::init(), shark::initRandomUniform(), shark::ContrastiveDivergence< Operator >::setData(), shark::ContrastiveDivergence< Operator >::setK(), shark::SteepestDescent< SearchPointType >::setLearningRate(), shark::RBM< VisibleLayerT, HiddenLayerT, randomT >::setParameterVector(), shark::ContrastiveDivergence< Operator >::setRegularizer(), shark::RBM< VisibleLayerT, HiddenLayerT, randomT >::setStructure(), shark::AbstractSingleObjectiveOptimizer< SearchPointType >::solution(), and shark::SteepestDescent< SearchPointType >::step().
Referenced by main().