build/examples/Unsupervised/KMeansTutorial.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
KMeansTutorial.cpp File Reference
#include <shark/Data/Csv.h>
#include <shark/Algorithms/Trainers/NormalizeComponentsUnitVariance.h>
#include <shark/Algorithms/KMeans.h>
#include <shark/Models/Clustering/HardClusteringModel.h>
#include <iostream>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 47 of file KMeansTutorial.cpp.
References shark::Centroids::centroids(), shark::dataDimension(), shark::Data< Type >::element(), shark::importCSV(), shark::kMeans(), shark::Data< Type >::numberOfElements(), and shark::NormalizeComponentsUnitVariance< DataType >::train().