build/examples/Supervised/KNNCrossValidationTutorial.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
KNNCrossValidationTutorial.cpp File Reference
#include <shark/Data/Csv.h>
#include <shark/Models/NearestNeighborModel.h>
#include <shark/Algorithms/NearestNeighbors/SimpleNearestNeighbors.h>
#include <shark/Models/Kernels/LinearKernel.h>
#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>
#include <shark/Data/CVDatasetTools.h>
#include <iostream>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 47 of file KNNCrossValidationTutorial.cpp.
References shark::createCVSameSizeBalanced(), shark::importCSV(), shark::inputDimension(), shark::LabeledData< InputT, LabelT >::inputs(), shark::LabeledData< InputT, LabelT >::labels(), shark::LAST_COLUMN, shark::numberOfClasses(), shark::LabeledData< InputT, LabelT >::numberOfElements(), shark::splitAtElement(), shark::CVFolds< DatasetTypeT >::training(), and shark::CVFolds< DatasetTypeT >::validation().