build/examples/EA/MOO/MOCMASimple.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
MOCMASimple.cpp File Reference
#include <shark/Algorithms/DirectSearch/MOCMA.h>
#include <shark/ObjectiveFunctions/Benchmarks/Benchmarks.h>
Functions
int main (int argc, char **argv)
Example for running MO-CMA-ES on an exemplary benchmark function.
Function Documentation
main()
int main (int argc, char ** argv)
Example for running MO-CMA-ES on an exemplary benchmark function.
Author
tvoss
Date
-
Copyright 1995-2017 Shark Development Team
This file is part of Shark. http://shark-ml.org/
Shark is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Shark is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with Shark. If not, see http://www.gnu.org/licenses/.
Definition at line 37 of file MOCMASimple.cpp.
References shark::AbstractObjectiveFunction< PointType, ResultT >::evaluationCounter(), shark::IndicatorBasedMOCMA< Indicator >::init(), shark::AbstractObjectiveFunction< PointType, ResultT >::init(), shark::benchmarks::DTLZ2::numberOfObjectives(), shark::benchmarks::DTLZ2::setNumberOfVariables(), shark::AbstractMultiObjectiveOptimizer< PointTypeT >::solution(), and shark::IndicatorBasedMOCMA< Indicator >::step().