build/examples/EA/MOO/MOCMAExperiment.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
MOCMAExperiment.cpp File Reference
#include <shark/Algorithms/DirectSearch/MOCMA.h>
#include <shark/ObjectiveFunctions/Benchmarks/ZDT1.h>
#include <shark/ObjectiveFunctions/Benchmarks/ZDT2.h>
#include <shark/ObjectiveFunctions/Benchmarks/ZDT3.h>
#include <shark/ObjectiveFunctions/Benchmarks/ZDT6.h>
Functions
template<class Solution >
double hypervolume (Solution const &solution)
int main (int argc, char **argv)
Function Documentation
hypervolume()
template<class Solution > double hypervolume (Solution const & solution)
Definition at line 41 of file MOCMAExperiment.cpp.
References shark::transform().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 51 of file MOCMAExperiment.cpp.
References hypervolume(), shark::IndicatorBasedMOCMA< Indicator >::init(), shark::IndicatorBasedMOCMA< Indicator >::mu(), shark::AbstractMultiObjectiveOptimizer< PointTypeT >::solution(), and shark::IndicatorBasedMOCMA< Indicator >::step().