build/examples/Supervised/McSvm.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
McSvm.cpp File Reference
#include <cstdio>
#include <tuple>
#include <shark/LinAlg/Base.h>
#include <shark/Core/Random.h>
#include <shark/Data/Dataset.h>
#include <shark/Data/DataDistribution.h>
#include <shark/Models/Kernels/GaussianRbfKernel.h>
#include <shark/Algorithms/Trainers/CSvmTrainer.h>
#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 31 of file McSvm.cpp.
References shark::ADM, shark::ATM, shark::ATS, shark::CS, shark::ZeroOneLoss< LabelType, OutputType >::eval(), shark::LabeledData< InputT, LabelT >::inputs(), shark::QpSolutionProperties::iterations, shark::LabeledData< InputT, LabelT >::labels(), shark::LLW, shark::MMR, shark::OVA, shark::ReinforcedSvm, shark::QpSolutionProperties::seconds, shark::CSvmTrainer< InputType, CacheType >::setMcSvmType(), shark::QpConfig::solutionProperties(), shark::CSvmTrainer< InputType, CacheType >::train(), shark::AbstractSvmTrainer< InputType, unsigned int, KernelClassifier< InputType >, AbstractWeightedTrainer< KernelClassifier< InputType > > >::trainOffset(), and shark::WW.