build/examples/Supervised/MklKernelTutorial.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
MklKernelTutorial.cpp File Reference
#include <shark/Data/Dataset.h>
#include <shark/Core/Random.h>
#include <shark/Algorithms/Trainers/NormalizeKernelUnitVariance.h>
#include <shark/Models/Kernels/GaussianRbfKernel.h>
#include <shark/Models/Kernels/WeightedSumKernel.h>
#include <shark/Models/Kernels/SubrangeKernel.h>
#include <shark/Models/Kernels/MklKernel.h>
#include <shark/Models/Kernels/LinearKernel.h>
#include <shark/Models/Kernels/DiscreteKernel.h>
#include <shark/Models/Kernels/PolynomialKernel.h>
#include <boost/fusion/algorithm/iteration/fold.hpp>
#include <boost/fusion/include/as_vector.hpp>
Namespaces
shark
AbstractMultiObjectiveOptimizer.
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 43 of file MklKernelTutorial.cpp.
References shark::createDataFromRange(), shark::Data< Type >::element(), shark::ScaledKernel< InputType >::eval(), shark::WeightedSumKernel< InputType >::eval(), shark::ScaledKernel< InputType >::factor(), shark::random::globalRng, shark::WeightedSumKernel< InputType >::isAdaptive(), shark::NormalizeKernelUnitVariance< InputType >::mean(), shark::WeightedSumKernel< InputType >::numberOfParameters(), shark::WeightedSumKernel< InputType >::parameterVector(), shark::WeightedSumKernel< InputType >::setAdaptive(), shark::WeightedSumKernel< InputType >::setAdaptiveAll(), shark::WeightedSumKernel< InputType >::setParameterVector(), shark::NormalizeKernelUnitVariance< InputType >::trace(), shark::NormalizeKernelUnitVariance< InputType >::train(), and shark::random::uni().