build/examples/Supervised/MultiTaskSvm.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
MultiTaskSvm.cpp File Reference
#include <shark/Algorithms/Trainers/CSvmTrainer.h>
#include <shark/Models/Kernels/GaussianRbfKernel.h>
#include <shark/Models/Kernels/MultiTaskKernel.h>
#include <shark/ObjectiveFunctions/Loss/ZeroOneLoss.h>
#include <shark/Data/DataDistribution.h>
Typedefs
typedef MultiTaskSample< RealVector > InputType
Functions
int main (int argc, char **argv)
Typedef Documentation
InputType
typedef MultiTaskSample<RealVector> InputType
Definition at line 13 of file MultiTaskSvm.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 56 of file MultiTaskSvm.cpp.
References shark::Data< Type >::element(), shark::ZeroOneLoss< LabelType, OutputType >::eval(), shark::LabeledData< InputT, LabelT >::inputs(), shark::LabeledData< InputT, LabelT >::labels(), and shark::CSvmTrainer< InputType, CacheType >::train().