build/examples/Statistics/Statistics.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
Statistics.cpp File Reference
#include <shark/Statistics/Statistics.h>
#include <shark/Core/Random.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 39 of file Statistics.cpp.
References shark::statistics::Statistics< Parameter >::addStatistic(), shark::random::coinToss(), shark::random::gauss(), shark::random::globalRng, shark::statistics::missingValue(), shark::statistics::printCSV(), shark::statistics::ResultTable< Parameter >::setDimensionName(), and shark::statistics::ResultTable< Parameter >::update().