build/examples/Data/Subsets.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
Subsets.cpp File Reference
#include <shark/Data/Dataset.h>
#include <shark/Data/CVDatasetTools.h>
#include <shark/Data/DataView.h>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 44 of file Subsets.cpp.
References shark::binarySubProblem(), shark::createCVIID(), shark::createCVIndexed(), shark::createCVSameSize(), shark::createCVSameSizeBalanced(), shark::LabeledData< InputT, LabelT >::indexedSubset(), shark::LabeledData< InputT, LabelT >::makeIndependent(), shark::randomSubset(), shark::repartitionByClass(), shark::DataView< DatasetType >::size(), shark::LabeledData< InputT, LabelT >::splice(), shark::splitAtElement(), shark::subset(), shark::swap(), shark::CVFolds< DatasetTypeT >::training(), and shark::CVFolds< DatasetTypeT >::validation().