build/examples/Unsupervised/VariationalAutoencoder.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
VariationalAutoencoder.cpp File Reference
#include <shark/Data/SparseData.h>
#include <shark/Data/Pgm.h>
#include <shark/Models/LinearModel.h>
#include <shark/Models/ConcatenatedModel.h>
#include <shark/Algorithms/GradientDescent/Adam.h>
#include <shark/ObjectiveFunctions/Loss/SquaredLoss.h>
#include <shark/ObjectiveFunctions/VariationalAutoencoderError.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 10 of file VariationalAutoencoder.cpp.
References shark::LabeledData< InputT, LabelT >::batch(), shark::exportFiltersToPGMGrid(), shark::importSparseData(), shark::Adam< SearchPointType >::init(), shark::initRandomNormal(), shark::LabeledData< InputT, LabelT >::inputs(), shark::LabeledData< InputT, LabelT >::inputShape(), shark::LinearModel< InputType, ActivationFunction >::outputShape(), shark::Adam< SearchPointType >::setEta(), shark::AbstractSingleObjectiveOptimizer< SearchPointType >::solution(), and shark::Adam< SearchPointType >::step().