shark::McPegasos< VectorType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::McPegasos< VectorType > Class Template Reference
Pegasos solver for linear multi-class support vector machines.
#include <shark/Algorithms/Pegasos.h>
Public Types
enum eMarginType { emRelative, emAbsolute }
Multi-class margin type.
enum eLossType {
elNaiveHinge, elDiscriminativeMax, elDiscriminativeSum, elTotalMax,
elTotalSum
}
Multi-class loss function type.
Static Public Member Functions
template<class WeightType >
static std::size_t solve (LabeledData< VectorType, unsigned int > const &data, eMarginType margintype, eLossType losstype, bool sumToZero, double C, std::vector< WeightType > &w, std::size_t batchsize=1, double varepsilon=0.001)
Solve the primal multi-class SVM problem.
Protected Types
typedef bool(* LossGradientFunction) (VectorType const &, unsigned int, RealVector const &, std::vector< VectorType > &, bool)
Static Protected Member Functions
static bool lossGradientANH (VectorType const &x, unsigned int y, RealVector const &f, std::vector< VectorType > &gradient, bool sumToZero)
static bool lossGradientRDM (VectorType const &x, unsigned int y, RealVector const &f, std::vector< VectorType > &gradient, bool sumToZero)
static bool lossGradientRDS (VectorType const &x, unsigned int y, RealVector const &f, std::vector< VectorType > &gradient, bool sumToZero)
static bool lossGradientADS (VectorType const &x, unsigned int y, RealVector const &f, std::vector< VectorType > &gradient, bool sumToZero)
static bool lossGradientADM (VectorType const &x, unsigned int y, RealVector const &f, std::vector< VectorType > &gradient, bool sumToZero)
static bool lossGradientATS (VectorType const &x, unsigned int y, RealVector const &f, std::vector< VectorType > &gradient, bool sumToZero)
static bool lossGradientATM (VectorType const &x, unsigned int y, RealVector const &f, std::vector< VectorType > &gradient, bool sumToZero)
Detailed Description
template<class VectorType>
class shark::McPegasos< VectorType >
Pegasos solver for linear multi-class support vector machines.
Definition at line 192 of file Pegasos.h.
Member Typedef Documentation
LossGradientFunction
template<class VectorType > typedef bool(* shark::McPegasos< VectorType >::LossGradientFunction) (VectorType const &, unsigned int, RealVector const &, std::vector< VectorType > &, bool) protected
Definition at line 384 of file Pegasos.h.
Member Enumeration Documentation
eLossType
template<class VectorType > enum shark::McPegasos::eLossType
Multi-class loss function type.
Enumerator
elNaiveHinge
elDiscriminativeMax
elDiscriminativeSum
elTotalMax
elTotalSum
Definition at line 203 of file Pegasos.h.
eMarginType
template<class VectorType > enum shark::McPegasos::eMarginType
Multi-class margin type.
Enumerator
emRelative
emAbsolute
Definition at line 196 of file Pegasos.h.
Member Function Documentation
lossGradientADM()
template<class VectorType > static bool shark::McPegasos< VectorType >::lossGradientADM (VectorType const & x, unsigned int y, RealVector const & f, std::vector< VectorType > & gradient, bool sumToZero) inline static protected
Definition at line 483 of file Pegasos.h.
Referenced by shark::McPegasos< VectorType >::solve().
lossGradientADS()
template<class VectorType > static bool shark::McPegasos< VectorType >::lossGradientADS (VectorType const & x, unsigned int y, RealVector const & f, std::vector< VectorType > & gradient, bool sumToZero) inline static protected
Definition at line 456 of file Pegasos.h.
References shark::mean().
Referenced by shark::McPegasos< VectorType >::solve().
lossGradientANH()
template<class VectorType > static bool shark::McPegasos< VectorType >::lossGradientANH (VectorType const & x, unsigned int y, RealVector const & f, std::vector< VectorType > & gradient, bool sumToZero) inline static protected
Definition at line 387 of file Pegasos.h.
Referenced by shark::McPegasos< VectorType >::solve().
lossGradientATM()
template<class VectorType > static bool shark::McPegasos< VectorType >::lossGradientATM (VectorType const & x, unsigned int y, RealVector const & f, std::vector< VectorType > & gradient, bool sumToZero) inline static protected
Definition at line 553 of file Pegasos.h.
Referenced by shark::McPegasos< VectorType >::solve().
lossGradientATS()
template<class VectorType > static bool shark::McPegasos< VectorType >::lossGradientATS (VectorType const & x, unsigned int y, RealVector const & f, std::vector< VectorType > & gradient, bool sumToZero) inline static protected
Definition at line 515 of file Pegasos.h.
References shark::mean().
Referenced by shark::McPegasos< VectorType >::solve().
lossGradientRDM()
template<class VectorType > static bool shark::McPegasos< VectorType >::lossGradientRDM (VectorType const & x, unsigned int y, RealVector const & f, std::vector< VectorType > & gradient, bool sumToZero) inline static protected
Definition at line 408 of file Pegasos.h.
Referenced by shark::McPegasos< VectorType >::solve().
lossGradientRDS()
template<class VectorType > static bool shark::McPegasos< VectorType >::lossGradientRDS (VectorType const & x, unsigned int y, RealVector const & f, std::vector< VectorType > & gradient, bool sumToZero) inline static protected
Definition at line 435 of file Pegasos.h.
Referenced by shark::McPegasos< VectorType >::solve().
solve()
template<class VectorType > template<class WeightType > static std::size_t shark::McPegasos< VectorType >::solve (LabeledData< VectorType, unsigned int > const & data, eMarginType margintype, eLossType losstype, bool sumToZero, double C, std::vector< WeightType > & w, std::size_t batchsize = 1, double varepsilon = 0.001) inline static
Solve the primal multi-class SVM problem.
In addition to "standard" Pegasos this solver checks a meaningful stopping criterion.
The function returns the number of model predictions during training (this is comparable to SMO iterations).
Parameters
data training data
margintype margin function type
losstype loss function type
sumToZero enforce the sum-to-zero constraint?
C SVM regularization parameter
w class-wise weight vectors
batchsize number of samples in each gradient estimate
varepsilon solution accuracy (factor by which the primal gradient should be reduced)
Definition at line 220 of file Pegasos.h.
References shark::McPegasos< VectorType >::elDiscriminativeMax, shark::McPegasos< VectorType >::elDiscriminativeSum, shark::McPegasos< VectorType >::elNaiveHinge, shark::McPegasos< VectorType >::elTotalMax, shark::McPegasos< VectorType >::elTotalSum, shark::McPegasos< VectorType >::emAbsolute, shark::McPegasos< VectorType >::emRelative, shark::McPegasos< VectorType >::lossGradientADM(), shark::McPegasos< VectorType >::lossGradientADS(), shark::McPegasos< VectorType >::lossGradientANH(), shark::McPegasos< VectorType >::lossGradientATM(), shark::McPegasos< VectorType >::lossGradientATS(), shark::McPegasos< VectorType >::lossGradientRDM(), shark::McPegasos< VectorType >::lossGradientRDS(), shark::LabeledData< InputT, LabelT >::numberOfElements(), SHARK_ASSERT, and SHARK_RUNTIME_CHECK.
The documentation for this class was generated from the following file:
include/shark/Algorithms/Pegasos.h