shark::NormalizeComponentsUnitVariance< DataType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::NormalizeComponentsUnitVariance< DataType > Class Template Reference
Unsupervised Trainers
Train a linear model to normalize the components of a dataset to unit variance, and optionally to zero mean.
#include <shark/Algorithms/Trainers/NormalizeComponentsUnitVariance.h>
Public Member Functions
NormalizeComponentsUnitVariance (bool zeroMean)
Constructor.
std::string name () const
From INameable: return the class name.
void train (Normalizer< DataType > &model, UnlabeledData< DataType > const &input)
Public Member Functions inherited from shark::AbstractUnsupervisedTrainer< Normalizer< DataType > >
virtual void train (ModelType &model, DatasetType const &inputset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Attributes
bool m_zeroMean
Additional Inherited Members
Public Types inherited from shark::AbstractUnsupervisedTrainer< Normalizer< DataType > >
typedef Normalizer< DataType > ModelType
typedef Normalizer< DataType > ::InputType InputType
typedef UnlabeledData< InputType > DatasetType
Detailed Description
template<class DataType = RealVector>
class shark::NormalizeComponentsUnitVariance< DataType >
Train a linear model to normalize the components of a dataset to unit variance, and optionally to zero mean.
Normalizing the components of a dataset works via training a Normalizer model. This model is then applied to the dataset in order to perform the normalization. The same model can be applied to different datasets.
The typical use case is that the Normalizer model is trained on the training data. Later, as "test" data comes in, the same model is used, of course without being recalibrated. Thus, the model used for normalization must be independent of the dataset it was trained on.
Note that subtracting the mean destroys sparsity. Therefore this feature is turned off by default. If you have non-sparse data and you need to move data to zero mean, not only to unit variance, then enable the flag zeroMean in the constructor.
Definition at line 74 of file NormalizeComponentsUnitVariance.h.
Constructor & Destructor Documentation
NormalizeComponentsUnitVariance()
template<class DataType = RealVector> shark::NormalizeComponentsUnitVariance< DataType >::NormalizeComponentsUnitVariance (bool zeroMean) inline
Constructor.
The normalizer scales the data to unit variance. It can also remove the mean of the data. This is usually desired, e.g., for neural network training. Note however that this feature is sometimes undesirable since it can destroy sparsity.
Parameters
zeroMean enable or disable data mean removal
Definition at line 89 of file NormalizeComponentsUnitVariance.h.
Member Function Documentation
name()
template<class DataType = RealVector> std::string shark::NormalizeComponentsUnitVariance< DataType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 93 of file NormalizeComponentsUnitVariance.h.
train()
template<class DataType = RealVector> void shark::NormalizeComponentsUnitVariance< DataType >::train (Normalizer< DataType > & model, UnlabeledData< DataType > const & input) inline
Definition at line 96 of file NormalizeComponentsUnitVariance.h.
References shark::dataDimension(), shark::NormalizeComponentsUnitVariance< DataType >::m_zeroMean, shark::mean(), shark::meanvar(), shark::Data< InputT >::numberOfElements(), shark::Normalizer< VectorType >::setStructure(), SHARK_RUNTIME_CHECK, and shark::variance().
Referenced by main(), and run_one_trial().
Member Data Documentation
m_zeroMean
template<class DataType = RealVector> bool shark::NormalizeComponentsUnitVariance< DataType >::m_zeroMean protected
Definition at line 129 of file NormalizeComponentsUnitVariance.h.
Referenced by shark::NormalizeComponentsUnitVariance< DataType >::train().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/NormalizeComponentsUnitVariance.h