shark::QpSolver< Problem, SelectionStrategy > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::QpSolver< Problem, SelectionStrategy > Class Template Reference
Quadratic program solver.
#include <shark/Algorithms/QP/QpSolver.h>
Public Member Functions
QpSolver (Problem &problem)
void solve (QpStoppingCondition &stop, QpSolutionProperties *prop=NULL)
Solve the quadratic program.
Protected Attributes
Problem & m_problem
Detailed Description
template<class Problem, class SelectionStrategy = typename Problem::PreferedSelectionStrategy>
class shark::QpSolver< Problem, SelectionStrategy >
Quadratic program solver.
todo: new documentation
Definition at line 403 of file QpSolver.h.
Constructor & Destructor Documentation
QpSolver()
template<class Problem, class SelectionStrategy = typename Problem::PreferedSelectionStrategy> shark::QpSolver< Problem, SelectionStrategy >::QpSolver (Problem & problem) inline
Definition at line 406 of file QpSolver.h.
Member Function Documentation
solve()
template<class Problem, class SelectionStrategy = typename Problem::PreferedSelectionStrategy> void shark::QpSolver< Problem, SelectionStrategy >::solve (QpStoppingCondition & stop, QpSolutionProperties * prop = NULL) inline
Solve the quadratic program.
The function iteratively refines the solution by applying the SMO (subset descent) algorithm until one of the stopping criteria is fulfilled.
Definition at line 415 of file QpSolver.h.
References shark::QpSolver< Problem, SelectionStrategy >::m_problem, shark::QpStoppingCondition::maxIterations, shark::QpStoppingCondition::maxSeconds, shark::QpStoppingCondition::minAccuracy, shark::Timer::now(), shark::QpAccuracyReached, shark::QpMaxIterationsReached, and shark::QpTimeout.
Referenced by shark::RadiusMarginQuotient< InputType, CacheType >::computeRadiusMargin(), shark::BiasSolver< Matrix >::solve(), and shark::BiasSolverSimplex< Matrix >::solve().
Member Data Documentation
m_problem
template<class Problem, class SelectionStrategy = typename Problem::PreferedSelectionStrategy> Problem& shark::QpSolver< Problem, SelectionStrategy >::m_problem protected
Definition at line 481 of file QpSolver.h.
Referenced by shark::QpSolver< Problem, SelectionStrategy >::solve().
The documentation for this class was generated from the following file:
include/shark/Algorithms/QP/QpSolver.h