shark::AbstractStoppingCriterion< ResultSetT > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::AbstractStoppingCriterion< ResultSetT > Class Template Reference abstract
Base class for stopping criteria of optimization algorithms.
#include <shark/Algorithms/StoppingCriteria/AbstractStoppingCriterion.h>
Public Types
typedef ResultSetT ResultSet
Public Member Functions
virtual void reset ()=0
resets the internal state. call before a new trial
virtual bool stop (ResultSet const &set)=0
Detailed Description
template<class ResultSetT>
class shark::AbstractStoppingCriterion< ResultSetT >
Base class for stopping criteria of optimization algorithms.
Each stopping criterion provides a stop method which takes as argument the latest result of an optimization algorithm. This result is passed as a ResultSetT, which is a template type of this interface. In actual implementations, that type will usually hold the latest objective function value reached by the optimizer on the training set, but may also additionally encapsulate a performance value reached on a validation set. The stopping criteria may then use this information to reach their characteristic decision of whether or not stopping the optimization process is indicated or not.
Definition at line 51 of file AbstractStoppingCriterion.h.
Member Typedef Documentation
ResultSet
template<class ResultSetT> typedef ResultSetT shark::AbstractStoppingCriterion< ResultSetT >::ResultSet
Definition at line 53 of file AbstractStoppingCriterion.h.
Member Function Documentation
reset()
template<class ResultSetT> virtual void shark::AbstractStoppingCriterion< ResultSetT >::reset () pure virtual
resets the internal state. call before a new trial
Implemented in shark::GeneralizationQuotient< PointType >, shark::TrainingProgress< PointType >, shark::GeneralizationLoss< PointType >, shark::TrainingError< PointType >, shark::ValidatedStoppingCriterion, and shark::MaxIterations< ResultSet >.
Referenced by shark::ValidatedStoppingCriterion::reset(), and shark::OptimizationTrainer< Model, LabelTypeT >::train().
stop()
template<class ResultSetT> virtual bool shark::AbstractStoppingCriterion< ResultSetT >::stop (ResultSet const & set) pure virtual
after an iteration, updates the internal state and checks whether the algorithm should stop
Parameters
set the result of the current iteration
Implemented in shark::GeneralizationQuotient< PointType >, shark::GeneralizationLoss< PointType >, shark::TrainingProgress< PointType >, shark::TrainingError< PointType >, shark::ValidatedStoppingCriterion, and shark::MaxIterations< ResultSet >.
Referenced by shark::ValidatedStoppingCriterion::stop(), and shark::OptimizationTrainer< Model, LabelTypeT >::train().
The documentation for this class was generated from the following file:
include/shark/Algorithms/StoppingCriteria/AbstractStoppingCriterion.h