shark::DropoutLayer< VectorType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::DropoutLayer< VectorType > Class Template Reference
Models
Implements Dropout layer semantics.
#include <shark/Models/DropoutLayer.h>
Public Types
typedef base_type::BatchInputType BatchInputType
typedef base_type::BatchOutputType BatchOutputType
typedef base_type::ParameterVectorType ParameterVectorType
Public Types inherited from shark::AbstractModel< VectorType, VectorType, VectorType >
enum Feature
typedef VectorType InputType
Defines the input type of the model.
typedef VectorType OutputType
Defines the output type of the model.
typedef AbstractModel< VectorType, VectorType, VectorType > ModelBaseType
Defines the BaseType used by the model (this type). Useful for creating derived models.
typedef Batch< InputType >::type BatchInputType
defines the batch type of the input type.
typedef Batch< OutputType >::type BatchOutputType
defines the batch type of the output type
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::IParameterizable< VectorType >
typedef VectorType ParameterVectorType
Public Member Functions
DropoutLayer (Shape const &inputShape, double probability=0.5, random::rng_type &rng=random::globalRng)
std::string name () const
From INameable: return the class name.
ParameterVectorType parameterVector () const
obtain the parameter vector
void setParameterVector (ParameterVectorType const &newParameters)
overwrite the parameter vector
size_t numberOfParameters () const
return the number of parameter
Shape inputShape () const
Returns the expected shape of the input.
Shape outputShape () const
Returns the shape of the output.
boost::shared_ptr< State > createState () const
Creates an internal state of the model.
void eval (BatchInputType const &inputs, BatchOutputType &outputs) const
Standard interface for evaluating the response of the model to a batch of patterns.
void eval (VectorType const &input, VectorType &output) const
Standard interface for evaluating the response of the model to a single pattern.
void eval (BatchInputType const &inputs, BatchOutputType &outputs, State &state) const
Standard interface for evaluating the response of the model to a batch of patterns.
void weightedParameterDerivative (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, ParameterVectorType &gradient) const
Calculates the first derivative w.r.t the parameters and summing them up over all patterns of the last computed batch.
void weightedInputDerivative (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchInputType &derivative) const
Calculates the first derivative w.r.t the inputs and summs them up over all patterns of the last computed batch.
void read (InArchive &archive)
From ISerializable.
void write (OutArchive &archive) const
From ISerializable.
Public Member Functions inherited from shark::AbstractModel< VectorType, VectorType, VectorType >
AbstractModel ()
virtual ~AbstractModel ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
Returns true when the first parameter derivative is implemented.
bool hasFirstInputDerivative () const
Returns true when the first input derivative is implemented.
Data< OutputType > operator() (Data< InputType > const &patterns) const
Model evaluation as an operator for a whole dataset. This is a convenience function.
OutputType operator() (InputType const &pattern) const
Model evaluation as an operator for a single pattern. This is a convenience function.
BatchOutputType operator() (BatchInputType const &patterns) const
Model evaluation as an operator for a single pattern. This is a convenience function.
virtual void weightedDerivatives (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, VectorType &parameterDerivative, BatchInputType &inputDerivative) const
calculates weighted input and parameter derivative at the same time
Public Member Functions inherited from shark::IParameterizable< VectorType >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Additional Inherited Members
Protected Attributes inherited from shark::AbstractModel< VectorType, VectorType, VectorType >
Features m_features
Detailed Description
template<class VectorType = RealVector>
class shark::DropoutLayer< VectorType >
Implements Dropout layer semantics.
A dropout layer drops its input, i.e. sets it to 0 with a given probability. This is done for each element separately. This means, model prodections are not deterministic any more. Thus, after training the output of several evaluations should be averaged.
Dropout during training often leads to better regularized solutions in deep neural networks.
Definition at line 48 of file DropoutLayer.h.
Member Typedef Documentation
BatchInputType
template<class VectorType = RealVector> typedef base_type::BatchInputType shark::DropoutLayer< VectorType >::BatchInputType
Definition at line 60 of file DropoutLayer.h.
BatchOutputType
template<class VectorType = RealVector> typedef base_type::BatchOutputType shark::DropoutLayer< VectorType >::BatchOutputType
Definition at line 61 of file DropoutLayer.h.
ParameterVectorType
template<class VectorType = RealVector> typedef base_type::ParameterVectorType shark::DropoutLayer< VectorType >::ParameterVectorType
Definition at line 62 of file DropoutLayer.h.
Constructor & Destructor Documentation
DropoutLayer()
template<class VectorType = RealVector> shark::DropoutLayer< VectorType >::DropoutLayer (Shape const & inputShape, double probability = 0.5, random::rng_type & rng = random::globalRng) inline
Definition at line 64 of file DropoutLayer.h.
References shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_INPUT_DERIVATIVE, shark::AbstractModel< VectorType, VectorType, VectorType >::HAS_FIRST_PARAMETER_DERIVATIVE, and shark::AbstractModel< VectorType, VectorType, VectorType >::m_features.
Member Function Documentation
createState()
template<class VectorType = RealVector> boost::shared_ptr<State> shark::DropoutLayer< VectorType >::createState () const inline virtual
Creates an internal state of the model.
The state is needed when the derivatives are to be calculated. Eval can store a state which is then reused to speed up the calculations of the derivatives. This also allows eval to be evaluated in parallel!
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 98 of file DropoutLayer.h.
eval() [1/3]
template<class VectorType = RealVector> void shark::DropoutLayer< VectorType >::eval (BatchInputType const & patterns, BatchOutputType & outputs) const inline virtual
Standard interface for evaluating the response of the model to a batch of patterns.
Parameters
patterns the inputs of the model
outputs the predictions or response of the model to every pattern
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 104 of file DropoutLayer.h.
eval() [2/3]
template<class VectorType = RealVector> void shark::DropoutLayer< VectorType >::eval (VectorType const & pattern, VectorType & output) const inline virtual
Standard interface for evaluating the response of the model to a single pattern.
Parameters
pattern the input of the model
output the prediction or response of the model to the pattern
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 116 of file DropoutLayer.h.
eval() [3/3]
template<class VectorType = RealVector> void shark::DropoutLayer< VectorType >::eval (BatchInputType const & patterns, BatchOutputType & outputs, State & state) const inline virtual
Standard interface for evaluating the response of the model to a batch of patterns.
Parameters
patterns the inputs of the model
outputs the predictions or response of the model to every pattern
state intermediate results stored by eval which can be reused for derivative computation.
Implements shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 125 of file DropoutLayer.h.
References shark::random::coinToss(), and shark::State::toState().
inputShape()
template<class VectorType = RealVector> Shape shark::DropoutLayer< VectorType >::inputShape () const inline virtual
Returns the expected shape of the input.
Implements shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 90 of file DropoutLayer.h.
name()
template<class VectorType = RealVector> std::string shark::DropoutLayer< VectorType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 71 of file DropoutLayer.h.
numberOfParameters()
template<class VectorType = RealVector> size_t shark::DropoutLayer< VectorType >::numberOfParameters () const inline virtual
return the number of parameter
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 85 of file DropoutLayer.h.
outputShape()
template<class VectorType = RealVector> Shape shark::DropoutLayer< VectorType >::outputShape () const inline virtual
Returns the shape of the output.
Implements shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 94 of file DropoutLayer.h.
parameterVector()
template<class VectorType = RealVector> ParameterVectorType shark::DropoutLayer< VectorType >::parameterVector () const inline virtual
obtain the parameter vector
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 75 of file DropoutLayer.h.
read()
template<class VectorType = RealVector> void shark::DropoutLayer< VectorType >::read (InArchive & archive) inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 165 of file DropoutLayer.h.
setParameterVector()
template<class VectorType = RealVector> void shark::DropoutLayer< VectorType >::setParameterVector (ParameterVectorType const & newParameters) inline virtual
overwrite the parameter vector
Reimplemented from shark::IParameterizable< VectorType >.
Definition at line 80 of file DropoutLayer.h.
References SIZE_CHECK.
weightedInputDerivative()
template<class VectorType = RealVector> void shark::DropoutLayer< VectorType >::weightedInputDerivative (BatchInputType const & patterns, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, BatchInputType & derivative) const inline virtual
Calculates the first derivative w.r.t the inputs and summs them up over all patterns of the last computed batch.
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 149 of file DropoutLayer.h.
References SIZE_CHECK, and shark::State::toState().
weightedParameterDerivative()
template<class VectorType = RealVector> void shark::DropoutLayer< VectorType >::weightedParameterDerivative (BatchInputType const & patterns, BatchOutputType const & outputs, BatchOutputType const & coefficients, State const & state, ParameterVectorType & gradient) const inline virtual
Calculates the first derivative w.r.t the parameters and summing them up over all patterns of the last computed batch.
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 138 of file DropoutLayer.h.
References SIZE_CHECK.
write()
template<class VectorType = RealVector> void shark::DropoutLayer< VectorType >::write (OutArchive & archive) const inline virtual
From ISerializable.
Reimplemented from shark::AbstractModel< VectorType, VectorType, VectorType >.
Definition at line 167 of file DropoutLayer.h.
The documentation for this class was generated from the following file:
include/shark/Models/DropoutLayer.h