shark::DifferenceKernelMatrix< InputType, CacheType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::DifferenceKernelMatrix< InputType, CacheType > Class Template Reference
SVM ranking matrix.
#include <shark/LinAlg/DifferenceKernelMatrix.h>
Public Types
typedef CacheType QpFloatType
Public Member Functions
DifferenceKernelMatrix (AbstractKernelFunction< InputType > const &kernel, Data< InputType > const &dataset, std::vector< std::pair< std::size_t, std::size_t >> const &pairs)
Constructor.
QpFloatType operator() (std::size_t i, std::size_t j) const
return a single matrix entry
QpFloatType entry (std::size_t i, std::size_t j) const
return a single matrix entry
void row (std::size_t i, std::size_t start, std::size_t end, QpFloatType *storage) const
Computes the i-th row of the kernel matrix.
template<class M >
void matrix (blas::matrix_expression< M, blas::cpu_tag > &storage) const
Computes the kernel-matrix.
void flipColumnsAndRows (std::size_t i, std::size_t j)
swap two variables
std::size_t size () const
return the size of the quadratic matrix
Protected Attributes
AbstractKernelFunction< InputType > const & m_kernel
underlying kernel function
Data< InputType > const & m_dataset
underlying set of points
std::vector< std::tuple< std::size_t, std::size_t, std::size_t, std::size_t > > m_indices
pairs of points defining the matrix components
Detailed Description
template<class InputType, class CacheType>
class shark::DifferenceKernelMatrix< InputType, CacheType >
SVM ranking matrix.
The DifferenceKernelMatrix class is kernel matrix with entries of the form \(K_{i,j} = k(g_i, g_j) - k(g_i, s_j) - k(s_i, g_j) + k(s_i, s_j) \) where for data consisting of pairs of point \((g_i, s_i) \). This matrix form is needed in SVM ranking problems.
Definition at line 64 of file DifferenceKernelMatrix.h.
Member Typedef Documentation
QpFloatType
template<class InputType, class CacheType> typedef CacheType shark::DifferenceKernelMatrix< InputType, CacheType >::QpFloatType
Definition at line 67 of file DifferenceKernelMatrix.h.
Constructor & Destructor Documentation
DifferenceKernelMatrix()
template<class InputType, class CacheType> shark::DifferenceKernelMatrix< InputType, CacheType >::DifferenceKernelMatrix (AbstractKernelFunction< InputType > const & kernel, Data< InputType > const & dataset, std::vector< std::pair< std::size_t, std::size_t >> const & pairs) inline
Constructor.
Definition at line 70 of file DifferenceKernelMatrix.h.
References shark::DataView< DatasetType >::batch(), shark::DifferenceKernelMatrix< InputType, CacheType >::m_indices, and shark::DataView< DatasetType >::positionInBatch().
Member Function Documentation
entry()
template<class InputType, class CacheType> QpFloatType shark::DifferenceKernelMatrix< InputType, CacheType >::entry (std::size_t i, std::size_t j) const inline
return a single matrix entry
Definition at line 94 of file DifferenceKernelMatrix.h.
References shark::Data< Type >::batch(), shark::getBatchElement(), shark::DifferenceKernelMatrix< InputType, CacheType >::m_dataset, shark::DifferenceKernelMatrix< InputType, CacheType >::m_indices, and shark::DifferenceKernelMatrix< InputType, CacheType >::m_kernel.
Referenced by shark::DifferenceKernelMatrix< InputType, CacheType >::matrix(), shark::DifferenceKernelMatrix< InputType, CacheType >::operator()(), and shark::DifferenceKernelMatrix< InputType, CacheType >::row().
flipColumnsAndRows()
template<class InputType, class CacheType> void shark::DifferenceKernelMatrix< InputType, CacheType >::flipColumnsAndRows (std::size_t i, std::size_t j) inline
swap two variables
Definition at line 137 of file DifferenceKernelMatrix.h.
References shark::DifferenceKernelMatrix< InputType, CacheType >::m_indices, and shark::swap().
matrix()
template<class InputType, class CacheType> template<class M > void shark::DifferenceKernelMatrix< InputType, CacheType >::matrix (blas::matrix_expression< M, blas::cpu_tag > & storage) const inline
Computes the kernel-matrix.
Definition at line 128 of file DifferenceKernelMatrix.h.
References shark::DifferenceKernelMatrix< InputType, CacheType >::entry(), and shark::DifferenceKernelMatrix< InputType, CacheType >::size().
operator()()
template<class InputType, class CacheType> QpFloatType shark::DifferenceKernelMatrix< InputType, CacheType >::operator() (std::size_t i, std::size_t j) const inline
return a single matrix entry
Definition at line 90 of file DifferenceKernelMatrix.h.
References shark::DifferenceKernelMatrix< InputType, CacheType >::entry().
row()
template<class InputType, class CacheType> void shark::DifferenceKernelMatrix< InputType, CacheType >::row (std::size_t i, std::size_t start, std::size_t end, QpFloatType * storage) const inline
Computes the i-th row of the kernel matrix.
The entries start,...,end of the i-th row are computed and stored in storage. There must be enough room for this operation preallocated.
Definition at line 122 of file DifferenceKernelMatrix.h.
References shark::DifferenceKernelMatrix< InputType, CacheType >::entry().
size()
template<class InputType, class CacheType> std::size_t shark::DifferenceKernelMatrix< InputType, CacheType >::size () const inline
return the size of the quadratic matrix
Definition at line 144 of file DifferenceKernelMatrix.h.
References shark::DifferenceKernelMatrix< InputType, CacheType >::m_indices.
Referenced by shark::DifferenceKernelMatrix< InputType, CacheType >::matrix().
Member Data Documentation
m_dataset
template<class InputType, class CacheType> Data<InputType> const& shark::DifferenceKernelMatrix< InputType, CacheType >::m_dataset protected
underlying set of points
Definition at line 152 of file DifferenceKernelMatrix.h.
Referenced by shark::DifferenceKernelMatrix< InputType, CacheType >::entry().
m_indices
template<class InputType, class CacheType> std::vector<std::tuple<std::size_t, std::size_t, std::size_t, std::size_t> > shark::DifferenceKernelMatrix< InputType, CacheType >::m_indices protected
pairs of points defining the matrix components
Definition at line 155 of file DifferenceKernelMatrix.h.
Referenced by shark::DifferenceKernelMatrix< InputType, CacheType >::DifferenceKernelMatrix(), shark::DifferenceKernelMatrix< InputType, CacheType >::entry(), shark::DifferenceKernelMatrix< InputType, CacheType >::flipColumnsAndRows(), and shark::DifferenceKernelMatrix< InputType, CacheType >::size().
m_kernel
template<class InputType, class CacheType> AbstractKernelFunction<InputType> const& shark::DifferenceKernelMatrix< InputType, CacheType >::m_kernel protected
underlying kernel function
Definition at line 149 of file DifferenceKernelMatrix.h.
Referenced by shark::DifferenceKernelMatrix< InputType, CacheType >::entry().
The documentation for this class was generated from the following file:
include/shark/LinAlg/DifferenceKernelMatrix.h