shark::AbstractLoss< LabelT, OutputT > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::AbstractLoss< LabelT, OutputT > Class Template Reference abstract
Loss Functions
Loss function interface.
#include <shark/ObjectiveFunctions/Loss/AbstractLoss.h>
Public Types
typedef OutputT OutputType
typedef LabelT LabelType
typedef RealMatrix MatrixType
typedef Batch< OutputType >::type BatchOutputType
typedef Batch< LabelType >::type BatchLabelType
typedef ConstProxyReference< LabelType const >::type ConstLabelReference
Const references to LabelType.
typedef ConstProxyReference< OutputType const >::type ConstOutputReference
Const references to OutputType.
Public Types inherited from shark::AbstractCost< LabelT, OutputT >
enum Feature { HAS_FIRST_DERIVATIVE = 1, HAS_SECOND_DERIVATIVE = 2, IS_LOSS_FUNCTION = 4 }
list of features a cost function can have
typedef OutputT OutputType
typedef LabelT LabelType
typedef Batch< OutputType >::type BatchOutputType
typedef Batch< LabelType >::type BatchLabelType
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
AbstractLoss ()
virtual double eval (BatchLabelType const &target, BatchOutputType const &prediction) const =0
evaluate the loss for a batch of targets and a prediction
virtual double eval (ConstLabelReference target, ConstOutputReference prediction) const
evaluate the loss for a target and a prediction
virtual double evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType &gradient) const
evaluate the loss and its derivative for a target and a prediction
virtual double evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType &gradient, MatrixType &hessian) const
evaluate the loss and its first and second derivative for a target and a prediction
virtual double evalDerivative (BatchLabelType const &target, BatchOutputType const &prediction, BatchOutputType &gradient) const
evaluate the loss and the derivative w.r.t. the prediction
double eval (Data< LabelType > const &targets, Data< OutputType > const &predictions) const
double operator() (LabelType const &target, OutputType const &prediction) const
evaluate the loss for a target and a prediction
double operator() (BatchLabelType const &target, BatchOutputType const &prediction) const
Public Member Functions inherited from shark::AbstractCost< LabelT, OutputT >
virtual ~AbstractCost ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstDerivative () const
returns true when the first parameter derivative is implemented
bool isLossFunction () const
returns true when the cost function is in fact a loss function
double operator() (Data< LabelType > const &targets, Data< OutputType > const &predictions) const
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
virtual std::string name () const
returns the name of the object
Additional Inherited Members
Protected Attributes inherited from shark::AbstractCost< LabelT, OutputT >
Features m_features
Detailed Description
template<class LabelT, class OutputT = LabelT>
class shark::AbstractLoss< LabelT, OutputT >
Loss function interface.
In statistics and machine learning, a loss function encodes the severity of getting a label wrong. This is am important special case of a cost function (see AbstractCost), where the cost is computed as the average loss over a set, also known as (empirical) risk.
It is generally agreed that loss values are non-negative, and that the loss of correct prediction is zero. This rule is not formally checked, but instead left to the various sub-classes.
Definition at line 62 of file AbstractLoss.h.
Member Typedef Documentation
BatchLabelType
template<class LabelT, class OutputT = LabelT> typedef Batch<LabelType>::type shark::AbstractLoss< LabelT, OutputT >::BatchLabelType
Definition at line 71 of file AbstractLoss.h.
BatchOutputType
template<class LabelT, class OutputT = LabelT> typedef Batch<OutputType>::type shark::AbstractLoss< LabelT, OutputT >::BatchOutputType
Definition at line 70 of file AbstractLoss.h.
ConstLabelReference
template<class LabelT, class OutputT = LabelT> typedef ConstProxyReference<LabelType const>::type shark::AbstractLoss< LabelT, OutputT >::ConstLabelReference
Const references to LabelType.
Definition at line 74 of file AbstractLoss.h.
ConstOutputReference
template<class LabelT, class OutputT = LabelT> typedef ConstProxyReference<OutputType const>::type shark::AbstractLoss< LabelT, OutputT >::ConstOutputReference
Const references to OutputType.
Definition at line 76 of file AbstractLoss.h.
LabelType
template<class LabelT, class OutputT = LabelT> typedef LabelT shark::AbstractLoss< LabelT, OutputT >::LabelType
Definition at line 67 of file AbstractLoss.h.
MatrixType
template<class LabelT, class OutputT = LabelT> typedef RealMatrix shark::AbstractLoss< LabelT, OutputT >::MatrixType
Definition at line 68 of file AbstractLoss.h.
OutputType
template<class LabelT, class OutputT = LabelT> typedef OutputT shark::AbstractLoss< LabelT, OutputT >::OutputType
Definition at line 66 of file AbstractLoss.h.
Constructor & Destructor Documentation
AbstractLoss()
template<class LabelT, class OutputT = LabelT> shark::AbstractLoss< LabelT, OutputT >::AbstractLoss () inline
Definition at line 78 of file AbstractLoss.h.
Member Function Documentation
eval() [1/3]
template<class LabelT, class OutputT = LabelT> virtual double shark::AbstractLoss< LabelT, OutputT >::eval (BatchLabelType const & target, BatchOutputType const & prediction) const pure virtual
evaluate the loss for a batch of targets and a prediction
Parameters
target target values
prediction predictions, typically made by a model
Implemented in shark::SquaredLoss< Sequence, Sequence >, shark::ZeroOneLoss< unsigned int, blas::vector< Float > >, shark::SquaredLoss< OutputType, unsigned int >, shark::HingeLoss, shark::SquaredHingeLoss, shark::AbsoluteLoss< VectorType >, shark::DiscreteLoss, shark::ZeroOneLoss< LabelType, OutputType >, shark::SquaredLoss< OutputType, LabelType >, shark::EpsilonHingeLoss, shark::SquaredEpsilonHingeLoss, and shark::HuberLoss.
Referenced by shark::AbstractLoss< unsigned int, RealVector >::eval(), and shark::AbstractLoss< unsigned int, RealVector >::operator()().
eval() [2/3]
template<class LabelT, class OutputT = LabelT> virtual double shark::AbstractLoss< LabelT, OutputT >::eval (ConstLabelReference target, ConstOutputReference prediction) const inline virtual
evaluate the loss for a target and a prediction
Parameters
target target value
prediction prediction, typically made by a model
Reimplemented in shark::CrossEntropy< unsigned int, OutputType >.
Definition at line 92 of file AbstractLoss.h.
eval() [3/3]
template<class LabelT, class OutputT = LabelT> double shark::AbstractLoss< LabelT, OutputT >::eval (Data< LabelType > const & targets, Data< OutputType > const & predictions) const inline virtual
from AbstractCost
Parameters
targets target values
predictions predictions, typically made by a model
Implements shark::AbstractCost< LabelT, OutputT >.
Definition at line 149 of file AbstractLoss.h.
evalDerivative() [1/3]
template<class LabelT, class OutputT = LabelT> virtual double shark::AbstractLoss< LabelT, OutputT >::evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType & gradient) const inline virtual
evaluate the loss and its derivative for a target and a prediction
Parameters
target target value
prediction prediction, typically made by a model
gradient the gradient of the loss function with respect to the prediction
Reimplemented in shark::CrossEntropy< unsigned int, OutputType >.
Definition at line 105 of file AbstractLoss.h.
Referenced by shark::AbstractLoss< unsigned int, RealVector >::evalDerivative().
evalDerivative() [2/3]
template<class LabelT, class OutputT = LabelT> virtual double shark::AbstractLoss< LabelT, OutputT >::evalDerivative (ConstLabelReference target, ConstOutputReference prediction, OutputType & gradient, MatrixType & hessian) const inline virtual
evaluate the loss and its first and second derivative for a target and a prediction
Parameters
target target value
prediction prediction, typically made by a model
gradient the gradient of the loss function with respect to the prediction
hessian the hessian of the loss function with respect to the prediction
Definition at line 122 of file AbstractLoss.h.
evalDerivative() [3/3]
template<class LabelT, class OutputT = LabelT> virtual double shark::AbstractLoss< LabelT, OutputT >::evalDerivative (BatchLabelType const & target, BatchOutputType const & prediction, BatchOutputType & gradient) const inline virtual
evaluate the loss and the derivative w.r.t. the prediction
The default implementations throws an exception. If you overwrite this method, don't forget to set the flag HAS_FIRST_DERIVATIVE.
Parameters
target target value
prediction prediction, typically made by a model
gradient the gradient of the loss function with respect to the prediction
Reimplemented in shark::SquaredLoss< Sequence, Sequence >, shark::SquaredLoss< OutputType, unsigned int >, shark::HingeLoss, shark::SquaredHingeLoss, shark::HuberLoss, shark::SquaredLoss< OutputType, LabelType >, shark::SquaredEpsilonHingeLoss, and shark::EpsilonHingeLoss.
Definition at line 139 of file AbstractLoss.h.
operator()() [1/2]
template<class LabelT, class OutputT = LabelT> double shark::AbstractLoss< LabelT, OutputT >::operator() (LabelType const & target, OutputType const & prediction) const inline
evaluate the loss for a target and a prediction
convenience operator
Parameters
target target value
prediction prediction, typically made by a model
Definition at line 170 of file AbstractLoss.h.
operator()() [2/2]
template<class LabelT, class OutputT = LabelT> double shark::AbstractLoss< LabelT, OutputT >::operator() (BatchLabelType const & target, BatchOutputType const & prediction) const inline
Definition at line 173 of file AbstractLoss.h.
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/Loss/AbstractLoss.h