shark::benchmarks::CigarDiscus Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::benchmarks::CigarDiscus Class Reference
Objective functions » Benchmark functions
Convex quadratic benchmark function.
#include <shark/ObjectiveFunctions/Benchmarks/CigarDiscus.h>
Public Member Functions
CigarDiscus (std::size_t numberOfVariables=5, double alpha=1E-3)
std::string name () const
From INameable: return the class name.
std::size_t numberOfVariables () const
Accesses the number of variables.
bool hasScalableDimensionality () const
void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
double eval (const SearchPointType &p) const
Evaluates the objective function for the supplied argument.
double alpha () const
void setAlpha (double alpha)
Public Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
virtual void init ()
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual std::size_t numberOfObjectives () const
virtual bool hasScalableObjectives () const
virtual void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Public Types inherited from shark::AbstractObjectiveFunction< RealVector, double >
enum Feature
List of features that are supported by an implementation.
typedef RealVector SearchPointType
typedef double ResultType
typedef boost::mpl::if_< std::is_arithmetic< double >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Protected Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< RealVector, double >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
Convex quadratic benchmark function.
Definition at line 43 of file CigarDiscus.h.
Constructor & Destructor Documentation
CigarDiscus()
shark::benchmarks::CigarDiscus::CigarDiscus (std::size_t numberOfVariables = 5, double alpha = 1E-3) inline
Definition at line 46 of file CigarDiscus.h.
References shark::AbstractObjectiveFunction< RealVector, double >::CAN_PROPOSE_STARTING_POINT, shark::AbstractObjectiveFunction< RealVector, double >::m_features, and numberOfVariables().
Member Function Documentation
alpha()
double shark::benchmarks::CigarDiscus::alpha () const inline
Definition at line 89 of file CigarDiscus.h.
Referenced by setAlpha().
eval()
double shark::benchmarks::CigarDiscus::eval (const SearchPointType & input) const inline virtual
Evaluates the objective function for the supplied argument.
Parameters
[in] input The argument for which the function shall be evaluated.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 78 of file CigarDiscus.h.
References shark::AbstractObjectiveFunction< RealVector, double >::m_evaluationCounter.
hasScalableDimensionality()
bool shark::benchmarks::CigarDiscus::hasScalableDimensionality () const inline virtual
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 59 of file CigarDiscus.h.
name()
std::string shark::benchmarks::CigarDiscus::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 52 of file CigarDiscus.h.
numberOfVariables()
std::size_t shark::benchmarks::CigarDiscus::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 55 of file CigarDiscus.h.
Referenced by CigarDiscus(), proposeStartingPoint(), and setNumberOfVariables().
proposeStartingPoint()
SearchPointType shark::benchmarks::CigarDiscus::proposeStartingPoint () const inline virtual
Proposes a starting point in the feasible search space of the function.
Returns
The generated starting point.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 69 of file CigarDiscus.h.
References shark::AbstractObjectiveFunction< RealVector, double >::mep_rng, numberOfVariables(), and shark::random::uni().
setAlpha()
void shark::benchmarks::CigarDiscus::setAlpha (double alpha) inline
Definition at line 93 of file CigarDiscus.h.
References alpha().
setNumberOfVariables()
void shark::benchmarks::CigarDiscus::setNumberOfVariables (std::size_t numberOfVariables) inline virtual
Adjusts the number of variables if the function is scalable.
Parameters
[in] numberOfVariables The new dimension.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 65 of file CigarDiscus.h.
References numberOfVariables().
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/Benchmarks/CigarDiscus.h