shark::MultiChainApproximator< MarkovChainType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::MultiChainApproximator< MarkovChainType > Class Template Reference
Approximates the gradient by taking samples from an ensemble of Markov chains running in parallel.
#include <shark/Unsupervised/RBM/GradientApproximations/MultiChainApproximator.h>
Public Types
typedef MarkovChainType::RBM RBM
Public Types inherited from shark::AbstractObjectiveFunction< RealVector, double >
enum Feature
List of features that are supported by an implementation.
typedef RealVector SearchPointType
typedef double ResultType
typedef boost::mpl::if_< std::is_arithmetic< double >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
MultiChainApproximator (RBM *rbm)
std::string name () const
From INameable: return the class name.
void setK (unsigned int k)
void setNumberOfSamples (std::size_t samples)
void setBatchSize (std::size_t batchSize)
MarkovChainType & chain ()
MarkovChainType const & chain () const
std::size_t numBatches () const
Returns the number of batches of the dataset that are used in every iteration.
std::size_t & numBatches ()
Returns a reference to the number of batches of the dataset that are used in every iteration.
void setData (UnlabeledData< RealVector > const &data)
SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
std::size_t numberOfVariables () const
Accesses the number of variables.
void setRegularizer (double factor, SingleObjectiveFunction *regularizer)
double evalDerivative (SearchPointType const &parameter, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
virtual void init ()
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual bool hasScalableDimensionality () const
virtual void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
virtual std::size_t numberOfObjectives () const
virtual bool hasScalableObjectives () const
virtual void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
virtual ResultType eval (SearchPointType const &input) const
Evaluates the objective function for the supplied argument.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Protected Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< RealVector, double >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
template<class MarkovChainType>
class shark::MultiChainApproximator< MarkovChainType >
Approximates the gradient by taking samples from an ensemble of Markov chains running in parallel.
The advantage is, that every chain can produce samples of a different mode of the distribution. The disadvantage is however, that mixing is slower and a higher value of sampling steps between subsequent samples need to be chosen.
Definition at line 44 of file MultiChainApproximator.h.
Member Typedef Documentation
RBM
template<class MarkovChainType > typedef MarkovChainType::RBM shark::MultiChainApproximator< MarkovChainType >::RBM
Definition at line 46 of file MultiChainApproximator.h.
Constructor & Destructor Documentation
MultiChainApproximator()
template<class MarkovChainType > shark::MultiChainApproximator< MarkovChainType >::MultiChainApproximator (RBM * rbm) inline
Definition at line 48 of file MultiChainApproximator.h.
References shark::AbstractObjectiveFunction< RealVector, double >::CAN_PROPOSE_STARTING_POINT, shark::AbstractObjectiveFunction< RealVector, double >::HAS_FIRST_DERIVATIVE, shark::AbstractObjectiveFunction< RealVector, double >::HAS_VALUE, shark::AbstractObjectiveFunction< RealVector, double >::m_features, shark::TypedFlags< Flag >::reset(), shark::MultiChainApproximator< MarkovChainType >::setBatchSize(), and SHARK_ASSERT.
Member Function Documentation
chain() [1/2]
template<class MarkovChainType > MarkovChainType& shark::MultiChainApproximator< MarkovChainType >::chain () inline
Definition at line 74 of file MultiChainApproximator.h.
chain() [2/2]
template<class MarkovChainType > MarkovChainType const& shark::MultiChainApproximator< MarkovChainType >::chain () const inline
Definition at line 77 of file MultiChainApproximator.h.
evalDerivative()
template<class MarkovChainType > double shark::MultiChainApproximator< MarkovChainType >::evalDerivative (SearchPointType const & input, FirstOrderDerivative & derivative) const inline virtual
Evaluates the objective function and calculates its gradient.
Parameters
[in] input The argument to eval the function for.
[out] derivative The derivate is placed here.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 136 of file MultiChainApproximator.h.
References shark::swap().
name()
template<class MarkovChainType > std::string shark::MultiChainApproximator< MarkovChainType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 59 of file MultiChainApproximator.h.
numBatches() [1/2]
template<class MarkovChainType > std::size_t shark::MultiChainApproximator< MarkovChainType >::numBatches () const inline
Returns the number of batches of the dataset that are used in every iteration.
If it is less than all batches, the batches are chosen at random. if it is 0, all batches are used
Definition at line 84 of file MultiChainApproximator.h.
numBatches() [2/2]
template<class MarkovChainType > std::size_t& shark::MultiChainApproximator< MarkovChainType >::numBatches () inline
Returns a reference to the number of batches of the dataset that are used in every iteration.
If it is less than all batches, the batches are chosen at random.if it is 0, all batches are used.
Definition at line 91 of file MultiChainApproximator.h.
numberOfVariables()
template<class MarkovChainType > std::size_t shark::MultiChainApproximator< MarkovChainType >::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 127 of file MultiChainApproximator.h.
proposeStartingPoint()
template<class MarkovChainType > SearchPointType shark::MultiChainApproximator< MarkovChainType >::proposeStartingPoint () const inline virtual
Proposes a starting point in the feasible search space of the function.
Returns
The generated starting point.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 123 of file MultiChainApproximator.h.
setBatchSize()
template<class MarkovChainType > void shark::MultiChainApproximator< MarkovChainType >::setBatchSize (std::size_t batchSize) inline
Definition at line 68 of file MultiChainApproximator.h.
References shark::batchSize().
Referenced by shark::MultiChainApproximator< MarkovChainType >::MultiChainApproximator().
setData()
template<class MarkovChainType > void shark::MultiChainApproximator< MarkovChainType >::setData (UnlabeledData< RealVector > const & data) inline
Definition at line 95 of file MultiChainApproximator.h.
References shark::Data< Type >::numberOfElements(), shark::MultiChainApproximator< MarkovChainType >::setNumberOfSamples(), and shark::swap().
setK()
template<class MarkovChainType > void shark::MultiChainApproximator< MarkovChainType >::setK (unsigned int k) inline
Definition at line 62 of file MultiChainApproximator.h.
setNumberOfSamples()
template<class MarkovChainType > void shark::MultiChainApproximator< MarkovChainType >::setNumberOfSamples (std::size_t samples) inline
Definition at line 65 of file MultiChainApproximator.h.
Referenced by shark::MultiChainApproximator< MarkovChainType >::setData().
setRegularizer()
template<class MarkovChainType > void shark::MultiChainApproximator< MarkovChainType >::setRegularizer (double factor, SingleObjectiveFunction * regularizer) inline
Definition at line 131 of file MultiChainApproximator.h.
The documentation for this class was generated from the following file:
include/shark/Unsupervised/RBM/GradientApproximations/MultiChainApproximator.h