shark::ISerializable Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::ISerializable Class Reference
Abstracts serializing functionality.
#include <shark/Core/ISerializable.h>
Public Member Functions
virtual ~ISerializable ()
Virtual d'tor.
virtual void read (InArchive &archive)
Read the component from the supplied archive.
virtual void write (OutArchive &archive) const
Write the component to the supplied archive.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Detailed Description
Abstracts serializing functionality.
In order to integrate alien serialization libraries with the components based on this interface, the classes boost::archive::polymorphic_iarchive and boost::archive::polymorphic_oarchive need to be implemented in terms of alien serialization library.
Definition at line 91 of file ISerializable.h.
Constructor & Destructor Documentation
~ISerializable()
virtual shark::ISerializable::~ISerializable () inline virtual
Virtual d'tor.
Definition at line 96 of file ISerializable.h.
Member Function Documentation
BOOST_SERIALIZATION_SPLIT_MEMBER()
shark::ISerializable::BOOST_SERIALIZATION_SPLIT_MEMBER ()
load()
void shark::ISerializable::load (InArchive & archive, unsigned int version) inline
Versioned loading of components, calls read(...).
Definition at line 115 of file ISerializable.h.
References read().
read()
virtual void shark::ISerializable::read (InArchive & archive) inline virtual
Read the component from the supplied archive.
Parameters
[in,out] archive The archive to read from.
Reimplemented in shark::LabeledData< InputT, LabelT >, shark::LabeledData< InputType, unsigned int >, shark::LabeledData< InputType, LabelType >, shark::PointSearch, shark::NestedGridSearch, shark::NeuronLayer< NeuronType, VectorType >, shark::WeightedSumKernel< InputType >, shark::LinearModel< InputType, ActivationFunction >, shark::LinearModel< VectorType >, shark::BinaryLayer, shark::RBM< VisibleLayerT, HiddenLayerT, randomT >, shark::PolynomialKernel< InputType >, shark::Conv2DModel< VectorType, ActivationFunction >, shark::ConcatenatedModel< VectorType >, shark::BipolarLayer, shark::KernelExpansion< InputType >, shark::Data< Type >, shark::Data< SearchPointType >, shark::Data< RealVector >, shark::Data< LabelType >, shark::Data< shark::MultiTaskSample >, shark::Data< InputT >, shark::Data< unsigned int >, shark::Data< InputType >, shark::Data< LabelT >, shark::GaussianLayer, shark::ARDKernelUnconstrained< InputType >, shark::CSvmDerivative< InputType, CacheType >, shark::GaussianTaskKernel< InputTypeT >, shark::GridSearch, shark::OneVersusOneClassifier< InputType, VectorType >, shark::ResizeLayer< VectorType >, shark::MonomialKernel< InputType >, shark::AbstractClustering< InputT >, shark::AbstractClustering< RealVector >, shark::PoolingLayer< VectorType >, shark::Classifier< Model >, shark::Classifier< detail::BaseNearestNeighbor< InputType, unsigned int > >, shark::Classifier< LinearModel< VectorType > >, shark::Classifier< detail::EnsembleImpl< BaseModelType, std::remove_pointer< BaseModelType >::type::ParameterVectorType > >, shark::Classifier< KernelExpansion< InputType > >, shark::ProductKernel< InputType >, shark::ProductKernel< MultiTaskSample< InputTypeT > >, shark::DropoutLayer< VectorType >, shark::RBFLayer, shark::Normalizer< VectorType >, shark::Rprop< SearchPointType >, shark::CMACMap, shark::Adam< SearchPointType >, shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >, shark::ScaledKernel< InputType >, shark::AbstractModel< InputType, RealVector >, shark::AbstractModel< std::remove_pointer< CARTree< LabelType > >::type::InputType, void, std::remove_pointer< CARTree< LabelType > >::type::ParameterVectorType >, shark::AbstractModel< InputType, unsigned int, VectorType >, shark::AbstractModel< KernelExpansion< InputType > ::InputType, unsigned int, KernelExpansion< InputType > ::ParameterVectorType >, shark::AbstractModel< InputT, OutputT >, shark::AbstractModel< RealVector, RealVector >, shark::AbstractModel< std::remove_pointer< BaseModelType >::type::InputType, VectorType, std::remove_pointer< BaseModelType >::type::ParameterVectorType >, shark::AbstractModel< VectorType, blas::vector< VectorType ::value_type, VectorType ::device_type >, blas::vector< VectorType ::value_type, VectorType ::device_type > >, shark::AbstractModel< LinearModel< VectorType > ::InputType, unsigned int, LinearModel< VectorType > ::ParameterVectorType >, shark::AbstractModel< std::remove_pointer< ModelType >::type::InputType, OutputType, std::remove_pointer< ModelType >::type::ParameterVectorType >, shark::AbstractModel< VectorType, VectorType >, shark::AbstractModel< std::remove_pointer< ModelType >::type::InputType, std::remove_pointer< ModelType >::type::OutputType, std::remove_pointer< ModelType >::type::ParameterVectorType >, shark::AbstractModel< detail::BaseNearestNeighbor< InputType, unsigned int > ::InputType, unsigned int, detail::BaseNearestNeighbor< InputType, unsigned int > ::ParameterVectorType >, shark::AbstractModel< RealVector, LabelType >, shark::AbstractModel< detail::EnsembleImpl< BaseModelType, std::remove_pointer< BaseModelType >::type::ParameterVectorType > ::InputType, unsigned int, detail::EnsembleImpl< BaseModelType, std::remove_pointer< BaseModelType >::type::ParameterVectorType > ::ParameterVectorType >, shark::AbstractModel< std::remove_pointer< BaseModelType >::type::InputType, std::remove_pointer< BaseModelType >::type::ParameterVectorType, std::remove_pointer< BaseModelType >::type::ParameterVectorType >, shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >, shark::AbstractModel< InputType, blas::vector< InputType::value_type, InputType::device_type >, blas::vector< InputType::value_type, InputType::device_type > >, shark::AbstractModel< VectorType, VectorType, VectorType >, shark::AbstractModel< InputT, RealVector >, shark::AbstractModel< InputT, unsigned int >, shark::DiscreteKernel, shark::CARTree< LabelType >, shark::GaussianRbfKernel< InputType >, shark::IndicatorBasedRealCodedNSGAII< Indicator >, shark::LinearKernel< InputType >, shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >, shark::CrossEntropyMethod, shark::TypedFlags< Flag >, shark::TypedFlags< Feature >, shark::Centroids, shark::LineSearch< SearchPointType >, shark::IndicatorBasedSteadyStateMOCMA< Indicator >, shark::SMSEMOA, shark::SteepestDescent< SearchPointType >, shark::OptimizationTrainer< Model, LabelTypeT >, shark::IndicatorBasedMOCMA< Indicator >, shark::LBFGS< SearchPointType >, shark::CMA, shark::CMSA, shark::AbstractLineSearchOptimizer< SearchPointType >, shark::ElitistCMA, shark::ClusteringModel< InputT, OutputT >, shark::ClusteringModel< InputT, RealVector >, shark::ClusteringModel< InputT, unsigned int >, shark::SimplexDownhill, shark::CG< SearchPointType >, shark::MultiTaskSample< InputTypeT >, shark::AbstractMetric< InputTypeT >, shark::AbstractMetric< Batch< InputType >::type >, shark::AbstractMetric< std::size_t >, shark::AbstractMetric< InputType >, shark::AbstractMetric< MultiTaskSample< InputTypeT > >, and shark::BFGS< SearchPointType >.
Definition at line 102 of file ISerializable.h.
Referenced by load().
save()
void shark::ISerializable::save (OutArchive & archive, unsigned int version) const inline
Versioned storing of components, calls write(...).
Definition at line 124 of file ISerializable.h.
References write().
write()
virtual void shark::ISerializable::write (OutArchive & archive) const inline virtual
Write the component to the supplied archive.
Parameters
[in,out] archive The archive to write to.
Reimplemented in shark::LabeledData< InputT, LabelT >, shark::LabeledData< InputType, unsigned int >, shark::LabeledData< InputType, LabelType >, shark::PointSearch, shark::NestedGridSearch, shark::NeuronLayer< NeuronType, VectorType >, shark::WeightedSumKernel< InputType >, shark::LinearModel< InputType, ActivationFunction >, shark::LinearModel< VectorType >, shark::BinaryLayer, shark::RBM< VisibleLayerT, HiddenLayerT, randomT >, shark::Conv2DModel< VectorType, ActivationFunction >, shark::PolynomialKernel< InputType >, shark::ConcatenatedModel< VectorType >, shark::BipolarLayer, shark::KernelExpansion< InputType >, shark::Data< Type >, shark::Data< SearchPointType >, shark::Data< RealVector >, shark::Data< LabelType >, shark::Data< shark::MultiTaskSample >, shark::Data< InputT >, shark::Data< unsigned int >, shark::Data< InputType >, shark::Data< LabelT >, shark::ModelKernel< InputType >, shark::GaussianLayer, shark::ARDKernelUnconstrained< InputType >, shark::CSvmDerivative< InputType, CacheType >, shark::GaussianTaskKernel< InputTypeT >, shark::GridSearch, shark::OneVersusOneClassifier< InputType, VectorType >, shark::ResizeLayer< VectorType >, shark::MonomialKernel< InputType >, shark::AbstractClustering< InputT >, shark::PoolingLayer< VectorType >, shark::AbstractClustering< RealVector >, shark::ProductKernel< InputType >, shark::ProductKernel< MultiTaskSample< InputTypeT > >, shark::Classifier< Model >, shark::Classifier< detail::BaseNearestNeighbor< InputType, unsigned int > >, shark::Classifier< LinearModel< VectorType > >, shark::Classifier< detail::EnsembleImpl< BaseModelType, std::remove_pointer< BaseModelType >::type::ParameterVectorType > >, shark::Classifier< KernelExpansion< InputType > >, shark::DropoutLayer< VectorType >, shark::Normalizer< VectorType >, shark::RBFLayer, shark::Adam< SearchPointType >, shark::Rprop< SearchPointType >, shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >, shark::AbstractModel< InputType, RealVector >, shark::AbstractModel< std::remove_pointer< CARTree< LabelType > >::type::InputType, void, std::remove_pointer< CARTree< LabelType > >::type::ParameterVectorType >, shark::AbstractModel< InputType, unsigned int, VectorType >, shark::AbstractModel< KernelExpansion< InputType > ::InputType, unsigned int, KernelExpansion< InputType > ::ParameterVectorType >, shark::AbstractModel< InputT, OutputT >, shark::AbstractModel< RealVector, RealVector >, shark::AbstractModel< std::remove_pointer< BaseModelType >::type::InputType, VectorType, std::remove_pointer< BaseModelType >::type::ParameterVectorType >, shark::AbstractModel< VectorType, blas::vector< VectorType ::value_type, VectorType ::device_type >, blas::vector< VectorType ::value_type, VectorType ::device_type > >, shark::AbstractModel< LinearModel< VectorType > ::InputType, unsigned int, LinearModel< VectorType > ::ParameterVectorType >, shark::AbstractModel< std::remove_pointer< ModelType >::type::InputType, OutputType, std::remove_pointer< ModelType >::type::ParameterVectorType >, shark::AbstractModel< VectorType, VectorType >, shark::AbstractModel< std::remove_pointer< ModelType >::type::InputType, std::remove_pointer< ModelType >::type::OutputType, std::remove_pointer< ModelType >::type::ParameterVectorType >, shark::AbstractModel< detail::BaseNearestNeighbor< InputType, unsigned int > ::InputType, unsigned int, detail::BaseNearestNeighbor< InputType, unsigned int > ::ParameterVectorType >, shark::AbstractModel< RealVector, LabelType >, shark::AbstractModel< detail::EnsembleImpl< BaseModelType, std::remove_pointer< BaseModelType >::type::ParameterVectorType > ::InputType, unsigned int, detail::EnsembleImpl< BaseModelType, std::remove_pointer< BaseModelType >::type::ParameterVectorType > ::ParameterVectorType >, shark::AbstractModel< std::remove_pointer< BaseModelType >::type::InputType, std::remove_pointer< BaseModelType >::type::ParameterVectorType, std::remove_pointer< BaseModelType >::type::ParameterVectorType >, shark::AbstractModel< Model::InputType, unsigned int, Model::ParameterVectorType >, shark::AbstractModel< InputType, blas::vector< InputType::value_type, InputType::device_type >, blas::vector< InputType::value_type, InputType::device_type > >, shark::AbstractModel< VectorType, VectorType, VectorType >, shark::AbstractModel< InputT, RealVector >, shark::AbstractModel< InputT, unsigned int >, shark::ScaledKernel< InputType >, shark::CMACMap, shark::CARTree< LabelType >, shark::DiscreteKernel, shark::IndicatorBasedRealCodedNSGAII< Indicator >, shark::GaussianRbfKernel< InputType >, shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >, shark::LinearKernel< InputType >, shark::CrossEntropyMethod, shark::TypedFlags< Flag >, shark::TypedFlags< Feature >, shark::IndicatorBasedSteadyStateMOCMA< Indicator >, shark::SMSEMOA, shark::LineSearch< SearchPointType >, shark::Centroids, shark::IndicatorBasedMOCMA< Indicator >, shark::SteepestDescent< SearchPointType >, shark::OptimizationTrainer< Model, LabelTypeT >, shark::LBFGS< SearchPointType >, shark::CMA, shark::CMSA, shark::AbstractLineSearchOptimizer< SearchPointType >, shark::ClusteringModel< InputT, OutputT >, shark::ClusteringModel< InputT, RealVector >, shark::ClusteringModel< InputT, unsigned int >, shark::ElitistCMA, shark::SimplexDownhill, shark::AbstractMetric< InputTypeT >, shark::AbstractMetric< Batch< InputType >::type >, shark::AbstractMetric< std::size_t >, shark::AbstractMetric< InputType >, shark::AbstractMetric< MultiTaskSample< InputTypeT > >, shark::CG< SearchPointType >, shark::MultiTaskSample< InputTypeT >, and shark::BFGS< SearchPointType >.
Definition at line 109 of file ISerializable.h.
Referenced by save().
The documentation for this class was generated from the following file:
include/shark/Core/ISerializable.h