shark::OneNormRegularizer< SearchPointType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::OneNormRegularizer< SearchPointType > Class Template Reference
Objective functions
One-norm of the input as an objective function.
#include <shark/ObjectiveFunctions/Regularizer.h>
Public Member Functions
OneNormRegularizer (std::size_t numVariables=0)
Constructor.
std::string name () const
From INameable: return the class name.
std::size_t numberOfVariables () const
Accesses the number of variables.
bool hasScalableDimensionality () const
void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
void setMask (SearchPointType const &mask)
SearchPointType const & mask () const
double eval (SearchPointType const &input) const
Evaluates the objective function.
double evalDerivative (SearchPointType const &input, SearchPointType &derivative) const
Public Member Functions inherited from shark::AbstractObjectiveFunction< SearchPointType, double >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
virtual void init ()
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual std::size_t numberOfObjectives () const
virtual bool hasScalableObjectives () const
virtual void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
virtual SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Public Types inherited from shark::AbstractObjectiveFunction< SearchPointType, double >
enum Feature
List of features that are supported by an implementation.
typedef SearchPointType SearchPointType
typedef double ResultType
typedef boost::mpl::if_< std::is_arithmetic< double >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Protected Member Functions inherited from shark::AbstractObjectiveFunction< SearchPointType, double >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< SearchPointType, double >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
template<class SearchPointType = RealVector>
class shark::OneNormRegularizer< SearchPointType >
One-norm of the input as an objective function.
The OneNormRegularizer is intended to be used together with other objective functions within a CombinedObjectiveFunction, in order to obtain a more smooth and more sparse solution.
Definition at line 52 of file Regularizer.h.
Constructor & Destructor Documentation
OneNormRegularizer()
template<class SearchPointType = RealVector> shark::OneNormRegularizer< SearchPointType >::OneNormRegularizer (std::size_t numVariables = 0) inline
Constructor.
Definition at line 57 of file Regularizer.h.
References shark::AbstractObjectiveFunction< SearchPointType, double >::HAS_FIRST_DERIVATIVE, and shark::AbstractObjectiveFunction< SearchPointType, double >::m_features.
Member Function Documentation
eval()
template<class SearchPointType = RealVector> double shark::OneNormRegularizer< SearchPointType >::eval (SearchPointType const & input) const inline virtual
Evaluates the objective function.
Reimplemented from shark::AbstractObjectiveFunction< SearchPointType, double >.
Definition at line 84 of file Regularizer.h.
Referenced by shark::OneNormRegularizer< SearchPointType >::evalDerivative().
evalDerivative()
template<class SearchPointType = RealVector> double shark::OneNormRegularizer< SearchPointType >::evalDerivative (SearchPointType const & input, SearchPointType & derivative) const inline
Evaluates the objective function and calculates its gradient.
Definition at line 94 of file Regularizer.h.
References shark::OneNormRegularizer< SearchPointType >::eval(), and SIZE_CHECK.
hasScalableDimensionality()
template<class SearchPointType = RealVector> bool shark::OneNormRegularizer< SearchPointType >::hasScalableDimensionality () const inline virtual
Reimplemented from shark::AbstractObjectiveFunction< SearchPointType, double >.
Definition at line 69 of file Regularizer.h.
mask()
template<class SearchPointType = RealVector> SearchPointType const& shark::OneNormRegularizer< SearchPointType >::mask () const inline
Definition at line 80 of file Regularizer.h.
Referenced by shark::OneNormRegularizer< SearchPointType >::setMask().
name()
template<class SearchPointType = RealVector> std::string shark::OneNormRegularizer< SearchPointType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 62 of file Regularizer.h.
numberOfVariables()
template<class SearchPointType = RealVector> std::size_t shark::OneNormRegularizer< SearchPointType >::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< SearchPointType, double >.
Definition at line 65 of file Regularizer.h.
Referenced by shark::OneNormRegularizer< SearchPointType >::setNumberOfVariables().
setMask()
template<class SearchPointType = RealVector> void shark::OneNormRegularizer< SearchPointType >::setMask (SearchPointType const & mask) inline
Definition at line 77 of file Regularizer.h.
References shark::OneNormRegularizer< SearchPointType >::mask().
setNumberOfVariables()
template<class SearchPointType = RealVector> void shark::OneNormRegularizer< SearchPointType >::setNumberOfVariables (std::size_t numberOfVariables) inline virtual
Adjusts the number of variables if the function is scalable.
Parameters
[in] numberOfVariables The new dimension.
Reimplemented from shark::AbstractObjectiveFunction< SearchPointType, double >.
Definition at line 73 of file Regularizer.h.
References shark::OneNormRegularizer< SearchPointType >::numberOfVariables().
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/Regularizer.h