shark::KHCTree< Container, CuttingAccuracy > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::KHCTree< Container, CuttingAccuracy > Class Template Reference
Models » Space Partitioning Trees
KHC-tree, a binary space-partitioning tree.
#include <shark/Models/Trees/KHCTree.h>
Public Types
typedef IndexedIterator< typename boost::range_iterator< Container const >::type > const_iterator
Public Member Functions
KHCTree (Container const &points, kernel_type const *kernel, TreeConstruction tc=TreeConstruction())
double squaredDistanceLowerBound (value_type const &reference) const
Protected Member Functions
KHCTree (KHCTree *parent, std::size_t *list, std::size_t size)
(internal) construction of a non-root node
template<class Range >
void buildTree (TreeConstruction tc, Range &points)
template<class Range >
void calculateNormal (Range const &samples)
double funct (value_type const &reference) const
function describing the separating hyperplane
Protected Attributes
kernel_type const * mep_kernel
kernel function
const_iterator mep_positive
"positive" side cluster center
const_iterator mep_negative
"negative" side cluster center
double m_normalInvNorm
one divided by squared distance between "positive" and "negative" cluster center
BinaryTree * mep_parent
parent node
BinaryTree * mp_left
"left" child node
BinaryTree * mp_right
"right" child node
std::size_t * mp_indexList
list of indices to points in the dataset
std::size_t m_size
number of points in this node
std::size_t m_nodes
number of nodes in the sub-tree represented by this node
Detailed Description
template<class Container, int CuttingAccuracy = 25>
class shark::KHCTree< Container, CuttingAccuracy >
KHC-tree, a binary space-partitioning tree.
KHC-tree data structure for efficient nearest neighbor searches in kernel-induced feature spaces. "KHC" stands for Kernel Hierarchical Clustering. The space separation is based on distances to cluster centers.
The tree is constructed from data by splitting along the pair of data points with largest distance. This quantity is approximated using a given number of randomly sampled pairs, which is controlled by the template parameter CuttingAccuracy.
The bucket size for the tree is always one, such that there is a unique point in each leaf cell.
Since the KHCTree needs direct access to the elements, it's template parameter is not the actual point type But the Range, the points are stored in. Be aware that this range should be a View when a Dataset is used as storage, since during construction, the KHC-Tree needs random access to the elements.
Definition at line 75 of file KHCTree.h.
Member Typedef Documentation
const_iterator
template<class Container , int CuttingAccuracy = 25> typedef IndexedIterator<typename boost::range_iterator<Container const>::type> shark::KHCTree< Container, CuttingAccuracy >::const_iterator
Definition at line 78 of file KHCTree.h.
Constructor & Destructor Documentation
KHCTree() [1/2]
template<class Container , int CuttingAccuracy = 25> shark::KHCTree< Container, CuttingAccuracy >::KHCTree (Container const & points, kernel_type const * kernel, TreeConstruction tc = TreeConstruction()) inline
Construct the tree from data. It is assumed that the container exceeds the lifetime of the KHCTree (which holds only references to the points), and that the memory locations of the points remain unchanged.
Definition at line 89 of file KHCTree.h.
References shark::KHCTree< Container, CuttingAccuracy >::buildTree(), shark::BinaryTree< Container::value_type >::m_size, and shark::BinaryTree< Container::value_type >::mp_indexList.
KHCTree() [2/2]
template<class Container , int CuttingAccuracy = 25> shark::KHCTree< Container, CuttingAccuracy >::KHCTree (KHCTree< Container, CuttingAccuracy > * parent, std::size_t * list, std::size_t size) inline protected
(internal) construction of a non-root node
Definition at line 138 of file KHCTree.h.
Member Function Documentation
buildTree()
template<class Container , int CuttingAccuracy = 25> template<class Range > void shark::KHCTree< Container, CuttingAccuracy >::buildTree (TreeConstruction tc, Range & points) inline protected
(internal) construction method: median-cuts of the dimension with widest spread
Definition at line 147 of file KHCTree.h.
References shark::KHCTree< Container, CuttingAccuracy >::calculateNormal(), shark::BinaryTree< Container::value_type >::m_nodes, shark::BinaryTree< Container::value_type >::m_size, shark::TreeConstruction::maxBucketSize(), and shark::TreeConstruction::maxDepth().
Referenced by shark::KHCTree< Container, CuttingAccuracy >::KHCTree().
calculateNormal()
template<class Container , int CuttingAccuracy = 25> template<class Range > void shark::KHCTree< Container, CuttingAccuracy >::calculateNormal (Range const & samples) inline protected
Definition at line 200 of file KHCTree.h.
References shark::batchSize(), shark::AbstractKernelFunction< InputTypeT >::featureDistanceSqr(), shark::KHCTree< Container, CuttingAccuracy >::m_normalInvNorm, shark::KHCTree< Container, CuttingAccuracy >::mep_kernel, shark::KHCTree< Container, CuttingAccuracy >::mep_negative, and shark::KHCTree< Container, CuttingAccuracy >::mep_positive.
Referenced by shark::KHCTree< Container, CuttingAccuracy >::buildTree().
funct()
template<class Container , int CuttingAccuracy = 25> double shark::KHCTree< Container, CuttingAccuracy >::funct (value_type const & reference) const inline protected
function describing the separating hyperplane
Definition at line 221 of file KHCTree.h.
References shark::AbstractKernelFunction< InputTypeT >::eval(), shark::KHCTree< Container, CuttingAccuracy >::m_normalInvNorm, shark::KHCTree< Container, CuttingAccuracy >::mep_kernel, shark::KHCTree< Container, CuttingAccuracy >::mep_negative, and shark::KHCTree< Container, CuttingAccuracy >::mep_positive.
squaredDistanceLowerBound()
template<class Container , int CuttingAccuracy = 25> double shark::KHCTree< Container, CuttingAccuracy >::squaredDistanceLowerBound (value_type const & reference) const inline
Compute the squared distance of this cell to the given reference point, or alternatively a lower bound on this value.
Definition at line 113 of file KHCTree.h.
References shark::KHCTree< Container, CuttingAccuracy >::mep_parent, shark::BinaryTree< Container::value_type >::mep_parent, and shark::KHCTree< Container, CuttingAccuracy >::mp_right.
Member Data Documentation
m_nodes
template<class Container , int CuttingAccuracy = 25> std::size_t shark::BinaryTree< InputT >::m_nodes protected
number of nodes in the sub-tree represented by this node
Definition at line 361 of file BinaryTree.h.
m_normalInvNorm
template<class Container , int CuttingAccuracy = 25> double shark::KHCTree< Container, CuttingAccuracy >::m_normalInvNorm protected
one divided by squared distance between "positive" and "negative" cluster center
Definition at line 238 of file KHCTree.h.
Referenced by shark::KHCTree< Container, CuttingAccuracy >::calculateNormal(), and shark::KHCTree< Container, CuttingAccuracy >::funct().
m_size
template<class Container , int CuttingAccuracy = 25> std::size_t shark::BinaryTree< InputT >::m_size protected
number of points in this node
Definition at line 358 of file BinaryTree.h.
mep_kernel
template<class Container , int CuttingAccuracy = 25> kernel_type const* shark::KHCTree< Container, CuttingAccuracy >::mep_kernel protected
kernel function
Definition at line 229 of file KHCTree.h.
Referenced by shark::KHCTree< Container, CuttingAccuracy >::calculateNormal(), and shark::KHCTree< Container, CuttingAccuracy >::funct().
mep_negative
template<class Container , int CuttingAccuracy = 25> const_iterator shark::KHCTree< Container, CuttingAccuracy >::mep_negative protected
"negative" side cluster center
Definition at line 235 of file KHCTree.h.
Referenced by shark::KHCTree< Container, CuttingAccuracy >::calculateNormal(), and shark::KHCTree< Container, CuttingAccuracy >::funct().
mep_parent
template<class Container , int CuttingAccuracy = 25> BinaryTree* shark::BinaryTree< InputT >::mep_parent protected
parent node
Definition at line 346 of file BinaryTree.h.
Referenced by shark::KHCTree< Container, CuttingAccuracy >::squaredDistanceLowerBound().
mep_positive
template<class Container , int CuttingAccuracy = 25> const_iterator shark::KHCTree< Container, CuttingAccuracy >::mep_positive protected
"positive" side cluster center
Definition at line 232 of file KHCTree.h.
Referenced by shark::KHCTree< Container, CuttingAccuracy >::calculateNormal(), and shark::KHCTree< Container, CuttingAccuracy >::funct().
mp_indexList
template<class Container , int CuttingAccuracy = 25> std::size_t* shark::BinaryTree< InputT >::mp_indexList protected
list of indices to points in the dataset
Definition at line 355 of file BinaryTree.h.
mp_left
template<class Container , int CuttingAccuracy = 25> BinaryTree* shark::BinaryTree< InputT >::mp_left protected
"left" child node
Definition at line 349 of file BinaryTree.h.
mp_right
template<class Container , int CuttingAccuracy = 25> BinaryTree* shark::BinaryTree< InputT >::mp_right protected
"right" child node
Definition at line 352 of file BinaryTree.h.
Referenced by shark::KHCTree< Container, CuttingAccuracy >::squaredDistanceLowerBound().
The documentation for this class was generated from the following file:
include/shark/Models/Trees/KHCTree.h