shark::RegularizedKernelMatrix< InputType, CacheType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::RegularizedKernelMatrix< InputType, CacheType > Class Template Reference
Kernel Gram matrix with modified diagonal.
#include <shark/LinAlg/RegularizedKernelMatrix.h>
Public Types
typedef Matrix::QpFloatType QpFloatType
Public Member Functions
RegularizedKernelMatrix (AbstractKernelFunction< InputType > const &kernelfunction, Data< InputType > const &data, const RealVector &diagModification)
QpFloatType operator() (std::size_t i, std::size_t j) const
return a single matrix entry
QpFloatType entry (std::size_t i, std::size_t j) const
return a single matrix entry
void row (std::size_t k, std::size_t start, std::size_t end, QpFloatType *storage) const
Computes the i-th row of the kernel matrix.
template<class M >
void matrix (blas::matrix_expression< M, blas::cpu_tag > &storage) const
Computes the kernel-matrix.
void flipColumnsAndRows (std::size_t i, std::size_t j)
swap two variables
std::size_t size () const
return the size of the quadratic matrix
unsigned long long getAccessCount () const
query the kernel access counter
void resetAccessCount ()
reset the kernel access counter
Protected Attributes
Matrix m_matrix
RealVector m_diagMod
Detailed Description
template<class InputType, class CacheType>
class shark::RegularizedKernelMatrix< InputType, CacheType >
Kernel Gram matrix with modified diagonal.
Regularized version of KernelMatrix. The regularization is achieved by adding a vector to the matrix diagonal. In particular, this is useful for support vector machines with 2-norm penalty term.
Definition at line 62 of file RegularizedKernelMatrix.h.
Member Typedef Documentation
QpFloatType
template<class InputType , class CacheType > typedef Matrix::QpFloatType shark::RegularizedKernelMatrix< InputType, CacheType >::QpFloatType
Definition at line 67 of file RegularizedKernelMatrix.h.
Constructor & Destructor Documentation
RegularizedKernelMatrix()
template<class InputType , class CacheType > shark::RegularizedKernelMatrix< InputType, CacheType >::RegularizedKernelMatrix (AbstractKernelFunction< InputType > const & kernelfunction, Data< InputType > const & data, const RealVector & diagModification) inline
Constructor
Parameters
kernelfunction kernel function
data data to evaluate the kernel function
diagModification vector d of diagonal modifiers
Definition at line 73 of file RegularizedKernelMatrix.h.
References shark::RegularizedKernelMatrix< InputType, CacheType >::size(), and SIZE_CHECK.
Member Function Documentation
entry()
template<class InputType , class CacheType > QpFloatType shark::RegularizedKernelMatrix< InputType, CacheType >::entry (std::size_t i, std::size_t j) const inline
return a single matrix entry
Definition at line 86 of file RegularizedKernelMatrix.h.
References shark::RegularizedKernelMatrix< InputType, CacheType >::m_diagMod, and shark::RegularizedKernelMatrix< InputType, CacheType >::m_matrix.
Referenced by shark::RegularizedKernelMatrix< InputType, CacheType >::operator()().
flipColumnsAndRows()
template<class InputType , class CacheType > void shark::RegularizedKernelMatrix< InputType, CacheType >::flipColumnsAndRows (std::size_t i, std::size_t j) inline
swap two variables
Definition at line 117 of file RegularizedKernelMatrix.h.
References shark::KernelMatrix< InputType, CacheType >::flipColumnsAndRows(), shark::RegularizedKernelMatrix< InputType, CacheType >::m_diagMod, shark::RegularizedKernelMatrix< InputType, CacheType >::m_matrix, and shark::swap().
getAccessCount()
template<class InputType , class CacheType > unsigned long long shark::RegularizedKernelMatrix< InputType, CacheType >::getAccessCount () const inline
query the kernel access counter
Definition at line 127 of file RegularizedKernelMatrix.h.
References shark::KernelMatrix< InputType, CacheType >::getAccessCount(), and shark::RegularizedKernelMatrix< InputType, CacheType >::m_matrix.
matrix()
template<class InputType , class CacheType > template<class M > void shark::RegularizedKernelMatrix< InputType, CacheType >::matrix (blas::matrix_expression< M, blas::cpu_tag > & storage) const inline
Computes the kernel-matrix.
Definition at line 107 of file RegularizedKernelMatrix.h.
References shark::RegularizedKernelMatrix< InputType, CacheType >::m_diagMod, shark::RegularizedKernelMatrix< InputType, CacheType >::m_matrix, shark::KernelMatrix< InputType, CacheType >::matrix(), and shark::RegularizedKernelMatrix< InputType, CacheType >::size().
operator()()
template<class InputType , class CacheType > QpFloatType shark::RegularizedKernelMatrix< InputType, CacheType >::operator() (std::size_t i, std::size_t j) const inline
return a single matrix entry
Definition at line 82 of file RegularizedKernelMatrix.h.
References shark::RegularizedKernelMatrix< InputType, CacheType >::entry().
resetAccessCount()
template<class InputType , class CacheType > void shark::RegularizedKernelMatrix< InputType, CacheType >::resetAccessCount () inline
reset the kernel access counter
Definition at line 131 of file RegularizedKernelMatrix.h.
References shark::RegularizedKernelMatrix< InputType, CacheType >::m_matrix, and shark::KernelMatrix< InputType, CacheType >::resetAccessCount().
row()
template<class InputType , class CacheType > void shark::RegularizedKernelMatrix< InputType, CacheType >::row (std::size_t k, std::size_t start, std::size_t end, QpFloatType * storage) const inline
Computes the i-th row of the kernel matrix.
The entries start,...,end of the i-th row are computed and stored in storage. There must be enough room for this operation preallocated.
Definition at line 97 of file RegularizedKernelMatrix.h.
References shark::RegularizedKernelMatrix< InputType, CacheType >::m_diagMod, shark::RegularizedKernelMatrix< InputType, CacheType >::m_matrix, and shark::KernelMatrix< InputType, CacheType >::row().
size()
template<class InputType , class CacheType > std::size_t shark::RegularizedKernelMatrix< InputType, CacheType >::size () const inline
return the size of the quadratic matrix
Definition at line 123 of file RegularizedKernelMatrix.h.
References shark::RegularizedKernelMatrix< InputType, CacheType >::m_matrix, and shark::KernelMatrix< InputType, CacheType >::size().
Referenced by shark::RegularizedKernelMatrix< InputType, CacheType >::matrix(), and shark::RegularizedKernelMatrix< InputType, CacheType >::RegularizedKernelMatrix().
Member Data Documentation
m_diagMod
template<class InputType , class CacheType > RealVector shark::RegularizedKernelMatrix< InputType, CacheType >::m_diagMod protected
Definition at line 136 of file RegularizedKernelMatrix.h.
Referenced by shark::RegularizedKernelMatrix< InputType, CacheType >::entry(), shark::RegularizedKernelMatrix< InputType, CacheType >::flipColumnsAndRows(), shark::RegularizedKernelMatrix< InputType, CacheType >::matrix(), and shark::RegularizedKernelMatrix< InputType, CacheType >::row().
m_matrix
template<class InputType , class CacheType > Matrix shark::RegularizedKernelMatrix< InputType, CacheType >::m_matrix protected
Definition at line 135 of file RegularizedKernelMatrix.h.
Referenced by shark::RegularizedKernelMatrix< InputType, CacheType >::entry(), shark::RegularizedKernelMatrix< InputType, CacheType >::flipColumnsAndRows(), shark::RegularizedKernelMatrix< InputType, CacheType >::getAccessCount(), shark::RegularizedKernelMatrix< InputType, CacheType >::matrix(), shark::RegularizedKernelMatrix< InputType, CacheType >::resetAccessCount(), shark::RegularizedKernelMatrix< InputType, CacheType >::row(), and shark::RegularizedKernelMatrix< InputType, CacheType >::size().
The documentation for this class was generated from the following file:
include/shark/LinAlg/RegularizedKernelMatrix.h