shark::INameable Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::INameable Class Reference
This class is an interface for all objects which can have a name.
#include <shark/Core/INameable.h>
Public Member Functions
virtual ~INameable ()
virtual std::string name () const
returns the name of the object
Detailed Description
This class is an interface for all objects which can have a name.
Definition at line 43 of file INameable.h.
Constructor & Destructor Documentation
~INameable()
virtual shark::INameable::~INameable () inline virtual
Definition at line 45 of file INameable.h.
Member Function Documentation
name()
virtual std::string shark::INameable::name () const inline virtual
returns the name of the object
Reimplemented in shark::SquaredHingeLinearCSvmTrainer< InputType >, shark::SquaredHingeCSvmTrainer< InputType, CacheType >, shark::LinearCSvmTrainer< InputType >, shark::PointSearch, shark::NestedGridSearch, shark::LinearClassifier< VectorType >, shark::KernelClassifier< InputType >, shark::MultiTaskKernel< InputTypeT >, shark::NeuronLayer< NeuronType, VectorType >, shark::Ensemble< ModelType, OutputType >, shark::Ensemble< CARTree< LabelType > >, shark::NearestNeighborModel< InputType, unsigned int >, shark::CrossEntropy< blas::vector< T, Device >, blas::vector< T, Device > >, shark::KernelBudgetedSGDTrainer< InputType, CacheType >, shark::ModelKernel< InputType >, shark::NearestNeighborModel< InputType, LabelType >, shark::RFTrainer< RealVector >, shark::LMCMA, shark::NegativeWilcoxonMannWhitneyStatistic< LabelType, OutputType >, shark::GaussianTaskKernel< InputTypeT >, shark::SquaredLoss< Sequence, Sequence >, shark::Rprop< SearchPointType >, shark::CSvmDerivative< InputType, CacheType >, shark::KernelSGDTrainer< InputType, CacheType >, shark::TwoNormRegularizer< SearchPointType >, shark::RFClassifier< LabelType >, shark::WeightedSumKernel< InputType >, shark::KernelTargetAlignment< InputType, LabelType >, shark::CSvmTrainer< InputType, CacheType >, shark::MergeBudgetMaintenanceStrategy< RealVector >::MergingProblemFunction, shark::CrossEntropyMethod, shark::RBM< VisibleLayerT, HiddenLayerT, randomT >, shark::LinearSAGTrainer< InputType, LabelType >, shark::ErrorFunction< SearchPointType >, shark::CrossValidationError< ModelTypeT, LabelTypeT >, shark::SvmLogisticInterpretation< InputType >, shark::EpsilonSvmTrainer< InputType, CacheType >, shark::OneClassSvmTrainer< InputType, CacheType >, shark::KernelExpansion< InputType >, shark::SquaredLoss< OutputType, unsigned int >, shark::RegularizationNetworkTrainer< InputType >, shark::ZeroOneLoss< unsigned int, blas::vector< Float > >, shark::ProductKernel< InputType >, shark::LinearModel< InputType, ActivationFunction >, shark::ProductKernel< MultiTaskSample< InputTypeT > >, shark::LinearModel< VectorType >, shark::RankingSvmTrainer< InputType, CacheType >, shark::LooError< ModelTypeT, LabelType >, shark::CrossEntropy< unsigned int, OutputType >, shark::PCA, shark::Conv2DModel< VectorType, ActivationFunction >, shark::ARDKernelUnconstrained< InputType >, shark::NormalizedKernel< InputType >, shark::RFTrainer< unsigned int >, shark::NormalizeComponentsUnitVariance< DataType >, shark::MissingFeatureSvmTrainer< InputType, CacheType >, shark::PolynomialKernel< InputType >, shark::benchmarks::MultiObjectiveBenchmark< Objectives >, shark::NegativeGaussianProcessEvidence< InputType, OutputType, LabelType >, shark::LassoRegression< InputVectorType >, shark::ResizeLayer< VectorType >, shark::TrustRegionNewton, shark::VariationalAutoencoderError< SearchPointType >, shark::CMSA, shark::FisherLDA, shark::OptimizationTrainer< Model, LabelTypeT >, shark::Classifier< Model >, shark::CARTree< LabelType >, shark::Classifier< detail::BaseNearestNeighbor< InputType, unsigned int > >, shark::Classifier< LinearModel< VectorType > >, shark::Classifier< detail::EnsembleImpl< BaseModelType, std::remove_pointer< BaseModelType >::type::ParameterVectorType > >, shark::Classifier< KernelExpansion< InputType > >, shark::RBFLayer, shark::CMACMap, shark::MklKernel< InputType >, shark::LBFGS< SearchPointType >, shark::LogisticRegression< InputVectorType >, shark::NormalizeComponentsUnitInterval< DataType >, shark::MonomialKernel< InputType >, shark::RadiusMarginQuotient< InputType, CacheType >, shark::CMA, shark::HierarchicalClustering< InputT >, shark::Centroids, shark::GaussianRbfKernel< InputType >, shark::SoftClusteringModel< InputT >, shark::DiscreteKernel, shark::PointSetKernel< InputType >, shark::Normalizer< VectorType >, shark::OneVersusOneClassifier< InputType, VectorType >, shark::PoolingLayer< VectorType >, shark::ElitistCMA, shark::benchmarks::Rosenbrock, shark::IndicatorBasedMOCMA< Indicator >, shark::IndicatorBasedRealCodedNSGAII< Indicator >, shark::LabelOrder, shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >, shark::HardClusteringModel< InputT >, shark::ScaledKernel< InputType >, shark::GridSearch, shark::DropoutLayer< VectorType >, shark::NegativeLogLikelihood, shark::IndicatorBasedSteadyStateMOCMA< Indicator >, shark::SMSEMOA, shark::LooErrorCSvm< InputType, CacheType >, shark::LDA, shark::NormalizeKernelUnitVariance< InputType >, shark::MissingFeaturesKernelExpansion< InputType >, shark::benchmarks::IHR6, shark::SimplexDownhill, shark::CG< SearchPointType >, shark::NormalizeComponentsZCA, shark::ConcatenatedModel< VectorType >, shark::benchmarks::ELLI1, shark::benchmarks::ELLI2, shark::benchmarks::ZDT4, shark::DiscreteLoss, shark::HingeLoss, shark::SquaredHingeLoss, shark::VDCMA, shark::LinearRegression, shark::benchmarks::CIGTAB1, shark::benchmarks::CIGTAB2, shark::benchmarks::IHR2, shark::benchmarks::ZDT1, shark::CombinedObjectiveFunction< SearchPointType, ResultT >, shark::benchmarks::IHR1, shark::benchmarks::IHR3, shark::benchmarks::IHR4, shark::benchmarks::ZDT2, shark::benchmarks::ZDT6, shark::benchmarks::LZ2, shark::benchmarks::LZ8, shark::benchmarks::LZ9, shark::benchmarks::ZDT3, shark::ZeroOneLoss< LabelType, OutputType >, shark::NegativeAUC< LabelType, OutputType >, shark::LinearKernel< InputType >, shark::benchmarks::Fonseca, shark::benchmarks::LZ1, shark::benchmarks::LZ3, shark::benchmarks::LZ4, shark::benchmarks::LZ5, shark::benchmarks::LZ6, shark::benchmarks::LZ7, shark::AbsoluteLoss< VectorType >, shark::SquaredLoss< OutputType, LabelType >, shark::RealCodedNSGAIII, shark::OneNormRegularizer< SearchPointType >, shark::ContrastiveDivergence< Operator >, shark::SingleChainApproximator< MarkovChainType >, shark::Adam< SearchPointType >, shark::EpsilonHingeLoss, shark::SquaredEpsilonHingeLoss, shark::RVEA, shark::KernelMeanClassifier< InputType >, shark::benchmarks::Himmelblau, shark::MultiChainApproximator< MarkovChainType >, shark::NormalizeComponentsWhitening, shark::benchmarks::ConstrainedSphere, shark::benchmarks::DTLZ1, shark::HuberLoss, shark::MOEAD, shark::BFGS< SearchPointType >, shark::Perceptron< InputType >, shark::benchmarks::DTLZ2, shark::benchmarks::DTLZ4, shark::benchmarks::DTLZ5, shark::benchmarks::DTLZ6, shark::benchmarks::DTLZ7, shark::SteepestDescent< SearchPointType >, shark::benchmarks::DTLZ3, shark::benchmarks::RotatedObjectiveFunction, shark::benchmarks::Ellipsoid, shark::ExactGradient< RBMType >, shark::benchmarks::Cigar, shark::benchmarks::CigarDiscus, shark::benchmarks::Discus, shark::benchmarks::Ackley, shark::benchmarks::DiffPowers, shark::benchmarks::Sphere, shark::benchmarks::Schwefel, and shark::benchmarks::GSP.
Definition at line 48 of file INameable.h.
Referenced by shark::AbstractOptimizer< RealVector, RealVector, std::vector< ResultSet< RealVector, RealVector > > >::checkFeatures(), shark::benchmarks::RotatedObjectiveFunction::name(), shark::PointSetKernel< InputType >::name(), shark::OptimizationTrainer< Model, LabelTypeT >::name(), shark::NormalizedKernel< InputType >::name(), shark::LooError< ModelTypeT, LabelType >::name(), and shark::CrossValidationError< ModelTypeT, LabelTypeT >::name().
The documentation for this class was generated from the following file:
include/shark/Core/INameable.h