shark::TreeConstruction Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::TreeConstruction Class Reference
Models » Space Partitioning Trees
Stopping criteria for tree construction.
#include <shark/Models/Trees/BinaryTree.h>
Public Member Functions
TreeConstruction ()
Default constructor: only stop at trivial leaves.
TreeConstruction (TreeConstruction const &other)
Copy constructor.
TreeConstruction (unsigned int maxDepth, unsigned int maxBucketSize)
Constructor.
TreeConstruction nextDepthLevel () const
return a TreeConstruction object with maxDepth reduced by one
unsigned int maxDepth () const
return maximum depth of the tree
unsigned int maxBucketSize () const
return maximum "size" of a leaf node
Protected Attributes
unsigned int m_maxDepth
maximum depth of the tree
unsigned int m_maxBucketSize
maximum "size" of a leaf node
Detailed Description
Stopping criteria for tree construction.
Conditions for automatic tree construction. The data structure allows to specify a maximum bucket size (number of instances represented by a leaf), and a maximum tree depth.
Note: If a data instance appears more often in a dataset than specified by the maximum bucket size then this condition will be violated; this is because a space partitioning tree has no means of separating a single point.
Definition at line 73 of file BinaryTree.h.
Constructor & Destructor Documentation
TreeConstruction() [1/3]
shark::TreeConstruction::TreeConstruction () inline
Default constructor: only stop at trivial leaves.
Definition at line 77 of file BinaryTree.h.
Referenced by nextDepthLevel().
TreeConstruction() [2/3]
shark::TreeConstruction::TreeConstruction (TreeConstruction const & other) inline
Copy constructor.
Definition at line 83 of file BinaryTree.h.
TreeConstruction() [3/3]
shark::TreeConstruction::TreeConstruction (unsigned int maxDepth, unsigned int maxBucketSize) inline
Constructor.
Parameters
maxDepth stop as soon as the given tree depth is reached (zero means unrestricted)
maxBucketSize stop as soon as a node holds at most the bucket size of data points (zero means unrestricted)
Definition at line 92 of file BinaryTree.h.
Member Function Documentation
maxBucketSize()
unsigned int shark::TreeConstruction::maxBucketSize () const inline
return maximum "size" of a leaf node
Definition at line 108 of file BinaryTree.h.
References m_maxBucketSize.
Referenced by shark::LCTree< VectorType, CuttingAccuracy >::buildTree(), shark::KHCTree< Container, CuttingAccuracy >::buildTree(), and shark::KDTree< InputT >::buildTree().
maxDepth()
unsigned int shark::TreeConstruction::maxDepth () const inline
return maximum depth of the tree
Definition at line 104 of file BinaryTree.h.
References m_maxDepth.
Referenced by shark::LCTree< VectorType, CuttingAccuracy >::buildTree(), shark::KHCTree< Container, CuttingAccuracy >::buildTree(), and shark::KDTree< InputT >::buildTree().
nextDepthLevel()
TreeConstruction shark::TreeConstruction::nextDepthLevel () const inline
return a TreeConstruction object with maxDepth reduced by one
Definition at line 99 of file BinaryTree.h.
References m_maxBucketSize, m_maxDepth, and TreeConstruction().
Member Data Documentation
m_maxBucketSize
unsigned int shark::TreeConstruction::m_maxBucketSize protected
maximum "size" of a leaf node
Definition at line 116 of file BinaryTree.h.
Referenced by maxBucketSize(), and nextDepthLevel().
m_maxDepth
unsigned int shark::TreeConstruction::m_maxDepth protected
maximum depth of the tree
Definition at line 113 of file BinaryTree.h.
Referenced by maxDepth(), and nextDepthLevel().
The documentation for this class was generated from the following file:
include/shark/Models/Trees/BinaryTree.h