shark::OptimizationTrainer< Model, LabelTypeT > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::OptimizationTrainer< Model, LabelTypeT > Class Template Reference
Supervised Trainers
Wrapper for training schemes based on (iterative) optimization.
#include <shark/Algorithms/Trainers/OptimizationTrainer.h>
Public Types
typedef base_type::InputType InputType
typedef Model::OutputType OutputType
typedef base_type::LabelType LabelType
typedef Model ModelType
typedef ModelType::ParameterVectorType ParameterVectorType
typedef AbstractSingleObjectiveOptimizer< ParameterVectorType > OptimizerType
typedef AbstractLoss< LabelType, OutputType > LossType
typedef AbstractStoppingCriterion< SingleObjectiveResultSet< ParameterVectorType > > StoppingCriterionType
Public Types inherited from shark::AbstractTrainer< Model, LabelTypeT >
typedef Model ModelType
typedef ModelType::InputType InputType
typedef LabelTypeT LabelType
typedef LabeledData< InputType, LabelType > DatasetType
Public Member Functions
OptimizationTrainer (LossType *loss, OptimizerType *optimizer, StoppingCriterionType *stoppingCriterion)
std::string name () const
From INameable: return the class name.
void train (ModelType &model, LabeledData< InputType, LabelType > const &dataset)
void read (InArchive &archive)
Read the component from the supplied archive.
void write (OutArchive &archive) const
Write the component to the supplied archive.
Public Member Functions inherited from shark::AbstractTrainer< Model, LabelTypeT >
virtual void train (ModelType &model, DatasetType const &dataset)=0
Core of the Trainer interface.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Attributes
LossType * mep_loss
OptimizerType * mep_optimizer
StoppingCriterionType * mep_stoppingCriterion
Detailed Description
template<class Model, class LabelTypeT = typename Model::OutputType>
class shark::OptimizationTrainer< Model, LabelTypeT >
Wrapper for training schemes based on (iterative) optimization.
The OptimizationTrainer class is designed to allow for model training via iterative minimization of a loss function, such as in neural network "backpropagation" training.
Definition at line 58 of file OptimizationTrainer.h.
Member Typedef Documentation
InputType
template<class Model, class LabelTypeT = typename Model::OutputType> typedef base_type::InputType shark::OptimizationTrainer< Model, LabelTypeT >::InputType
Definition at line 63 of file OptimizationTrainer.h.
LabelType
template<class Model, class LabelTypeT = typename Model::OutputType> typedef base_type::LabelType shark::OptimizationTrainer< Model, LabelTypeT >::LabelType
Definition at line 65 of file OptimizationTrainer.h.
LossType
template<class Model, class LabelTypeT = typename Model::OutputType> typedef AbstractLoss< LabelType, OutputType > shark::OptimizationTrainer< Model, LabelTypeT >::LossType
Definition at line 70 of file OptimizationTrainer.h.
ModelType
template<class Model, class LabelTypeT = typename Model::OutputType> typedef Model shark::OptimizationTrainer< Model, LabelTypeT >::ModelType
Definition at line 66 of file OptimizationTrainer.h.
OptimizerType
template<class Model, class LabelTypeT = typename Model::OutputType> typedef AbstractSingleObjectiveOptimizer< ParameterVectorType > shark::OptimizationTrainer< Model, LabelTypeT >::OptimizerType
Definition at line 69 of file OptimizationTrainer.h.
OutputType
template<class Model, class LabelTypeT = typename Model::OutputType> typedef Model::OutputType shark::OptimizationTrainer< Model, LabelTypeT >::OutputType
Definition at line 64 of file OptimizationTrainer.h.
ParameterVectorType
template<class Model, class LabelTypeT = typename Model::OutputType> typedef ModelType::ParameterVectorType shark::OptimizationTrainer< Model, LabelTypeT >::ParameterVectorType
Definition at line 67 of file OptimizationTrainer.h.
StoppingCriterionType
template<class Model, class LabelTypeT = typename Model::OutputType> typedef AbstractStoppingCriterion<SingleObjectiveResultSet<ParameterVectorType> > shark::OptimizationTrainer< Model, LabelTypeT >::StoppingCriterionType
Definition at line 71 of file OptimizationTrainer.h.
Constructor & Destructor Documentation
OptimizationTrainer()
template<class Model, class LabelTypeT = typename Model::OutputType> shark::OptimizationTrainer< Model, LabelTypeT >::OptimizationTrainer (LossType * loss, OptimizerType * optimizer, StoppingCriterionType * stoppingCriterion) inline
Definition at line 73 of file OptimizationTrainer.h.
References SHARK_RUNTIME_CHECK.
Member Function Documentation
name()
template<class Model, class LabelTypeT = typename Model::OutputType> std::string shark::OptimizationTrainer< Model, LabelTypeT >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 85 of file OptimizationTrainer.h.
References shark::OptimizationTrainer< Model, LabelTypeT >::mep_loss, shark::OptimizationTrainer< Model, LabelTypeT >::mep_optimizer, and shark::INameable::name().
read()
template<class Model, class LabelTypeT = typename Model::OutputType> void shark::OptimizationTrainer< Model, LabelTypeT >::read (InArchive & archive) inline virtual
Read the component from the supplied archive.
Parameters
[in,out] archive The archive to read from.
Reimplemented from shark::ISerializable.
Definition at line 104 of file OptimizationTrainer.h.
train()
template<class Model, class LabelTypeT = typename Model::OutputType> void shark::OptimizationTrainer< Model, LabelTypeT >::train (ModelType & model, LabeledData< InputType, LabelType > const & dataset) inline
Definition at line 92 of file OptimizationTrainer.h.
References shark::AbstractSingleObjectiveOptimizer< PointType >::init(), shark::ErrorFunction< SearchPointType >::init(), shark::OptimizationTrainer< Model, LabelTypeT >::mep_loss, shark::OptimizationTrainer< Model, LabelTypeT >::mep_optimizer, shark::OptimizationTrainer< Model, LabelTypeT >::mep_stoppingCriterion, shark::AbstractStoppingCriterion< ResultSetT >::reset(), shark::AbstractSingleObjectiveOptimizer< PointType >::solution(), shark::AbstractOptimizer< PointType, ResultT, SolutionTypeT >::step(), and shark::AbstractStoppingCriterion< ResultSetT >::stop().
Referenced by experiment().
write()
template<class Model, class LabelTypeT = typename Model::OutputType> void shark::OptimizationTrainer< Model, LabelTypeT >::write (OutArchive & archive) const inline virtual
Write the component to the supplied archive.
Parameters
[in,out] archive The archive to write to.
Reimplemented from shark::ISerializable.
Definition at line 107 of file OptimizationTrainer.h.
Member Data Documentation
mep_loss
template<class Model, class LabelTypeT = typename Model::OutputType> LossType* shark::OptimizationTrainer< Model, LabelTypeT >::mep_loss protected
Definition at line 111 of file OptimizationTrainer.h.
Referenced by shark::OptimizationTrainer< Model, LabelTypeT >::name(), and shark::OptimizationTrainer< Model, LabelTypeT >::train().
mep_optimizer
template<class Model, class LabelTypeT = typename Model::OutputType> OptimizerType* shark::OptimizationTrainer< Model, LabelTypeT >::mep_optimizer protected
Definition at line 112 of file OptimizationTrainer.h.
Referenced by shark::OptimizationTrainer< Model, LabelTypeT >::name(), and shark::OptimizationTrainer< Model, LabelTypeT >::train().
mep_stoppingCriterion
template<class Model, class LabelTypeT = typename Model::OutputType> StoppingCriterionType* shark::OptimizationTrainer< Model, LabelTypeT >::mep_stoppingCriterion protected
Definition at line 113 of file OptimizationTrainer.h.
Referenced by shark::OptimizationTrainer< Model, LabelTypeT >::train().
The documentation for this class was generated from the following file:
include/shark/Algorithms/Trainers/OptimizationTrainer.h