shark::DataDistribution< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::DataDistribution< InputType > Class Template Reference abstract
A DataDistribution defines an unsupervised learning problem.
#include <shark/Data/DataDistribution.h>
Public Member Functions
virtual ~DataDistribution ()
Virtual destructor.
virtual void draw (InputType &input) const =0
Generates a single pair of input and label.
InputType operator() ()
UnlabeledData< InputType > generateDataset (std::size_t size, std::size_t maximumBatchSize) const
Generates a data set with samples from from the distribution.
UnlabeledData< InputType > generateDataset (std::size_t size) const
Generates a data set with samples from from the distribution.
Detailed Description
template<class InputType>
class shark::DataDistribution< InputType >
A DataDistribution defines an unsupervised learning problem.
The unsupervised learning problem is defined by an explicit distribution (in contrast to a finite dataset). The only method we need is to draw a sample from the distribution.
Definition at line 57 of file DataDistribution.h.
Constructor & Destructor Documentation
~DataDistribution()
template<class InputType> virtual shark::DataDistribution< InputType >::~DataDistribution () inline virtual
Virtual destructor.
Definition at line 61 of file DataDistribution.h.
Member Function Documentation
draw()
template<class InputType> virtual void shark::DataDistribution< InputType >::draw (InputType & input) const pure virtual
Generates a single pair of input and label.
Parameters
input the generated input
Implemented in shark::ImagePatches, and shark::NormalDistributedPoints.
Referenced by shark::DataDistribution< RealVector >::generateDataset(), and shark::DataDistribution< RealVector >::operator()().
generateDataset() [1/2]
template<class InputType> UnlabeledData<InputType> shark::DataDistribution< InputType >::generateDataset (std::size_t size, std::size_t maximumBatchSize) const inline
Generates a data set with samples from from the distribution.
Parameters
size the number of samples in the dataset
maximumBatchSize the maximum size of a batch
Definition at line 79 of file DataDistribution.h.
Referenced by shark::DataDistribution< RealVector >::generateDataset().
generateDataset() [2/2]
template<class InputType> UnlabeledData<InputType> shark::DataDistribution< InputType >::generateDataset (std::size_t size) const inline
Generates a data set with samples from from the distribution.
Parameters
size the number of samples in the dataset
Definition at line 93 of file DataDistribution.h.
operator()()
template<class InputType> InputType shark::DataDistribution< InputType >::operator() () inline
Definition at line 69 of file DataDistribution.h.
The documentation for this class was generated from the following file:
include/shark/Data/DataDistribution.h