shark::SoftClusteringModel< InputT > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::SoftClusteringModel< InputT > Class Template Reference
Models » Clustering Algorithms
Model for "soft" clustering.
#include <shark/Models/Clustering/SoftClusteringModel.h>
Public Member Functions
SoftClusteringModel (ClusteringType *clustering)
Constructor.
std::string name () const
From INameable: return the class name.
Shape inputShape () const
Returns the expected shape of the input.
Shape outputShape () const
Returns the shape of the output.
void eval (InputType const &pattern, OutputType &output) const
Compute best matching cluster.
void eval (BatchInputType const &patterns, BatchOutputType &outputs) const
Compute best matching cluster for a batch of inputs.
Public Member Functions inherited from shark::ClusteringModel< InputT, RealVector >
ClusteringModel (ClusteringType *clustering)
Constructor.
RealVector parameterVector () const
Redirect parameter access to the clustering object.
void setParameterVector (RealVector const &newParameters)
Redirect parameter access to the clustering object.
std::size_t numberOfParameters () const
Redirect parameter access to the clustering object.
void read (InArchive &archive)
From ISerializable, reads a model from an archive.
void write (OutArchive &archive) const
From ISerializable, writes a model to an archive.
void eval (BatchInputType const &patterns, BatchOutputType &outputs, State &state) const
Standard interface for evaluating the response of the model to a batch of patterns.
Public Member Functions inherited from shark::AbstractModel< InputT, RealVector >
AbstractModel ()
virtual ~AbstractModel ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
Returns true when the first parameter derivative is implemented.
bool hasFirstInputDerivative () const
Returns true when the first input derivative is implemented.
virtual boost::shared_ptr< State > createState () const
Creates an internal state of the model.
virtual void eval (BatchInputType const &patterns, BatchOutputType &outputs) const
Standard interface for evaluating the response of the model to a batch of patterns.
Data< OutputType > operator() (Data< InputType > const &patterns) const
Model evaluation as an operator for a whole dataset. This is a convenience function.
OutputType operator() (InputType const &pattern) const
Model evaluation as an operator for a single pattern. This is a convenience function.
BatchOutputType operator() (BatchInputType const &patterns) const
Model evaluation as an operator for a single pattern. This is a convenience function.
virtual void weightedParameterDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, RealVector &derivative) const
calculates the weighted sum of derivatives w.r.t the parameters.
virtual void weightedInputDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchInputType &derivative) const
calculates the weighted sum of derivatives w.r.t the inputs
virtual void weightedDerivatives (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, RealVector &parameterDerivative, BatchInputType &inputDerivative) const
calculates weighted input and parameter derivative at the same time
Public Member Functions inherited from shark::IParameterizable< RealVector >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Additional Inherited Members
Public Types inherited from shark::ClusteringModel< InputT, RealVector >
typedef AbstractClustering< InputT > ClusteringType
typedef base_type::BatchInputType BatchInputType
typedef base_type::BatchOutputType BatchOutputType
Public Types inherited from shark::AbstractModel< InputT, RealVector >
enum Feature
typedef InputT InputType
Defines the input type of the model.
typedef RealVector OutputType
Defines the output type of the model.
typedef AbstractModel< InputT, RealVector, RealVector > ModelBaseType
Defines the BaseType used by the model (this type). Useful for creating derived models.
typedef Batch< InputType >::type BatchInputType
defines the batch type of the input type.
typedef Batch< OutputType >::type BatchOutputType
defines the batch type of the output type
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::IParameterizable< RealVector >
typedef RealVector ParameterVectorType
Protected Attributes inherited from shark::ClusteringModel< InputT, RealVector >
ClusteringType * mep_clustering
Clustering object, see class AbstractClustering.
Protected Attributes inherited from shark::AbstractModel< InputT, RealVector >
Features m_features
Detailed Description
template<class InputT>
class shark::SoftClusteringModel< InputT >
Model for "soft" clustering.
The SoftClusteringModel is based on an Clustering Algorithms object. Given an input, the model outputs the cluster membership function, which consists of a non-negative value per cluster, and all memberships add up to one.
See also HardClusteringModel for the best matching cluster.
Definition at line 59 of file SoftClusteringModel.h.
Constructor & Destructor Documentation
SoftClusteringModel()
template<class InputT > shark::SoftClusteringModel< InputT >::SoftClusteringModel (ClusteringType * clustering) inline
Constructor.
Definition at line 69 of file SoftClusteringModel.h.
References shark::AbstractClustering< InputT >::hasSoftMembershipFunction(), and SHARK_RUNTIME_CHECK.
Member Function Documentation
eval() [1/2]
template<class InputT > void shark::SoftClusteringModel< InputT >::eval (InputType const & pattern, OutputType & output) const inline virtual
Compute best matching cluster.
The actual computation is redirected to the clustering object.
Reimplemented from shark::AbstractModel< InputT, RealVector >.
Definition at line 92 of file SoftClusteringModel.h.
References shark::ClusteringModel< InputT, RealVector >::mep_clustering, and shark::AbstractClustering< InputT >::softMembership().
eval() [2/2]
template<class InputT > void shark::SoftClusteringModel< InputT >::eval (BatchInputType const & patterns, BatchOutputType & outputs) const inline
Compute best matching cluster for a batch of inputs.
The actual computation is redirected to the clustering object.
Definition at line 100 of file SoftClusteringModel.h.
References shark::ClusteringModel< InputT, RealVector >::mep_clustering, and shark::AbstractClustering< InputT >::softMembership().
inputShape()
template<class InputT > Shape shark::SoftClusteringModel< InputT >::inputShape () const inline virtual
Returns the expected shape of the input.
Implements shark::AbstractModel< InputT, RealVector >.
Definition at line 81 of file SoftClusteringModel.h.
References shark::AbstractClustering< InputT >::inputShape(), and shark::ClusteringModel< InputT, RealVector >::mep_clustering.
name()
template<class InputT > std::string shark::SoftClusteringModel< InputT >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 78 of file SoftClusteringModel.h.
outputShape()
template<class InputT > Shape shark::SoftClusteringModel< InputT >::outputShape () const inline virtual
Returns the shape of the output.
Implements shark::AbstractModel< InputT, RealVector >.
Definition at line 84 of file SoftClusteringModel.h.
References shark::ClusteringModel< InputT, RealVector >::mep_clustering, and shark::AbstractClustering< InputT >::numberOfClusters().
The documentation for this class was generated from the following file:
include/shark/Models/Clustering/SoftClusteringModel.h