shark::LabeledDataDistribution< InputType, LabelType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::LabeledDataDistribution< InputType, LabelType > Class Template Reference abstract
A LabeledDataDistribution defines a supervised learning problem.
#include <shark/Data/DataDistribution.h>
Public Member Functions
virtual ~LabeledDataDistribution ()
Virtual destructor.
virtual void draw (InputType &input, LabelType &label) const =0
Generates a single pair of input and label.
std::pair< InputType, LabelType > operator() ()
LabeledData< InputType, LabelType > generateDataset (std::size_t size, std::size_t maximumBatchSize) const
Generates a dataset with samples from from the distribution.
LabeledData< InputType, LabelType > generateDataset (std::size_t size) const
Generates a data set with samples from from the distribution.
Detailed Description
template<class InputType, class LabelType>
class shark::LabeledDataDistribution< InputType, LabelType >
A LabeledDataDistribution defines a supervised learning problem.
The supervised learning problem is defined by an explicit distribution (in contrast to a finite dataset). The only method we need is to draw a sample from the distribution.
Definition at line 108 of file DataDistribution.h.
Constructor & Destructor Documentation
~LabeledDataDistribution()
template<class InputType, class LabelType> virtual shark::LabeledDataDistribution< InputType, LabelType >::~LabeledDataDistribution () inline virtual
Virtual destructor.
Definition at line 112 of file DataDistribution.h.
Member Function Documentation
draw()
template<class InputType, class LabelType> virtual void shark::LabeledDataDistribution< InputType, LabelType >::draw (InputType & input, LabelType & label) const pure virtual
Generates a single pair of input and label.
Parameters
input the generated input
label the generated label
Implemented in shark::DiagonalWithCircle, shark::CircleInSquare, shark::PamiToy, shark::Wave, and shark::Chessboard.
Referenced by shark::LabeledDataDistribution< RealVector, unsigned int >::generateDataset(), and shark::LabeledDataDistribution< RealVector, unsigned int >::operator()().
generateDataset() [1/2]
template<class InputType, class LabelType> LabeledData<InputType, LabelType> shark::LabeledDataDistribution< InputType, LabelType >::generateDataset (std::size_t size, std::size_t maximumBatchSize) const inline
Generates a dataset with samples from from the distribution.
Parameters
size the number of samples in the dataset
maximumBatchSize the maximum size of a batch
Definition at line 130 of file DataDistribution.h.
Referenced by shark::LabeledDataDistribution< RealVector, unsigned int >::generateDataset(), main(), and run_one_trial().
generateDataset() [2/2]
template<class InputType, class LabelType> LabeledData<InputType, LabelType> shark::LabeledDataDistribution< InputType, LabelType >::generateDataset (std::size_t size) const inline
Generates a data set with samples from from the distribution.
Parameters
size the number of samples in the dataset
Definition at line 145 of file DataDistribution.h.
operator()()
template<class InputType, class LabelType> std::pair<InputType,LabelType> shark::LabeledDataDistribution< InputType, LabelType >::operator() () inline
Definition at line 120 of file DataDistribution.h.
The documentation for this class was generated from the following file:
include/shark/Data/DataDistribution.h