shark::NegativeLogLikelihood Class Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::NegativeLogLikelihood Class Reference
Objective functions
Computes the negative log likelihood of a dataset under a model.
#include <shark/ObjectiveFunctions/NegativeLogLikelihood.h>
Public Types
typedef UnlabeledData< RealVector > DatasetType
Public Types inherited from shark::AbstractObjectiveFunction< RealVector, double >
enum Feature
List of features that are supported by an implementation.
typedef RealVector SearchPointType
typedef double ResultType
typedef boost::mpl::if_< std::is_arithmetic< double >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
NegativeLogLikelihood (DatasetType const &data, AbstractModel< RealVector, RealVector > *model)
std::string name () const
From INameable: return the class name.
SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
std::size_t numberOfVariables () const
Accesses the number of variables.
ResultType eval (RealVector const &input) const
Evaluates the objective function for the supplied argument.
ResultType evalDerivative (SearchPointType const &input, FirstOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
virtual void init ()
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual bool hasScalableDimensionality () const
virtual void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
virtual std::size_t numberOfObjectives () const
virtual bool hasScalableObjectives () const
virtual void setNumberOfObjectives (std::size_t numberOfObjectives)
Adjusts the number of objectives if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual bool isFeasible (const SearchPointType &input) const
Tests whether a point in SearchSpace is feasible, e.g., whether the constraints are fulfilled.
virtual void closestFeasible (SearchPointType &input) const
If supported, the supplied point is repaired such that it satisfies all of the function's constraints.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
virtual ResultType evalDerivative (SearchPointType const &input, SecondOrderDerivative &derivative) const
Evaluates the objective function and calculates its gradient.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Additional Inherited Members
Protected Member Functions inherited from shark::AbstractObjectiveFunction< RealVector, double >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< RealVector, double >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
Computes the negative log likelihood of a dataset under a model.
The negative log likelihood is defined as
\[ L(\theta) = -\frac 1 N \sum_{i=1}^N log(p_{\theta}(x_i)) \]
where \(\theta \) is the vector of parameters of the model \(p \) and \(x \) are the datapoints of the training set. Minimizing this maximizes the probability of the datast under p. This error measure is closely related to the Kulback-Leibler-Divergence.
For this error function, the model is only allowed to have a single output
the probability of the sample. The distribution must be normalized as otherwise the likeelihood does not mean anything.
Definition at line 56 of file NegativeLogLikelihood.h.
Member Typedef Documentation
DatasetType
typedef UnlabeledData<RealVector> shark::NegativeLogLikelihood::DatasetType
Definition at line 59 of file NegativeLogLikelihood.h.
Constructor & Destructor Documentation
NegativeLogLikelihood()
shark::NegativeLogLikelihood::NegativeLogLikelihood (DatasetType const & data, AbstractModel< RealVector, RealVector > * model) inline
Definition at line 61 of file NegativeLogLikelihood.h.
References shark::AbstractObjectiveFunction< RealVector, double >::CAN_PROPOSE_STARTING_POINT, shark::AbstractObjectiveFunction< RealVector, double >::HAS_FIRST_DERIVATIVE, shark::AbstractModel< InputTypeT, OutputTypeT, ParameterVectorType >::hasFirstParameterDerivative(), and shark::AbstractObjectiveFunction< RealVector, double >::m_features.
Member Function Documentation
eval()
ResultType shark::NegativeLogLikelihood::eval (RealVector const & input) const inline virtual
Evaluates the objective function for the supplied argument.
Parameters
[in] input The argument for which the function shall be evaluated.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 82 of file NegativeLogLikelihood.h.
References shark::Data< Type >::batch(), shark::AbstractObjectiveFunction< RealVector, double >::m_evaluationCounter, shark::Data< Type >::numberOfBatches(), numberOfVariables(), shark::IParameterizable< VectorType >::setParameterVector(), SHARK_PARALLEL_FOR, and SIZE_CHECK.
evalDerivative()
ResultType shark::NegativeLogLikelihood::evalDerivative (SearchPointType const & input, FirstOrderDerivative & derivative) const inline virtual
Evaluates the objective function and calculates its gradient.
Parameters
[in] input The argument to eval the function for.
[out] derivative The derivate is placed here.
Returns
The result of evaluating the function for the supplied argument.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 100 of file NegativeLogLikelihood.h.
References shark::AbstractObjectiveFunction< RealVector, double >::m_evaluationCounter, shark::Data< Type >::numberOfBatches(), shark::Data< Type >::numberOfElements(), numberOfVariables(), shark::IParameterizable< VectorType >::setParameterVector(), and SIZE_CHECK.
name()
std::string shark::NegativeLogLikelihood::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::INameable.
Definition at line 71 of file NegativeLogLikelihood.h.
numberOfVariables()
std::size_t shark::NegativeLogLikelihood::numberOfVariables () const inline virtual
Accesses the number of variables.
Implements shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 78 of file NegativeLogLikelihood.h.
References shark::IParameterizable< VectorType >::numberOfParameters().
Referenced by eval(), and evalDerivative().
proposeStartingPoint()
SearchPointType shark::NegativeLogLikelihood::proposeStartingPoint () const inline virtual
Proposes a starting point in the feasible search space of the function.
Returns
The generated starting point.
Exceptions
FeatureNotAvailableException in the default implementation and if a function does not support this feature.
Reimplemented from shark::AbstractObjectiveFunction< RealVector, double >.
Definition at line 74 of file NegativeLogLikelihood.h.
References shark::IParameterizable< VectorType >::parameterVector().
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/NegativeLogLikelihood.h