shark::ModifiedKernelMatrix< InputType, CacheType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::ModifiedKernelMatrix< InputType, CacheType > Class Template Reference
Modified Kernel Gram matrix.
#include <shark/LinAlg/ModifiedKernelMatrix.h>
Public Types
typedef Matrix::QpFloatType QpFloatType
Public Member Functions
ModifiedKernelMatrix (AbstractKernelFunction< InputType > const &kernelfunction, LabeledData< InputType, unsigned int > const &data, QpFloatType modifierEq, QpFloatType modifierNe)
QpFloatType operator() (std::size_t i, std::size_t j) const
return a single matrix entry
QpFloatType entry (std::size_t i, std::size_t j) const
return a single matrix entry
void row (std::size_t i, std::size_t start, std::size_t end, QpFloatType *storage) const
Computes the i-th row of the kernel matrix.
template<class M >
void matrix (blas::matrix_expression< M, blas::cpu_tag > &storage) const
Computes the kernel-matrix.
void flipColumnsAndRows (std::size_t i, std::size_t j)
swap two variables
std::size_t size () const
return the size of the quadratic matrix
unsigned long long getAccessCount () const
query the kernel access counter
void resetAccessCount ()
reset the kernel access counter
Protected Attributes
Matrix m_matrix
Kernel matrix which computes the basic entries.
std::vector< unsigned int > m_labels
QpFloatType m_modifierEq
modifier in case the labels are equal
QpFloatType m_modifierNe
modifier in case the labels differ
Detailed Description
template<class InputType, class CacheType>
class shark::ModifiedKernelMatrix< InputType, CacheType >
Modified Kernel Gram matrix.
The ModifiedKernelMatrix represents the kernel matrix multiplied element-wise with a factor depending on the labels of the training examples. This is useful for the MCMMR method (multi-class maximum margin regression).
Definition at line 60 of file ModifiedKernelMatrix.h.
Member Typedef Documentation
QpFloatType
template<class InputType , class CacheType > typedef Matrix::QpFloatType shark::ModifiedKernelMatrix< InputType, CacheType >::QpFloatType
Definition at line 65 of file ModifiedKernelMatrix.h.
Constructor & Destructor Documentation
ModifiedKernelMatrix()
template<class InputType , class CacheType > shark::ModifiedKernelMatrix< InputType, CacheType >::ModifiedKernelMatrix (AbstractKernelFunction< InputType > const & kernelfunction, LabeledData< InputType, unsigned int > const & data, QpFloatType modifierEq, QpFloatType modifierNe) inline
Constructor
Parameters
kernelfunction kernel function
data data to evaluate the kernel function
modifierEq multiplier for same-class labels
modifierNe multiplier for different-class kernels
Definition at line 72 of file ModifiedKernelMatrix.h.
References shark::LabeledData< InputT, LabelT >::element(), and shark::ModifiedKernelMatrix< InputType, CacheType >::m_labels.
Member Function Documentation
entry()
template<class InputType , class CacheType > QpFloatType shark::ModifiedKernelMatrix< InputType, CacheType >::entry (std::size_t i, std::size_t j) const inline
return a single matrix entry
Definition at line 91 of file ModifiedKernelMatrix.h.
References shark::ModifiedKernelMatrix< InputType, CacheType >::m_labels, shark::ModifiedKernelMatrix< InputType, CacheType >::m_matrix, shark::ModifiedKernelMatrix< InputType, CacheType >::m_modifierEq, and shark::ModifiedKernelMatrix< InputType, CacheType >::m_modifierNe.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::operator()().
flipColumnsAndRows()
template<class InputType , class CacheType > void shark::ModifiedKernelMatrix< InputType, CacheType >::flipColumnsAndRows (std::size_t i, std::size_t j) inline
swap two variables
Definition at line 128 of file ModifiedKernelMatrix.h.
References shark::KernelMatrix< InputType, CacheType >::flipColumnsAndRows(), shark::ModifiedKernelMatrix< InputType, CacheType >::m_labels, shark::ModifiedKernelMatrix< InputType, CacheType >::m_matrix, and shark::swap().
getAccessCount()
template<class InputType , class CacheType > unsigned long long shark::ModifiedKernelMatrix< InputType, CacheType >::getAccessCount () const inline
query the kernel access counter
Definition at line 138 of file ModifiedKernelMatrix.h.
References shark::KernelMatrix< InputType, CacheType >::getAccessCount(), and shark::ModifiedKernelMatrix< InputType, CacheType >::m_matrix.
matrix()
template<class InputType , class CacheType > template<class M > void shark::ModifiedKernelMatrix< InputType, CacheType >::matrix (blas::matrix_expression< M, blas::cpu_tag > & storage) const inline
Computes the kernel-matrix.
Definition at line 114 of file ModifiedKernelMatrix.h.
References shark::ModifiedKernelMatrix< InputType, CacheType >::m_labels, shark::ModifiedKernelMatrix< InputType, CacheType >::m_matrix, shark::ModifiedKernelMatrix< InputType, CacheType >::m_modifierEq, shark::ModifiedKernelMatrix< InputType, CacheType >::m_modifierNe, shark::KernelMatrix< InputType, CacheType >::matrix(), and shark::ModifiedKernelMatrix< InputType, CacheType >::size().
operator()()
template<class InputType , class CacheType > QpFloatType shark::ModifiedKernelMatrix< InputType, CacheType >::operator() (std::size_t i, std::size_t j) const inline
return a single matrix entry
Definition at line 87 of file ModifiedKernelMatrix.h.
References shark::ModifiedKernelMatrix< InputType, CacheType >::entry().
resetAccessCount()
template<class InputType , class CacheType > void shark::ModifiedKernelMatrix< InputType, CacheType >::resetAccessCount () inline
reset the kernel access counter
Definition at line 142 of file ModifiedKernelMatrix.h.
References shark::ModifiedKernelMatrix< InputType, CacheType >::m_matrix, and shark::KernelMatrix< InputType, CacheType >::resetAccessCount().
row()
template<class InputType , class CacheType > void shark::ModifiedKernelMatrix< InputType, CacheType >::row (std::size_t i, std::size_t start, std::size_t end, QpFloatType * storage) const inline
Computes the i-th row of the kernel matrix.
The entries start,...,end of the i-th row are computed and stored in storage. There must be enough room for this operation preallocated.
Definition at line 102 of file ModifiedKernelMatrix.h.
References shark::ModifiedKernelMatrix< InputType, CacheType >::m_labels, shark::ModifiedKernelMatrix< InputType, CacheType >::m_matrix, shark::ModifiedKernelMatrix< InputType, CacheType >::m_modifierEq, shark::ModifiedKernelMatrix< InputType, CacheType >::m_modifierNe, and shark::KernelMatrix< InputType, CacheType >::row().
size()
template<class InputType , class CacheType > std::size_t shark::ModifiedKernelMatrix< InputType, CacheType >::size () const inline
return the size of the quadratic matrix
Definition at line 134 of file ModifiedKernelMatrix.h.
References shark::ModifiedKernelMatrix< InputType, CacheType >::m_matrix, and shark::KernelMatrix< InputType, CacheType >::size().
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::matrix().
Member Data Documentation
m_labels
template<class InputType , class CacheType > std::vector<unsigned int> shark::ModifiedKernelMatrix< InputType, CacheType >::m_labels protected
Definition at line 148 of file ModifiedKernelMatrix.h.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::entry(), shark::ModifiedKernelMatrix< InputType, CacheType >::flipColumnsAndRows(), shark::ModifiedKernelMatrix< InputType, CacheType >::matrix(), shark::ModifiedKernelMatrix< InputType, CacheType >::ModifiedKernelMatrix(), and shark::ModifiedKernelMatrix< InputType, CacheType >::row().
m_matrix
template<class InputType , class CacheType > Matrix shark::ModifiedKernelMatrix< InputType, CacheType >::m_matrix protected
Kernel matrix which computes the basic entries.
Definition at line 147 of file ModifiedKernelMatrix.h.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::entry(), shark::ModifiedKernelMatrix< InputType, CacheType >::flipColumnsAndRows(), shark::ModifiedKernelMatrix< InputType, CacheType >::getAccessCount(), shark::ModifiedKernelMatrix< InputType, CacheType >::matrix(), shark::ModifiedKernelMatrix< InputType, CacheType >::resetAccessCount(), shark::ModifiedKernelMatrix< InputType, CacheType >::row(), and shark::ModifiedKernelMatrix< InputType, CacheType >::size().
m_modifierEq
template<class InputType , class CacheType > QpFloatType shark::ModifiedKernelMatrix< InputType, CacheType >::m_modifierEq protected
modifier in case the labels are equal
Definition at line 151 of file ModifiedKernelMatrix.h.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::entry(), shark::ModifiedKernelMatrix< InputType, CacheType >::matrix(), and shark::ModifiedKernelMatrix< InputType, CacheType >::row().
m_modifierNe
template<class InputType , class CacheType > QpFloatType shark::ModifiedKernelMatrix< InputType, CacheType >::m_modifierNe protected
modifier in case the labels differ
Definition at line 154 of file ModifiedKernelMatrix.h.
Referenced by shark::ModifiedKernelMatrix< InputType, CacheType >::entry(), shark::ModifiedKernelMatrix< InputType, CacheType >::matrix(), and shark::ModifiedKernelMatrix< InputType, CacheType >::row().
The documentation for this class was generated from the following file:
include/shark/LinAlg/ModifiedKernelMatrix.h