shark::MissingFeaturesKernelExpansion< InputType > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::MissingFeaturesKernelExpansion< InputType > Class Template Reference
Models
Kernel expansion with missing features support For a choice of kernel, see Kernels.
#include <shark/Models/Kernels/MissingFeaturesKernelExpansion.h>
Public Types
typedef Base::KernelType KernelType
typedef Base::BatchInputType BatchInputType
typedef Base::BatchOutputType BatchOutputType
Public Types inherited from shark::KernelExpansion< InputType >
typedef AbstractKernelFunction< InputType > KernelType
typedef base_type::BatchInputType BatchInputType
typedef base_type::BatchOutputType BatchOutputType
Public Types inherited from shark::AbstractModel< InputType, RealVector >
enum Feature
typedef InputType InputType
Defines the input type of the model.
typedef RealVector OutputType
Defines the output type of the model.
typedef AbstractModel< InputType, RealVector, RealVector > ModelBaseType
Defines the BaseType used by the model (this type). Useful for creating derived models.
typedef Batch< InputType >::type BatchInputType
defines the batch type of the input type.
typedef Batch< OutputType >::type BatchOutputType
defines the batch type of the output type
typedef TypedFlags< Feature > Features
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Types inherited from shark::IParameterizable< RealVector >
typedef RealVector ParameterVectorType
Public Member Functions
std::string name () const
From INameable: return the class name.
boost::shared_ptr< State > createState () const
Creates an internal state of the model.
virtual void eval (BatchInputType const &patterns, BatchOutputType &outputs) const
Override eval(...) in the base class.
void eval (BatchInputType const &patterns, BatchOutputType &outputs, State &state) const
Standard interface for evaluating the response of the model to a batch of patterns.
template<class InputTypeT >
double computeNorm (const RealVector &alpha, const RealVector &scalingCoefficient, InputTypeT const &missingness) const
double computeNorm (const RealVector &alpha, const RealVector &scalingCoefficient) const
void setScalingCoefficients (const RealVector &scalingCoefficients)
void setClassifierNorm (double classifierNorm)
MissingFeaturesKernelExpansion ()
MissingFeaturesKernelExpansion (KernelType *kernel)
MissingFeaturesKernelExpansion (KernelType *kernel, Data< InputType > const &basis, bool offset)
Public Member Functions inherited from shark::KernelExpansion< InputType >
KernelExpansion ()
KernelExpansion (KernelType *kernel)
KernelExpansion (KernelType *kernel, Data< InputType > const &basis, bool offset, std::size_t outputs=1)
void setStructure (KernelType *kernel, Data< InputType > const &basis, bool offset, std::size_t outputs=1)
Shape outputShape () const
dimensionality of the output RealVector
Shape inputShape () const
Returns the expected shape of the input.
KernelType const * kernel () const
KernelType * kernel ()
void setKernel (KernelType *kernel)
bool hasOffset () const
RealMatrix & alpha ()
RealMatrix const & alpha () const
double & alpha (std::size_t example, std::size_t cls)
double const & alpha (std::size_t example, std::size_t cls) const
RealVector & offset ()
RealVector const & offset () const
double & offset (std::size_t cls)
double const & offset (std::size_t cls) const
Data< InputType > const & basis () const
Data< InputType > & basis ()
void sparsify ()
RealVector parameterVector () const
Return the parameter vector.
void setParameterVector (RealVector const &newParameters)
Set the parameter vector.
std::size_t numberOfParameters () const
Return the number of parameters.
void read (InArchive &archive)
From ISerializable, reads a model from an archive.
void write (OutArchive &archive) const
From ISerializable, writes a model to an archive.
Public Member Functions inherited from shark::AbstractModel< InputType, RealVector >
AbstractModel ()
virtual ~AbstractModel ()
const Features & features () const
virtual void updateFeatures ()
bool hasFirstParameterDerivative () const
Returns true when the first parameter derivative is implemented.
bool hasFirstInputDerivative () const
Returns true when the first input derivative is implemented.
virtual void eval (InputType const &pattern, OutputType &output) const
Standard interface for evaluating the response of the model to a single pattern.
Data< OutputType > operator() (Data< InputType > const &patterns) const
Model evaluation as an operator for a whole dataset. This is a convenience function.
OutputType operator() (InputType const &pattern) const
Model evaluation as an operator for a single pattern. This is a convenience function.
BatchOutputType operator() (BatchInputType const &patterns) const
Model evaluation as an operator for a single pattern. This is a convenience function.
virtual void weightedParameterDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, RealVector &derivative) const
calculates the weighted sum of derivatives w.r.t the parameters.
virtual void weightedInputDerivative (BatchInputType const &pattern, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, BatchInputType &derivative) const
calculates the weighted sum of derivatives w.r.t the inputs
virtual void weightedDerivatives (BatchInputType const &patterns, BatchOutputType const &outputs, BatchOutputType const &coefficients, State const &state, RealVector &parameterDerivative, BatchInputType &inputDerivative) const
calculates weighted input and parameter derivative at the same time
Public Member Functions inherited from shark::IParameterizable< RealVector >
virtual ~IParameterizable ()
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
Public Member Functions inherited from shark::ISerializable
virtual ~ISerializable ()
Virtual d'tor.
void load (InArchive &archive, unsigned int version)
Versioned loading of components, calls read(...).
void save (OutArchive &archive, unsigned int version) const
Versioned storing of components, calls write(...).
BOOST_SERIALIZATION_SPLIT_MEMBER ()
Protected Attributes
RealVector m_scalingCoefficients
The scaling coefficients.
double m_classifierNorm
The norm of classifier(w)
Protected Attributes inherited from shark::KernelExpansion< InputType >
KernelType * mep_kernel
kernel function used in the expansion
Data< InputType > m_basis
"support" basis vectors
RealMatrix m_alpha
kernel coefficients
RealVector m_b
offset or bias term
Protected Attributes inherited from shark::AbstractModel< InputType, RealVector >
Features m_features
Detailed Description
template<class InputType>
class shark::MissingFeaturesKernelExpansion< InputType >
Kernel expansion with missing features support For a choice of kernel, see Kernels.
Definition at line 45 of file MissingFeaturesKernelExpansion.h.
Member Typedef Documentation
BatchInputType
template<class InputType> typedef Base::BatchInputType shark::MissingFeaturesKernelExpansion< InputType >::BatchInputType
Definition at line 51 of file MissingFeaturesKernelExpansion.h.
BatchOutputType
template<class InputType> typedef Base::BatchOutputType shark::MissingFeaturesKernelExpansion< InputType >::BatchOutputType
Definition at line 52 of file MissingFeaturesKernelExpansion.h.
KernelType
template<class InputType> typedef Base::KernelType shark::MissingFeaturesKernelExpansion< InputType >::KernelType
Definition at line 50 of file MissingFeaturesKernelExpansion.h.
Constructor & Destructor Documentation
MissingFeaturesKernelExpansion() [1/3]
template<class InputType> shark::MissingFeaturesKernelExpansion< InputType >::MissingFeaturesKernelExpansion () inline
Constructors from the base class
Definition at line 55 of file MissingFeaturesKernelExpansion.h.
MissingFeaturesKernelExpansion() [2/3]
template<class InputType> shark::MissingFeaturesKernelExpansion< InputType >::MissingFeaturesKernelExpansion (KernelType * kernel) inline
Definition at line 58 of file MissingFeaturesKernelExpansion.h.
MissingFeaturesKernelExpansion() [3/3]
template<class InputType> shark::MissingFeaturesKernelExpansion< InputType >::MissingFeaturesKernelExpansion (KernelType * kernel, Data< InputType > const & basis, bool offset) inline
Definition at line 62 of file MissingFeaturesKernelExpansion.h.
Member Function Documentation
computeNorm() [1/2]
template<class InputType> template<class InputTypeT > double shark::MissingFeaturesKernelExpansion< InputType >::computeNorm (const RealVector & alpha, const RealVector & scalingCoefficient, InputTypeT const & missingness) const inline
Calculate norm of classifier, i.e., ||w||
formula: \(\sum_{i,j=1}^{n}\alpha_i\frac{y_i}{s_i}K\left(x_i,x_j)\right)\frac{y_j}{s_j}\alpha_j \) where \(s_i \) is scaling coefficient, and \(K \) is kernel function, \(K\left(x_i,x_j)\right) \) is taken only over features that are valid for both \(x_i \) and \(x_j \)
Definition at line 121 of file MissingFeaturesKernelExpansion.h.
References shark::KernelExpansion< InputType >::alpha(), shark::KernelExpansion< InputType >::m_basis, shark::KernelExpansion< InputType >::mep_kernel, SHARK_ASSERT, and SIZE_CHECK.
computeNorm() [2/2]
template<class InputType> double shark::MissingFeaturesKernelExpansion< InputType >::computeNorm (const RealVector & alpha, const RealVector & scalingCoefficient) const inline
Definition at line 153 of file MissingFeaturesKernelExpansion.h.
References shark::KernelExpansion< InputType >::alpha(), shark::KernelExpansion< InputType >::m_basis, shark::KernelExpansion< InputType >::mep_kernel, SHARK_ASSERT, and SIZE_CHECK.
createState()
template<class InputType> boost::shared_ptr<State> shark::MissingFeaturesKernelExpansion< InputType >::createState () const inline virtual
Creates an internal state of the model.
The state is needed when the derivatives are to be calculated. Eval can store a state which is then reused to speed up the calculations of the derivatives. This also allows eval to be evaluated in parallel!
Reimplemented from shark::KernelExpansion< InputType >.
Definition at line 71 of file MissingFeaturesKernelExpansion.h.
eval() [1/2]
template<class InputType> virtual void shark::MissingFeaturesKernelExpansion< InputType >::eval (BatchInputType const & patterns, BatchOutputType & outputs) const inline virtual
Override eval(...) in the base class.
Reimplemented from shark::KernelExpansion< InputType >.
Definition at line 76 of file MissingFeaturesKernelExpansion.h.
References shark::batchSize(), shark::KernelExpansion< InputType >::hasOffset(), shark::KernelExpansion< InputType >::m_alpha, shark::KernelExpansion< InputType >::m_basis, shark::KernelExpansion< InputType >::mep_kernel, shark::KernelExpansion< InputType >::outputShape(), SHARK_ASSERT, and SIZE_CHECK.
Referenced by shark::MissingFeaturesKernelExpansion< InputType >::eval().
eval() [2/2]
template<class InputType> void shark::MissingFeaturesKernelExpansion< InputType >::eval (BatchInputType const & patterns, BatchOutputType & outputs, State & state) const inline virtual
Standard interface for evaluating the response of the model to a batch of patterns.
Parameters
patterns the inputs of the model
outputs the predictions or response of the model to every pattern
state intermediate results stored by eval which can be reused for derivative computation.
Reimplemented from shark::KernelExpansion< InputType >.
Definition at line 110 of file MissingFeaturesKernelExpansion.h.
References shark::MissingFeaturesKernelExpansion< InputType >::eval().
name()
template<class InputType> std::string shark::MissingFeaturesKernelExpansion< InputType >::name () const inline virtual
From INameable: return the class name.
Reimplemented from shark::KernelExpansion< InputType >.
Definition at line 68 of file MissingFeaturesKernelExpansion.h.
setClassifierNorm()
template<class InputType> void shark::MissingFeaturesKernelExpansion< InputType >::setClassifierNorm (double classifierNorm) inline
Definition at line 194 of file MissingFeaturesKernelExpansion.h.
References shark::MissingFeaturesKernelExpansion< InputType >::m_classifierNorm, and SHARK_ASSERT.
setScalingCoefficients()
template<class InputType> void shark::MissingFeaturesKernelExpansion< InputType >::setScalingCoefficients (const RealVector & scalingCoefficients) inline
Definition at line 183 of file MissingFeaturesKernelExpansion.h.
References shark::MissingFeaturesKernelExpansion< InputType >::m_scalingCoefficients, and SHARK_ASSERT.
Member Data Documentation
m_classifierNorm
template<class InputType> double shark::MissingFeaturesKernelExpansion< InputType >::m_classifierNorm protected
The norm of classifier(w)
Definition at line 205 of file MissingFeaturesKernelExpansion.h.
Referenced by shark::MissingFeaturesKernelExpansion< InputType >::setClassifierNorm().
m_scalingCoefficients
template<class InputType> RealVector shark::MissingFeaturesKernelExpansion< InputType >::m_scalingCoefficients protected
The scaling coefficients.
Definition at line 202 of file MissingFeaturesKernelExpansion.h.
Referenced by shark::MissingFeaturesKernelExpansion< InputType >::setScalingCoefficients().
The documentation for this class was generated from the following file:
include/shark/Models/Kernels/MissingFeaturesKernelExpansion.h