shark::EvaluationArchive< PointType, ResultT > Class Template Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::EvaluationArchive< PointType, ResultT > Class Template Reference
Objective functions
Objective function wrapper storing all function evaluations.
#include <shark/ObjectiveFunctions/EvaluationArchive.h>
Classes
class PointResultPairType
Pair of point and result.
Public Types
typedef base_type::SearchPointType SearchPointType
typedef base_type::ResultType ResultType
typedef base_type::FirstOrderDerivative FirstOrderDerivative
typedef base_type::SecondOrderDerivative SecondOrderDerivative
typedef std::set< PointResultPairType > PointResultPairContainer
typedef PointResultPairContainer::iterator PointResultPairIterator
typedef PointResultPairContainer::const_iterator PointResultPairConstIterator
Public Types inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
enum Feature {
HAS_VALUE = 1, HAS_FIRST_DERIVATIVE = 2, HAS_SECOND_DERIVATIVE = 4, CAN_PROPOSE_STARTING_POINT = 8,
IS_CONSTRAINED_FEATURE = 16, HAS_CONSTRAINT_HANDLER = 32, CAN_PROVIDE_CLOSEST_FEASIBLE = 64, IS_THREAD_SAFE = 128,
IS_NOISY = 256
}
List of features that are supported by an implementation.
typedef PointType SearchPointType
typedef ResultT ResultType
typedef boost::mpl::if_< std::is_arithmetic< ResultT >, SearchPointType, RealMatrix >::type FirstOrderDerivative
typedef TypedFlags< Feature > Features
This statement declares the member m_features. See Core/Flags.h for details.
typedef TypedFeatureNotAvailableException< Feature > FeatureNotAvailableException
Public Member Functions
EvaluationArchive (base_type *objective)
Constructor.
base_type * objective ()
Access to the underlying objective function.
const base_type * objective () const
Access to the underlying objective function.
void init ()
Wrapper function.
virtual std::size_t numberOfObjectives () const
Wrapper function.
bool hasScalableObjectives () const
Wrapper function.
void setNumberOfObjectives (std::size_t numberOfObjectives)
Wrapper function.
bool isFeasible (const SearchPointType &input) const
Wrapper function.
void closestFeasible (SearchPointType &input) const
Wrapper function.
void proposeStartingPoint (SearchPointType &startingPoint) const
Wrapper function.
std::size_t numberOfVariables () const
Wrapper function; conditional on vector space property.
ResultType eval (const SearchPointType &input) const
Wrapper function storing point and result.
ResultType operator() (const SearchPointType &input) const
ResultType evalDerivative (const SearchPointType &input, FirstOrderDerivative &derivative) const
Wrapper function storing point and result.
ResultType evalDerivative (const SearchPointType &input, SecondOrderDerivative &derivative) const
Wrapper function storing point and result.
std::size_t size () const
Return the size of the archive; which is the number of point/result pairs.
PointResultPairIterator begin ()
Begin iterator to the point/result pairs.
PointResultPairConstIterator begin () const
Begin iterator to the point/result pairs.
PointResultPairIterator end ()
End iterator to the point/result pairs.
PointResultPairConstIterator end () const
End iterator to the point/result pairs.
Public Member Functions inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
const Features & features () const
virtual void updateFeatures ()
bool hasValue () const
returns whether this function can calculate it's function value
bool hasFirstDerivative () const
returns whether this function can calculate the first derivative
bool hasSecondDerivative () const
returns whether this function can calculate the second derivative
bool canProposeStartingPoint () const
returns whether this function can propose a starting point.
bool isConstrained () const
returns whether this function can return
bool hasConstraintHandler () const
returns whether this function can return
bool canProvideClosestFeasible () const
Returns whether this function can calculate thee closest feasible to an infeasible point.
bool isThreadSafe () const
Returns true, when the function can be usd in parallel threads.
bool isNoisy () const
Returns true, when the function can be usd in parallel threads.
AbstractObjectiveFunction ()
Default ctor.
virtual ~AbstractObjectiveFunction ()
Virtual destructor.
void setRng (random::rng_type *rng)
Sets the Rng used by the objective function.
virtual bool hasScalableDimensionality () const
virtual void setNumberOfVariables (std::size_t numberOfVariables)
Adjusts the number of variables if the function is scalable.
std::size_t evaluationCounter () const
Accesses the evaluation counter of the function.
AbstractConstraintHandler< SearchPointType > const & getConstraintHandler () const
Returns the constraint handler of the function if it has one.
virtual SearchPointType proposeStartingPoint () const
Proposes a starting point in the feasible search space of the function.
ResultType operator() (SearchPointType const &input) const
Evaluates the function. Useful together with STL-Algorithms like std::transform.
Public Member Functions inherited from shark::INameable
virtual ~INameable ()
virtual std::string name () const
returns the name of the object
Additional Inherited Members
Protected Member Functions inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
void announceConstraintHandler (AbstractConstraintHandler< SearchPointType > const *handler)
helper function which is called to announce the presence of an constraint handler.
Protected Attributes inherited from shark::AbstractObjectiveFunction< PointType, ResultT >
Features m_features
std::size_t m_evaluationCounter
Evaluation counter, default value: 0.
AbstractConstraintHandler< SearchPointType > const * m_constraintHandler
random::rng_type * mep_rng
Detailed Description
template<typename PointType, typename ResultT>
class shark::EvaluationArchive< PointType, ResultT >
Objective function wrapper storing all function evaluations.
Template Parameters
PointType The search space the function is defined upon.
ResultT The objective space the function is defined upon.
The EvaluationArchive class serves as an archive of all evaluated points and the corresponding result. It can be used transparently instead of the original objective function, e.g., by an optimizer. Point/result pairs are added to the archive only if the specific combination is not yet stored.
For fast-to-evaluate objective functions the archive wrapper can be a considerable performance killer. However, whenever function evaluations are costly (and an archive makes sense) then the storage and maintenance overhead should be negligible.
Definition at line 68 of file EvaluationArchive.h.
Member Typedef Documentation
FirstOrderDerivative
template<typename PointType, typename ResultT> typedef base_type::FirstOrderDerivative shark::EvaluationArchive< PointType, ResultT >::FirstOrderDerivative
Definition at line 75 of file EvaluationArchive.h.
PointResultPairConstIterator
template<typename PointType, typename ResultT> typedef PointResultPairContainer::const_iterator shark::EvaluationArchive< PointType, ResultT >::PointResultPairConstIterator
Definition at line 118 of file EvaluationArchive.h.
PointResultPairContainer
template<typename PointType, typename ResultT> typedef std::set<PointResultPairType> shark::EvaluationArchive< PointType, ResultT >::PointResultPairContainer
Definition at line 116 of file EvaluationArchive.h.
PointResultPairIterator
template<typename PointType, typename ResultT> typedef PointResultPairContainer::iterator shark::EvaluationArchive< PointType, ResultT >::PointResultPairIterator
Definition at line 117 of file EvaluationArchive.h.
ResultType
template<typename PointType, typename ResultT> typedef base_type::ResultType shark::EvaluationArchive< PointType, ResultT >::ResultType
Definition at line 73 of file EvaluationArchive.h.
SearchPointType
template<typename PointType, typename ResultT> typedef base_type::SearchPointType shark::EvaluationArchive< PointType, ResultT >::SearchPointType
Definition at line 72 of file EvaluationArchive.h.
SecondOrderDerivative
template<typename PointType, typename ResultT> typedef base_type::SecondOrderDerivative shark::EvaluationArchive< PointType, ResultT >::SecondOrderDerivative
Definition at line 76 of file EvaluationArchive.h.
Constructor & Destructor Documentation
EvaluationArchive()
template<typename PointType, typename ResultT> shark::EvaluationArchive< PointType, ResultT >::EvaluationArchive (base_type * objective) inline
Constructor.
The constructor takes the objective function to be wrapped as an argument. It is assumed that the objective object's life time exceeds the life time of the present instance.
Definition at line 126 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::features(), shark::AbstractObjectiveFunction< PointType, ResultT >::getConstraintHandler(), shark::AbstractObjectiveFunction< PointType, ResultT >::hasConstraintHandler(), shark::AbstractObjectiveFunction< PointType, ResultT >::m_constraintHandler, and shark::AbstractObjectiveFunction< PointType, ResultT >::m_features.
Member Function Documentation
begin() [1/2]
template<typename PointType, typename ResultT> PointResultPairIterator shark::EvaluationArchive< PointType, ResultT >::begin () inline
Begin iterator to the point/result pairs.
Definition at line 221 of file EvaluationArchive.h.
begin() [2/2]
template<typename PointType, typename ResultT> PointResultPairConstIterator shark::EvaluationArchive< PointType, ResultT >::begin () const inline
Begin iterator to the point/result pairs.
Definition at line 225 of file EvaluationArchive.h.
closestFeasible()
template<typename PointType, typename ResultT> void shark::EvaluationArchive< PointType, ResultT >::closestFeasible (SearchPointType & input) const inline virtual
Wrapper function.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 165 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::closestFeasible().
end() [1/2]
template<typename PointType, typename ResultT> PointResultPairIterator shark::EvaluationArchive< PointType, ResultT >::end () inline
End iterator to the point/result pairs.
Definition at line 229 of file EvaluationArchive.h.
end() [2/2]
template<typename PointType, typename ResultT> PointResultPairConstIterator shark::EvaluationArchive< PointType, ResultT >::end () const inline
End iterator to the point/result pairs.
Definition at line 233 of file EvaluationArchive.h.
eval()
template<typename PointType, typename ResultT> ResultType shark::EvaluationArchive< PointType, ResultT >::eval (const SearchPointType & input) const inline virtual
Wrapper function storing point and result.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 179 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::eval(), and shark::AbstractObjectiveFunction< PointType, ResultT >::m_evaluationCounter.
Referenced by shark::EvaluationArchive< PointType, ResultT >::operator()().
evalDerivative() [1/2]
template<typename PointType, typename ResultT> ResultType shark::EvaluationArchive< PointType, ResultT >::evalDerivative (const SearchPointType & input, FirstOrderDerivative & derivative) const inline virtual
Wrapper function storing point and result.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 194 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::evalDerivative(), and shark::AbstractObjectiveFunction< PointType, ResultT >::m_evaluationCounter.
evalDerivative() [2/2]
template<typename PointType, typename ResultT> ResultType shark::EvaluationArchive< PointType, ResultT >::evalDerivative (const SearchPointType & input, SecondOrderDerivative & derivative) const inline virtual
Wrapper function storing point and result.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 203 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::evalDerivative(), and shark::AbstractObjectiveFunction< PointType, ResultT >::m_evaluationCounter.
hasScalableObjectives()
template<typename PointType, typename ResultT> bool shark::EvaluationArchive< PointType, ResultT >::hasScalableObjectives () const inline virtual
Wrapper function.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 153 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::hasScalableObjectives().
init()
template<typename PointType, typename ResultT> void shark::EvaluationArchive< PointType, ResultT >::init () inline virtual
Wrapper function.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 143 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::init(), shark::AbstractObjectiveFunction< PointType, ResultT >::mep_rng, and shark::AbstractObjectiveFunction< PointType, ResultT >::setRng().
isFeasible()
template<typename PointType, typename ResultT> bool shark::EvaluationArchive< PointType, ResultT >::isFeasible (const SearchPointType & input) const inline virtual
Wrapper function.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 161 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::isFeasible().
numberOfObjectives()
template<typename PointType, typename ResultT> virtual std::size_t shark::EvaluationArchive< PointType, ResultT >::numberOfObjectives () const inline virtual
Wrapper function.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 149 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::numberOfObjectives().
Referenced by shark::EvaluationArchive< PointType, ResultT >::setNumberOfObjectives().
numberOfVariables()
template<typename PointType, typename ResultT> std::size_t shark::EvaluationArchive< PointType, ResultT >::numberOfVariables () const inline virtual
Wrapper function; conditional on vector space property.
Implements shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 173 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::numberOfVariables().
objective() [1/2]
template<typename PointType, typename ResultT> base_type* shark::EvaluationArchive< PointType, ResultT >::objective () inline
Access to the underlying objective function.
Definition at line 135 of file EvaluationArchive.h.
objective() [2/2]
template<typename PointType, typename ResultT> const base_type* shark::EvaluationArchive< PointType, ResultT >::objective () const inline
Access to the underlying objective function.
Definition at line 139 of file EvaluationArchive.h.
operator()()
template<typename PointType, typename ResultT> ResultType shark::EvaluationArchive< PointType, ResultT >::operator() (const SearchPointType & input) const inline
Definition at line 190 of file EvaluationArchive.h.
References shark::EvaluationArchive< PointType, ResultT >::eval().
proposeStartingPoint()
template<typename PointType, typename ResultT> void shark::EvaluationArchive< PointType, ResultT >::proposeStartingPoint (SearchPointType & startingPoint) const inline
Wrapper function.
Definition at line 169 of file EvaluationArchive.h.
References shark::AbstractObjectiveFunction< PointType, ResultT >::proposeStartingPoint().
setNumberOfObjectives()
template<typename PointType, typename ResultT> void shark::EvaluationArchive< PointType, ResultT >::setNumberOfObjectives (std::size_t numberOfObjectives) inline virtual
Wrapper function.
Reimplemented from shark::AbstractObjectiveFunction< PointType, ResultT >.
Definition at line 157 of file EvaluationArchive.h.
References shark::EvaluationArchive< PointType, ResultT >::numberOfObjectives(), and shark::AbstractObjectiveFunction< PointType, ResultT >::setNumberOfObjectives().
size()
template<typename PointType, typename ResultT> std::size_t shark::EvaluationArchive< PointType, ResultT >::size () const inline
Return the size of the archive; which is the number of point/result pairs.
Definition at line 217 of file EvaluationArchive.h.
The documentation for this class was generated from the following file:
include/shark/ObjectiveFunctions/EvaluationArchive.h