examples/Benchmark/shark/logistic_regression_LBFGS.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
logistic_regression_LBFGS.cpp File Reference
#include <shark/Data/SparseData.h>
#include <shark/ObjectiveFunctions/Loss/CrossEntropy.h>
#include <shark/ObjectiveFunctions/Regularizer.h>
#include <shark/Algorithms/GradientDescent/LBFGS.h>
#include <shark/ObjectiveFunctions/ErrorFunction.h>
#include <shark/Models/LinearModel.h>
#include <shark/Core/Timer.h>
#include <iostream>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 14 of file logistic_regression_LBFGS.cpp.
References shark::Classifier< LinearModel< VectorType > >::decisionFunction(), shark::importSparseData(), shark::AbstractLineSearchOptimizer< SearchPointType >::init(), shark::inputDimension(), shark::LabeledData< InputT, LabelT >::inputs(), shark::LabeledData< InputT, LabelT >::labels(), shark::numberOfClasses(), shark::ResultSet< SearchPointT, ResultT >::point, shark::Classifier< LinearModel< VectorType > >::setParameterVector(), shark::ErrorFunction< SearchPointType >::setRegularizer(), shark::AbstractSingleObjectiveOptimizer< PointType >::solution(), shark::AbstractLineSearchOptimizer< SearchPointType >::step(), and shark::Timer::stop().