shark::random Namespace Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::random Namespace Reference
Functions
template<class RngType >
bool coinToss (RngType &rng, double pHeads=0.5)
Flips a coin with probability of heads being pHeads by drawing random numbers from rng.
template<class RngType >
double uni (RngType &rng, double lower=0.0, double upper=1.0)
Draws a number uniformly in [lower,upper] by drawing random numbers from rng.
template<class RngType , class T >
T discrete (RngType &rng, T low, T high)
Draws a discrete number in {low,low+1,...,high} by drawing random numbers from rng.
template<class RngType >
double gauss (RngType &rng, double mean=0.0, double variance=1.0)
Draws a number from the normal distribution with given mean and variance by drawing random numbers from rng.
template<class RngType >
double logNormal (RngType &rng, double m=0.0, double v=1.0)
Draws a number from the log-normal distribution as exp(gauss(m,v))
template<class RngType >
double truncExp (RngType &rng, double lambda, double maximum, double Z=-1.0)
draws a number from the truncated exponential distribution
Variables
SHARK_EXPORT_SYMBOL rng_type globalRng
Function Documentation
coinToss()
template<class RngType > bool shark::random::coinToss (RngType & rng, double pHeads = 0.5)
Flips a coin with probability of heads being pHeads by drawing random numbers from rng.
Definition at line 48 of file Random.h.
Referenced by createProblem(), shark::CircleInSquare::draw(), shark::DropoutLayer< VectorType >::eval(), shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >::generateOffspring(), main(), shark::PolynomialMutator::operator()(), shark::SimulatedBinaryCrossover< RealVector >::operator()(), shark::BitflipMutator::operator()(), shark::MultiNomialDistribution::operator()(), shark::BipolarLayer::sample(), and shark::BinaryLayer::sample().
discrete()
template<class RngType , class T > T shark::random::discrete (RngType & rng, T low, T high)
Draws a discrete number in {low,low+1,...,high} by drawing random numbers from rng.
Definition at line 62 of file Random.h.
Referenced by shark::bootstrap(), shark::createCVIID(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::doInit(), shark::IndicatorBasedMOCMA< Indicator >::doInit(), shark::SMSEMOA::doInit(), shark::IndicatorBasedRealCodedNSGAII< NSGA3Indicator >::doInit(), shark::PamiToy::draw(), shark::ImagePatches::draw(), shark::IndicatorBasedSteadyStateMOCMA< Indicator >::generateOffspring(), shark::PartiallyMappedCrossover::operator()(), shark::OnePointCrossover::operator()(), shark::MultiNomialDistribution::operator()(), shark::benchmarks::MultiObjectiveBenchmark< Objectives >::proposeStartingPoint(), shark::shuffle(), shark::RFTrainer< unsigned int >::train(), shark::KernelBudgetedSGDTrainer< InputType, CacheType >::train(), and shark::RFTrainer< RealVector >::train().
gauss()
template<class RngType > double shark::random::gauss (RngType & rng, double mean = 0.0, double variance = 1.0)
Draws a number from the normal distribution with given mean and variance by drawing random numbers from rng.
Definition at line 69 of file Random.h.
References shark::mean(), and shark::variance().
Referenced by shark::Wave::draw(), shark::PamiToy::draw(), shark::MultiVariateNormalDistributionCholesky::generate(), shark::benchmarks::MultiObjectiveBenchmark< Objectives >::init(), logNormal(), main(), shark::MultiVariateNormalDistribution::operator()(), shark::benchmarks::Schwefel::proposeStartingPoint(), shark::benchmarks::Sphere::proposeStartingPoint(), shark::benchmarks::ConstrainedSphere::proposeStartingPoint(), shark::benchmarks::MultiObjectiveBenchmark< Objectives >::proposeStartingPoint(), and shark::GaussianLayer::sample().
logNormal()
template<class RngType > double shark::random::logNormal (RngType & rng, double m = 0.0, double v = 1.0)
Draws a number from the log-normal distribution as exp(gauss(m,v))
Definition at line 76 of file Random.h.
References gauss().
truncExp()
template<class RngType > double shark::random::truncExp (RngType & rng, double lambda, double maximum, double Z = -1.0)
draws a number from the truncated exponential distribution
draws from the exponential distribution p(x|lambda)= 1/Z exp(-lambda*x) subject to x < maximum as optuonal third argument it is possible to return the precomputed value of Z.
Definition at line 85 of file Random.h.
References uni().
uni()
template<class RngType > double shark::random::uni (RngType & rng, double lower = 0.0, double upper = 1.0)
Draws a number uniformly in [lower,upper] by drawing random numbers from rng.
Definition at line 55 of file Random.h.
Referenced by shark::Chessboard::draw(), shark::Wave::draw(), shark::CircleInSquare::draw(), shark::DiagonalWithCircle::draw(), shark::BoxConstraintHandler< SearchPointType >::generateRandomPoint(), main(), shark::RouletteWheelSelection::operator()(), shark::PolynomialMutator::operator()(), shark::SimulatedBinaryCrossover< RealVector >::operator()(), shark::benchmarks::Himmelblau::proposeStartingPoint(), shark::benchmarks::Ackley::proposeStartingPoint(), shark::benchmarks::DiffPowers::proposeStartingPoint(), shark::benchmarks::Cigar::proposeStartingPoint(), shark::benchmarks::Discus::proposeStartingPoint(), shark::benchmarks::Ellipsoid::proposeStartingPoint(), shark::benchmarks::CigarDiscus::proposeStartingPoint(), shark::benchmarks::Rosenbrock::proposeStartingPoint(), shark::benchmarks::ELLI1::proposeStartingPoint(), shark::benchmarks::CIGTAB2::proposeStartingPoint(), shark::benchmarks::ELLI2::proposeStartingPoint(), shark::benchmarks::CIGTAB1::proposeStartingPoint(), and truncExp().
Variable Documentation
globalRng
SHARK_EXPORT_SYMBOL rng_type shark::random::globalRng
Referenced by shark::bootstrap(), shark::createCVBatch(), shark::createCVIID(), createProblem(), shark::Chessboard::draw(), shark::Wave::draw(), shark::PamiToy::draw(), shark::CircleInSquare::draw(), shark::DiagonalWithCircle::draw(), shark::ImagePatches::draw(), main(), shark::partial_shuffle(), shark::UnlabeledData< InputType >::shuffle(), shark::LabeledData< InputType, LabelType >::shuffle(), shark::LinearSAGTrainer< InputType, LabelType >::train(), shark::RFTrainer< unsigned int >::train(), shark::KernelBudgetedSGDTrainer< InputType, CacheType >::train(), shark::RFTrainer< RealVector >::train(), and trainRBM().