shark::statistics Namespace Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::statistics Namespace Reference
Classes
class BaseStatisticsObject
Base class for all Statistic Objects to be used with Statistics.
class FractionMissing
for a vector of points computes for every dimension the fraction of missing values
class LowerQuantile
For a vector of points computes for every dimension the 25%-quantile.
class Mean
For a vector of points computes for every dimension the mean.
class Median
For a vector of points computes for every dimension the median.
class Quantile
For a vector of points computes for every dimension the p-quantile.
class ResultTable
Stores results of a running experiment.
struct Statistics
Generates Statistics over the results of an experiment.
class UpperQuantile
For a vector of points computes for every dimension the 75%-quantile.
class Variance
For a vector of points computes for every dimension the variance.
Functions
double missingValue ()
bool isMissing (double value)
template<class Parameter >
void printCSV (Statistics< Parameter > const &statistics)
Function Documentation
isMissing()
bool shark::statistics::isMissing (double value) inline
Definition at line 62 of file Statistics.h.
Referenced by shark::statistics::FractionMissing::statistics(), shark::statistics::Variance::statistics(), and shark::statistics::Quantile::statistics().
missingValue()
double shark::statistics::missingValue () inline
Definition at line 58 of file Statistics.h.
Referenced by main(), and shark::statistics::Quantile::statistics().
printCSV()
template<class Parameter > void shark::statistics::printCSV (Statistics< Parameter > const & statistics)
Definition at line 356 of file Statistics.h.
References shark::statistics::Statistics< Parameter >::dimensionName(), shark::statistics::Statistics< Parameter >::numDimensions(), shark::statistics::Statistics< Parameter >::numParams(), shark::statistics::Statistics< Parameter >::numStatistics(), shark::statistics::Statistics< Parameter >::parameterName(), shark::statistics::Statistics< Parameter >::parameterValue(), and shark::statistics::Statistics< Parameter >::statisticName().
Referenced by main().