shark::image Namespace Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::image Namespace Reference
Functions
template<class T >
void maxPooling (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > inputs, Shape const &shape, Shape const &patchSize, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > outputs)
template<class T >
void maxPoolingDerivative (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > inputs, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > coefficients, Shape const &shape, Shape const &patchSize, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > derivatives)
template<class T >
void reorder_impl (blas::dense_vector_adaptor< T const, blas::continuous_dense_tag, blas::cpu_tag > inputs, blas::dense_vector_adaptor< T, blas::continuous_dense_tag, blas::cpu_tag > outputs, std::size_t sizes[4], std::size_t strides[4])
template<class T >
void splineInterpolation2D (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > images, Shape const &shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > points, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > values)
template<class T >
void splineInterpolation2D (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > images, Shape const &shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > points, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > values, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > valuesdx, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > valuesdy)
template<class T >
void splineInterpolation2DDerivative (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > imageDerivatives, Shape const &shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > points, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > results)
template<class T >
void maxPooling (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > inputs_unreg, Shape const &shape, Shape const &patchSize, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > outputs_unreg)
template<class T >
void maxPoolingDerivative (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > inputs_unreg, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > coefficients_unreg, Shape const &shape, Shape const &patchSize, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > derivatives_unreg)
template<class T >
void reorder_impl (blas::dense_vector_adaptor< T const, blas::continuous_dense_tag, blas::gpu_tag > inputs_unreg, blas::dense_vector_adaptor< T, blas::continuous_dense_tag, blas::gpu_tag > outputs_unreg, std::size_t size[4], std::size_t stride[4])
template<class T >
void splineInterpolation2D (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > images_unreg, Shape const &shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > points_unreg, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > values_unreg)
template<class T >
void splineInterpolation2DDerivative (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > imageDerivatives_unreg, Shape const &shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > points_unreg, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > results_unreg)
template<class T , class Device >
void reorder (blas::dense_vector_adaptor< T const, blas::continuous_dense_tag, Device > input, blas::dense_vector_adaptor< T, blas::continuous_dense_tag, Device > output, Shape const &shapeIn, ImageFormat orderIn, ImageFormat orderOut)
Function Documentation
maxPooling() [1/2]
template<class T > void shark::image::maxPooling (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > inputs, Shape const & shape, Shape const & patchSize, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > outputs)
Definition at line 10 of file Pooling.h.
References SIZE_CHECK.
maxPooling() [2/2]
template<class T > void shark::image::maxPooling (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > inputs_unreg, Shape const & shape, Shape const & patchSize, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > outputs_unreg)
Definition at line 10 of file Pooling.h.
References SIZE_CHECK.
maxPoolingDerivative() [1/2]
template<class T > void shark::image::maxPoolingDerivative (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > inputs, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > coefficients, Shape const & shape, Shape const & patchSize, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > derivatives)
Definition at line 49 of file Pooling.h.
References SIZE_CHECK.
maxPoolingDerivative() [2/2]
template<class T > void shark::image::maxPoolingDerivative (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > inputs_unreg, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > coefficients_unreg, Shape const & shape, Shape const & patchSize, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > derivatives_unreg)
Definition at line 86 of file Pooling.h.
References SIZE_CHECK.
reorder()
template<class T , class Device > void shark::image::reorder (blas::dense_vector_adaptor< T const, blas::continuous_dense_tag, Device > input, blas::dense_vector_adaptor< T, blas::continuous_dense_tag, Device > output, Shape const & shapeIn, ImageFormat orderIn, ImageFormat orderOut)
Definition at line 21 of file Reorder.h.
References reorder_impl(), shark::Shape::size(), SIZE_CHECK, and shark::Shape::stride().
reorder_impl() [1/2]
template<class T > void shark::image::reorder_impl (blas::dense_vector_adaptor< T const, blas::continuous_dense_tag, blas::cpu_tag > inputs, blas::dense_vector_adaptor< T, blas::continuous_dense_tag, blas::cpu_tag > outputs, std::size_t sizes[4], std::size_t strides[4])
Definition at line 10 of file Reorder.h.
Referenced by reorder().
reorder_impl() [2/2]
template<class T > void shark::image::reorder_impl (blas::dense_vector_adaptor< T const, blas::continuous_dense_tag, blas::gpu_tag > inputs_unreg, blas::dense_vector_adaptor< T, blas::continuous_dense_tag, blas::gpu_tag > outputs_unreg, std::size_t size[4], std::size_t stride[4])
Definition at line 11 of file Reorder.h.
References SIZE_CHECK.
splineInterpolation2D() [1/3]
template<class T > void shark::image::splineInterpolation2D (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > images_unreg, Shape const & shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > points_unreg, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > values_unreg)
Definition at line 9 of file SplineInterpolation2D.h.
splineInterpolation2D() [2/3]
template<class T > void shark::image::splineInterpolation2D (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > images, Shape const & shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > points, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > values)
Definition at line 10 of file SplineInterpolation2D.h.
References SHARK_PARALLEL_FOR.
Referenced by shark::imageInterpolate2D().
splineInterpolation2D() [3/3]
template<class T > void shark::image::splineInterpolation2D (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > images, Shape const & shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > points, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > values, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > valuesdx, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > valuesdy)
Definition at line 65 of file SplineInterpolation2D.h.
References SHARK_PARALLEL_FOR.
splineInterpolation2DDerivative() [1/2]
template<class T > void shark::image::splineInterpolation2DDerivative (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > imageDerivatives_unreg, Shape const & shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > points_unreg, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::gpu_tag > results_unreg)
Definition at line 79 of file SplineInterpolation2D.h.
splineInterpolation2DDerivative() [2/2]
template<class T > void shark::image::splineInterpolation2DDerivative (blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > imageDerivatives, Shape const & shape, blas::dense_matrix_adaptor< T const, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > points, std::size_t pointsPerImage, blas::dense_matrix_adaptor< T, blas::row_major, blas::continuous_dense_tag, blas::cpu_tag > results)
Definition at line 133 of file SplineInterpolation2D.h.
References SHARK_PARALLEL_FOR.
Referenced by shark::weightedImageInterpolate2DDerivative().