build/examples/Supervised/regressionTutorial.cpp File Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
regressionTutorial.cpp File Reference
#include <shark/Data/Csv.h>
#include <shark/Algorithms/GradientDescent/CG.h>
#include <shark/ObjectiveFunctions/ErrorFunction.h>
#include <shark/ObjectiveFunctions/Loss/SquaredLoss.h>
#include <shark/Models/LinearModel.h>
#include <iostream>
Functions
RegressionDataset loadData (const std::string &dataFile, const std::string &labelFile)
int main ()
Function Documentation
loadData()
RegressionDataset loadData (const std::string & dataFile, const std::string & labelFile)
Definition at line 14 of file regressionTutorial.cpp.
References shark::importCSV().
Referenced by main().
main()
int main ()
Definition at line 30 of file regressionTutorial.cpp.
References shark::SquaredLoss< OutputType, LabelType >::eval(), shark::AbstractLineSearchOptimizer< SearchPointType >::init(), shark::ErrorFunction< SearchPointType >::init(), shark::inputDimension(), shark::LabeledData< InputT, LabelT >::inputs(), shark::labelDimension(), shark::LabeledData< InputT, LabelT >::labels(), loadData(), shark::LabeledData< InputT, LabelT >::numberOfElements(), shark::LinearModel< InputType, ActivationFunction >::setParameterVector(), shark::AbstractSingleObjectiveOptimizer< SearchPointType >::solution(), shark::splitAtElement(), and shark::AbstractLineSearchOptimizer< SearchPointType >::step().