shark::NSGA3Indicator Struct Reference
Shark machine learning library
Installation
Tutorials
Benchmarks
Documentation
Quick references
Class list
Global functions
shark::NSGA3Indicator Struct Reference
#include <shark/Algorithms/DirectSearch/Operators/Indicators/NSGA3Indicator.h>
Public Member Functions
template<typename ParetofrontType , typename ParetoArchive >
std::vector< std::size_t > leastContributors (ParetofrontType const &front, ParetoArchive const &archive, std::size_t K) const
template<typename Archive >
void serialize (Archive &ar, const unsigned int)
void setReferencePoints (std::vector< RealVector > const &Z)
template<class random >
void init (std::size_t numOfObjectives, std::size_t mu, random &rng, std::vector< Preference > const &preferences=std::vector< Preference >())
Detailed Description
Definition at line 43 of file NSGA3Indicator.h.
Member Function Documentation
init()
template<class random > void shark::NSGA3Indicator::init (std::size_t numOfObjectives, std::size_t mu, random & rng, std::vector< Preference > const & preferences = std::vector<Preference>()) inline
Definition at line 137 of file NSGA3Indicator.h.
References shark::computeOptimalLatticeTicks(), shark::preferenceAdjustedUnitVectors(), shark::sampleLatticeUniformly(), and shark::unitVectorsOnLattice().
Referenced by shark::RealCodedNSGAIII::doInit().
leastContributors()
template<typename ParetofrontType , typename ParetoArchive > std::vector<std::size_t> shark::NSGA3Indicator::leastContributors (ParetofrontType const & front, ParetoArchive const & archive, std::size_t K) const inline
Definition at line 45 of file NSGA3Indicator.h.
serialize()
template<typename Archive > void shark::NSGA3Indicator::serialize (Archive & ar, const unsigned int) inline
Definition at line 124 of file NSGA3Indicator.h.
setReferencePoints()
void shark::NSGA3Indicator::setReferencePoints (std::vector< RealVector > const & Z) inline
Definition at line 128 of file NSGA3Indicator.h.
The documentation for this struct was generated from the following file:
include/shark/Algorithms/DirectSearch/Operators/Indicators/NSGA3Indicator.h